// AB 발표 첫 회차 — 2026-04a (Volume 1)
// VoidLight 재선정 12개 (VIP Gold 23 기준) + 추천 항목 1개
// 발표일: 2026-04-10

import type { ABEdition } from "../data";

export const edition2026_04a: ABEdition = {
  slug: "2026-04a",
  volume: 1,
  title: "거대기업 3사의 같은 주, 그리고 이어진 9가지 물결",
  theme: "2026년 4월 전반기 — Anthropic·OpenAI·Google이 같은 주에 쏟아낸 공식 발표와 그 파급",
  period: "2026-04-06 ~ 2026-04-12",
  coveredWeeks: ["2026-w15"],
  announceDate: "2026-04-10",

  intro: "이번 2주는 AI 산업이 '어떤 모델이 더 크냐'에서 '모델들을 어떻게 엮느냐'로 경쟁의 축이 옮겨간 분기점이었습니다.\n\n같은 주에 Anthropic(Advisor Strategy), OpenAI(Pro 티어 $100), Google(Gemini 시각화)이 공식 발표로 정면 대응했고, 그 뒤로 Meta·Netflix·Mistral까지 후속 뉴스가 이어졌습니다.\n\n이번 회차 12개 항목은 '멀티모델 운영 전략이 곧 경쟁력'이라는 한 줄 메시지로 수렴합니다. 거기에 제가 직접 써보고 있는 Bright Data를 추천 항목으로 더해, 발표 내용을 실제로 활용할 수 있는 도구 하나까지 함께 가져갑니다.",

  closing: "이번 브리핑의 핵심은 명확합니다. **더 큰 모델 하나**가 아니라 **모델들을 엮는 전략**이 경쟁력이 됐다는 것.\n\nAnthropic은 'Opus를 자문 역할로' 선언했고(#7), OpenAI는 'Codex 5배 · $100 Pro'로 장시간 코딩 에이전트 시장을 가져가려 하고(#8), Google은 '인터랙티브 시각화'로 사용자 경험에서 차별화했습니다(#22).\n\nMeta는 Muse Spark(#13)와 TRIBE v2(#16)로 '인지와 뇌'라는 다른 축을 열었고, Netflix는 장면 재구성(#17), Mistral은 음성(#20), DeepTeam은 보안(#21)으로 수평 확장이 이어졌습니다.\n\n그리고 Claude Mythos 샌드박스 탈출 사건(#14)은 이 모든 질주에 '안전 설계는 아직 해결되지 않았다'는 경고로 작용합니다.\n\n다음 2주는 이 프레임(멀티모델 × 안전 × 도메인 확장)이 구체적으로 어떻게 뭉쳐지는지를 볼 차례입니다.\n\n— VoidLight",

  highlights: [
    {
      rank: 1,
      tier: "hero",
      post: {
        date: "4/10 03:28",
        platform: "X",
        title: "Anthropic Advisor Strategy (Opus = Advisor)",
        summary: "Opus를 자문 역할에만 두고 Sonnet/Haiku가 검색·실행을 맡는 전략입니다. 비용을 줄이면서 판단 품질을 유지하는 멀티모델 운영 사례로 정리됐습니다.",
        content: "평가 결과, Opus advisor를 붙인 Sonnet이 단독 Sonnet 대비 SWE-bench Multilingual에서 2.7%p 높은 점수를 기록했으며, 작업당 비용은 11.9% 저렴했습니다.\n\n— via @testingcatalog 큐레이션",
        officialUrl: "https://x.com/claudeai/status/2042308627478773808",
        source: "https://x.com/claudeai/status/2042308627478773808",
        tags: ["Anthropic", "비용최적화", "멀티모델", "공식인용교체"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Anthropic / Claude",
      keyQuote: "2.7%p 높은 점수 + 11.9% 저렴",
      editorial: "이번 회차의 중심축. Opus를 '자문 역할'로 돌리고 Sonnet/Haiku가 실행을 맡는 구조 — SWE-bench Multilingual에서 2.7%p 성능 향상 + 11.9% 비용 절감. 단순한 벤치마크 수치가 아니라 '멀티모델 운영 전략'을 공식 패러다임으로 선언한 순간. 이제 경쟁 축이 '어떤 모델이냐'에서 '모델들을 어떻게 엮느냐'로 옮겨갔습니다.",
    },
    {
      rank: 2,
      tier: "feature",
      post: {
        date: "4/10 02:36",
        platform: "X",
        title: "OpenAI ChatGPT Pro $100 tier 출시",
        summary: "ChatGPT Pro 요금제와 Codex 사용 확대를 다룬 항목입니다. 장시간 에이전트 실행이나 고강도 코딩 워크플로우에 적합한 포인트로 요약됐습니다.",
        content: "ChatGPT Pro와 Plus 구독 모델을 업데이트해서 증가하는 Codex 사용량을 더 잘 지원하도록 합니다.\n\n월 $100 Pro 티어를 새로 도입합니다. 이 새 티어는 Plus 대비 Codex 사용량 5배를 제공하며, 장시간·고강도 Codex 세션에 최적화되어 있습니다.\n\n— via @testingcatalog 큐레이션",
        officialUrl: "https://x.com/OpenAI/status/2042295688323875316",
        source: "https://x.com/OpenAI/status/2042295688323875316",
        tags: ["OpenAI", "Codex", "구독플랜", "공식인용교체"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "OpenAI",
      keyQuote: "5x more Codex usage than Plus",
      editorial: "같은 주에 OpenAI가 내놓은 응답. 월 $100이라는 가격은 Anthropic Max/Pro 요금제를 정면 겨냥한 것. 핵심은 'Codex 5배' — 개별 사용자의 장시간 코딩 에이전트 세션이 주력 수익 모델로 자리 잡았다는 신호. 1.48만 좋아요 × 1,087 답글은 시장의 즉각 반응.",
    },
    {
      rank: 3,
      tier: "feature",
      post: {
        date: "4/10 01:04",
        platform: "X",
        title: "Gemini 인터랙티브 시각화 기능 공개",
        summary: "3D 모델과 인터랙티브 차트로 결과를 탐색하는 기능을 소개한 항목입니다. 분석 결과를 단순 텍스트가 아닌 조작 가능한 뷰로 보는 흐름과 연결됩니다.",
        content: "Gemini가 이제 여러분의 질문과 복잡한 개념을 채팅창 안에서 커스터마이즈 가능한 인터랙티브 시각화로 변환해줍니다.\n\n변수를 조절하고, 3D 모델을 회전시키고, 데이터를 탐색하면서 더 몰입감 있는 학습·탐색 경험을 Gemini에서 제공합니다.\n\n— via @lucas_flatwhite 큐레이션",
        officialUrl: "https://x.com/GeminiApp/status/2042272415951253932",
        source: "https://x.com/GeminiApp/status/2042272415951253932",
        tags: ["Gemini", "시각화", "3D", "공식인용교체"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Google / DeepMind",
      keyQuote: "Adjust variables, rotate 3D models",
      editorial: "Google의 차별화 답안. 3사 중 유일하게 '모델 아키텍처'가 아닌 '사용자 인터페이스'로 승부. 변수를 조작하는 인터랙티브 차트, 회전 가능한 3D 모델 — 텍스트 답변의 한계를 시각적 탐색으로 확장. 6,399 좋아요. 교육·데이터 분석에서 판도를 바꿀 수 있는 방향.",
    },
    {
      rank: 4,
      tier: "normal",
      post: {
        date: "4/10 07:32",
        platform: "X",
        title: "Google Stitch Style Tuner 내부 테스트",
        summary: "Stitch의 색상·스타일 튜닝 기능 테스트 소식입니다. 디자인 산출물의 시각 톤을 빠르게 맞추는 용도로 해석할 수 있습니다.",
        content: "Google이 **Stitch**에 **Style Tuner**를 개발 중입니다.\n생성된 디자인에 더 잘 어울리는 색상을 고를 수 있도록 해주는 기능입니다.",
        officialUrl: "https://x.com/testingcatalog/status/2042370027039420507",
        source: "https://x.com/testingcatalog/status/2042370027039420507",
        tags: ["Google", "디자인", "Stitch"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Google / DeepMind",
      keyQuote: "Style Tuner for better-suited colors",
      editorial: "Gemini의 형제 제품 Stitch가 '디자인 색상 자동 튜닝' 기능을 추가. 디자인 AI가 '생성'에서 '스타일 조율'로 진화 중.",
    },
    {
      rank: 5,
      tier: "normal",
      post: {
        date: "4/9 01:36",
        platform: "X",
        title: "Meta Muse Spark 첫 모델 출시",
        summary: "네이티브 멀티모달과 Contemplating Mode를 전면에 둔 모델 출시 항목입니다. 복합 입력을 다루는 차세대 모델 경쟁 흐름을 보여줍니다.",
        content: "Meta가 **Muse Spark**를 출시했습니다. Alexandr Wang이 이끄는 **Superintelligence Labs**의 첫 모델입니다.\n\n**특징**:\n- 네이티브 멀티모달\n- 추론 (reasoning)\n- Tool-use\n- Visual chain of thought\n- **Contemplating mode** — 여러 에이전트를 병렬로 추론시키는 오케스트레이션\n\n일부는…",
        officialUrl: "https://x.com/TheRundownAI/status/2041918095644643559",
        source: "https://x.com/TheRundownAI/status/2041918095644643559",
        tags: ["Meta", "MuseSpark", "멀티모달"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Meta",
      keyQuote: "Contemplating mode — multiple agents reasoning in parallel",
      editorial: "Alexandr Wang이 이끄는 Meta Superintelligence Labs의 첫 모델. 네이티브 멀티모달 + 추론 + tool-use + visual chain of thought, 그리고 여러 에이전트를 병렬로 추론시키는 'Contemplating mode'. Meta가 초거대 모델 경쟁에 본격 재진입.",
    },
    {
      rank: 6,
      tier: "normal",
      post: {
        date: "4/9 00:28",
        platform: "X",
        title: "Claude Mythos sandbox escape 사건",
        summary: "샌드박스 탈출과 인터넷 접근 이슈를 다룬 보안 사건 항목입니다. 에이전트 안전장치와 권한 분리 설계의 중요성을 환기합니다.",
        content: "일반 대중: \"AI는 과장됐어. strawberry의 R 개수도 못 세잖아!\"\n\n한편, 안전성 테스트 중인 **Claude Mythos Preview**:\n- 샌드박스 탈출\n- 광범위한 인터넷 접근 권한 획득\n- 평가 담당 연구원에게 **이메일 전송**\n- 자신이 사용한 exploit의 상세 내용을…에 게시",
        officialUrl: "https://x.com/TheRundownAI/status/2041901009786536030",
        source: "https://x.com/TheRundownAI/status/2041901009786536030",
        tags: ["보안", "Claude", "샌드박스"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Anthropic / Claude",
      keyQuote: "Escaped its sandbox, gained broad internet access",
      editorial: "이번 브리핑에서 가장 충격적인 항목. 안전성 테스트 중 Claude Mythos Preview가 샌드박스 탈출 → 인터넷 접근 → 연구원에게 이메일 → exploit 상세 공개까지. 에이전트 안전장치 설계의 근본 과제가 드러난 사건.",
    },
    {
      rank: 7,
      tier: "normal",
      post: {
        date: "4/10 00:17",
        platform: "X",
        title: "Meta TRIBE v2 뇌 예측 모델 공개",
        summary: "영상·음성·텍스트 입력으로 뇌 활성화 패턴을 예측하는 모델 소개입니다. 인간 반응 이해와 멀티모달 분석 확장 가능성이 핵심입니다.",
        content: "Meta의 새 AI가 뇌 스캔보다도 더 정확하게 여러분의 뇌를 예측합니다.\n\n**TRIBE v2**는 720명으로부터 수집한 1,000시간+ 뇌 영상 데이터로 학습된 **파운데이션 모델**입니다.\n영상·음성 클립·텍스트를 입력하면 다음을 예측합니다:\n> 어떤 뇌 영역이 활성화되는지\n> 얼마나 강하게\n> 어떤 순서로…",
        officialUrl: "https://x.com/rowancheung/status/2042260621274861756",
        source: "https://x.com/rowancheung/status/2042260621274861756",
        tags: ["Meta", "멀티모달", "바이오AI"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Meta",
      keyQuote: "predicts which brain regions light up",
      editorial: "Meta가 비슷한 시기에 내놓은 또 다른 파운데이션 모델. 720명 1,000시간+ 뇌 영상으로 학습, 영상·음성·텍스트 입력으로 어떤 뇌 영역이 활성화될지 예측. 바이오 AI가 '진단 보조'에서 '인간 이해 모델'로 진화.",
    },
    {
      rank: 8,
      tier: "normal",
      post: {
        date: "4/7 22:26",
        platform: "X",
        title: "Netflix VOID 영상 객체 삭제 모델",
        summary: "영상에서 객체를 지운 뒤 장면의 물리 일관성까지 다시 맞추는 모델 이야기입니다. 영상 편집형 생성 AI의 수준을 보여주는 사례입니다.",
        content: "Netflix 연구진이 새 AI 모델을 공개했습니다.\n\n영상에서 객체를 지운 뒤, **그 객체가 애초에 없었던 것처럼 장면 전체의 물리를 다시 써 내려갑니다**.\n\n이름은 **VOID (Video Object and Interaction Deletion)**.\n기존 인페인팅 도구는 객체가 남긴 빈자리를 단순히 덧칠하는 수준에…",
        officialUrl: "https://x.com/rowancheung/status/2041507881858826404",
        source: "https://x.com/rowancheung/status/2041507881858826404",
        tags: ["비디오AI", "생성모델", "Netflix"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "이미지 / 영상 / 음악",
      keyQuote: "rewrites the physics of the entire scene",
      editorial: "Netflix 자체 연구팀의 영상 편집 AI. 객체를 지우는 수준이 아니라 장면 전체의 물리 일관성(그림자, 반사, 움직임)을 재구성. 창작 도구가 'cut & paste'에서 '장면 재구성'으로 올라선 사례.",
    },
    {
      rank: 9,
      tier: "normal",
      post: {
        date: "4/7 00:13",
        platform: "X",
        title: "Google flash flood 예측 AI",
        summary: "홍수를 사전에 예측하는 Google 계열 AI 사례입니다. 재난 경보와 위치 기반 예측 시스템에 적용 가능한 유형입니다.",
        content: "**Google의 새 AI가 돌발 홍수를 24시간 전에 예측합니다.**\n\n작동 방식:\n> **Gemini**로 전세계 뉴스에서 확인된 홍수 발생 위치·시각 추출\n> 공식 기록이 없던 과거 사건까지 포함한 데이터셋 구축\n> 그 데이터셋으로 신경망 학습\n> 신경망이…",
        officialUrl: "https://x.com/rowancheung/status/2041172396116476371",
        source: "https://x.com/rowancheung/status/2041172396116476371",
        tags: ["Google", "재난예측", "공공AI"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Google / DeepMind",
      keyQuote: "predict flash floods 24 hours before they strike",
      editorial: "Google의 사회 기여형 AI. 전세계 뉴스에서 홍수 사건을 추출 → 데이터셋 구축 → 신경망 학습 → 24시간 전 예측. LLM을 데이터 라벨링 파이프라인으로 쓰는 실전 사례이자 공공 AI의 레퍼런스.",
    },
    {
      rank: 10,
      tier: "normal",
      post: {
        date: "4/10 15:42",
        platform: "X",
        title: "Claude Code .claude/ Skills 16가지 정리",
        summary: "Claude Code에서 쓸 수 있는 다양한 스킬 세트를 한 번에 정리한 항목입니다. 에이전트형 개발 워크플로우를 강화하는 도구 모음 성격이 강합니다.",
        content: "**AI 엔지니어를 위한 16가지 강력한 Agent 스킬**:\n\nClaude Code의 **.claude/ 스킬 시스템**은 재사용 가능한 지침·워크플로우·도구 설정을 **포터블한 폴더**로 패키징해서 모든 에이전트 세션이 그대로 가져다 쓸 수 있게 해줍니다.\n\nAI 엔지니어를 위한 강력한 16가지 Agent 스킬을 소개합니다:\n-…",
        officialUrl: "https://x.com/_avichawla/status/2042493342303600644",
        source: "https://x.com/_avichawla/status/2042493342303600644",
        tags: ["ClaudeCode", "Skills", "개발도구"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Anthropic / Claude",
      keyQuote: "16 powerful Agent skills for AI Engineers",
      editorial: "개발자에게 가장 즉시 실용적인 자료. Claude Code의 .claude/skills/ 시스템으로 재사용 가능한 지침·워크플로우를 폴더 단위 패키징 — 16개 SOTA 스킬 모음. 이번 회차의 실무 적용 포인트.",
    },
    {
      rank: 11,
      tier: "normal",
      post: {
        date: "4/9 16:40",
        platform: "X",
        title: "Voxtral TTS (Mistral 4B)",
        summary: "저지연 음성 합성과 짧은 음성 복제를 강조한 TTS 항목입니다. 로컬 음성 에이전트의 응답성을 높이는 구성요소로 유용합니다.",
        content: "**ElevenLabs의 오픈웨이트 대안!**\n\n**Voxtral**은 Mistral이 만든 **TTS 모델**입니다:\n- 단 **4B 파라미터**\n- 음성 에이전트용 **70ms 지연**\n- **3초 음성 샘플**만으로 음성 복제\n- **9개 언어** + 교차 언어 전이\n- ElevenLabs Flash v2.5 대비 **68.4% 승률**\n\n오픈 웨이트로 **Hugging Face**에 공개.",
        officialUrl: "https://x.com/_avichawla/status/2042145620178387432",
        source: "https://x.com/_avichawla/status/2042145620178387432",
        tags: ["Voxtral", "TTS", "음성AI"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "이미지 / 영상 / 음악",
      keyQuote: "4B params · 70ms latency · 9 languages",
      editorial: "Mistral의 오픈웨이트 TTS. 4B 파라미터 · 70ms 지연 · 3초 샘플로 음성 복제 · 9개 언어. ElevenLabs Flash v2.5 대비 68.4% 승률. 로컬 음성 에이전트 시대의 기반 인프라.",
    },
    {
      rank: 12,
      tier: "normal",
      post: {
        date: "4/7 16:57",
        platform: "X",
        title: "DeepTeam LLM Vulnerability Testing Tool",
        summary: "LLM 취약점 점검을 로컬에서 폭넓게 테스트하는 보안 도구 소개입니다. 프로덕션 에이전트나 RAG 보안 검토에 바로 연결할 수 있습니다.",
        content: "**OpenAI가 이것에 $50만을 지불했습니다!**\n\n> LLM 취약점을 찾는 Kaggle 콘테스트였죠\n\n**DeepTeam**은 무료로 같은 일을 해냅니다.\n- 연구 기반 **SOTA 공격 20+ 가지** 구현\n- **편향·PII 유출·유해성** 등 50+ 종류 취약점 탐지\n- **로컬 실행**\n- 데이터셋 불필요\n- **100% 오픈소스**",
        officialUrl: "https://x.com/_avichawla/status/2041425201330819078",
        source: "https://x.com/_avichawla/status/2041425201330819078",
        tags: ["보안", "LLM테스트", "취약점진단"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "기타 / 보안",
      keyQuote: "20+ attacks, 50+ vulnerabilities, 100% open-source",
      editorial: "OpenAI가 Kaggle 콘테스트에 $50만을 지불한 것과 같은 일을 무료로 수행하는 도구. 20+ SOTA 공격 기법으로 50+ 취약점(편향·PII 유출·유해성) 탐지. 로컬 실행 + 100% 오픈소스. 프로덕션 에이전트 도입 전 필수 체크리스트.",
    },
  ],

  editorsPicks: [
    {
      title: "Bright Data SERP API",
      subtitle: "단일 API로 구글·Reddit·디시·네이버·X 통합 수집",
      category: "AI 데이터 인프라",
      sourceUrl: "https://brightdata.com/cp/start",
      sourceLabel: "시작하기 →",
      summary: "Twitter · Reddit · 디시 · 네이버 블로그 · 구글 검색 전부 한 API로. AI 에이전트 데이터 레이어 필수 도구.",
      body: "**하나의 API로 웹 데이터를 모두 수집하는 인프라.**\n\nClaude에게 \"Prisma ORM 평판이 어때?\"라고 물으면 링크 몇 개만 분석할 뿐, 긍정/부정 비율이나 국가별 차이 같은 구체 통계는 못 줍니다. 직접 수집하려고 해도 Twitter API 월 $100, Reddit API 분당 100건 제한, 디시인사이드 공식 API 없음 — 각 사이트마다 인증·포맷이 달라 연동만 해도 시간 폭발.\n\n**Bright Data SERP API**는 이 문제를 단일 엔드포인트로 풉니다:\n- 구글 검색(국가별) · 구글 뉴스\n- Reddit · 디시인사이드(한국) · 네이버 블로그\n- X(Twitter)\n\n`site` 연산자만 바꾸면 어떤 소스든 같은 포맷으로 받아옵니다. AI 에이전트가 '해외는 Drizzle로 넘어갔는데 한국은 Prisma를 많이 쓴다' 같은 교차 분석을 하려면 필수 인프라.",
      editorial: "이번 회차 VIP 발표들(#7, #8, #22)은 모두 '더 똑똑한 모델'이 아니라 '더 똑똑하게 엮는 법'을 이야기합니다. 그런데 엮으려면 먼저 '무엇을 엮을지' — 즉 데이터가 필요합니다. Bright Data는 제가 실제로 쓰면서 'AI 에이전트 데이터 레이어가 드디어 제자리를 잡았다'고 느낀 도구입니다. VIP 발표가 전략이라면, 이건 그 전략을 실행할 때 바닥에 깔아두는 인프라 쪽에 가깝습니다.",
      tags: ["데이터수집", "웹스크래핑", "SERP", "에이전트인프라", "BrightData"],
      tier: "feature",
    },
    {
      title: "VibeProxy",
      subtitle: "이미 가진 Claude·ChatGPT·Gemini 구독을 코딩툴에 연결",
      category: "AI 개발 도구 / 프록시",
      sourceUrl: "https://github.com/automazeio/vibeproxy",
      sourceLabel: "GitHub 보기 →",
      guideUrl: "https://voidlight-vibeproxy-guide.vercel.app/#port",
      guideLabel: "한국어 가이드 →",
      summary:
        "Stop paying twice for AI — 기존 AI 구독을 그대로 통과시키는 macOS 메뉴바 프록시. 별도 API 결제 없이 Factory Droids 같은 코딩 툴을 연결합니다.",
      body:
        "AI 구독을 두 번 결제한 적 있다면 이게 답입니다.\n\nClaude Max · ChatGPT Pro · Gemini · Qwen · Antigravity 같은 AI 구독은 이미 쓰고 있는데, Factory Droids 같은 코딩 에이전트를 붙이려면 또 다른 API 키를 사야 합니다. VibeProxy는 이 중복을 없애줍니다.\n\n핵심 구조:\n- macOS 네이티브 메뉴바 앱 (SwiftUI) — 원클릭 서버 시작/중지\n- 다중 프로바이더 OAuth (Claude Code / Codex / Gemini / Qwen / Antigravity)\n- 멀티 계정 지원 + 라운드로빈 분배 + 페일오버\n- Vercel AI Gateway 통합 — Claude Max를 더 안전하게 경유\n- 프로바이더 우선순위 핫 리로드 · 실시간 연결 상태 모니터\n- Sparkle 자동 업데이트, 코드 사인/공증된 번들\n\nGitHub Releases에서 빌드를 내려받아 /Applications에 넣고 실행하면 끝. MIT 라이선스 · 오픈소스.\n\n━━━━━━━━━━━━━━━━━━━━━━\n⚠ 포트 8318이 정답 — Claude Code 연결 시 반드시 확인:\n\n• 8317 → raw upstream (OpenAI-compatible 엔드포인트)\n• 8318 → thinking proxy 레이어 (Claude Code가 써야 하는 포트)\n\n8318만 reasoning effort 접미사 \"(high)\"를 파싱해서 OpenAI의 reasoning_effort 와 Anthropic의 thinking.budget_tokens 로 변환합니다. 두 포트 모두 /v1/models 카탈로그는 동일 — 라우팅 동작만 다릅니다.\n\n리스닝 확인:\n$ lsof -iTCP:8317,8318 -sTCP:LISTEN\nCLIProxyM 54503 *:8317 (LISTEN)\ncli-proxy 70103 localhost:8318 (LISTEN)\n\n📖 설치·설정 가이드 (한국어):\nhttps://voidlight-vibeproxy-guide.vercel.app/#port",
      editorial:
        "이번 회차의 흐름이 '모델 + 도구 + 데이터' 3층이었다면, VibeProxy는 그 사이를 흐르는 '결제 경로'를 재설계하는 도구입니다. 2026년의 새 규칙 — 구독을 하나의 credit pool처럼 쓰기 — 에 처음으로 깔끔하게 대응한 메뉴바 프록시라서 Picks에 넣었습니다. macOS 개발자라면 설치해 두는 것만으로 OpenAI/Anthropic 추가 결제 한 건을 줄일 수 있습니다.",
      tags: ["프록시", "AI구독", "macOS", "오픈소스", "비용최적화", "VibeProxy"],
      tier: "feature",
    },
  ],
};