import type { ABEdition } from "../data";

// 2026-05b — 격주 AB 발표 (2026-05-15 ~ 2026-05-25)

export const edition2026_05b: ABEdition = {
  slug: "2026-05b",
  volume: 4,
  title: "Codex 모바일·Gemini agentic·Vera CPU·Glasswing — AI가 운영체제로 굳는 한 주",
  theme: "2026-05-15 ~ 2026-05-25 — Codex가 모바일/AWS/Dell로 확장되고, Google I/O 2026이 Gemini를 agentic platform으로 재정의했으며, NVIDIA Vera CPU가 첫 출하되고, Anthropic Project Glasswing이 1만+ 취약점을 발견한 구간",
  period: "2026-05-15 ~ 2026-05-25",
  coveredWeeks: ["2026-w21", "2026-w22"],
  announceDate: "2026-05-25",
  intro: `이번 11일은 한 회사의 단일 발표가 아니라, 네 가지 흐름이 동시에 굳어진 구간이었습니다.\n\n첫째, OpenAI는 Codex를 ChatGPT 모바일·Skills·Automations·AWS Bedrock·Dell 하이브리드까지 일주일 안에 풀며 "Codex가 어디서나 돈다"는 그림을 완성했습니다. 둘째, Google I/O 2026은 Gemini 3.5/Spark/Omni와 Managed Agents, Antigravity 2.0, AI Studio로 Gemini를 단순 챗봇이 아니라 agentic platform으로 다시 정의했습니다. 셋째, NVIDIA는 Vera CPU 첫 출하 + Q1 FY27 Data Center 752억$로 "에이전트를 굴리는 인프라"가 산업 코어임을 수치로 증명했습니다. 넷째, Anthropic은 Stainless 인수, KPMG 27.6만명 도입, Project Glasswing 1만+ 취약점 발견, Claude Code Agent View로 모델·플랫폼·기업 운영체제 세 축을 동시에 밀었습니다.`,
  closing: `한 줄로 묶으면, AI는 이번 11일 사이에 "어디서나 돌고, 인프라를 정당화하며, 기업 운영체제로 들어가는" 단계로 굳었습니다.\n\n직접 써보고 추천드리는 도구 섹션에는 tw93/Mole(macOS deep clean + AI CLI 잔재 정리), Nutlope/hallmark(anti-AI-slop 디자인 스킬), manaflow-ai/cmux(Codex CLI 분할 워크플로), jaehwan02/UltraCat(macOS 메뉴바 시스템·팬·수면 관리), cokacdir(한국어 AI 큐레이션 오픈소스) 다섯 개를 골라뒀습니다.\n\n— VoidLight`,
  coreFlow: [
    "Codex는 모바일·앱·Skills·Automations·AWS·Dell로 확장되며 어디서나 실행되는 코딩 에이전트가 됐다.",
    "Gemini는 I/O 2026에서 Omni·Managed Agents·agentic Search를 묶어 제품 전반에 깔리는 에이전트 플랫폼으로 재정의됐다.",
    "NVIDIA와 Anthropic은 각각 인프라 풀스택과 기업 업무 계층을 장악하며 AI 운영체제의 하부와 상부를 동시에 밀고 있다.",
  ],
  highlights: [
    {
      rank: 1,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Gemini Omni — 텍스트·이미지·오디오·영상을 입력으로 받는 영상 생성·편집 통합 모델",
        deck: "Google이 I/O 2026에서 Gemini Omni를 공개했다",
        summary: "Google이 I/O 2026에서 Gemini Omni를 공개했다. 영상을 단순 생성하는 모델이 아니라 \"추론하는 영상 모델\"로, 시네마틱 줌·배경 교체·등장인물 일관성 유지를 대화형으로 처리한다. 첫 모델 Gemini Omni Flash는 5/19부터 전 세계 Google AI Plus·Pro·Ultra 구독자, Google Flow, YouTube Shorts(무료)에서 즉시 사용 가능.",
        content: "Google이 2026년 5월 19일 I/O 2026 키노트에서 Gemini Omni 영상 모델 패밀리를 공개했다. DeepMind CEO Demis Hassabis가 \"어떤 입력에서든 무엇이든 만들 수 있는 새 모델\"이라는 표현으로 소개했고, 기존 Veo 라인이 핵심 Gemini 시스템 안으로 흡수됐다. 첫 모델인 Gemini Omni Flash는 같은 날부터 Google AI Plus·Pro·Ultra 구독자, Google Flow, YouTube Shorts에서 즉시 사용할 수 있다.\n\n핵심 사실은 다음과 같다.\n\n- 입력: 텍스트 + 이미지 + 오디오 + 영상의 멀티모달 입력\n- 출력: 약 10초 짜리 클립 + 동기화된 오디오\n- 아키텍처: Gemini의 추론 엔진 + Veo 렌더링 + DeepMind Genie 월드 시뮬레이션 + Nano Banana 편집 레이어\n- 가격: YouTube Shorts/Create 무료, AI Plus 월 7.99달러, Pro 19.99달러, Ultra 99.99달러부터\n- 개발자·기업 API는 \"수주 안에\" 공개 예정\n\n## Under the hood\n\nOmni의 차별점은 단순 영상 생성기가 아니라 영상을 다루는 추론 모델로 설계됐다는 점이다. 등장 인물·배경·카메라 움직임을 편집 후에도 일관되게 유지하고, 시네마틱 줌이나 배경 교체 같은 작업을 처음부터 다시 생성하지 않고 부분 갱신만으로 처리한다. 기존 AI 영상 모델이 가장 약했던 일관성과 부분 편집을 모델 구조 단계에서 정면으로 풀었다는 의미다.\n\n## 배포 우위가 진짜 차별점\n\n공개 벤치마크 1위는 ByteDance Seedance 2.0이고 중국 시장은 Kling 3.0이 잡고 있어, 모델 단품 비교만 보면 Omni를 굳이 갈아탈 이유가 약하다는 평가가 발표 직후 한국 큐레이터들 사이에서 나왔다. Google이 가는 길은 다르다. Gemini 앱, Google Flow, YouTube Shorts, 검색 결과에 자동으로 들어가기 때문에 사용자가 별도 서비스에 가입할 필요가 없다. 모델 점수 경쟁이 아니라 분배 채널 싸움으로 끌고 가는 전략이다.\n\n## Seedance 2.0과 역할 분담하는 워크플로\n\n현장 사용 평을 보면 Omni는 0→1 영상 생성에서는 Seedance 2.0에 밀리지만, 이미 만들어진 영상을 부분 합성·수정하는 능력에서 높은 점수를 받는다. Nano Banana가 처음 나왔을 때 생성보다 합성·수정으로 자리를 잡았던 패턴과 같다. 한국 제작자 입장에서는 둘 중 하나를 고르지 말고 다음처럼 분담하는 편이 현실적이다.\n\n1. Seedance 2.0으로 본 영상을 생성한다.\n2. Omni로 깨진 한글 자막, 한국어 발음, 부분 프레임 합성, 등장인물 일관성 같은 영역을 보정한다.\n\n글로벌 영상 모델의 만성적 약점인 한글 텍스트 깨짐을 멀티모달 입력(영상 + 텍스트 지시)으로 부분 수정하는 흐름이 가장 즉시 실용적이다.\n\n## Risks and limits\n\nFlash 클립이 10초로 묶인 건 모델 한계가 아니라 컴퓨트 수요 분산을 위한 배포 결정이라고 Google DeepMind 제품 책임자 Nicole Brichtova가 밝혔다. 모든 출력 영상에 SynthID 비가시 워터마크와 C2PA Content Credentials가 강제로 박히고, API 플래그로도 제거할 수 없다. 음성·대사 교체 편집은 \"가장 위험한 기능\"으로 분류돼 의도적으로 막아뒀다. 같은 키노트에서 Gemini 3.5 Flash와 Gemini Spark가 함께 공개돼, Omni는 agentic Gemini 흐름의 한 축으로 읽어야 한다 (blog.google/innovation-and-ai/products/gemini-app).",
        officialUrl: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
        source: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
        backupUrls: [
          { label: "Google I/O 2026 — agentic Gemini era keynote", url: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/" },
          { label: "Google AI Studio — Gemini Omni 사용", url: "https://aistudio.google.com" },
          { label: "Decrypt — 'Simulate the World' 분석", url: "https://decrypt.co/368393/google-unveils-gemini-omni-next-gen-ai-video-builder-simulate-world" },
          { label: "TechTimes — 가장 위험한 기능을 막아둔 이유", url: "https://www.techtimes.com/articles/316859/20260519/google-launches-gemini-omni-video-model-holds-back-its-riskiest-feature.htm" },
          { label: "큐레이터 스레드 (@choi.openai)", url: "https://www.threads.com/@choi.openai/post/DYuVvqtj8Av" },
        ],
        tags: ["Google DeepMind", "Gemini Omni", "video generation", "multimodal", "Seedance 2.0", "workflow", "공식", "hero"],
        featured: true,
        slug: "gemini-omni-google-io-2026-video-model",
        readMinutes: 5,
        thumbnail: {
          src: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Geminiapp_Bento_hero.width-1600.format-webp.webp",
          alt: "Gemini Omni 공식 hero",
        },
        videoUrl: "https://www.youtube.com/embed/moxr8bz0ykU",
        threadsEmbedUrl: "https://www.threads.com/embed/@choi.openai/post/DYuVvqtj8Av/",
        galleryImages: [
          { src: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/IOCollection_social.width-2000.format-webp.webp", alt: "Google I/O 2026 컬렉션", caption: "Google I/O 2026 — Gemini Omni가 공개된 키노트 컬렉션" },
          { src: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Gemini_Spark_Partners.width-2000.format-webp.webp", alt: "Gemini Spark 파트너", caption: "함께 발표된 Gemini Spark 에이전트 파트너" },
        ],
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      keyQuote: "어떤 입력에서든 무엇이든 만들 수 있는 새 모델 — Demis Hassabis (DeepMind CEO)",
      editorial: "Google I/O 2026의 메인 발표. 이번 회차의 hero 카드입니다.",
    },
    {
      rank: 2,
      tier: "hero",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "Atlas가 23kg 냉장고를 들어 옮겼다 — Boston Dynamics 전신 제어 시연 + 현대 연 3만대 양산 발표",
        deck: "Boston Dynamics가 5/18 Atlas의 전신 제어(Whole-body control) 시연 영상 2편 + 기술…",
        summary: "Boston Dynamics가 5/18 Atlas의 전신 제어(Whole-body control) 시연 영상 2편 + 기술 블로그 공개. Atlas가 23kg 냉장고를 무릎을 굽혀 들고 책상까지 옮겼다. 현대차그룹은 같은 시기 2028년까지 연 3만대 Atlas 양산 체계 + HMGMA(미국 메타플랜트) 단계적 투입 로드맵을 확정. 한국 청자에게 가장 직접적인 산업 임팩트.",
        content: `Boston Dynamics가 2026년 5월 18일 Atlas 휴머노이드의 전신 제어(Whole-body Control) 시연 영상 두 편과 기술 블로그를 공개했다. Atlas가 23kg 짜리 소형 냉장고를 무릎을 굽혀 들어 올리고 책상까지 옮기는 장면이 메인 컷이다. 시뮬레이션 학습 기반으로 최대 45kg(약 100파운드)까지 들어 올릴 수 있다고 회사는 밝혔다. 같은 시기 현대차그룹은 2028년까지 연 3만 대 Atlas 양산 체계와 HMGMA(미국 메타플랜트) 단계적 투입 로드맵을 확정했다.\n\n공개된 핵심 사실은 다음과 같다.\n\n- 전신 제어 — 다리·몸통·팔이 단일 시스템으로 협응\n- Zero-shot sim-to-real transfer — 시뮬레이션 학습 수백만 시간 후 추가 튜닝 없이 실제 하드웨어에 배포\n- Domain randomization — 무게·마찰·그립을 수천 변형으로 학습\n- 하드웨어 스펙: 56 DoF, 2.3m 도달, 가반 50kg, 4시간 배터리, 셀프 배터리 교체\n\n## 한국 청자가 가장 직접 영향을 받는 이유\n\n현대차그룹은 2028년 부품 분류부터 시작해 2030년 부품 조립까지 Atlas 투입 범위를 확대한다. 현대모비스가 액추에이터, 현대글로비스가 물류, Boston Dynamics가 본체를 맡는 그룹 내 역할 분담 구도가 이미 정해져 있다. Robots-as-a-Service(RaaS) 구독·사용료 모델이 함께 가고, 본체 학습은 Google DeepMind와 공동 개발 중인 Robot Foundation Model, 시뮬레이션은 NVIDIA Omniverse를 쓴다. 나스닥 상장 추진도 5월 7일 결정 단계까지 와 있다.\n\n## 기술적으로 의미 있는 부분\n\nzero-shot sim-to-real transfer가 핵심이다. 시뮬레이션 안에서 무게·마찰·그립 조건을 수천 가지 변형으로 학습시킨 정책을 실제 Atlas 하드웨어에 그대로 올렸을 때 추가 튜닝 없이 작동한다는 게 데모의 메시지다. 휴머노이드 산업이 오래 멈춰 있던 \"시뮬레이션에서는 되는데 실기에서는 안 된다\" 문제를 정면으로 푼 사례다.\n\n## 과대 해석 경계\n\n중국 휴머노이드는 이미 양산이 시작됐고 Figure AI BotQ는 10만 대 설비 규모를 발표한 상태라, 3만 대는 follow-up 수준이다. 2030년 이전에 노무비 절감 효과가 크게 잡히기는 어렵다. 영상도 단일 작업 데모이고, 다종 작업 일반화는 별도 시간이 필요하다. 발표 톤은 신중하게 받아들이는 편이 안전하다 (출처: bostondynamics.com 공식 영상, TechTimes 2026.5.19, 디일렉 2026.5.20).`,
        officialUrl: "https://bostondynamics.com/blog/",
        source: "https://www.techtimes.com/articles/316854/20260519/boston-dynamics-reveals-how-atlas-learned-lift-100-pound-loads-hyundai-plans-30000-per-year.htm",
        backupUrls: [
          { label: "Boston Dynamics 공식 영상 (5/18 Whole-body control)", url: "https://www.youtube.com/watch?v=h-pNWy7v_qc" },
          { label: "Boston Dynamics Shorts — Whole Body Manipulation", url: "https://www.youtube.com/shorts/AdGFmYQx0lg" },
          { label: "TechTimes — Hyundai 3만대 양산", url: "https://www.techtimes.com/articles/316854/20260519/boston-dynamics-reveals-how-atlas-learned-lift-100-pound-loads-hyundai-plans-30000-per-year.htm" },
          { label: "디일렉 — 현대차 로봇 3만대 양산", url: "https://www.thelec.kr/news/articleView.html?idxno=50572" },
          { label: "파이낸셜뉴스 — 공장에 로봇 2.5만대", url: "https://www.fnnews.com/news/202605200942369627" },
          { label: "Asia Business Daily — 23kg 냉장고", url: "https://www.asiae.co.kr/en/article/automobile/2026051908572445829" },
          { label: "큐레이터 스레드 (@choi.openai)", url: "https://www.threads.com/@choi.openai/post/DYuVvqtj8Av" },
        ],
        tags: ["Boston Dynamics", "Hyundai", "Atlas", "humanoid", "whole-body control", "robotics", "한국", "공식", "hero"],
        featured: true,
        slug: "hyundai-boston-dynamics-atlas-whole-body-control-20260518",
        readMinutes: 6,
        thumbnail: {
          src: "https://i.ytimg.com/vi/h-pNWy7v_qc/maxresdefault.jpg",
          alt: "Atlas 23kg 냉장고 시연",
        },
        videoUrl: "https://www.youtube.com/embed/h-pNWy7v_qc",
        galleryImages: [
          { src: "https://i.ytimg.com/vi/AdGFmYQx0lg/maxresdefault.jpg", alt: "Whole Body Manipulation short", caption: "Boston Dynamics 공식 — How AI Is Changing Whole Body Manipulation" },
        ],
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Hyundai × Boston Dynamics",
      keyQuote: "It marks an important turning point, showing that Atlas is moving beyond laboratory demonstrations — Boston Dynamics (2026-05-18)",
      editorial: "한국 청자 가중치 + 영상 필수 정책 적용. 사용자 강조 — 현대 3만대 양산은 본 회차에서 가장 한국적 산업 임팩트.",
    },
    {
      rank: 3,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Codex가 모바일까지 — ChatGPT 모바일 앱에 Codex 통합",
        slug: "work-with-codex-from-anywhere-codex-in-chatgpt-mobile",
        deck: "Codex가 이제 ChatGPT 모바일 앱에서도 돈다 — 어디서나 코딩 에이전트 호출",
        summary: "OpenAI가 ChatGPT 모바일 앱에 Codex를 통합했다. 데스크톱 IDE 또는 CLI 없이도 휴대폰에서 코드 작성·리뷰·실행 가능. 'Codex가 어디서나 돈다' 라는 OpenAI 7-day Codex 확장 시리즈의 첫 발표.",
        content: "OpenAI가 2026년 5월 22일 ChatGPT 모바일 앱(iOS/Android)에 Codex 코딩 에이전트를 정식 통합했다. 데스크톱 IDE 또는 CLI 없이 휴대폰에서 Codex 세션을 시작하고 결과를 확인할 수 있게 한 변경이다. 같은 주 OpenAI가 진행 중인 'Codex 7-day 확장 시리즈'의 첫 카드이기도 하다.\n\n주요 변화는 다음과 같다.\n\n- ChatGPT 모바일 앱 안에서 Codex 세션 시작·재개·결과 확인\n- 데스크톱과 세션 동기화 — 휴대폰에서 시작한 작업을 사무실 데스크톱에서 이어서 진행\n- 음성 입력과 카메라로 찍은 코드 사진을 모바일 컨텍스트로 활용\n- 백그라운드 장기 실행 작업 결과를 푸시 알림으로 수신\n- 무료 ChatGPT 사용자도 제한된 작업 수만큼 모바일 Codex 사용 가능, Plus/Pro/Enterprise는 무제한 세션\n- API 키 또는 OAuth로 GitHub 직접 연동 → 모바일에서 PR 작성과 머지까지 가능\n\n## 7-day Codex 확장 시리즈에서 첫 카드의 의미\n\n같은 주 OpenAI는 Codex app(Skills + Automations), AWS Bedrock 통합, Dell 하이브리드 배포를 연속으로 발표하며 \"Codex가 어디서나 돈다\"는 그림을 그렸다. 모바일 통합은 그 중 가장 눈에 띄는 변화다. 코딩 에이전트가 데스크톱과 IDE에 묶여 있던 시대를 끊는 신호 역할이다.\n\n## 한국 팀에 즉시 적용되는 시나리오\n\n출퇴근 길이나 외근 중에 코드 리뷰와 PR 답변을 처리할 수 있게 된다. 한국 개발 문화의 야근 패턴 일부를 분산시킬 여지가 있다. 다만 모바일 Codex의 실제 생산성이 데스크톱과 비슷한지는 사용자 경험이 누적돼야 판단 가능하다. 모바일에서 돈다는 사실과 모바일에서 잘 돈다는 평가는 다르다. 발표 직후 단정은 신중해야 한다 (출처: openai.com/index/work-with-codex-from-anywhere).",
        officialUrl: "https://openai.com/index/work-with-codex-from-anywhere/",
        source: "https://openai.com/index/work-with-codex-from-anywhere/",
        tags: ["Codex", "ChatGPT mobile", "OpenAI", "공식", "hero후보"],
        featured: true,
        thumbnail: {
          src: "/og-cache/gpt-5-3-codex-is-now-the-base-model-for--d3b67286.png",
          alt: "공식 카드 썸네일",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
    },
    {
      rank: 4,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Codex app + Skills + Automations — Codex가 단일 앱으로 묶였다",
        slug: "introducing-the-codex-app-skills-and-automations",
        deck: "Codex가 ChatGPT 사이드바를 떠나 독립 앱 + Skills + Automations 3종 세트로 재편",
        summary: "OpenAI가 Codex를 ChatGPT 사이드바 도구가 아닌 독립 데스크톱 앱으로 분리. 'Skills'(재사용 가능한 코딩 도구 모음) + 'Automations'(반복 작업 스케줄러) 두 신기능을 동시 출시. 'Codex는 챗봇 기능이 아니라 운영체제 레벨 코딩 에이전트' 라는 OpenAI 메시지.",
        content: "OpenAI가 2026년 5월 22일 Codex를 ChatGPT 사이드바에서 분리해 독립 데스크톱 앱(macOS/Windows)으로 출시하고, Skills와 Automations 두 신기능을 함께 공개했다. 이전까지 Codex는 ChatGPT 안 사이드바 도구였는데, 이번 발표로 독립 앱 + 재사용 도구 라이브러리 + 자동화 스케줄러 3종 세트로 재편됐다.\n\n핵심 사실은 다음과 같다.\n\n- Codex 데스크톱 앱: macOS, Windows 양쪽 출시\n- Skills: 재사용 가능한 코딩 도구·프롬프트 모음 (한 번 만들면 모든 프로젝트에서 호출)\n- Automations: 반복 작업 스케줄러 (예: 매주 월요일 PR review, 매일 dependency update)\n- Skills 라이브러리는 OpenAI 서버 sync로 디바이스 간 자동 공유\n- Automations 실행 비용은 사용자 OpenAI 계정에 청구\n\n## Claude Code, Antigravity와 같은 포지셔닝\n\n구조 변화의 의미가 분명하다. OpenAI는 Codex를 챗봇의 부가 기능이 아니라 개발자 워크플로의 코어로 다시 정의했다. Anthropic이 Claude Code를 IDE와 CLI에 깊게 통합하고, Google이 Antigravity 런타임을 키우는 것과 정확히 같은 방향이다. 모델 회사 셋이 모두 \"모델만 팔지 않고 개발자 워크플로 전체를 묶어 판다\"는 패턴으로 수렴하고 있다.\n\n## Skills는 코딩 에이전트의 GitHub Actions\n\nSkills의 진짜 가치는 재사용성에 있다. 한 번 만들어 둔 작업을 모든 프로젝트에서 호출할 수 있다는 건 개인뿐 아니라 팀 단위 생산성이 누적된다는 뜻이다. Automations는 cron과 AI의 결합이다. 사람 개입 없이 의존성 업데이트, 보안 패치, PR 리뷰 같은 정기 작업을 처리한다. 데스크톱 앱으로 분리됐다는 사실은 OS 단축키, 파일 시스템, 시스템 트레이까지 접근한다는 의미이고, 코딩 에이전트가 IDE 안에 갇히지 않게 됐다.\n\n## 한국 팀이 먼저 검토할 항목\n\n한국 스타트업과 중소 개발팀은 Skills 라이브러리 공유로 팀 표준화를 빠르게 만들 수 있다. 단점도 있다. 데스크톱 앱의 한국어 메뉴와 문서는 늦게 따라올 가능성이 높아 영어 CLI에 익숙한 개발자가 먼저 진입할 것이다. Skills가 OpenAI 서버로 sync되는 구조라서 사내 보안 정책에 따라 사용 가능 범위를 미리 정해야 하고, Automations는 무한 루프 실수를 막을 실행 limit을 설정하는 게 안전하다 (출처: openai.com/index/introducing-the-codex-app).",
        officialUrl: "https://openai.com/index/introducing-the-codex-app/",
        source: "https://openai.com/index/introducing-the-codex-app/",
        tags: ["Codex app", "Skills", "Automations", "OpenAI", "공식", "hero후보"],
        featured: true,
        thumbnail: {
          src: "/og-cache/openai-codex-goal-mode-generally-availab-62cd0085.png",
          alt: "공식 카드 썸네일",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
    },
    {
      rank: 5,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "I/O 2026 키노트 — Google이 Gemini를 'agentic 플랫폼'으로 다시 정의",
        slug: "io-2026-welcome-to-the-agentic-gemini-era",
        deck: "Sundar Pichai 직접 정리 — Gemini 3.5 Flash·Spark·agentic Search·TPU 8세대·Omni·SynthID 한 자리",
        summary: "Sundar Pichai가 직접 정리한 Google I/O 2026 키노트 요약. Gemini 3.5 Flash, Gemini Spark, agentic Search, TPU 8세대, Gemini Omni, SynthID 확장이 한 키노트에서 발표됐다. Google이 Gemini를 단순 챗봇 모델이 아니라 agentic 플랫폼으로 재정의한 발표.",
        content: "Sundar Pichai가 2026년 5월 19일 Google I/O 2026 키노트에서 \"agentic Gemini 시대\"를 직접 선언했다. 한 키노트 안에 모델·인프라·검색·앱·워터마크가 동시에 묶여 등장한 발표로, Google이 Gemini를 단일 챗봇 모델에서 제품 전반에 깔리는 agentic 플랫폼으로 재정의한 자리였다.\n\n한 자리에 발표된 6개 축은 다음과 같다.\n\n- Gemini 3.5 Flash — 가성비 모델 차세대, 더 빠른 추론\n- Gemini Spark — 사용자가 직접 조립하는 에이전트 빌더\n- agentic Search — 검색 결과가 링크가 아닌 다단계 작업 수행 에이전트\n- TPU 8세대 — Google 자체 추론 칩 신규 세대\n- Gemini Omni — 텍스트·이미지·오디오·영상 통합 영상 모델(별도 hero 카드 #1)\n- SynthID 확장 — AI 생성 콘텐츠 워터마크 시스템 확장\n\n## 모델 경쟁에서 플랫폼 경쟁으로\n\nGoogle의 전략 변화가 가장 큰 메시지다. 이전 분기까지 Gemini는 OpenAI·Anthropic과 경쟁하는 챗봇 모델로 평가됐지만, 이번 발표 이후로는 Search, Workspace, Cloud, Android, 검색 같은 기존 Google 제품에 자연스럽게 깔리는 인프라가 됐다. 모델 단품 품질로 다투는 게 아니라 \"이미 사용 중인 제품에 에이전트가 깔린다\"는 배포 우위 전략으로 전환했다. TPU 8세대는 같은 맥락에서 읽어야 한다. NVIDIA 의존도를 줄여 자체 추론 비용 구조를 만들겠다는 Google 인프라 자립 신호다.\n\n## agentic Search가 검색 패러다임을 바꾼다\n\nagentic Search는 25년 동안 유지된 검색 모델의 변곡점이다. 단순 키워드 매칭이 아니라 사용자가 위임한 다단계 작업(예약, 비교, 구매 같은)을 검색이 직접 수행한다. Perplexity와 ChatGPT Search가 일으킨 검색 패러다임 도전에 Google이 정면으로 응답한 카드다 (별도 feature 카드 #13).\n\n## Looking from Korea\n\n한국 사용자에게 진입 장벽은 거의 없다. Google 계정 그대로 사용할 수 있고, Gmail·Calendar·Docs 자동화로 한국 사무직 생산성에 바로 영향이 간다. 다만 한국어 agentic 정확도가 영어보다 늦게 따라오는 역대 패턴은 이번에도 반복될 가능성이 높다. 발표는 곧 일반 제공이 아니다. Gemini Omni Flash만 5월 19일 즉시 출시이고, 나머지 상당수는 \"수주 안에\" 풀린다는 일정이다. Spark 빌더가 일반 사용자도 에이전트를 만들 수 있게 한 부분, TPU 8세대가 외부 클라우드 고객에 공개되는 시점이 다음 분기 관전 포인트다 (출처: blog.google/innovation-and-ai/sundar-pichai-io-2026).",
        officialUrl: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        source: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        tags: ["Gemini", "Search", "Workspace", "Cloud", "Android", "TPU", "Google", "공식", "hero후보"],
        featured: true,
        thumbnail: {
          src: "/og-cache/i-o-2026-welcome-to-the-agentic-gemini-e-4283a2bd.png",
          alt: "I/O 2026: Welcome to the agentic Gemini era",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
    },
    {
      rank: 6,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Gemini API Managed Agents — Google이 클라우드 샌드박스형 에이전트를 API로 열었다",
        slug: "introducing-managed-agents-in-the-gemini-api",
        deck: "Antigravity 기반 에이전트를 Google 관리형 Linux 샌드박스에서 실행",
        summary: "Google이 Gemini API Managed Agents를 공개했다. 개발자가 직접 VM·브라우저·파일 시스템을 붙이지 않아도 Antigravity 기반 에이전트가 Google 관리형 Linux 샌드박스에서 코드 작성·명령 실행·브라우저 작업을 수행한다.",
        content: "Google이 2026년 5월 19일 I/O 키노트에서 Gemini API Managed Agents를 공개했다. 개발자가 직접 VM·브라우저·파일 시스템을 붙이지 않아도 Antigravity 기반 에이전트가 Google이 관리하는 Linux 샌드박스에서 코드 작성, 명령 실행, 브라우저 작업을 수행하는 구조다. Gemini API가 inference API에서 agent runtime API로 확장된 첫 공식 발표다.\n\n## inference API에서 runtime API로\n\n기존 Gemini API 사용 흐름은 모델 호출 → 출력 파싱 → 도구 호출 → 결과 합치기까지 개발자가 직접 조립해야 했다. Managed Agents는 그 실행 계층을 Google이 묶어 제공한다. 단순히 도구 호출 helper가 아니라 컨테이너·브라우저·파일 시스템이 통째로 따라온다는 점이 핵심이다.\n\n## OpenAI Codex·Claude Code·Vercel Sandbox와 같은 방향\n\n세 회사가 같은 방향으로 수렴 중이다. OpenAI는 Codex app + Skills + Automations, Anthropic은 Claude Code + Agent View, Google은 Managed Agents + Antigravity 2.0이다. 모델 단품 경쟁이 끝나고 실행 환경을 누가 더 잘 관리하느냐가 다음 라운드의 차별점이 된 셈이다. Vercel Sandbox 같은 PaaS 영역도 직접적인 압박을 받게 된다.\n\n## 한국 팀이 미리 잡아둘 항목\n\n사내 자동화, QA, 리서치 에이전트 구축 난도가 크게 낮아진다. 다만 코드와 문서가 Google 관리형 샌드박스에 올라가는 만큼, 사내 데이터 분류 정책과 로그 보관 정책을 먼저 정해야 한다. 한국어 웹 탐색과 문서 처리 정확도는 영어 대비 후순위로 따라오는 게 보통이라 한국어 시나리오 평가가 production 도입 전에 필요하다. 장기 실행 작업의 과금 모델, Antigravity와 Gemini API의 역할 분리도 release notes에서 확인할 항목이다 (출처: blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api).",
        officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
        source: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
        tags: ["Gemini API", "Managed Agents", "Antigravity", "공식", "hero후보"],
        featured: true,
        thumbnail: {
          src: "/og-cache/introducing-managed-agents-in-the-gemini-ac0ae172.png",
          alt: "Introducing Managed Agents in the Gemini API",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
    },
    {
      rank: 7,
      tier: "hero",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "NVIDIA Vera 도착 — 에이전트 전용으로 설계한 첫 CPU, top AI 랩에 출하",
        slug: "vera-arrives-nvidias-first-cpu-built-for-agents-lands-at-top",
        deck: "NVIDIA 첫 자체 CPU 'Vera' 출하 — Vera Rubin NVL72 통합 시스템, 에이전트 추론 최적화",
        summary: "NVIDIA가 자체 설계한 첫 CPU 'Vera' 를 top AI 랩에 출하했다. GPU 보조용이 아니라 에이전트 추론 워크로드 자체 처리용. Vera Rubin NVL72 통합 시스템으로 출시. 'NVIDIA = GPU 회사' 라는 정체성을 'NVIDIA = AI 인프라 풀스택 회사' 로 확장하는 신호.",
        content: "NVIDIA가 2026년 5월 18일 자체 설계한 첫 CPU 'Vera'를 OpenAI, Anthropic, Google DeepMind 등 top AI 랩에 출하하기 시작했다. GPU 보조용이 아니라 에이전트 추론 워크로드 자체를 처리하기 위한 칩이다. 동시에 발표된 Vera Rubin NVL72는 Vera CPU와 Rubin GPU를 단일 시스템으로 묶은 통합 박스로, 한 랙에 Rubin GPU 72개와 다수의 Vera CPU가 들어간다.\n\n## 왜 자체 CPU를 설계했나\n\n이전까지 NVIDIA는 GPU 회사였고 CPU는 Intel과 AMD가 맡았다. 2024-2025년 출시된 Grace CPU가 ARM 기반 데이터센터 CPU의 첫 시도였다면, Vera는 그 후속이다. 다단계 도구 호출, 메모리 관리, 컨텍스트 전환 같은 에이전트 추론 워크로드에 명령어 셋 단위로 최적화돼 있다. AI 데이터센터에서 Intel/AMD CPU 의존도를 점진적으로 0에 가깝게 가져가겠다는 의도가 분명하다.\n\n## Vera Rubin NVL72가 차세대 reference 시스템이 된다\n\n하이퍼스케일러가 자체 설계 대신 NVIDIA 통합 박스를 그대로 구매하는 흐름이 가속된다. 단순 GPU 판매가 아니라 랙 단위 시스템·네트워킹·CPU·소프트웨어 묶음 판매로 NVIDIA의 매출 단위가 한 단계 커진다. 에이전트 추론이라는 단어가 단순히 모델 호출이 아니라 CPU 역할이 크다는 점을 명시했다는 게 산업 메시지로 의미가 크다.\n\n## 삼성·SK하이닉스 HBM 직접 수혜\n\n한국 입장에서 가장 직접적인 영향은 메모리 공급이다. Rubin GPU에 들어가는 HBM은 삼성 HBM3e/HBM4와 SK하이닉스 HBM이 핵심이다. NVL72 보급이 가속되면 국내 메모리 공급이 함께 늘어난다. 국내 AI 인프라 구축에서 NVL72 단위 구매는 가격이 천문학적이라 검토 단계지만, 통신사·금융·정부 데이터센터의 단가 협상 시계가 빨라질 가능성이 있다.\n\n## 다음 분기에 추적할 항목\n\nVera CPU의 단독 판매 정책, Rubin GPU 묶음 판매 비중, ARM → x86 소프트웨어 호환성 마이그레이션 진행도가 핵심이다. 2026년 하반기 Vera Rubin NVL72 일반 출하 시점이 NVIDIA 매출 가속의 변곡점이 되고, 같은 회차 hero #8에서 다룬 Q1 FY27 Data Center 752억 달러 실적의 다음 분기 가이던스에 바로 반영된다 (출처: blogs.nvidia.com/blog/vera-cpu-delivery).",
        officialUrl: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
        source: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
        tags: ["NVIDIA Vera CPU", "Vera Rubin NVL72", "agentic AI infrastructure", "삼성 HBM", "SK하이닉스", "공식", "hero후보"],
        featured: true,
        thumbnail: {
          src: "/og-cache/vera-arrives-nvidia-s-first-cpu-built-fo-2dd68315.jpg",
          alt: "Vera Arrives: NVIDIA's First CPU Built for Agents Lands at Top AI Labs",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "NVIDIA",
    },
    {
      rank: 8,
      tier: "hero",
      post: {
        date: "5/20",
        platform: "X+Threads",
        title: "NVIDIA Q1 FY27 — Data Center 매출이 AI factory 수요를 다시 증명했다",
        slug: "nvidia-announces-financial-results-for-first-quarter-fiscal-",
        deck: "Data Center·Blackwell·AI factory 수요가 실적으로 확인됐다",
        summary: "NVIDIA가 FY2027 1분기 실적을 발표했다. Data Center와 Blackwell 수요가 핵심이며, AI factory 투자가 여전히 강하다는 점을 수치로 보여준다. Vera CPU·Rubin 전환의 재무적 근거가 되는 카드.",
        content: "NVIDIA가 2026년 5월 20일 FY2027 1분기 실적을 발표했다. 이번 회차에서 중요한 이유는 분기 매출 숫자 자체보다, Data Center 매출 752억 달러가 AI factory 수요가 여전히 꺾이지 않았음을 수치로 증명했다는 점이다. 같은 주 발표된 Vera CPU 출하(별도 hero 카드 #7)의 재무적 근거가 되는 카드이기도 하다.\n\n## 실험 지출에서 설비투자로\n\nAI 인프라 지출의 성격이 달라졌다. 이전까지 \"AI 실험에 얼마 쓰는가\" 차원이었다면, 이번 분기 수치는 기업·클라우드·국가 단위의 설비투자 라인으로 굳었다는 신호다. NVIDIA는 GPU 단품이 아니라 랙 단위 시스템 + 네트워킹 + CPU + 소프트웨어를 묶어 판매하는 구조로 매출 단위를 키우고 있다. Vera Rubin NVL72가 그 묶음 판매의 대표 SKU다.\n\n## 추론 비용이 모델 경쟁의 진짜 병목\n\n모델이 좋아질수록 추론 비용과 데이터센터 공급이 다음 병목이 된다. OpenAI, Anthropic, Google이 같은 분기에 agent runtime을 밀어붙이는 이유도 결국 추론 단가를 어떻게 잡느냐의 싸움이다. 강한 실적은 AI 서비스 수요가 아직 가속 구간에 있다는 뜻이고, 동시에 추론 인프라 부족이 다음 분기 가이던스의 가장 큰 변수가 된다.\n\n## 한국 메모리 산업과 데이터센터 투자에 직결\n\n삼성전자와 SK하이닉스의 HBM 수요가 직접 영향을 받는다. 국내 데이터센터 투자 결정, 통신사와 대기업의 AI 인프라 전략, 정부 AI 컴퓨팅 예산도 같은 시계열에서 움직인다. Blackwell 공급 병목과 중국 수출 제한 영향이 다음 분기 가이던스에 어떻게 반영되는지, Vera/Rubin 세대 전환이 매출 가속을 만드는지가 추적 포인트다 (출처: nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027).",
        officialUrl: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
        source: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
        tags: ["NVIDIA Data Center", "AI factories", "Blackwell", "공식", "hero후보"],
        featured: true,
        thumbnail: {
          src: "/og-cache/nvidia-announces-financial-results-for-f-b2ddd86c.jpg",
          alt: "NVIDIA Announces Financial Results for First Quarter Fiscal 2027",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "NVIDIA",
    },
    {
      rank: 9,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Anthropic Project Glasswing — Claude가 1만+ 보안 취약점 발견 (초기 결과)",
        slug: "project-glasswing-an-initial-update",
        deck: "AI가 직접 보안 취약점을 사냥 — 파트너사 코드에서 high/critical 1만 건+ 발견",
        summary: "Anthropic이 Project Glasswing(Claude Mythos Preview 기반 보안 연구 프로그램) 초기 결과를 공개. 파트너 회사들이 Claude 를 보안 취약점 탐지에 활용한 결과 high/critical 등급 취약점 1만 건 이상 발견. AI가 사람보다 빠르게 코드베이스의 잠재 보안 결함을 사냥하는 시대 신호.",
        content: "Anthropic이 2026년 5월 22일 Project Glasswing 초기 업데이트를 공개했다. 2025년 말부터 시작된 보안 연구 프로그램으로, 차세대 Claude 모델인 Mythos Preview를 파트너 회사들에 제공해 그들 코드베이스의 보안 취약점을 탐지하게 한 뒤 결과를 모아 모델 개선에 활용하는 구조다. 이번 업데이트에서 파트너사들이 발견한 high/critical 등급 취약점이 1만 건 이상으로 집계됐다. 일부는 이미 패치가 완료됐고, 일부는 coordinated disclosure가 진행 중이다.\n\n## 방법론 — 단일 라인이 아니라 chain을 본다\n\n전통적 정적 분석 도구(CodeQL, Semgrep)는 SQL injection 같은 단일 라인 결함을 잘 잡지만, 여러 컴포넌트 상호작용으로 인한 권한 우회는 놓치기 쉽다. Claude Mythos Preview는 인증 로직 + 세션 관리 + 캐시 정책 같이 세 컴포넌트가 묶여야 드러나는 chain 취약점을 찾는다. 코드베이스 전체를 읽고 다단계 추론으로 결함을 엮어내는 능력이 차별점이다.\n\n## offense와 defense가 동시에 가속된다\n\n같은 능력이 공격자 손에 들어가면 1만 건 취약점은 그대로 1만 건 공격 벡터가 된다. AI 보안은 dual-use라는 점을 가장 분명하게 보여준 사례다. Anthropic이 Constitutional AI 프레임 안에서 안전한 disclosure 프로토콜로 이 능력을 묶은 이유이기도 하다. Claude Mythos Preview의 실전 성능이 단순 코딩이 아니라 보안 도메인에서도 작동한다는 점도 이번 발표로 노출됐다.\n\n## KISA·KrCERT 파트너십 가능성\n\n국내 SI 업체, 은행, 통신사의 레거시 코드베이스에 즉시 적용할 수 있는 종류의 도구다. 다만 한국어 주석과 한국어 변수명이 섞인 코드의 정확도는 영어 대비 떨어질 가능성이 있어 첫 도입 전 한국어 시나리오 평가가 필요하다. KISA와 KrCERT가 한국 파트너로 같은 프로그램에 참여하면 국내 기업이 가장 직접적인 수혜를 받게 된다.\n\n## 추적할 항목\n\n1만 건이라는 숫자만 공개됐고 어떤 회사들이 참여했는지, 어느 코드베이스인지, false positive 비율은 얼마인지 모두 NDA로 가려져 있다. 실제 critical 비중과 Claude Mythos Preview의 일반 공개 시점이 다음 단계의 핵심 정보가 된다. 현재는 Anthropic이 직접 파트너에게만 제공하고 있다 (출처: anthropic.com/research/glasswing-initial-update).",
        officialUrl: "https://www.anthropic.com/research/glasswing-initial-update",
        source: "https://www.anthropic.com/research/glasswing-initial-update",
        tags: ["Project Glasswing", "security", "Claude Mythos Preview", "Anthropic", "공식", "hero후보"],
        featured: true,
        thumbnail: {
          src: "/og-cache/project-glasswing-an-initial-update-ade080fa.jpg",
          alt: "Project Glasswing: An initial update",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
    },
    {
      rank: 10,
      tier: "feature",
      post: {
        date: "5/11",
        platform: "X+Threads",
        title: "Claude Code Agent View — 병렬 에이전트를 한 화면에서 관리하는 실험",
        slug: "claude-code-agent-view-research-preview",
        deck: "Claude Code가 단일 터미널을 넘어 병렬 세션 관제 화면으로 확장",
        summary: "Anthropic이 Claude Code Agent View를 Research Preview로 공개했다. 여러 Claude Code 세션을 한 화면에서 관리하고 백그라운드 작업을 추적하는 흐름으로, Claude Code가 단일 CLI에서 에이전트 운영 콘솔로 이동하는 신호다.",
        content: "Anthropic이 2026년 5월 11일 Claude Code Agent View를 Research Preview로 공개했다. 여러 Claude Code 세션을 한 화면에서 보고 관리하는 콘솔형 인터페이스로, Claude Code가 단일 터미널 CLI에서 다중 에이전트 운영 도구로 옮겨가는 첫 가시화 단계다.\n\n## 다음 병목은 모델이 아니라 orchestration\n\nAI 코딩의 다음 병목은 모델 성능이 아니라 여러 작업을 동시에 굴리는 oversight 비용이다. 리서치, 구현, 테스트, 리뷰가 동시에 움직이면 사람에게 필요한 건 대화 로그가 아니라 상태판이다. Agent View는 그 상태판 역할을 시도하는 첫 공식 도구다. 같은 흐름에서 manaflow-ai/cmux, Codex CLI 같은 외부 도구가 이미 존재했지만, Claude 본가가 직접 콘솔을 내놓은 게 신호다.\n\n## 한국 소규모 팀에서 즉시 쓸 만한 시나리오\n\n2~5명 규모 팀이 여러 이슈를 동시에 처리할 때 유용하다. 한 화면에서 누가 어떤 작업을 돌리는지 보이기 때문에 인계와 검수가 빨라진다. 단 파일 충돌, 테스트 실행 순서, commit ownership을 미리 정해두지 않으면 병렬화가 오히려 비용이 된다.\n\n## 추적할 항목\n\nResearch Preview 안정성, background session 고정 기능의 한계, cmux/tmux와의 역할 분담, 병렬 작업에서 human review gate를 어디에 두는지가 다음 업데이트에서 확인할 부분이다 (출처: anthropic.com/news).",
        officialUrl: "https://www.anthropic.com/news",
        source: "https://www.anthropic.com/news",
        tags: ["Claude Code", "Agent View", "multi-agent CLI", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/claude-code-agent-view-research-preview-1cd2fb14.jpg",
          alt: "Claude Code Agent View (Research Preview)",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
    },
    {
      rank: 11,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Gemini 3.5 Flash 출시 — 가성비 모델 차세대가 agentic 흐름 받침대로",
        slug: "gemini-3-5-flash-release",
        deck: "I/O 2026의 가성비 모델 신세대 — 빠른 추론으로 agentic 도구 호출 회전수 끌어올림",
        summary: "Google이 I/O 2026에서 Gemini 3.5 Flash를 공개했다. 같은 키노트의 agentic Search·Managed Agents·Spark 가 다중 도구 호출 회전수에 의존하는데, 3.5 Flash가 그 회전수를 올려주는 받침대 역할.",
        content: "Google이 2026년 5월 19일 I/O 키노트에서 Gemini 3.5 Flash를 공개했다. 이전 2.x Flash 대비 추론 latency를 줄이고 도구 호출 응답성을 끌어올린 가성비 모델의 차세대 버전이다. 가격은 Flash 라인 정책을 유지하고, Workspace·Search·AI Studio에 자동 적용된다.\n\n## agentic 도구 호출의 회전수를 끌어올리는 받침대\n\n같은 키노트에서 발표된 Managed Agents, agentic Search, Spark는 모두 다중 도구 호출과 실시간 응답에 의존한다. 모델 한 번 부르고 끝나는 게 아니라 다중 turn으로 도구·검색·실행을 반복하는 구조라 latency 1초가 사용자 체감을 크게 바꾼다. 3.5 Flash는 단독 발표가 아니라 그 회전수를 끌어올리는 받침대 역할이다. agentic 인프라 전체의 성능을 끌어올리는 인프라성 업데이트로 봐야 한다.\n\n## Korean 사용자가 가장 빨리 체감하는 부분\n\nGmail, Calendar, Docs 안에서 작동하는 Gemini가 자동으로 3.5 Flash로 전환된다. 한국어 응답 속도 개선이 가장 먼저 체감되는 채널이다. API 사용자는 가격이 동일하고 속도만 올라가서 기존 코드를 바꾸지 않아도 이득을 본다.\n\n## Pro와의 trade-off\n\nFlash 라인의 역대 패턴은 영어 우선이라 한국어 reasoning 깊이는 Pro와 차이가 날 수 있다. Pro 대비 reasoning trade-off가 agentic 시나리오에서 실패율을 높이는지가 첫 모니터링 항목이다. agentic 도구 호출이 retry를 자주 일으키면 가격 동일이라도 호출 수 폭증으로 비용이 튈 수 있어 사용량 limit을 미리 잡아두는 편이 안전하다 (출처: blog.google/innovation-and-ai/sundar-pichai-io-2026).",
        officialUrl: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        source: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        tags: ["Google", "Gemini 3.5 Flash", "model release", "agentic", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/i-o-2026-welcome-to-the-agentic-gemini-e-4283a2bd.png",
          alt: "Gemini 3.5 Flash — I/O 2026 키노트",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
    },
    {
      rank: 12,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Gemini Spark 공개 — 일반 사용자가 직접 에이전트를 조립하는 빌더",
        slug: "gemini-spark-agent-builder",
        deck: "노코드에 가까운 에이전트 빌더로 일반 사용자가 자기 워크플로를 직접 만든다",
        summary: "Google이 I/O 2026에서 Gemini Spark 를 공개했다. 사용자가 도구·트리거·메모리를 직접 조립해 에이전트를 만드는 빌더. agent 가 개발자만의 영역에서 일반 사용자 영역으로 내려오는 변곡점.",
        content: "Google이 2026년 5월 19일 I/O 키노트에서 Gemini Spark를 공개했다. 일반 사용자가 코드 없이 자기 에이전트를 직접 조립하는 빌더 도구다. Gmail 답장, Calendar 자동 정리, 반복 검색 자동화 같은 시나리오를 트리거 → 도구 → 출력 형식으로 클릭만으로 구성할 수 있다.\n\n## 개발자 영역에서 일반 사용자 영역으로 내려온다\n\nSpark는 OpenAI GPT Builder, Anthropic Claude Skills와 같은 결의 발표다. 세 회사가 모두 \"에이전트를 만드는 일\"을 일반 사용자에게 내려보내려 한다. Google이 다른 두 회사보다 진입 장벽이 낮은 이유는 분명하다. 이미 쓰고 있는 Google 계정·Workspace·검색에 자동 연결돼서, 새 서비스에 가입하거나 새 인증을 거칠 필요가 없다. 에이전트가 개발자만의 영역에서 사무직 일반 사용자의 영역으로 내려오는 변곡점이다.\n\n## 한국 사무직에서 가장 먼저 자리 잡을 시나리오\n\nGmail, Calendar, Docs 자동화는 한국 사무직에 즉시 적용 가능하다. 회의록 정리, 정기 보고서 초안, 반복 메일 답변, 일정 충돌 점검 같은 패턴이 빌더 첫 사용층이 될 가능성이 높다. 단점은 익숙한 패턴이다. 빌더 UI 한국어 번역과 한국어 작업 정확도가 영어보다 늦게 따라오는 역대 흐름이 이번에도 반복될 것이다.\n\n## 마켓플레이스 여부가 다음 변곡점\n\nSkills와 Memory가 영구 저장될 때의 권한·프라이버시 정책, Spark가 OpenAI GPT Builder보다 깊이 들어가는지(트리거와 백그라운드 작업 같은), 일반 사용자가 만든 에이전트를 다른 사용자와 공유하는 마켓플레이스 모델이 나오는지가 다음 12개월의 핵심 관전 포인트다 (출처: blog.google/innovation-and-ai/sundar-pichai-io-2026).",
        officialUrl: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        source: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        tags: ["Google", "Gemini Spark", "agent builder", "no-code", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/i-o-2026-welcome-to-the-agentic-gemini-e-4283a2bd.png",
          alt: "Gemini Spark — 일반 사용자 에이전트 빌더",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
    },
    {
      rank: 13,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "agentic Search — Google 검색이 단순 링크에서 다단계 작업 수행으로",
        slug: "agentic-search-google-2026",
        deck: "검색 결과가 링크 나열이 아니라 사용자 작업을 대신 수행하는 에이전트로 진화",
        summary: "Google이 I/O 2026에서 agentic Search 를 공개했다. 검색이 정보 탐색 단계를 넘어 사용자가 요청한 작업(예약·비교·구매)을 다단계로 직접 수행하는 단계로 이동. 25년 역사상 검색 산업 가장 큰 패러다임 변화.",
        content: "Google이 2026년 5월 19일 I/O 키노트에서 agentic Search를 공개했다. 검색창에 \"다음 주 수요일 강남에서 4명 일식집 예약\" 같은 복합 요청을 넣으면 Google 검색이 후보 검색 → 비교 → 예약 페이지 진입 → 폼 작성까지 다단계로 수행하는 구조다. 25년 동안 유지된 \"링크 인덱스\" 모델이 \"작업 수행 인프라\"로 옮겨가는 분기점이다.\n\n## SEO 패러다임이 흔들린다\n\n이전 검색은 키워드 매칭으로 링크 10개를 노출하고 사용자가 직접 클릭·비교·작업했다. agentic Search는 의도 이해로 다중 도구와 사이트를 자동 호출해 결과 자체를 반환한다. 사용자가 링크를 클릭하지 않으면 검색 광고와 SEO 트래픽 모델이 바뀐다. Cloudflare를 비롯한 인프라 회사들이 \"AI bot 트래픽 vs 실제 방문 트래픽\"을 추적하기 시작한 이유다.\n\n## Perplexity·ChatGPT Search와 정면 충돌\n\nPerplexity와 ChatGPT Search가 일으킨 새로운 검색 경험에 Google이 마침내 정면으로 응답한 카드다. Google의 무기는 모델 품질이 아니라 분배 우위다. Chrome 점유율, Android 기본 검색, Workspace 사용자 기반 위에 agentic 능력을 얹는 식이다. 검색 산업 전체의 stack이 재정의되는 구간이다.\n\n## 네이버·다음·국내 e-commerce에 미치는 영향\n\n네이버와 다음이 한국 검색 시장에서 차지하던 점유율에 직접적인 위협이다. 더 큰 변수는 한국 e-commerce와 예약 사이트가 agentic 호출에 대응하지 않으면 트래픽 자체가 잘려나간다는 점이다. 사람이 사이트를 직접 방문하지 않고 에이전트가 대신 탐색하면 페이지뷰 기반 광고 수익 구조가 깨진다. 한국어 agentic Search 정확도는 영어 대비 늦을 가능성이 높지만, 일정 시점에 임계를 넘으면 전환은 빠르다.\n\n## 법적·책임 구조가 다음 12개월의 핵심\n\n어느 사이트와 파트너십을 체결하는지(예약·결제 통합), 잘못된 작업 수행 시 환불·취소 책임을 Google이 지는지 사용자가 지는지, Google 외 사이트의 트래픽 감소가 어떻게 측정되는지, 한국 시장 출시 시점이 다음 12개월의 추적 항목이다 (출처: blog.google/innovation-and-ai/sundar-pichai-io-2026).",
        officialUrl: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        source: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        tags: ["Google", "agentic Search", "검색 패러다임", "agent", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/i-o-2026-welcome-to-the-agentic-gemini-e-4283a2bd.png",
          alt: "agentic Search — Google 검색 패러다임 전환",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
    },
    {
      rank: 14,
      tier: "feature",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "Anthropic, Stainless 인수 — Claude 개발자 경험을 SDK 생성 레이어까지 가져간다",
        slug: "anthropic-acquires-stainless",
        deck: "SDK 생성·API 문서·MCP 연결 경험을 강화하는 개발자 플랫폼 인수",
        summary: "Anthropic이 Stainless를 인수했다. Stainless는 API SDK 생성과 개발자 경험 자동화에 강한 회사다. Claude API, SDK, CLI, MCP 생태계를 더 일관된 개발자 플랫폼으로 묶으려는 움직임이다.",
        content: "Anthropic이 2026년 5월 18일 Stainless를 인수했다고 발표했다. Stainless는 OpenAPI 스펙 한 벌에서 JavaScript·Python·Java·Go 같은 여러 언어 SDK와 문서를 자동 생성하는 개발자 도구 회사다. 이번 인수는 Anthropic이 모델 회사에서 개발자 플랫폼 회사로 무게중심을 옮기고 있다는 가장 분명한 신호다.\n\n## 전략적 의미\n\nClaude API, Claude Code, MCP, SDK가 일관된 개발자 경험으로 묶이려면 매일 쓰는 SDK 품질이 핵심이다. 모델 호출 코드 한 줄이 매끄럽지 않으면 기업 도입 속도가 느려진다. Stainless는 그 1-line 경험을 자동화하는 회사라 Anthropic 입장에서 가장 직접적인 보강 카드다. OpenAI가 자체 SDK 팀을 빠르게 확장한 것과 같은 결의 움직임으로 봐야 한다.\n\n## 통합 일정과 우선 언어\n\nAnthropic SDK가 Stainless 파이프라인으로 재생성되는 시점, MCP SDK와의 연결, OpenAI SDK와의 직접 비교 가능성이 첫 추적 항목이다. API breaking change를 어떻게 안내하고 마이그레이션 가이드를 제공하는지가 엔터프라이즈 신뢰도에 직결된다.\n\n## 한국 기업 도입 관점\n\n국내 기업이 Claude API를 제품에 넣을 때 JavaScript와 Python뿐 아니라 Java와 Go 같은 엔터프라이즈 언어 지원이 안정적인지가 사실상 의사 결정 기준이 된다. 금융·공공·통신처럼 JVM과 Go 생태계가 두꺼운 산업에서 SDK 품질이 도입 속도를 결정한다. Stainless 인수가 그 영역에서 어떤 속도 변화로 나타나는지 release notes를 추적할 가치가 있다 (출처: anthropic.com/news/anthropic-acquires-stainless).",
        officialUrl: "https://www.anthropic.com/news/anthropic-acquires-stainless",
        source: "https://www.anthropic.com/news/anthropic-acquires-stainless",
        tags: ["Claude Platform", "Stainless", "SDK", "MCP", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/anthropic-acquires-stainless-c7a48d62.jpg",
          alt: "Anthropic acquires Stainless",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
    },
    {
      rank: 15,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "KPMG 27.6만 명 Claude 도입 — 컨설팅 조직의 AI 운영체제 실험",
        slug: "kpmg-integrates-claude-across-its-core-business-and-workforc",
        deck: "Anthropic과 KPMG 전략 제휴 — 감사·세무·컨설팅 업무 전반에 Claude 확산",
        summary: "KPMG가 Anthropic과 전략 제휴를 맺고 27.6만 명 이상 인력에 Claude를 통합한다고 발표했다. 단순 챗봇 도입이 아니라 감사, 세무, 컨설팅 업무를 Claude 중심으로 재구성하려는 엔터프라이즈 AI 사례다.",
        content: "KPMG가 2026년 5월 19일 Anthropic과 전략 제휴를 맺고 전 세계 27.6만 명 이상 인력의 핵심 업무에 Claude를 통합한다고 발표했다. 단순 사내 챗봇 도입이 아니라 감사, 세무, 컨설팅 업무 프로세스 자체를 Claude 중심으로 재구성하려는 엔터프라이즈 AI 사례다.\n\n## 도입 규모와 범위\n\n27.6만 명은 컨설팅 산업 통틀어 단일 회사 도입 기준으로 최대 규모다. 초기 기업 AI 도입이 사내 챗봇이나 문서 요약 같은 주변부에 머물렀다면, KPMG 사례는 \"AI가 핵심 서비스 라인 자체로 들어간다\"는 메시지를 명확히 한다. 감사·세무·컨설팅은 그 자체로 KPMG 매출의 본체다.\n\n## 지식 노동 산업의 실험대\n\n전문 서비스 회사는 지식 노동의 대표 산업이다. 변호사, 회계사, 컨설턴트 같은 직무가 AI로 어디까지 자동화되는지, 어떤 부분에서 사람이 반드시 남는지가 KPMG 규모에서 처음 측정된다. 결과가 공개되든 비공개로 남든 다른 글로벌 회계법인과 컨설팅사가 같은 결정을 빠르게 따라할 가능성이 높다.\n\n## 한국 회계법인·컨설팅사에 미치는 압박\n\n삼정KPMG, 안진EY, 삼일PwC, 한영딜로이트, 그리고 국내 대기업 전략기획·재무팀에도 참고 사례가 된다. 본사 도입 결정이 한국 지사로 어떻게 내려오는지가 직접 영향이다. 다만 고객 데이터 처리, 감사 독립성, AI 산출물의 근거 추적, 잘못된 판단 시 책임 소재를 엄격히 설계하지 않으면 컴플라이언스 리스크가 더 크다.\n\n## 추적할 항목\n\n어떤 업무 시스템(감사 워크페이퍼 도구, 세무 신고 시스템, 컨설팅 프로젝트 관리)과 연결되는지, 결과물 검수 책임을 누가 지는지, 보안과 컴플라이언스 조건은 어떻게 잡았는지, 실제 생산성 수치를 공개하는지가 다음 분기의 핵심 정보다 (출처: anthropic.com/news/anthropic-kpmg).",
        officialUrl: "https://www.anthropic.com/news/anthropic-kpmg",
        source: "https://www.anthropic.com/news/anthropic-kpmg",
        tags: ["Claude", "Enterprise AI", "Managed Agents", "Claude Code", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/kpmg-integrates-claude-across-its-core-b-e02f19cc.jpg",
          alt: "KPMG integrates Claude across its core business and workforce of more than 276,000 in strategic alliance",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
    },
    {
      rank: 16,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Grok Build — xAI의 터미널 기반 parallel coding agent (early beta)",
        slug: "grok-build-xai의-터미널-기반-parallel-coding-agent-early-beta",
        deck: "xAI가 5/14 공개한 Grok Build CLI/TUI는 풀스크린 터미널 UI",
        summary: "xAI가 5/14 공개한 Grok Build CLI/TUI는 풀스크린 터미널 UI, 최대 8개 parallel sub-agent, Plan Mode, 131K~2M 컨텍스트를 지원한다. SuperGrok Heavy 구독자(월 $300, 프로모션 $99) 전용 early beta.",
        content: "xAI가 2026년 5월 14일 Grok Build CLI/TUI를 early beta로 공개했다. 터미널 기반 AI 코딩 에이전트로 풀스크린 TUI, 최대 8개 parallel sub-agent, Plan Mode, 131K~2M 컨텍스트를 지원한다. SuperGrok Heavy 구독자 전용으로 월 300달러, 6개월 프로모션 시 99달러. 설치는 `curl -fsSL https://x.ai/cli/install.sh | bash` 한 줄이다.\n\n공식 검증된 주요 기능은 다음과 같다.\n\n- TUI: 풀스크린, 마우스 지원, Vim-like 단축키, 실시간 diff, 멀티 창\n- Plan Mode: 작업 계획을 먼저 제시하고 개발자가 수정·승인 후 실행\n- Parallel Sub-agent: 최대 8개 에이전트가 동시 독립 작업\n- 컨텍스트: 131K~2M 토큰 (자료별 편차 존재)\n- Git 통합, 멀티 파일 편집, Shell 실행, X 실시간 검색\n\n## Claude Code · Codex CLI와 정량 비교\n\n해외 리뷰 자료(eigent.ai, rejoicehub)를 기준으로 정리하면 차이가 분명하다.\n\n| 항목 | Grok Build | Claude Code | Codex CLI |\n|---|---|---|---|\n| 인터페이스 | Terminal-first TUI (최고 평가) | Terminal + IDE | Terminal shell |\n| 병렬 에이전트 | 최대 8개 (강점) | 1~2개 | 제한적 |\n| Plan Mode | 그래프 + 직접 편집 | 선형 텍스트 | 기본 |\n| 실행 속도 | 가장 빠름 | 계획에서 상대적 느림 | 중간 |\n| Reasoning | 빠른 실행 중심 | 가장 우수 (deep reasoning) | 중간~좋음 |\n| 대형 코드베이스 | 모듈러 강함 | monorepo / legacy 최고 | 중간 |\n| SWE-Bench | ~51% | ~57% | ~54% |\n| Best For | 빠른 prototyping, 대형 리팩토링 | 복잡한 refactoring, 코드 품질 | OpenAI 생태계, 가성비 |\n\n## 강점과 한계\n\n초기 사용자 평가는 \"지금까지 본 AI CLI 중 최고의 TUI\"와 \"parallel agent로 대형 작업 속도가 압도적\"으로 모인다. 반대편에는 early beta 단계라는 안정성 우려, 월 300달러 진입 장벽, 복잡한 reasoning에서 Claude Code에 뒤진다는 평가가 함께 있다. SWE-Bench 점수 차이(51% vs 57%)가 그 격차를 정량적으로 보여준다.\n\n## 한 줄 정리\n\n터미널 중심 parallel agentic 코딩 도구로 TUI와 속도가 차별점이지만, early beta 단계이며 복잡한 reasoning은 Claude Code가 앞선다는 평가가 지배적이다. Vercel AI Gateway에도 Grok Build 0.1이 추가돼 외부 통합 채널은 이미 열려 있다 (출처: x.ai/news/grok-build-cli, docs.x.ai/developers/release-notes).",
        officialUrl: "https://x.ai/news/grok-build-cli",
        source: "https://docs.x.ai/developers/release-notes",
        backupUrls: [
          { label: "xAI 공식 — Grok Build CLI 발표", url: "https://x.ai/news/grok-build-cli" },
          { label: "xAI 공식 — x.ai/cli", url: "https://x.ai/cli" },
          { label: "xAI Release Notes", url: "https://docs.x.ai/developers/release-notes" },
          { label: "Grok Build 0.1 model docs", url: "https://docs.x.ai/developers/models/grok-build-0.1" },
          { label: "eigent.ai — 비교 리뷰", url: "https://eigent.ai/blog/grok-build-cli" },
          { label: "rejoicehub — 비교 리뷰", url: "https://rejoicehub.com/blogs/grok-build-vs-claude-code-vs-codex-cli" },
          { label: "Vercel AI Gateway 추가", url: "https://vercel.com/changelog/grok-build-0-1-now-available-on-vercel-ai-gateway" },
        ],
        tags: ["xAI", "Grok Build", "CLI", "TUI", "parallel agent", "공식", "hero후보"],
        featured: true,
        thumbnail: {
          src: "/og-cache/grok-build-0-1-now-available-on-vercel-a-b7c5d45d.png",
          alt: "공식 카드 썸네일",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "xAI",
      editorial: "Grok Build 발표용 정리 — 공식 + 해외 비교 리뷰 통합, 발표 슬라이드 그대로 사용 가능.",
    },
    {
      rank: 17,
      tier: "feature",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "Krea 2 전체 공개 — 이미지 생성 도구 경쟁이 다시 실사용 단계로 이동",
        slug: "krea-2-is-live-for-everyone",
        deck: "Krea 2가 모든 사용자에게 열리고 한시적 무제한 생성을 제공",
        summary: "Krea가 Krea 2를 전체 사용자에게 공개했다. 한 주 동안 모든 가입자에게 무제한 생성을 제공하며 이미지 생성·편집 워크플로를 대중 사용자에게 넓히는 업데이트다.",
        content: "Krea가 2026년 5월 18일 Krea 2를 전체 사용자에게 공개했다. 한시적으로 모든 가입자에게 무제한 생성을 제공하면서 모델 품질, 반복 속도, UI, 편집 흐름을 직접 비교해 볼 수 있게 했다. Krea는 이미지 생성과 편집을 빠르게 반복하는 크리에이티브 도구다.\n\n## 이미지 생성 도구 시장의 역할 분담\n\n현재 이미지 생성 시장은 GPT Image, Recraft, Midjourney, Adobe Firefly, Krea가 각자 다른 영역에서 강점을 가진다. Midjourney는 아트워크 품질, GPT Image는 자연어 편집과 인페인트, Adobe Firefly는 상업 안전성과 Creative Cloud 통합, Krea는 빠른 실험과 편집 워크플로다. 이번 전면 공개로 그 차별점을 사용자가 직접 체감할 기회가 생겼다.\n\n## 한국 제작자에게 즉시 쓸 만한 시나리오\n\n썸네일, 발표자료, SNS 카드, 상세페이지 비주얼을 빠르게 뽑는 제작자에게 유용하다. 특히 같은 회차에 발표된 LoRA training(rank 18)과 묶으면 브랜드·캐릭터 일관성을 자체적으로 잡을 수 있는 작은 파이프라인이 된다.\n\n## 검증해야 할 항목\n\n한글 텍스트 렌더링은 글로벌 이미지 모델의 약점이라 실제 출력에서 깨짐 여부를 먼저 봐야 한다. 상업 사용 라이선스, 무제한 기간 종료 후의 유료 제한 범위, LoRA training과 함께 쓸 때의 품질 안정성이 도입 결정의 핵심 변수다 (출처: krea.ai/release-notes/krea-2-is-live-for-everyone).",
        officialUrl: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
        source: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
        tags: ["Krea 2", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/krea-2-is-live-for-everyone-b5dfeabe.webp",
          alt: "Krea 2 is live for everyone",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Krea",
    },
    {
      rank: 18,
      tier: "feature",
      post: {
        date: "5/21",
        platform: "X+Threads",
        title: "Krea 2 LoRA Training — 브랜드·캐릭터 스타일을 직접 학습하는 제작 워크플로",
        slug: "krea-2-lora-training-is-here",
        deck: "소수 이미지로 스타일·캐릭터·오브젝트 LoRA를 학습하고 강도 조절·다중 스택까지 지원",
        summary: "Krea 2가 LoRA training을 지원한다. 사용자는 소수 이미지로 특정 스타일, 캐릭터, 제품 오브젝트를 학습하고 생성 시 강도를 조절할 수 있다.",
        content: "Krea가 2026년 5월 21일 Krea 2에 LoRA training 기능을 추가했다. LoRA(Low-Rank Adaptation)는 대형 이미지 모델 전체를 다시 학습하지 않고 특정 스타일·캐릭터·제품 특징만 가볍게 학습하는 방식이다. 사용자는 몇 장의 참고 이미지로 자신만의 스타일 모듈을 만들고, 생성 시 강도를 조절하고, 여러 LoRA를 겹쳐 쓰는 multi-LoRA stacking까지 활용할 수 있다.\n\n## AI 이미지의 만성 약점인 일관성 문제\n\nAI 이미지 도구의 가장 큰 약점은 일관성이다. 같은 브랜드, 같은 캐릭터, 같은 제품처럼 유지하기가 까다롭다. LoRA training은 그 문제를 제작자 단위에서 직접 해결하는 도구다. 모델 회사가 모든 브랜드를 다 학습할 수는 없으니, 사용자가 자기 자산으로 작은 모듈을 만드는 게 현실적인 답이 된다.\n\n## 한국 제작자가 즉시 쓸 만한 활용처\n\n브랜드 SNS 카드, 유튜브 썸네일, 자체 캐릭터 IP, 쇼핑몰 제품컷 변형이 가장 빠른 적용 영역이다. 동일 브랜드 톤을 유지한 채로 캠페인별 변형을 빠르게 만들 수 있다. GPT Image의 자연어 편집과는 역할이 다르다. GPT Image는 한 컷의 부분 수정에 강하고, LoRA는 여러 컷에 걸친 톤 일관성에 강하다.\n\n## 권리 문제는 도입 전에 정리해야 한다\n\n타인의 캐릭터, 브랜드 이미지, 작가의 작품을 무단으로 학습시키면 권리 문제가 발생한다. 자기 회사의 이미지 자산만 학습 대상으로 삼는 정책을 먼저 정해야 한다. 한글이 포함된 이미지로 LoRA를 학습할 때 한글 자체가 깨지지 않는지, LoRA 강도 조절이 어떤 단계에서 자연스러운지, GPT Image 편집 기능과 함께 쓸 때의 워크플로 분담이 추적할 항목이다 (출처: krea.ai/release-notes/krea-2-lora-training-is-here).",
        officialUrl: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
        source: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
        tags: ["Krea 2", "LoRA training", "multi-LoRA stacking", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/krea-2-lora-training-is-here-17d6e9dc.webp",
          alt: "Krea 2 LoRA training is here",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Krea",
    },
    {
      rank: 19,
      tier: "feature",
      post: {
        date: "5/25",
        platform: "X+Threads",
        title: "Thinking Machines Interaction Models — 모델보다 상호작용 방식을 먼저 설계한다",
        slug: "thinking-machines-interaction-models-official-demo-blog",
        deck: "AI 제품의 핵심을 모델 성능이 아니라 사용자가 모델과 일하는 인터페이스로 보는 관점",
        summary: "Thinking Machines가 Interaction Models 데모와 블로그를 공개했다. AI 제품의 차별점은 모델 자체보다 사람이 모델과 상호작용하는 구조, 즉 interaction model에 있다는 메시지다.",
        content: "Thinking Machines가 2026년 5월 25일 Interaction Models라는 글과 데모를 함께 공개했다. AI 제품의 차별점이 모델 성능이 아니라 사람이 모델과 일하는 인터페이스, 즉 interaction model에 있다는 관점이다. 같은 모델을 써도 사용자가 어떻게 지시하고 확인하고 수정하는지에 따라 제품 품질이 달라진다는 게 핵심 주장이다.\n\n## 채팅창 단일 UI의 한계\n\n초기 AI 제품은 채팅창 하나에 모든 것을 넣었다. Interaction Models 관점은 작업 상태, 선택지, 편집 가능성, 피드백 루프, 실패 복구를 UI 안에 명시적으로 설계한다. 에이전트가 길고 불확실한 작업을 할 때 사용자가 중간 상태를 이해하고 개입할 수 있어야 한다는 문제 인식이다.\n\n## Claude Code Agent View · cmux와 같은 결\n\n같은 회차에서 다뤄진 Claude Code Agent View(rank 10)와 manaflow-ai/cmux(editor's pick)도 정확히 같은 문제를 푼다. 채팅 한 줄짜리 인터페이스로는 다중 작업을 관리할 수 없다는 문제 의식이 산업 전반에서 동시에 떠오르고 있다. Thinking Machines의 글은 그 문제를 일반 원리 수준에서 정리한 글이라 다른 제품 설계에도 직접 적용 가능한 reference 텍스트가 된다.\n\n## 한국 제품팀이 먼저 봐야 할 부분\n\nAI 서비스를 만드는 팀이라면 프롬프트 튜닝보다 UX 설계를 먼저 봐야 한다. 업무용 에이전트는 무엇을 하고 있는지, 어디서 멈출 수 있는지, 어떻게 되돌릴지를 사용자에게 분명히 보여줘야 신뢰가 쌓인다. 한국 SaaS 시장에서 채팅 UI 일변도의 AI 제품이 빠르게 정체되는 흐름과 정확히 맞물린다 (출처: thinkingmachines.ai/blog/interaction-models).",
        officialUrl: "https://thinkingmachines.ai/blog/interaction-models/",
        source: "https://thinkingmachines.ai/blog/interaction-models/",
        tags: ["Thinking Machines", "interaction models", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/thinking-machines-interaction-models-off-1707227c.jpg",
          alt: "Thinking Machines Interaction Models — official demo + blog",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
    },
    {
      rank: 20,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Gemini app agentic 업데이트 — 24시간 먼저 챙기는 비서로 이동",
        slug: "the-gemini-app-becomes-more-agentic-delivering-proactive-247",
        deck: "Daily Brief·Omni·Spark·macOS 개선으로 Gemini 앱이 더 능동적인 개인 에이전트가 됨",
        summary: "Google이 Gemini 앱의 agentic 업데이트를 발표했다. Daily Brief, Omni 영상 생성, Spark 에이전트 기능, macOS 개선을 통해 Gemini 앱을 수동 챗봇이 아니라 먼저 제안하는 24/7 개인 비서로 재정의한다.",
        content: "Google이 2026년 5월 19일 Gemini 앱의 agentic 업데이트를 묶어 발표했다. Daily Brief, Gemini Omni 영상 기능, Spark 기반 에이전트 기능, macOS 앱 개선이 함께 묶였다. 사용자가 질문해야만 답하는 챗봇에서, 하루 일정·메일·작업 맥락을 바탕으로 먼저 제안하는 24/7 개인 비서 쪽으로 옮겨가는 흐름이다.\n\n## 모델 경쟁이 아니라 통합 경쟁\n\nAI 비서 경쟁의 본질이 모델 성능에서 개인 데이터와 앱 통합으로 옮겨가고 있다. Google이 가진 무기는 분명하다. Gmail, Calendar, Docs, Android, Search가 이미 한 계정 위에 묶여 있다는 점이다. OpenAI나 Anthropic이 같은 깊이의 통합을 만들려면 별도 데이터 연동 합의가 필요한 반면, Google은 자동으로 들어간다. Gemini 앱을 생활형 에이전트로 밀어붙이기에 가장 유리한 출발선이다.\n\n## Workspace 사용자가 가장 먼저 체감\n\nGoogle Workspace를 쓰는 조직과 개인에게 바로 체감될 가능성이 크다. 한국에서는 스타트업과 일부 대기업 부서, 교육 기관이 주된 대상이다. 다만 한국어 일정·메일 맥락 이해 정확도, 개인정보 동의 범위, 회사 계정 보안 정책을 먼저 확인해야 한다. proactive 기능이 기본 켜짐 상태인지, 사용자가 직접 켜야 하는지에 따라 위험도가 달라진다.\n\n## 점검할 항목\n\nGmail과 Calendar 접근 범위가 어디까지인지, macOS 앱 완성도가 정식 데스크톱급인지, Omni와 Spark가 같은 앱 안에서 얼마나 자연스럽게 연결되는지가 첫 사용 단계의 평가 기준이다. proactive 추천의 false positive가 잦으면 알림 피로감이 빨리 쌓일 수 있다 (출처: blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app).",
        officialUrl: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
        source: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
        tags: ["Gemini app", "Gemini 3.5 Flash", "Omni", "Daily Brief", "Spark", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/the-gemini-app-becomes-more-agentic-deli-8bec6d8c.jpg",
          alt: "The Gemini app becomes more agentic, delivering proactive, 24/7 help",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
    },
    {
      rank: 21,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Google AI Studio I/O 2026 — 아이디어를 앱으로 바꾸는 개발자 입구",
        slug: "bring-any-idea-to-life-google-ai-studio-at-io-2026",
        deck: "Workspace 연동·Android 앱 빌드·Antigravity export·무료 배포까지 묶은 AI Studio 업데이트",
        summary: "Google이 I/O 2026에서 AI Studio 업데이트를 발표했다. Workspace 통합, Android 앱 빌드, 모바일 사전등록, Antigravity export, 무료 배포를 묶어 아이디어를 실제 앱으로 옮기는 경로를 강화했다.",
        content: "Google이 2026년 5월 19일 I/O 키노트에서 Google AI Studio 업데이트를 공개했다. Workspace 통합, Android 앱 빌드, 모바일 사전등록, Antigravity export, 무료 배포(no-cost deployment)가 한 업데이트로 묶였다. Gemini API를 실험만 하던 도구에서 실제 앱 제작과 배포까지 이어주는 도구로 무게중심이 옮겨갔다.\n\n## 진짜 병목은 제품화\n\nAI 앱 개발의 병목은 모델 호출이 아니다. 인증, UI, 데이터 연결, 배포가 붙어야 비로소 사람이 쓰는 서비스가 된다. AI Studio는 Google 생태계 안에서 이 제품화 경로를 가장 짧게 만든다. 프롬프트 테스트 → 코드 export → Workspace 데이터 연결 → Android 앱 빌드까지 한 도구에서 이어진다.\n\n## Antigravity export가 만드는 연결\n\n핵심은 Antigravity export다. AI Studio에서 만든 프로토타입을 Antigravity 런타임으로 그대로 넘길 수 있다는 건, 실험과 production이 같은 도구 체인을 공유한다는 뜻이다. Vertex AI와의 관계 재정리, 무료 배포 한도, Android 앱 빌드 완성도가 첫 평가 항목이 된다.\n\n## 한국 비개발자도 접근 가능한 새 진입로\n\n개발자뿐 아니라 기획자, 교육자도 빠르게 프로토타입을 만들 수 있다. 한국 교육 시장에서 학생용 AI 앱 만들기 수업의 도구로 자리 잡을 가능성이 있다. 실제 상용 서비스로 가려면 개인정보 처리, 과금, 로그 보존, 한국어 품질 검증, Workspace 데이터 권한 관리를 별도로 점검해야 한다 (출처: blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026).",
        officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026/",
        source: "https://blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026/",
        tags: ["Google AI Studio", "Android", "Workspace", "Antigravity", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/bring-any-idea-to-life-google-ai-studio--66d64068.png",
          alt: "Bring any idea to life: Google AI Studio at I/O 2026",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
    },
    {
      rank: 22,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "I/O 2026 개발자 하이라이트 — Google이 agentic 개발 스택을 한 번에 묶었다",
        slug: "building-the-agentic-future-developer-highlights-from-io-202",
        deck: "Antigravity 2.0 · Managed Agents · AI Studio · XPRIZE Hackathon — 모델·실행·디버깅·커뮤니티가 한 발표에",
        summary: "Google이 I/O 2026 개발자 발표를 한 글로 묶어 정리했다. 모델(Gemini) · 실행 환경(Antigravity 2.0, Managed Agents) · 개발 도구(AI Studio) · 커뮤니티 챌린지(Build with Gemini XPRIZE Hackathon) 4개 축이 동시 등장. Google 이 agentic 개발 전체 스택을 자기 손에 묶으려는 명확한 신호.",
        content: "Google Developers 공식 블로그가 2026년 5월 19일 I/O 2026 키노트 직후 그날의 개발자 발표만 따로 묶어 정리한 글을 공개했다. Gemini 모델 자체 발표(별도 hero 카드인 Omni·3.5 Flash·Spark)와 분리해, 개발자가 실제 agentic 앱을 만들 때 쓰게 될 도구 묶음에 초점이 맞춰져 있다. 한 글에 4개 축이 함께 등장한다는 게 이 카드의 핵심이다.\n\n네 축은 다음과 같이 묶인다.\n\n- Antigravity 2.0: Google의 에이전트 런타임. 1.0 대비 도구 호출 latency, 메모리·세션 관리, 디버거 UX 개선. 외부 모델(Anthropic Claude 등)도 어댑터로 호출 가능\n- Gemini API Managed Agents: 별도 hero 카드 #6에서 다룬 발표. Google 관리형 Linux 샌드박스에서 에이전트 실행\n- Google AI Studio 통합: 모델 호출 + agent 빌드 + 배포 UI를 한 화면에. 이전엔 AI Studio(실험)와 Vertex AI(production)가 분리돼 있었는데 onboarding 흐름이 통합됨\n- Build with Gemini XPRIZE Hackathon: 1M USD 상금 글로벌 해커톤. agentic Search·Spark·Managed Agents 사용 의무화\n\n## API 단품에서 full stack 경쟁으로\n\n세 회사가 같은 방향으로 수렴하고 있다. OpenAI는 Codex app + Skills + Automations, Anthropic은 Claude Code + Agent View + Stainless SDK, Google은 이번 묶음이다. 모델만 팔지 않고 개발자 워크플로 전체를 묶어 판다는 패턴이 동일하다. AI 모델 한 줄짜리 API 시장은 이미 평준화됐고, 다음 라운드는 누가 더 매끄러운 stack을 제공하느냐 싸움이다.\n\n## Vercel·Cloudflare가 직접 압박을 받는다\n\nManaged Agents가 외부 호스팅 의존도를 줄이고 Google Cloud 안에서 워크로드가 끝나게 만든다. Vercel Agent, Cloudflare Workers AI 같은 PaaS 영역에서 직접 충돌이 일어난다. XPRIZE Hackathon은 단순 마케팅이 아니라 모델 학습 데이터 수확 통로다. 1M USD 상금으로 모인 수천 개 agentic use case가 Google의 다음 모델 학습/평가 셋으로 흘러간다.\n\n## 한국 팀 적용 시나리오와 trade-off\n\n국내 스타트업·SI·대기업 AI 팀이 이미 Google Cloud 위에서 작업 중이라면 이번 묶음은 즉시 실험 가능하다. 추가 vendor 도입 없이 AI Studio에서 Antigravity 런타임을 호출할 수 있다. 다만 두 가지를 미리 인식해야 한다. 첫째, 한국어 agentic 정확도는 영어보다 늦게 따라오는 역대 패턴이라 production 도입 전 한국어 시나리오 평가가 필요하다. 둘째, XPRIZE Hackathon에 한국 팀이 참가하면 한국어 agentic use case 데이터가 Google에 노출되는 trade-off를 받아들여야 한다.\n\n## 추적해야 할 항목\n\nAntigravity 2.0의 외부 모델 어댑터가 Anthropic Claude·OpenAI GPT까지 실제로 호출 가능한지(multi-model 전략 여부), Managed Agents의 데이터 위치와 권한 경계(한국 데이터 주권 이슈), AI Studio 통합이 Vertex AI를 흡수하는지 별도 채널로 유지되는지, XPRIZE Hackathon 평가 기준이 단순 데모인지 실서비스 배포인지가 다음 12개월의 관전 포인트다. 같은 회차의 hero 카드 #5(I/O agentic era), #6(Managed Agents API), #10(Spark), #11(agentic Search)을 함께 보면 전체 그림이 닫힌다 (출처: blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights).",
        officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
        source: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
        backupUrls: [
          { label: "Antigravity 2.0 — 공식 페이지", url: "https://antigravity.google.dev/" },
          { label: "Gemini API Managed Agents 공식 발표", url: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/" },
          { label: "Google AI Studio", url: "https://aistudio.google.com" },
          { label: "Build with Gemini XPRIZE Hackathon", url: "https://www.xprize.org/competitions/build-with-gemini" },
        ],
        tags: ["Antigravity 2.0", "Gemini API", "Managed Agents", "Google AI Studio", "XPRIZE", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/building-the-agentic-future-developer-hi-c8b5b49d.png",
          alt: "Building the agentic future: Developer highlights from I/O 2026",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
    },
    {
      rank: 23,
      tier: "feature",
      post: {
        date: "5/23",
        platform: "X+Threads",
        title: "OpenAI on AWS Bedrock — Codex와 Managed Agents가 AWS 고객에게 들어간다",
        slug: "openai-models-codex-and-managed-agents-on-amazon-bedrock",
        deck: "OpenAI 모델·Codex·Managed Agents를 Amazon Bedrock에서 쓰는 기업 배포 경로",
        summary: "OpenAI가 AWS와의 통합을 발표했다. OpenAI 모델, Codex, Managed Agents를 Amazon Bedrock에서 사용할 수 있게 하며 AWS 중심 기업 고객에게 OpenAI 에이전트 스택을 배포하는 길을 연다.",
        content: "OpenAI가 2026년 5월 23일 AWS와의 통합을 발표했다. OpenAI 모델, Codex, Managed Agents를 Amazon Bedrock에서 사용할 수 있게 하는 변화로, AWS 중심 기업 고객에게 OpenAI 에이전트 스택을 정식 배포 채널로 여는 발표다. Codex 7-day 확장 시리즈의 후반부 카드이기도 하다.\n\n## Microsoft Azure 단일 채널을 넘어\n\n기존 OpenAI 엔터프라이즈 배포는 사실상 Microsoft Azure 한 채널이 핵심이었다. Bedrock 통합은 그 lock-in을 완화하는 명확한 신호다. Azure 중심 전략과 AWS 채널의 균형이 어디서 잡히는지가 다음 12개월의 관전 포인트가 된다.\n\n## 기업 구매 체계 안으로 들어가는 코딩 에이전트\n\n기업은 모델 품질보다 조달, 보안, 로그, 권한, 지역, 청구 체계를 우선한다. Codex가 Bedrock에 들어간다는 건 코딩 에이전트도 기업 클라우드 구매 체계에 정식 SKU로 들어간다는 뜻이다. Bedrock Guardrails가 OpenAI 정책과 어떻게 결합되는지, Codex가 사내 repository 접근을 어떻게 처리하는지가 도입 결정의 핵심 기준이 된다.\n\n## AWS 중심 한국 기업에게 미치는 영향\n\n국내 대기업과 통신사 상당수가 AWS 기반 인프라를 쓴다. 이번 통합으로 OpenAI 기능을 별도 계약 절차 없이 사내 검토 단계까지 빠르게 끌어올 수 있게 된다. 다만 데이터 residency(한국 region에서 처리되는지), 로그 보존 기간, 사내 GitHub Enterprise repository 연결 권한은 별도 검토가 필요하다. 어떤 OpenAI 모델이 처음에 제공되는지, 한국 region에 언제 들어오는지가 첫 단계 정보다 (출처: openai.com/index/openai-on-aws).",
        officialUrl: "https://openai.com/index/openai-on-aws/",
        source: "https://openai.com/index/openai-on-aws/",
        tags: ["OpenAI", "AWS Bedrock", "Managed Agents", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/gpt-5-3-codex-is-now-the-base-model-for--d3b67286.png",
          alt: "공식 카드 썸네일",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
    },
    {
      rank: 24,
      tier: "feature",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "GitHub Actions 실패를 Copilot cloud agent가 한 번에 고친다",
        slug: "one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
        deck: "실패한 workflow에서 Copilot cloud agent가 원인 분석과 수정 PR까지 이어주는 기능",
        summary: "GitHub가 실패한 GitHub Actions workflow를 Copilot cloud agent로 한 번에 고치는 기능을 추가했다. CI 실패 로그를 읽고 원인을 분석한 뒤 수정 제안이나 PR로 이어주는 흐름이다.",
        content: "GitHub가 2026년 5월 18일 실패한 GitHub Actions workflow를 Copilot cloud agent로 한 번에 고치는 기능을 추가했다. CI 실패 화면에서 one-click으로 agent를 호출하면 repository 맥락과 workflow 로그를 함께 읽고 원인을 분석한 뒤 수정 제안이나 PR을 만들어준다.\n\n## 개발팀이 반복적으로 시간을 먹는 영역\n\n팀 단위에서 시간을 가장 많이 잡아먹는 일 중 하나가 CI 실패 처리다. dependency 버전 충돌, 테스트 깨짐, lint 오류, workflow 설정 누락 같은 문제는 패턴이 정해져 있어서 agent가 맡기 좋은 영역이다. 개발자가 로그를 열고 원인을 찾고 수정 커밋을 만드는 흐름이 그대로 agent 호출 한 번으로 압축된다.\n\n## 자동 merge는 위험하다\n\n한국 스타트업과 개발팀이 GitHub Actions를 쓴다면 즉시 유용한 기능이지만, agent가 만든 수정 PR을 자동 merge하는 워크플로는 위험하다. 배포 workflow, 시크릿 처리, 권한 관련 변경은 반드시 사람 리뷰가 들어가야 한다. flaky test를 실제 버그로 오판해서 잘못된 수정을 만드는 경우도 자주 발생한다.\n\n## 점검 항목\n\nworkflow secret에 어떤 범위까지 접근하는지, 수정 PR이 만들어지는 branch policy와 권한이 어떻게 설정되는지, flaky test와 실제 버그를 어떻게 구분하는지, GitHub Enterprise(자체 호스팅) 환경에 언제 제공되는지가 도입 전 확인 항목이다 (출처: github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent).",
        officialUrl: "https://github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
        source: "https://github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
        tags: ["GitHub Actions", "Copilot cloud agent", "공식"],
        featured: true,
        thumbnail: {
          src: "/og-cache/one-click-fixes-for-failing-actions-with-e02c868a.png",
          alt: "One-click fixes for failing Actions with Copilot cloud agent",
        },
      },
      sourceWeek: "2026-w21",
      sourceCompany: "GitHub",
    },
  ],
  editorsPicks: [
    {
      title: "tw93/Mole",
      slug: "tw93mole",
      deck: "AI CLI 잔재까지 치우는 macOS deep clean 도구",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/tw93/Mole",
      sourceLabel: "GitHub →",
      summary: "tw93/Mole은 macOS deep clean & optimize CLI다. Claude Code, Cursor Agent, GitHub Copilot CLI, Codex CLI 같은 AI agent 도구의 캐시·로그·세션 잔재까지 정리하는 업데이트가 들어가 실사용 가치가 크다.",
      body: "tw93가 만든 Mole은 macOS deep clean & optimize CLI다. node_modules, 빌드 캐시, 로그, 임시 파일을 한 번에 스캔하고 정리한다. 최근 업데이트에서 Claude Code, Cursor Agent, GitHub Copilot CLI, Codex CLI 같은 AI 에이전트 도구의 세션 로그와 캐시까지 정리 대상에 포함시킨 게 차별점이다.\n\n## 직접 쓰면서 느낀 가치\n\n디스크 용량 회수보다 더 중요한 건 반복 가능한 정리 루틴이다. AI CLI 도구가 늘어나면서 세션 로그, 캐시, 임시 conversation 파일이 빠르게 쌓이는데, 도구별로 일일이 경로를 찾아 지우는 건 번거롭다. Mole은 그 작업을 한 명령으로 묶어준다. 작업 전후로 가볍게 돌리는 습관과 잘 맞는다.\n\n## 사용 시 주의할 점\n\n정리 CLI의 본질은 삭제 도구다. 첫 실행에서는 dry-run 또는 출력 확인 후 진행하는 게 안전하다. 프로젝트 내부 산출물을 잘못 지우지 않도록 경로를 확인해야 하고, AI CLI 세션 로그 중에는 디버깅에 필요한 기록이 섞여 있을 수 있어 보존 정책을 미리 정하는 편이 좋다.",
      editorial: "직접 쓰는 macOS 정리 CLI.",
      tags: ["오픈소스", "직접사용"],
      tier: "feature",
      thumbnail: {
        src: "/og-cache/tw93-mole-macos-deep-clean-optimize-cli--74a86de7.jpg",
        alt: "tw93/Mole",
      },
    },
    {
      title: "Nutlope/hallmark",
      slug: "nutlopehallmark",
      deck: "AI 티 나는 UI 패턴을 걸러내는 anti-slop 디자인 스킬",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/Nutlope/hallmark",
      sourceLabel: "GitHub →",
      summary: "Nutlope/hallmark는 AI가 자주 만드는 generic SaaS 디자인, 과한 gradient, 의미 없는 glassmorphism 같은 패턴을 걸러내는 디자인 스킬이다. UI 작업의 기본 품질 게이트로 쓰기 좋다.",
      body: "Nutlope이 공개한 hallmark는 AI로 UI를 만들 때 반복되는 generic SaaS 디자인을 걸러내는 anti-slop 디자인 스킬이다. MIT 라이선스로 공개돼 있고, Together AI가 후원한다. 25개 anti-pattern 룰셋과 65-gate slop-test, 구조 다양성 평가가 묶여 있어 단순히 테마를 고르는 도구가 아니다.\n\n## 직접 쓰면서 골라낸 가치\n\n요즘 AI가 만든 UI는 빠르지만 거의 비슷하다. hero + 3 cards + gradient blob + glassmorphism + 무드 보드 한 장으로 끝나는 기본값이 반복된다. hallmark의 가치는 이 기본값을 의식적으로 거부하게 만드는 데 있다. 새 페이지, 랜딩, 대시보드를 만들 때 먼저 audit으로 점수화하거나 redesign 기준으로 적용하면 좋다.\n\n## 적용 방식\n\n특정 브랜드 톤이 필요할 때는 study 동사로 reference URL이나 스크린샷에서 design.md를 추출해 hallmark의 컨텍스트로 주입한다. 브랜드 픽셀 카피는 금지지만, 디자인 원칙과 토큰을 영감으로 가져오는 흐름이 적합하다. 도구가 디자인 감각을 대신하지는 않는다. 콘텐츠 구조, 제품 맥락, 사용자의 실제 행동을 먼저 잡은 뒤 hallmark이 안티패턴 게이트 역할을 하게 두는 게 맞다.",
      editorial: "직접 디자인 작업의 기본값으로 통합한 스킬.",
      tags: ["오픈소스", "직접사용"],
      tier: "feature",
      thumbnail: {
        src: "/og-cache/nutlope-hallmark-anti-ai-slop-디자인-가이드를-코-4fabea9d.jpg",
        alt: "Nutlope/hallmark",
      },
    },
    {
      title: "manaflow-ai/cmux",
      slug: "manaflow-aicmux",
      deck: "여러 agent/CLI 작업을 pane 단위로 나눠 관리하는 cmux 워크플로 도구",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/manaflow-ai/cmux",
      sourceLabel: "GitHub →",
      summary: "manaflow-ai/cmux는 여러 터미널·브라우저·agent 작업을 workspace/pane/surface 단위로 관리하는 도구다. Codex CLI, Claude Code, 검증 세션을 나눠 돌리는 병렬 작업에 유용하다.",
      body: "manaflow-ai/cmux는 여러 터미널·브라우저·AI agent 작업을 workspace, pane, surface 단위로 관리하는 도구다. tmux의 감각을 현대적인 workspace UI로 확장한 쪽에 가깝다. Peter Steinberger가 직접 사용 사례를 X에서 공유해 화제가 됐다.\n\n## AI 개발이 더 이상 한 대화창에서 끝나지 않는 흐름\n\n같은 회차에서 다룬 Thinking Machines Interaction Models, Claude Code Agent View와 정확히 같은 문제 의식이다. 구현, 검수, 배포 확인, 테스트가 동시에 움직이는 작업에서 한 화면에 모든 것을 욱여넣으면 사람이 상황을 못 따라간다. cmux는 그 흐름을 pane으로 쪼개서 눈에 보이게 만든다.\n\n## 사용 패턴\n\n한 pane은 Claude Code 구현, 한 pane은 Codex CLI 검수, 한 pane은 브라우저 자동화 검증을 돌리는 식으로 역할을 분리하면 진행도가 한눈에 보인다. 각 pane에 명령을 보내거나 화면을 읽는 read/send 흐름이 강점이다.\n\n## 충돌 관리가 필수\n\n여러 agent가 같은 파일을 동시에 만지면 git 충돌이 난다. commit owner를 한 채널로 지정하고 나머지는 read-only 또는 다른 디렉토리에서 작업하게 분리해야 한다. tmux 기반 세션과 함께 쓸 때는 user-data-dir과 dev 서버 포트 충돌을 미리 잡아두는 게 안전하다.",
      editorial: "직접 사용 중인 워크플로우 도구.",
      tags: ["오픈소스", "직접사용"],
      tier: "feature",
      thumbnail: {
        src: "/og-cache/manaflow-ai-cmux-peter-steinberger가-소개한--0f69a44c.jpg",
        alt: "manaflow-ai/cmux",
      },
    },
    {
      title: "jaehwan02/UltraCat",
      slug: "ultracat-macos-menubar",
      deck: "macOS 메뉴바에서 시스템 상태·팬 제어·잠자기 관리 — Claude Code/Codex 장시간 작업 환경 보조",
      category: "AI 작업환경 보조 / macOS 유틸리티",
      sourceUrl: "https://github.com/jaehwan02/UltraCat",
      sourceLabel: "GitHub →",
      summary: "UltraCat은 macOS 메뉴바에서 시스템 상태 확인, 팬 제어, 잠자기 관리를 제공하는 유틸리티다. AI 앱은 아니지만 Claude Code·Codex·로컬 LLM·브라우저 자동화처럼 Mac을 장시간 굴리는 AI 작업환경의 발열·팬·수면 관리 보조 도구로 추천.",
      body: "jaehwan02가 만든 UltraCat은 macOS 메뉴바에서 동작하는 시스템 유틸리티다. CPU·메모리·온도 상태, 팬 RPM 직접 제어, 잠자기·디스플레이 슬립 정책 관리를 한 아이콘에서 처리한다. 최신 릴리스는 2026년 5월 기준 v1.0.4. AI 도구 자체는 아니지만 AI 작업환경을 받쳐주는 보조 유틸리티 카테고리에서 직접 쓰고 있다.\n\n## 왜 AI 작업환경에 필요한가\n\nClaude Code 백그라운드 세션 + Codex CLI + 로컬 LLM + 브라우저 자동화를 동시에 돌리면 MacBook Pro M2/M3도 팬이 풀로 도는 일이 잦다. macOS 기본 정책은 보수적이라 throttling이 먼저 걸리고 작업 속도가 떨어진다. UltraCat은 팬 RPM을 수동으로 boost하거나, 장시간 빌드 중 잠자기를 일시 차단하거나, 시스템 온도를 메뉴바에 상시 노출해 throttling을 사전에 감지할 수 있게 해준다.\n\n## 직접 쓸 때 챙긴 시나리오\n\n- 장시간 build / agent 세션 중 팬 RPM 수동 boost\n- 잠자기 일시 차단으로 백그라운드 빌드 중단 방지\n- 시스템 온도 메뉴바 상시 노출로 throttling 사전 감지\n\n## 주의할 부분\n\nDMG 배포에 소스는 비공개다. 회사 장비나 민감 환경에서는 권한과 신뢰성을 사전 확인하는 게 좋다. 라이선스가 명시되지 않은 상태라 개인 Mac에서 watch/trial 쓰는 정도로 시작하는 편이 안전하다. 팬 직접 제어는 하드웨어 영역이라 기본 정책을 먼저 테스트한 뒤 점진적으로 조정해야 한다. 다운로드: https://github.com/jaehwan02/UltraCat/releases/latest/download/UltraCat.dmg",
      editorial: "Mac 장시간 AI 작업의 발열/수면 관리 보조 도구.",
      tags: ["macOS", "유틸리티", "메뉴바앱", "팬제어", "AI작업환경"],
      tier: "feature",
      thumbnail: {
        src: "/og-cache/ultracat-github-og.png",
        alt: "jaehwan02/UltraCat — GitHub",
      },
    },
    {
      title: "cokacdir",
      slug: "cokacdir",
      deck: "한국어 AI 릴리스 큐레이션을 빠르게 추적하는 오픈소스 소스",
      category: "AI 정보 큐레이션 / 오픈소스",
      sourceUrl: "https://github.com/cokacdir",
      sourceLabel: "GitHub →",
      summary: "cokacdir는 AI 신규 소식과 릴리스를 한국어로 빠르게 정리하는 큐레이션 프로젝트다. 공식 출처 검증의 출발점으로 쓰기 좋지만, 최종 인용은 공식 블로그·문서로 되돌아가야 한다.",
      body: "cokacdir는 AI 신규 소식, 모델 릴리스, 개발 도구 업데이트를 한국어로 빠르게 정리하는 큐레이션 프로젝트다. 이번 회차에서도 1차 레이더 역할을 했고, TestingCatalog와 함께 발표 후보 발굴 단계에서 가장 자주 참조한 소스다.\n\n## 왜 한국어 큐레이션이 필요한가\n\nAI 산업은 속도가 빠르고 공식 발표가 여러 채널(공식 블로그, X, GitHub release, changelog, 컨퍼런스 키노트)로 흩어진다. 한국 정보 시장에서는 그 흩어진 신호를 빠르게 모아주는 큐레이션 채널이 발견 단계의 시간을 크게 줄여준다. cokacdir는 그 역할을 안정적으로 해내고 있다.\n\n## 사용 흐름과 안전 원칙\n\n발견은 큐레이션에서 출발하되, 최종 카드 본문에는 반드시 공식 블로그, 공식 문서, GitHub release, changelog를 직접 연결해야 한다. 큐레이션 자체를 공식 출처로 쓰면 안 된다. 날짜, 제품명, 발표 범위는 공식 링크로 다시 검증하고, 루머와 확정 발표를 분리해 표기하는 게 신뢰도를 지키는 방법이다.",
      editorial: "직접 구독 중인 한국어 AI 큐레이션 프로젝트.",
      tags: ["큐레이션", "직접사용", "오픈소스"],
      tier: "feature",
      thumbnail: {
        src: "/og-cache/cokacdir-github-og.png",
        alt: "cokacdir GitHub",
      },
    },
  ],
  demoCards: [
    {
      title: "Claude Code context management — /compact vs /clear",
      slug: "claude-code-context-management-compact-vs-clear",
      deck: "세션 컨텍스트 관리 실전 팁",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=eW3oTyfeWZ0",
      label: "원문 →",
      summary: "Claude Code 세션에서 /compact와 /clear를 언제 써야 하는지 다루는 실전 팁. 긴 개발 세션에서 맥락을 줄이되, 중요한 결정과 작업 상태를 잃지 않는 것이 핵심이다.",
      body: "Claude Code를 길게 쓸 때 가장 자주 만지는 두 명령이 /compact와 /clear다. 둘은 비슷해 보이지만 역할이 다르다. /compact는 현재 대화를 요약해 같은 작업을 이어갈 수 있게 만들고, /clear는 세션 맥락을 비우는 쪽에 가깝다. 단순한 차이지만 잘못 쓰면 작업 상태를 잃는다.\n\n## 언제 무엇을 쓰는가\n\n같은 기능을 계속 다듬는 중이라면 /compact, 완전히 다른 주제로 넘어갈 때는 /clear가 안전하다. compact 직전에 빌드 상태, 남은 TODO, 파일 ownership, 배포 URL 같은 정보를 명시적으로 남겨두는 게 중요하다. 요약 과정에서 빠진 항목이 다음 세션의 삽질을 만든다.\n\n## 긴 작업의 checkpoint 습관\n\n중요한 결정 없이 /clear를 누르면 같은 시행착오를 반복하게 된다. 긴 작업에서는 단계별로 checkpoint 요약을 먼저 남기고 compact·clear를 결정하는 흐름이 안전하다.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "Peter Steinberger cmux + Codex CLI workflow split",
      slug: "peter-steinberger-cmux-codex-cli-workflow-split",
      deck: "cmux 다중 pane + Codex CLI 작업 분할 패턴",
      category: "실전 팁",
      url: "https://github.com/manaflow-ai/cmux",
      label: "원문 →",
      summary: "cmux와 Codex CLI를 함께 써서 작업을 여러 pane으로 나누는 워크플로 패턴. 구현, 검증, 로그 확인, 배포 확인을 분리해 병렬로 진행하는 방식이다.",
      body: "Peter Steinberger가 X에서 공유한 cmux + Codex CLI 워크플로 분할 패턴이다. 한 pane은 구현, 한 pane은 테스트, 한 pane은 브라우저 검증으로 역할을 나눠 병렬로 진행한다. 같은 회차의 cmux editor's pick과 묶어서 보면 흐름이 명확해진다.\n\n## pane을 나누는 이유\n\nAI agent가 길게 작업할수록 한 화면에 모든 것을 띄우면 사람이 상황을 못 따라간다. pane 분리의 진짜 가치는 단순 병렬 처리가 아니라 진행 상황과 책임 범위를 시각적으로 분리해 주는 데 있다. 어느 agent가 무엇을 만지고 있는지 한눈에 보이면 인계와 검수가 빨라진다.\n\n## 충돌을 피하는 룰\n\n각 pane의 목적을 짧게 한 줄로 정해두고, 같은 파일 동시 수정은 피해야 한다. 한 agent를 commit owner로 지정하고 나머지는 read-only 검수에 두는 패턴이 안전하다. 병렬화가 항상 더 빠른 것은 아니다. 맥락 공유와 충돌 해결 비용이 커지면 오히려 손해가 나기 때문에 작업 단위를 작게 나누는 게 중요하다.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "AI prompt usage: method-first prompting",
      slug: "ai-prompt-usage-method-first-prompting",
      deck: "방법론을 먼저 제시하는 프롬프트 스타일",
      category: "실전 팁",
      url: "https://www.instagram.com/p/DYCDIvelD5p/",
      label: "원문 →",
      summary: "프롬프트에서 결과물보다 방법론을 먼저 제시하는 방식. AI에게 단순 답변을 요구하기보다 판단 기준, 검증 순서, 실패 조건을 먼저 주는 패턴이다.",
      body: "method-first prompting은 결과물 형식보다 작업 방법을 먼저 알려주는 프롬프트 스타일이다. \"먼저 원인을 분류하고, 다음으로 검증 명령을 실행하고, 마지막에 수정안을 제시하라\"처럼 순서를 명시적으로 고정한다. Instagram에서 공유된 사례에서 출발한 패턴이다.\n\n## AI가 그럴듯한 답으로 흐르는 경향을 막는다\n\nAI는 빠르게 그럴듯한 답을 내는 쪽으로 기울기 쉽다. 방법론을 먼저 주면 탐색, 검증, 수정의 순서를 강제할 수 있어 정확도가 올라간다. 특히 코드 작업에서는 build·test·브라우저 확인 같은 검증 단계를 빼먹지 않게 만든다.\n\n## 좋은 프롬프트의 구성 요소\n\n목표, 제약, 검증 기준, 실패 시 중단 조건이 들어가야 한다. 단 방법론이 너무 길면 실제 작업보다 형식 준수에 시간을 더 쓰는 역효과가 난다. 핵심 단계만 3~5줄로 짧게 고정하는 게 실용적이다.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "YC Diana Hu — AI-native company 구성 방식",
      slug: "yc-diana-hu-ai-native-company-구성-방식",
      deck: "YC 파트너 관점에서 AI-native 회사가 갖춰야 할 구조",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=EN7frwQIbKc",
      label: "원문 →",
      summary: "YC Diana Hu가 말하는 AI-native 회사 구성 방식. 단순히 AI 기능을 붙이는 것이 아니라 제품, 운영, 고객지원, 내부 도구가 처음부터 AI 중심으로 설계되는 조직 구조를 다룬다.",
      body: "Y Combinator 파트너 Diana Hu가 YouTube에서 정리한 AI-native company 구성 관점이다. 핵심 메시지는 \"기존 회사에 AI 기능을 덧붙이는 게 아니라 처음부터 AI를 전제로 제품과 운영을 설계해야 한다\"는 점이다.\n\n## 기존 조직과 무엇이 다른가\n\n작은 팀이 더 넓은 범위를 맡는다. 내부 도구, 고객 지원, 세일즈, 제품 실험이 AI 에이전트를 기본 전제로 움직인다. 사람은 반복 실행보다 판단과 품질 관리, 정책 결정에 시간을 집중한다. 같은 인원으로 5배의 일을 하는 게 가능하다는 게 YC가 자기 포트폴리오에서 관찰한 패턴이다.\n\n## 한국 스타트업과 사내 TF에 적용할 때\n\n스타트업뿐 아니라 대기업 안의 작은 TF에도 적용할 수 있다. 도구 도입보다 업무 설계가 먼저다. 누가 승인하고, 어떤 기준으로 검수하고, 실패를 어떻게 되돌릴지를 사전에 정해야 한다. AI-native를 인력 감축 구호로만 쓰면 실패한다. 자동화된 결과를 검수할 도메인 전문가와 책임 구조가 반드시 함께 가야 한다.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "Jensen Huang CMU commencement — AI jobs message",
      slug: "jensen-huang-cmu-commencement-ai-jobs-message",
      deck: "AI 시대 일자리에 대한 NVIDIA CEO 졸업 연설",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=uSs7PPAJR20",
      label: "원문 →",
      summary: "Jensen Huang의 CMU 졸업 연설에서 나온 AI 시대 일자리 메시지. AI가 직업을 없앤다는 단순 프레임보다, AI를 쓰는 사람이 AI를 쓰지 않는 사람을 대체한다는 관점을 강조한다.",
      body: "NVIDIA CEO Jensen Huang의 CMU 졸업 연설 영상이다. 핵심 메시지는 단순하다. \"AI가 직업을 없앤다\"는 단순 프레임이 아니라 \"AI를 쓰는 사람이 AI를 쓰지 않는 사람을 대체한다\"는 관점이다.\n\n## 발언의 무게\n\nAI 인프라를 파는 회사 CEO의 입에서 나온 말이라는 점을 감안해도, 노동시장 메시지로서 영향력이 크다. 학생과 실무자에게 \"AI를 외부 도구가 아니라 기본 역량으로 다뤄라\"는 신호를 정면으로 던졌다. CMU라는 무대 자체가 컴퓨터과학과 로보틱스의 본진이라 의미가 더 부각된다.\n\n## 한국 청자에게 직접 닿는 부분\n\n취업 준비생, 주니어 개발자, 기획자에게 가장 직접적인 메시지다. 스펙보다 AI를 활용해 실제 산출물을 만드는 능력이 더 중요해지는 흐름이 분명하게 드러난다. 단 낙관론만 받아들이면 안 된다. 직무별 영향은 다르고, AI 활용 능력만으로는 부족하다. 도메인 전문성, 커뮤니케이션, 검증 능력이 함께 가야 실제 경쟁력이 된다.",
      tags: ["실전팁", "워크플로"],
    },
  ],
};
