// AB 발표 첫 회차 — 2026-04a (Volume 1)
// Week 15 (2026-04-06 ~ 2026-04-12) Gold 23에서 7개 엄선
// 발표일: 2026-04-10

import type { ABEdition } from "../data";

export const edition2026_04a: ABEdition = {
  slug: "2026-04a",
  volume: 1,
  title: "거대 발표와 로컬 반격",
  theme: "2026년 4월 전반기 — 공식 발표 러시와 로컬 AI 티핑 포인트가 같은 주에 겹친 기간",
  period: "2026-04-06 ~ 2026-04-12",
  coveredWeeks: ["2026-w15"],
  announceDate: "2026-04-10",

  intro: "이번 2주는 AI 산업의 두 축이 정면으로 부딪친 기간입니다.\n\n한 축에는 OpenAI·Anthropic·Google이 같은 주에 쏟아낸 공식 발표 러시가 있고, 다른 축에는 데스크톱 크기의 박스 4대로 397B 모델을 굴리는 로컬 AI 진영의 조용한 반격이 있습니다.\n\n'누가 더 큰 모델을 가졌느냐'에서 '누가 더 영리하게 엮느냐'로 경쟁의 축이 옮겨가는 변곡점 — 이번 회차 7개 항목은 그 변화를 가장 선명하게 보여주는 순간들입니다.",

  closing: "이번 브리핑의 핵심 메시지는 하나입니다. **멀티모델 운영 전략이 곧 경쟁력**.\n\nAnthropic Advisor Strategy(#3), OpenAI Pro 티어(#2), Gemini 시각화(#4) — 세 거인이 같은 주에 내놓은 발표는 모두 '모델 하나'가 아닌 '모델들을 엮는 방식'에 대한 답이었습니다. 그리고 로컬 진영(#1)은 아예 그 모델들을 자기 데스크톱 위로 끌어내리고 있습니다.\n\n다음 2주는 이 두 축이 어떻게 수렴할지 지켜볼 차례입니다. 공식 발표의 품질 × 로컬 실행의 자유도 — 둘이 만나는 지점이 2026년 하반기의 표준이 될 것 같습니다.\n\n— VoidLight",

  highlights: [
    {
      rank: 1,
      tier: "hero",
      post: {
        date: "4/10 00:55",
        platform: "X",
        title: "4x DGX Sparks Qwen3.5 397B MoE FP8",
        summary: "대형 MoE 모델을 DGX Sparks 구성에서 돌리는 고성능 사례입니다. 대규모 멀티에이전트나 병렬 추론 실험과 연결할 수 있습니다.",
        content: "**Qwen3.5 397B MoE** (토큰당 17B active)를 **4x DGX Sparks FP8**로 실행 중 (~400GB)\n\n> **OpenCode**가 구동 드라이버\n> 에이전트가 자신의 설정을 탐색\n> 모든 4개 Sparks에 **SSH로 접속**해서 온도 리포트\n> vLLM이 어떻게 서빙 중인지 점검\n> 자신의 통계를 수집·분석\n\n로컬 AI는 최고야 🔥",
        officialUrl: "https://x.com/TheAhmadOsman/status/2042270126838358204",
        source: "https://x.com/TheAhmadOsman/status/2042270126838358204",
        tags: ["DGX", "MoE", "고성능컴퓨팅"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "로컬 AI / 하드웨어",
      keyQuote: "local AI is awesome",
      editorial: "이 트윗이 상징하는 건 단순한 자랑이 아닙니다. 불과 1년 전만 해도 데이터센터에서나 돌릴 수 있던 397B MoE 모델이 이제 4대의 데스크톱 크기 DGX Sparks에서 FP8로 돌아갑니다. 더 중요한 건 에이전트가 자기 인프라를 직접 점검한다는 점 — SSH로 온도 체크하고 vLLM 서빙 상태까지 스스로 진단합니다. 로컬 AI가 '실험실 장난감'에서 '운영 가능한 인프라'로 건너가는 티핑 포인트.",
    },
    {
      rank: 2,
      tier: "feature",
      post: {
        date: "4/10 03:10",
        platform: "X",
        title: "OpenAI ChatGPT Pro $100 tier 출시",
        summary: "고사양 모델 접근성과 Codex 사용 확대를 강조한 요금제 소식입니다. 개발·에이전트 실험을 자주 하는 사용자에게 영향이 큰 업데이트입니다.",
        content: "OpenAI가 월 **$100짜리 새 ChatGPT 요금제**를 출시했습니다.\n\n\"이 새 요금제는 Plus 대비 **Codex 사용량 5배**를 제공하며, 장시간·고강도 Codex 세션에 최적화되어 있습니다.\"\n\nAnthropic의 최근 rate limit 이슈가 주목받는 시점과 겹치는 건 아마도 우연이 아닐 것입니다.",
        officialUrl: "https://x.com/TheRundownAI/status/2042304085307671000",
        source: "https://x.com/TheRundownAI/status/2042304085307671000",
        tags: ["OpenAI", "Pro", "Codex"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "OpenAI",
      keyQuote: "5x more Codex usage than Plus",
      editorial: "이 분기 가장 큰 파장을 일으킨 공식 발표. 월 $100이라는 가격은 Anthropic Max/Pro 요금제를 겨냥한 것이 분명합니다. 핵심은 'Codex 5배'라는 문구 — 개별 사용자의 장시간 코딩 에이전트 세션이 핵심 수익 모델로 자리 잡았다는 신호입니다. 1.48만 좋아요 × 1087 답글은 이 방향성에 대한 시장의 합의를 보여줍니다.",
    },
    {
      rank: 3,
      tier: "feature",
      post: {
        date: "4/10 03:28",
        platform: "X",
        title: "Anthropic Advisor Strategy (Opus = Advisor)",
        summary: "Opus를 자문 역할에만 두고 Sonnet/Haiku가 검색·실행을 맡는 전략입니다. 비용을 줄이면서 판단 품질을 유지하는 멀티모델 운영 사례로 정리됐습니다.",
        content: "평가 결과, Opus advisor를 붙인 Sonnet이 단독 Sonnet 대비 SWE-bench Multilingual에서 2.7%p 높은 점수를 기록했으며, 작업당 비용은 11.9% 저렴했습니다.\n\n— via @testingcatalog 큐레이션",
        officialUrl: "https://x.com/claudeai/status/2042308627478773808",
        source: "https://x.com/claudeai/status/2042308627478773808",
        tags: ["Anthropic", "비용최적화", "멀티모델", "공식인용교체"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Anthropic / Claude",
      keyQuote: "2.7%p 높은 점수 + 11.9% 저렴",
      editorial: "OpenAI의 $100 Pro 발표와 같은 주에 Anthropic이 내놓은 답. Opus를 '자문 역할'로 돌리고 Sonnet/Haiku가 실행을 맡는 구조 — SWE-bench Multilingual에서 2.7%p 성능 향상 + 11.9% 비용 절감. 단순한 벤치마크가 아니라 '멀티모델 운영 전략'이라는 새 패러다임을 공식화한 발표입니다. 이제 '어떤 모델을 쓰느냐'가 아니라 '모델들을 어떻게 엮느냐'가 경쟁의 축이 됐습니다.",
    },
    {
      rank: 4,
      tier: "normal",
      post: {
        date: "4/10 01:04",
        platform: "X",
        title: "Gemini 인터랙티브 시각화 기능 공개",
        summary: "3D 모델과 인터랙티브 차트로 결과를 탐색하는 기능을 소개한 항목입니다. 분석 결과를 단순 텍스트가 아닌 조작 가능한 뷰로 보는 흐름과 연결됩니다.",
        content: "Gemini가 이제 여러분의 질문과 복잡한 개념을 채팅창 안에서 커스터마이즈 가능한 인터랙티브 시각화로 변환해줍니다.\n\n변수를 조절하고, 3D 모델을 회전시키고, 데이터를 탐색하면서 더 몰입감 있는 학습·탐색 경험을 Gemini에서 제공합니다.\n\n— via @lucas_flatwhite 큐레이션",
        officialUrl: "https://x.com/GeminiApp/status/2042272415951253932",
        source: "https://x.com/GeminiApp/status/2042272415951253932",
        tags: ["Gemini", "시각화", "3D", "공식인용교체"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Google / DeepMind",
      keyQuote: "Adjust variables, rotate 3D models",
      editorial: "Gemini가 드디어 채팅창 밖으로 나왔습니다. 변수를 조작하는 인터랙티브 차트, 회전 가능한 3D 모델 — 텍스트 답변의 한계를 시각적 탐색으로 확장. 교육·데이터 분석·엔지니어링 설명에서 판도를 바꿀 수 있는 방향. 6,399 좋아요로 커뮤니티 반응도 뜨겁습니다.",
    },
    {
      rank: 5,
      tier: "normal",
      post: {
        date: "4/10 00:17",
        platform: "X",
        title: "Meta TRIBE v2 뇌 예측 모델 공개",
        summary: "영상·음성·텍스트 입력으로 뇌 활성화 패턴을 예측하는 모델 소개입니다. 인간 반응 이해와 멀티모달 분석 확장 가능성이 핵심입니다.",
        content: "Meta의 새 AI가 뇌 스캔보다도 더 정확하게 여러분의 뇌를 예측합니다.\n\n**TRIBE v2**는 720명으로부터 수집한 1,000시간+ 뇌 영상 데이터로 학습된 **파운데이션 모델**입니다.\n영상·음성 클립·텍스트를 입력하면 다음을 예측합니다:\n> 어떤 뇌 영역이 활성화되는지\n> 얼마나 강하게\n> 어떤 순서로…",
        officialUrl: "https://x.com/rowancheung/status/2042260621274861756",
        source: "https://x.com/rowancheung/status/2042260621274861756",
        tags: ["Meta", "멀티모달", "바이오AI"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Meta",
      keyQuote: "predicts which brain regions light up",
      editorial: "이번 브리핑에서 가장 '미래 지향적인' 항목. 720명의 1,000시간+ 뇌 영상 데이터로 학습한 파운데이션 모델이, 영상·음성·텍스트를 입력받아 어떤 뇌 영역이 어느 강도로 활성화될지 예측합니다. 바이오 AI가 '진단 보조'에서 '인간 이해 모델'로 올라서는 순간. 광고·UX 연구·교육 콘텐츠 개발에까지 파급 가능.",
    },
    {
      rank: 6,
      tier: "normal",
      post: {
        date: "4/7 22:26",
        platform: "X",
        title: "Netflix VOID 영상 객체 삭제 모델",
        summary: "영상에서 객체를 지운 뒤 장면의 물리 일관성까지 다시 맞추는 모델 이야기입니다. 영상 편집형 생성 AI의 수준을 보여주는 사례입니다.",
        content: "Netflix 연구진이 새 AI 모델을 공개했습니다.\n\n영상에서 객체를 지운 뒤, **그 객체가 애초에 없었던 것처럼 장면 전체의 물리를 다시 써 내려갑니다**.\n\n이름은 **VOID (Video Object and Interaction Deletion)**.\n기존 인페인팅 도구는 객체가 남긴 빈자리를 단순히 덧칠하는 수준에…",
        officialUrl: "https://x.com/rowancheung/status/2041507881858826404",
        source: "https://x.com/rowancheung/status/2041507881858826404",
        tags: ["비디오AI", "생성모델", "Netflix"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "이미지 / 영상 / 음악",
      keyQuote: "rewrites the physics of the entire scene",
      editorial: "Netflix가 자체 연구팀에서 공개한 영상 편집 AI. 단순히 객체를 지우는 게 아니라 장면 전체의 물리 일관성을 다시 써냅니다 — 그림자, 반사, 움직임까지. 창작 도구가 'cut & paste' 수준에서 '장면 재구성' 수준으로 올라선 사례. 영상 제작 파이프라인의 다음 세대를 보여줍니다.",
    },
    {
      rank: 7,
      tier: "normal",
      post: {
        date: "4/10 15:42",
        platform: "X",
        title: "Claude Code .claude/ Skills 16가지 정리",
        summary: "Claude Code에서 쓸 수 있는 다양한 스킬 세트를 한 번에 정리한 항목입니다. 에이전트형 개발 워크플로우를 강화하는 도구 모음 성격이 강합니다.",
        content: "**AI 엔지니어를 위한 16가지 강력한 Agent 스킬**:\n\nClaude Code의 **.claude/ 스킬 시스템**은 재사용 가능한 지침·워크플로우·도구 설정을 **포터블한 폴더**로 패키징해서 모든 에이전트 세션이 그대로 가져다 쓸 수 있게 해줍니다.\n\nAI 엔지니어를 위한 강력한 16가지 Agent 스킬을 소개합니다:\n-…",
        officialUrl: "https://x.com/_avichawla/status/2042493342303600644",
        source: "https://x.com/_avichawla/status/2042493342303600644",
        tags: ["ClaudeCode", "Skills", "개발도구"],
      },
      sourceWeek: "2026-w15",
      sourceCompany: "Anthropic / Claude",
      keyQuote: "16 powerful Agent skills for AI Engineers",
      editorial: "개발자에게 가장 실용적인 항목. Claude Code의 `.claude/skills/` 시스템을 활용한 16가지 Agent 스킬 모음 — 재사용 가능한 지침·워크플로우·도구 설정을 폴더 단위로 패키징해서 어떤 에이전트 세션에서든 가져다 쓸 수 있습니다. 스킬 기반 에이전트 생태계가 본격화되는 신호. 이번 회차의 실무 적용 포인트로 바로 복사해 쓸 수 있는 자료.",
    },
  ],
};