import type { ABEdition, ABEditorPick } from "../data";
import type { Post } from "../../data";

// 2026-08b — user-selected VIP set. Editorial cutoff: 2026-08-26 21:48 KST.
function post(input: Post): Post { return input; }

const vip1 = post({
  date: "8/17",
  platform: "X+Threads",
  title: "Claude Code, GitLab MR 상태 배지와 사용량 제한 자동 재개 추가",
  featured: true,
  deck: "GitLab remote와 인증된 glab CLI가 있으면 footer/statusline에 MR !N 상태 표시",
  summary: "GitLab remote와 인증된 glab CLI가 있으면 footer/statusline에 MR !N 상태 표시 claude.ai 사용량 제한 초기화 시 세션 자동 계속 Windows NT namespace 경로를 사전승인 파일 접근 경계에서 거부",
  content: "**운영 화면에 상태가 들어왔습니다**\n\nClaude Code 2.1.234는 GitLab remote와 인증된 glab CLI가 있으면 footer와 status line에 merge request 번호와 상태를 표시합니다. 사용량 제한이 초기화되면 세션을 자동으로 이어가며, Windows NT namespace 경로를 사전 승인 파일 접근 경계에서 거부합니다.\n\n**직접 확인할 것**\n\n팀이 GitLab을 사용한다면 상태 표시가 실제 인증과 remote 설정을 읽는지 확인하십시오. 자동 재개는 성공 판정이 아니라 사용량 제한 이후의 실행 재개입니다.",
  source: "https://github.com/anthropics/claude-code/releases/tag/v2.1.234",
  officialUrl: "https://github.com/anthropics/claude-code/releases/tag/v2.1.234",
  verifiedAt: "2026-08-26",
  backupUrls: [],
  slug: "claude-code-20260817-v2-1-234",
  tags: ["AI", "2026-08b", "Anthropic"],
  en: {
    title: "Claude Code adds GitLab MR status and automatic usage-limit resume",
    deck: "GitLab merge-request state now appears in the footer and status line.",
    summary: "Claude Code 2.1.234 displays authenticated GitLab merge-request status, resumes sessions after claude.ai usage limits reset, and rejects Windows NT namespace paths at the pre-approved file boundary.",
    content: "Claude Code 2.1.234 displays authenticated GitLab merge-request status, resumes sessions after claude.ai usage limits reset, and rejects Windows NT namespace paths at the pre-approved file boundary.",
  },
});

const vip2 = post({
  date: "8/17",
  platform: "X+Threads",
  title: "AI가 공동 작성한 CI 변경, Snowflake Jira 자격 증명 노출 경로 만들었다",
  featured: true,
  deck: "이슈 제목의 직접 셸 보간으로 인증 없는 명령 실행 가능",
  summary: "이슈 제목의 직접 셸 보간으로 인증 없는 명령 실행 가능 러너의 Jira 읽기 자격 증명 접근 가능 Snowflake가 6월 23일 수정하고 6월 24일 토큰 교체 감사 로그에서 제3자 접근 증거 없음 주의: 취약점 사건 발생은 6월이며 8월 17일은 연구 공개일 Copilot이 코드 자체를 생성했는지는 불명확",
  content: "**AI 작성 여부보다 실행 경계가 문제였습니다**\n\nWiz는 Snowflake GitHub Actions 흐름에서 이슈 제목이 셸에 직접 보간돼 인증 없는 명령 실행 경로가 생겼다고 공개했습니다. 러너가 Jira 읽기 자격 증명에 접근할 수 있었고, Snowflake는 6월 23일 수정하고 6월 24일 토큰을 교체했습니다.\n\n연구 공개일은 8월 17일이지만 사건 자체는 6월입니다. Copilot이 취약한 코드를 직접 생성했는지는 확인되지 않았습니다.\n\n**직접 확인할 것**\n\nAI가 공동 작성한 CI 변경도 외부 입력의 셸 보간, 러너 토큰 권한, 감사 로그를 별도 게이트로 검토하십시오.",
  source: "https://www.wiz.io/blog/red-agent-snowflake-copilot-cicd-bug",
  officialUrl: "https://www.wiz.io/blog/red-agent-snowflake-copilot-cicd-bug",
  verifiedAt: "2026-08-26",
  backupUrls: [],
  slug: "wiz-20260817-snowflake-cicd",
  tags: ["AI", "2026-08b", "Wiz"],
  en: {
    title: "A CI change exposed a Snowflake Jira credential path",
    deck: "Issue-title shell interpolation enabled unauthenticated command execution.",
    summary: "Wiz disclosed a Snowflake GitHub Actions flaw where issue titles reached a shell and exposed a path to Jira read credentials. The incident was fixed in June; the research was published August 17.",
    content: "Wiz disclosed a Snowflake GitHub Actions flaw where issue titles reached a shell and exposed a path to Jira read credentials. The incident was fixed in June; the research was published August 17.",
  },
});

const vip3 = post({
  date: "8/26",
  platform: "X+Threads",
  title: "GLM-5.3-Flash 공개, OpenRouter 익명 모델 Ox Alpha의 정체였다",
  featured: true,
  deck: "320B 중 18B만 활성화하고 100만 토큰 컨텍스트를 제공하는 네이티브 멀티모달 모델",
  summary: "Z.ai GLM-5.3-Flash는 320B total·18B active MoE와 이미지·영상 입력, 1,048,576토큰 컨텍스트를 제공 OpenRouter가 stealth model Ox Alpha의 정체가 GLM-5.3-Flash였다고 공식 FAQ에서 확인 입력 $0.075/M·출력 $0.25/M·캐시 읽기 $0.015/M 주의: 벤치마크·10분의 1 가격 주장은 Z.ai 자체 보고",
  content: "**Ox Alpha의 정체가 공개됐습니다**\n\nZ.ai는 8월 26일 GLM-5.3-Flash를 공개했습니다. 공식 가중치는 총 3,200억 파라미터 가운데 토큰당 180억을 활성화하고, 텍스트·이미지·영상을 입력받는 네이티브 멀티모달 구조와 MIT 라이선스를 사용합니다. OpenRouter는 모델 FAQ에서 이전 stealth model인 Ox Alpha가 GLM-5.3-Flash였다고 명시했습니다.\n\nOpenRouter 제공 사양은 1,048,576토큰 컨텍스트와 최대 131,072토큰 출력입니다. 50% 할인 가격은 100만 토큰당 입력 0.075달러, 출력 0.25달러, 캐시 읽기 0.015달러입니다.\n\n**검증 한계**\n\nGLM-5.2보다 전반적으로 높고 Claude Opus 4.8에 접근한다는 벤치마크 및 10분의 1 가격 주장은 Z.ai 공식 문서의 자체 평가입니다. OpenRouter의 Ox Alpha 확인은 공식 플랫폼 FAQ 근거이지만, Z.ai GitHub와 Hugging Face에는 Ox Alpha 명칭이 없습니다.\n\n**직접 확인할 것**\n\nOpenRouter의 `z-ai/glm-5.3-flash`로 실제 코딩·장기 에이전트 작업을 시험하고, 기존 Ox Alpha 사용 기록이 있다면 같은 프롬프트의 결과와 비용을 비교하십시오.",
  source: "https://docs.z.ai/guides/llm/glm-5.3-flash",
  officialUrl: "https://docs.z.ai/guides/llm/glm-5.3-flash",
  verifiedAt: "2026-08-27",
  backupUrls: [{ label: "OpenRouter 공식 모델 페이지 · Ox Alpha 확인", url: "https://openrouter.ai/z-ai/glm-5.3-flash" }, { label: "Z.ai GLM-5 공식 저장소", url: "https://github.com/zai-org/GLM-5" }, { label: "Hugging Face 공식 가중치", url: "https://huggingface.co/zai-org/GLM-5.3-Flash" }, { label: "Choi GLM-5.3-Flash 벤치마크 스레드", url: "https://www.threads.com/@choi.openai/post/Dcgb7pgDxYv" }, { label: "OddSVG GLM 시각 비교", url: "https://www.threads.com/@transurfer.ai/post/DcghJPLGudB" }],
  visualComparisons: [
    {
      title: "GLM-5.3-Flash 공개와 Ox Alpha 정체·비용·벤치마크",
      model: "GLM-5.3-Flash / Ox Alpha",
      task: "Terminal-Bench·DeepSWE·Artificial Analysis 수치와 모델 구조를 설명하는 큐레이터 브리핑",
      comparisonClass: "context",
      comparisonLabel: "벤치마크 맥락",
      sourceUrl: "https://www.threads.com/@choi.openai/post/Dcgb7pgDxYv",
      embedUrl: "https://www.threads.net/@choi.openai/post/Dcgb7pgDxYv/embed",
      promptStatus: "해당 없음 — 제작 과제 실행물이 아니라 지표 설명",
      runtimeStatus: "해당 없음",
      toolStatus: "Choi 큐레이션이며 수치는 Z.ai·Artificial Analysis 원자료 재확인 필요",
      benchmarkNote: "Terminal-Bench 2.1 84.3, DeepSWE 1.1 63.4, Artificial Analysis Intelligence Index 57·task cost $0.045라는 큐레이터 요약. 독립 재측정이 아닙니다.",
      caveat: "Choi님의 해설 화면은 비교 맥락용입니다. 벤더·평가기관 수치를 VoidNews가 다시 실행한 결과로 해석하면 안 됩니다.",
    },
    {
      title: "OddSVG 결과로 본 GLM-5.3과 GLM-5.3-Flash",
      model: "GLM-5.3 vs GLM-5.3-Flash",
      task: "SVG 생성 결과의 시각 품질 비교",
      comparisonClass: "showcase",
      comparisonLabel: "시연 비교 · 동일 조건 미확인",
      sourceUrl: "https://www.threads.com/@transurfer.ai/post/DcghJPLGudB",
      embedUrl: "https://www.threads.net/@transurfer.ai/post/DcghJPLGudB/embed",
      promptStatus: "원게시물에 정확한 프롬프트 전문이 공개되지 않음",
      runtimeStatus: "모델별 실행 시간·재시도 횟수 미공개",
      toolStatus: "OddSVG 사용은 명시됐으나 시작 자산·후처리·샘플 선택 기준 미공개",
      benchmarkNote: "게시자는 성능이 비슷하고 Flash 가격이 낮아졌다고 평가합니다. 정량 점수나 블라인드 판정은 제공되지 않았습니다.",
      caveat: "선별된 결과를 보여주는 showcase입니다. 같은 프롬프트·시간·도구·샘플링을 통제한 decisive experiment가 아닙니다.",
    },
    {
      title: "큐레이터 시연 영상으로 본 모델별 제작 결과",
      model: "GLM-5.3-Flash 포함 복수 모델 · 원게시물 표기 기준",
      task: "동일 과제를 여러 모델에 시켰을 때의 결과 화면 비교",
      comparisonClass: "showcase",
      comparisonLabel: "시연 비교 · 조건 미확인",
      sourceUrl: "https://www.threads.com/@aiwithgenzofficial/post/DcU1BlZCZ2I",
      embedUrl: "https://www.threads.net/@aiwithgenzofficial/post/DcU1BlZCZ2I/embed",
      promptStatus: "원게시물에 프롬프트 전문이 공개되지 않음",
      runtimeStatus: "모델별 실행 시간·재시도 횟수 미공개",
      toolStatus: "사용 도구와 시작 자산, 샘플 선택 기준 미공개",
      benchmarkNote: "게시자가 고른 결과 화면을 이어 붙인 영상입니다. 점수나 블라인드 판정은 제공되지 않습니다.",
      caveat: "@aiwithgenzofficial 계정의 큐레이션 영상이며 VoidNews가 재현한 결과가 아닙니다. 어떤 모델이 우월하다는 판정 근거로 쓰지 않습니다.",
    },
  ],
  slug: "zai-20260826-glm-5-3-flash-ox-alpha",
  tags: ["AI", "2026-08b", "Z.ai", "OpenRouter", "GLM"],
  en: {
    title: "GLM-5.3-Flash launches as the model behind OpenRouter's Ox Alpha",
    deck: "The native multimodal MoE activates 18B of 320B parameters with a one-million-token context.",
    summary: "Z.ai released GLM-5.3-Flash on August 26. OpenRouter identifies it as the former stealth model Ox Alpha and lists a 1,048,576-token context at discounted pricing of $0.075/M input and $0.25/M output tokens.",
    content: "Z.ai released GLM-5.3-Flash on August 26. OpenRouter identifies it as the former stealth model Ox Alpha and lists a 1,048,576-token context at discounted pricing of $0.075/M input and $0.25/M output tokens. Benchmark comparisons remain vendor-reported.",
  },
});

const vip4 = post({
  date: "8/18",
  platform: "X+Threads",
  title: "Pika, 음악·효과음·음성·영상 사운드 모델 4종 동시 공개",
  featured: true,
  deck: "Soundtrack은 영상에서 동기화된 음향 장면 생성",
  summary: "Soundtrack은 영상에서 동기화된 음향 장면 생성 Music은 최대 90초 곡을 평균 6.21초에 생성한다고 주장 SFX는 1~20초 MP3 효과음을 실시간 수준으로 생성 Speech는 5초 참조 음성 복제·최대 5분 생성·RTF 0.02 제시 주의: 성능 수치는 Pika 자체 주장 한국어 지원은 명시되지 않음",
  content: "**영상 서비스가 오디오 전체로 확장됐습니다**\n\nPika는 8월 18일 Soundtrack, Music, SFX, Speech를 함께 공개했습니다. Soundtrack은 영상 장면에 맞춘 음향을 만들고, Music은 최대 90초 곡, SFX는 1초에서 20초 효과음, Speech는 5초 참조 음성으로 최대 5분 음성을 생성한다고 설명합니다.\n\n성능과 속도 수치는 Pika 자체 주장이고 한국어 지원은 명시되지 않았습니다.\n\n**직접 확인할 것**\n\n영상 생성 비용과 별도로 음원 권리, 음성 복제 동의, 후반 편집 가능성을 확인하십시오.",
  source: "https://pika.art/blog/pika-soundtrack",
  officialUrl: "https://pika.art/blog/pika-soundtrack",
  verifiedAt: "2026-08-26",
  backupUrls: [],
  slug: "pika-20260818-audio-suite",
  tags: ["AI", "2026-08b", "Pika"],
  en: {
    title: "Pika launches models for music, effects, speech and video sound",
    deck: "The video platform expands across the full audio layer.",
    summary: "Pika announced Soundtrack, Music, SFX and Speech together on August 18. Performance figures are vendor claims, and Korean-language support was not specified.",
    content: "Pika announced Soundtrack, Music, SFX and Speech together on August 18. Performance figures are vendor claims, and Korean-language support was not specified.",
  },
});

const vip5 = post({
  date: "8/27",
  platform: "Threads",
  title: "Tiangong Omni, 휴머노이드 로봇 게임 400m를 45.66초에 완주",
  featured: true,
  deck: "팔을 높이 든 독특한 자세로 World Humanoid Robot Games 400m 우승",
  summary: "Tiangong Omni가 베이징 World Humanoid Robot Games 400m를 45.66초에 완주하고 우승했다는 행사 출처 영상 공개 곡선 구간에서 몸을 앞으로 기울이고 균형을 지속 보정하는 달리기 모습 확인 주의: 원게시물은 제어 방식과 자율 주행 여부를 명시하지 않으며 자세를 로봇이 스스로 발견했다는 주장은 공식 개발사 근거 미확인",
  content: "**피지컬 AI의 진전은 달리기 자세보다 완주 조건에서 봐야 합니다**\n\nTiangong Omni가 베이징 World Humanoid Robot Games의 400m 경기에서 45.66초로 우승했다는 영상이 공개됐습니다. 영상에서는 팔을 얼굴 가까이 높이 들고 몸을 앞으로 기울인 채 곡선을 도는 독특한 주법을 확인할 수 있습니다.\n\n**검증 한계**\n\n원게시물은 출처를 World Humanoid Robot Games로 적었지만 원격조종·자율제어·혼합제어 가운데 어떤 방식인지 밝히지 않았습니다. 관련 재게시물의 ‘자세를 자율적으로 발견했다’는 설명은 공식 개발사 원문으로 확인되지 않아 카드에서 제외했습니다.\n\n**직접 확인할 것**\n\n피지컬 AI 데모를 평가할 때 기록뿐 아니라 제어 방식, 넘어짐·재시도, 배터리와 트랙 조건을 함께 확인하십시오.",
  source: "https://www.threads.com/@uncover.robotics/post/DcgoEiLkvGU",
  officialUrl: "https://www.threads.com/@uncover.robotics/post/DcgoEiLkvGU",
  verifiedAt: "2026-08-27",
  backupUrls: [{ label: "곡선 주행 영상", url: "https://www.threads.com/@techniahqrobot/post/Dcb9Eljjar4" }, { label: "결승선 우승 영상", url: "https://www.threads.com/@lincoln_robotics_space/post/DcYsY-CCa4D" }],
  threadsEmbedUrl: "https://www.threads.net/@uncover.robotics/post/DcgoEiLkvGU/embed",
  slug: "physical-ai-20260827-tiangong-omni-400m",
  tags: ["AI", "2026-08b", "Physical AI", "휴머노이드", "로봇"],
  en: {
    title: "Tiangong Omni completes the humanoid robot 400 m in 45.66 seconds",
    deck: "The unusual running form won the World Humanoid Robot Games race.",
    summary: "A World Humanoid Robot Games-sourced video shows Tiangong Omni winning the 400 m in 45.66 seconds. The source does not specify autonomous, remote or mixed control.",
    content: "A World Humanoid Robot Games-sourced video shows Tiangong Omni winning the 400 m in 45.66 seconds. The source does not specify autonomous, remote or mixed control.",
  },
});

const vip6 = post({
  date: "8/25",
  platform: "X+Threads",
  title: "Apple, 첫 2nm M6와 최대 512GB 메모리 M5 Ultra 공개",
  featured: true,
  deck: "M6는 Apple 첫 2nm 칩으로 12코어 CPU·12코어 GPU·듀얼 16코어 Neural Engine·최대 32GB 통합 메모리를 제공",
  summary: "M6는 Apple 첫 2nm 칩으로 12코어 CPU·12코어 GPU·듀얼 16코어 Neural Engine·최대 32GB 통합 메모리를 제공 M5 Ultra는 최대 80코어 GPU·32코어 Neural Engine·최대 512GB 통합 메모리·1.2TB/s 대역폭 제공 Apple 자체 테스트로 M6 AI GPU 연산은 M5 대비 약 30%, M5 Ultra는 M3 Ultra 대비 최대 4.5배 향상 주장 새 Mac mini와 Mac Studio에 각각 탑재 주의: 성능 수치는 Apple 자체 테스트 가격·판매 개시일은 공식 본문에서 미확인",
  content: "**로컬 AI 하드웨어의 메모리 상한이 올라갔습니다**\n\nApple은 8월 25일 첫 2나노미터 M6와 M5 Ultra를 공개했습니다. M6는 12코어 CPU와 12코어 GPU, 듀얼 16코어 Neural Engine, 최대 32GB 통합 메모리를 제공합니다. M5 Ultra는 최대 80코어 GPU, 32코어 Neural Engine, 최대 512GB 통합 메모리와 1.2TB/s 대역폭을 제시합니다.\n\nApple 자체 테스트로 M6의 AI GPU 연산은 M5보다 약 30%, M5 Ultra는 M3 Ultra보다 최대 4.5배 높다고 주장합니다. 가격과 판매 개시일은 공식 본문에서 확인되지 않았습니다.\n\n**직접 확인할 것**\n\n로컬 모델을 고를 때 파라미터 수보다 실제 메모리 점유, 양자화, 대역폭과 전력 예산을 함께 계산하십시오.",
  source: "https://www.apple.com/newsroom/2026/08/apple-introduces-m6-and-m5-ultra-for-a-big-leap-in-performance-and-ai-compute/",
  officialUrl: "https://www.apple.com/newsroom/2026/08/apple-introduces-m6-and-m5-ultra-for-a-big-leap-in-performance-and-ai-compute/",
  verifiedAt: "2026-08-26",
  backupUrls: [],
  slug: "apple-20260825-m6-m5-ultra",
  tags: ["AI", "2026-08b", "Apple"],
  en: {
    title: "Apple unveils its first 2 nm M6 and an M5 Ultra with up to 512 GB",
    deck: "Local AI hardware expands in the Mac mini and Mac Studio.",
    summary: "Apple announced M6 for Mac mini and M5 Ultra for Mac Studio. Vendor specifications include up to 512 GB unified memory and 1.2 TB/s bandwidth; performance comparisons are Apple tests.",
    content: "Apple announced M6 for Mac mini and M5 Ultra for Mac Studio. Vendor specifications include up to 512 GB unified memory and 1.2 TB/s bandwidth; performance comparisons are Apple tests.",
  },
});

const lateNewsWatch: ABEditorPick[] = [
  {
    title: "GPT-6 학습 중단설 — 공식 원출처 없는 미확인 주장",
    slug: "openai-20260827-gpt6-training-stop-unverified",
    deck: "OpenAI 공식 발표와 식별 가능한 원보도에서 학습 중단 사건을 확인하지 못했습니다.",
    category: "AI 팩트체크",
    sourceUrl: "https://openai.com/",
    sourceLabel: "OpenAI 공식 홈페이지 →",
    summary: "8월 27일 기준 GPT-6 학습 중단·일시정지·취소를 확인하는 OpenAI 공식 원문이나 추적 가능한 원보도가 발견되지 않았습니다.",
    body: "공개 Threads 검색, Bing RSS와 일반 검색, OpenAI 공식 홈페이지를 확인했지만 해당 사건의 원출처는 나오지 않았습니다. 공개 자료 부재가 내부 실행의 부재를 증명하지는 않으므로, ‘거짓’이라고 단정하는 대신 ‘미확인 주장’으로 보류합니다.\n\n현재 공개 공식 정보에서 확인되는 최신 계열은 GPT-5.6입니다. GPT-6 이름과 학습 상태는 공식 확인 전까지 카드의 사실 문장으로 사용하지 않습니다.",
    editorial: "속보를 빨리 싣는 것보다 모델명·사건 정체·원출처를 먼저 고정하는 것이 중요합니다.",
    tags: ["OpenAI", "GPT-6", "팩트체크", "미확인"],
    tier: "feature",
  },
  {
    title: "Tiangong Omni — 휴머노이드 400m 45.66초",
    slug: "physical-ai-20260827-tiangong-omni-400m",
    deck: "World Humanoid Robot Games 출처 영상으로 확인한 피지컬 AI 달리기 사례입니다.",
    category: "Physical AI",
    sourceUrl: "https://www.threads.com/@uncover.robotics/post/DcgoEiLkvGU",
    sourceLabel: "원영상 보기 →",
    summary: "Tiangong Omni가 World Humanoid Robot Games 400m를 45.66초에 완주하고 우승했다는 행사 출처 영상입니다.",
    body: "영상에는 팔을 높이 들고 몸을 앞으로 기울인 채 곡선을 도는 달리기 모습이 담겼습니다. 기록과 우승 주장은 World Humanoid Robot Games 출처로 표시됐습니다.\n\n다만 원게시물은 원격조종·자율제어·혼합제어 여부를 밝히지 않았습니다. 자세를 로봇이 스스로 발견했다는 관련 재게시물 주장도 공식 개발사 원문으로 확인되지 않아 제외했습니다.",
    threadsEmbedUrl: "https://www.threads.net/@uncover.robotics/post/DcgoEiLkvGU/embed",
    editorial: "피지컬 AI 시연은 기록뿐 아니라 제어 방식·재시도·배터리·트랙 조건까지 함께 봐야 합니다.",
    tags: ["Physical AI", "Tiangong Omni", "휴머노이드", "로봇"],
    tier: "feature",
  },
];

const editorsPicks: ABEditorPick[] = [
  {
    title: "fluent-korean — Claude Code의 한국어 문장 품질을 다듬는 output style",
    slug: "fluent-korean",
    deck: "조사·어미 생략과 기계적인 명사 나열을 줄이는 한국어 출력 규칙입니다.",
    category: "한국어 AI 글쓰기",
    sourceUrl: "https://github.com/snflkd/fluent-korean",
    sourceLabel: "GitHub에서 보기 →",
    summary: "Claude Code가 조사와 어미를 생략하거나 명사구를 나열하는 문제를 줄이도록 설계된 한국어 output-style 플러그인입니다. MIT 라이선스이며 8월 21일 v1.0.2가 공개됐습니다.",
    body: "Claude Code의 코딩 지침을 유지하는 버전과 글쓰기 규칙만 제공하는 버전을 함께 제공합니다. `/plugin install fluent-korean@fluent-korean`으로 설치할 수 있고, 규칙 본문을 다른 AI 환경의 글쓰기 지침으로 활용할 수도 있습니다.\n\n실측(2026-08-26): ★905 · MIT · v1.0.2. 별 수는 시점에 따라 변합니다.",
    editorial: "한국어 사용자에게 직접 유용하고 설치가 간단합니다. 문장 품질을 개선하는 규칙이지 사실 정확도나 내용 검증을 대신하는 도구는 아닙니다.",
    tags: ["Claude Code", "한국어", "output style", "MIT"],
    tier: "feature",
  },
  {
    title: "lexicon-harness — 모호한 요청을 검증 가능한 실행 프롬프트로",
    slug: "voidlight-lexicon-harness",
    deck: "정확한 용어를 구속하고 EN–KO 지시문과 fail-closed 게이트로 실행까지 잇습니다.",
    category: "프롬프트 하네스",
    sourceUrl: "https://github.com/VoidLight00/lexicon-harness",
    sourceLabel: "GitHub에서 보기 →",
    guideUrl: "https://voidlight00.github.io/lexicon-harness",
    guideLabel: "12분 학습 가이드 →",
    summary: "사용자님께서 만든 하네스로, 해상도가 낮은 요청에서 정확한 도메인 용어를 선정하고 영어 실행 지시문과 한국어 해석을 작성한 뒤 HARD 게이트를 통과시켜 실제 작업까지 이어갑니다.",
    body: "결정론 엔진은 후보 용어를 순위화하고 브리프 스캐폴드를 만들며, `/lexicon` 스킬은 3~8개의 구속 용어를 채택해 EN–KO 실행 프롬프트를 작성합니다. `verify_lexicon.sh`가 브리프·엔진·비밀정보 검사를 fail-closed로 판정하고 exit 0일 때만 실행 경로가 열립니다.\n\n설치: `git clone https://github.com/VoidLight00/lexicon-harness.git ~/.claude/lexicon` 후 skill 파일을 `~/.claude/skills/lexicon/`에 복사합니다. Claude Code 없이도 `lex.py` CLI와 게이트를 직접 사용할 수 있습니다.\n\n실측(2026-08-26): Python · MIT · 공개 저장소. 별 수 0은 공개 직후 시점의 값이며 품질 지표로 사용하지 않습니다.",
    editorial: "이번 VoidNews 작업에도 실제로 적용한 사용자님 제작 오픈소스입니다. 프롬프트를 문서로 만드는 데서 끝나지 않고, 검증된 프롬프트로 요청 작업을 완료하는 것까지 계약에 포함합니다.",
    tags: ["VoidLight", "Lexicon", "프롬프트 엔지니어링", "fail-closed", "MIT"],
    tier: "feature",
  },
];

export const edition2026_08b: ABEdition = {
  slug: "2026-08b",
  volume: 11,
  title: "GLM-5.3-Flash·Ox Alpha 공개부터 에이전트 보안과 로컬 AI까지",
  theme: "운영 · 보안 · 오픈 모델 · 생성형 미디어 · 피지컬 AI · 로컬 AI",
  period: "2026-08-17 ~ 2026-08-26",
  coveredWeeks: [{ slug: "2026-w34", period: "8/17 ~ 8/23" }, { slug: "2026-w35", period: "8/24 ~ 8/30" }],
  announceDate: "2026-08-27",
  nextEditionDate: "2026-09-10",
  sourceCounts: { youtube: 96, x: 0, web: 54, "community-hn": 129, "community-reddit": 0 },
  intro: "8월 하반기에는 에이전트의 기능보다 운영 경계가 더 선명해졌습니다. 세션과 MR 상태를 이어 보고, AI가 공동 작성한 CI를 다시 검증해야 합니다. 편집 마감 뒤에는 OpenRouter 익명 모델 Ox Alpha의 정체가 GLM-5.3-Flash로 확인됐습니다. 생성형 미디어는 음향 제작으로 넓어졌고, 로컬 AI 하드웨어는 512GB 통합 메모리까지 올라갔습니다.",
  closing: "도입 전에 세 가지를 확인하십시오. 공식 날짜와 사건 정체성, 에이전트 권한과 사람 검토 경계, 그리고 벤더 자체 수치와 독립 검증의 차이입니다.",
  coreFlow: ["에이전트 운영", "CI 보안", "프런티어 오픈 모델", "생성형 미디어", "피지컬 AI", "로컬 AI 하드웨어"],
  highlights: [
    { rank: 1, tier: "hero", post: vip1, sourceWeek: "2026-w34", sourceCompany: "Anthropic", editorial: "사용자님께서 직접 선택한 최종 VIP 카드입니다." },
    { rank: 2, tier: "feature", post: vip2, sourceWeek: "2026-w34", sourceCompany: "Wiz", editorial: "사용자님께서 직접 선택한 최종 VIP 카드입니다." },
    { rank: 3, tier: "feature", post: vip3, sourceWeek: "2026-w35", sourceCompany: "Z.ai / OpenRouter", editorial: "OpenRouter 공식 FAQ가 Ox Alpha의 정체라고 확인하며, 성능 비교는 Z.ai 자체 평가로 구분합니다." },
    { rank: 4, tier: "feature", post: vip4, sourceWeek: "2026-w34", sourceCompany: "Pika", editorial: "생성형 미디어의 오디오 제작 확장을 대표하는 최종 VIP 카드입니다." },
    { rank: 5, tier: "feature", post: vip5, sourceWeek: "2026-w35", sourceCompany: "Physical AI", editorial: "사용자님 요청으로 승격한 영상형 피지컬 AI 카드입니다. 제어 방식은 공개되지 않았습니다." },
    { rank: 6, tier: "feature", post: vip6, sourceWeek: "2026-w35", sourceCompany: "Apple", editorial: "로컬 AI 하드웨어와 통합 메모리 상한을 다루는 최종 VIP 카드입니다." }
  ],
  modelWatch: lateNewsWatch,
  editorsPicks,
};
