import type { ABEdition } from "../data";

// 2026-05b — 격주 AB 발표 (2026-05-15 ~ 2026-05-25, 2주 묶음)
// top10 확정: Google I/O / Codex mobile / Glasswing / Vera CPU / Q1 FY27 /
// Managed Agents / Grok Build 0.1 / Thinking Machines / Qwen 3.7 Max / Krea 2
// editorsPicks: 오픈소스 11개 (Mole, hallmark 포함) + 빠진 hero 3개 보조 트랙
// demoCards: 실전 팁 5개

export const edition2026_05b: ABEdition = {
  slug: "2026-05b",
  volume: 4,
  title: "Codex 모바일·Gemini agentic·Vera CPU·Glasswing — AI가 운영체제로 굳는 2주",
  theme: "2026-05-15 ~ 2026-05-25 — Codex가 모바일/Skills/Automations로 확장되고, Google I/O 2026이 Gemini를 agentic platform으로 재정의했으며, NVIDIA Vera CPU가 첫 출하되고, Anthropic Project Glasswing이 10,000+ 취약점을 발견했으며, xAI Grok Build 0.1·Thinking Machines·Qwen 3.7 Max·Krea 2가 동시에 등장한 구간",
  period: "2026-05-15 ~ 2026-05-25",
  coveredWeeks: ["2026-w21", "2026-w22"],
  announceDate: "2026-05-25",
  intro: `이번 2주는 한 회사의 단일 발표가 아니라, 네 가지 흐름이 동시에 굳어진 구간이었습니다.\n\n첫째, OpenAI는 Codex를 ChatGPT 모바일·Skills·Automations·AWS Bedrock·Dell 하이브리드까지 일주일 안에 풀며 "Codex가 어디서나 돈다"는 그림을 완성했습니다. 둘째, Google I/O 2026은 Gemini 3.5/Spark/Omni와 Managed Agents, Antigravity 2.0, AI Studio로 Gemini를 단순 챗봇이 아니라 agentic platform으로 다시 정의했습니다. 셋째, NVIDIA는 Vera CPU 첫 출하 + Q1 FY27 Data Center 752억$로 "에이전트를 굴리는 인프라"가 산업 코어임을 수치로 증명했습니다. 넷째, Anthropic은 Project Glasswing 1만+ 취약점 발견으로 보안 milestone을 만들었고, xAI Grok Build 0.1·Thinking Machines Interaction Models·Qwen 3.7 Max·Krea 2가 동시에 등장하며 모델·창작 vertical까지 다양해졌습니다.\n\n이번 발표 hero는 4라운드 교차 검증(공식 출처 91 + 오픈소스 11 + 실전 팁 5) 풀에서 사용자가 직접 선정한 10개입니다.`,
  closing: `한 줄로 묶으면, AI는 이번 2주 사이에 "어디서나 돌고, 인프라를 정당화하며, 기업 운영체제로 들어가는" 단계로 굳었습니다.\n\n오픈소스 섹션에서는 tw93/Mole(macOS deep clean + AI CLI 잔재 정리), Nutlope/hallmark(anti-AI-slop design skill), manaflow-ai/cmux(Codex CLI 분할 워크플로)처럼 본인 작업 환경과 직접 맞물리는 도구를 골라뒀습니다. 실전 팁 섹션은 Claude Code /compact vs /clear, cmux + Codex CLI split 같이 발표 후 바로 따라할 수 있는 워크플로 중심입니다.\n\n— VoidLight`,
  highlights: [
    {
      rank: 1,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "I/O 2026: Welcome to the agentic Gemini era",
        summary: "Google summarized I/O 2026 AI announcements including Gemini 3.5 Flash, Spark, agentic Search, TPU 8, Gemini Omni, and SynthID expansion.",
        officialUrl: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        source: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        backupUrls: [
          {
            label: "Google I/O 2026 keynote (YouTube)",
            url: "https://www.youtube.com/watch?v=GfTDA_TbVQI",
          },
          {
            label: "Sundar Pichai 키노트 정리",
            url: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
          },
        ],
        tags: ["Gemini", "Search", "Workspace", "Cloud", "Android", "TPU", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      editorial: "Google I/O 2026 — 새 OS급 발표 묶음",
    },
    {
      rank: 2,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Work with Codex from anywhere — Codex in ChatGPT mobile",
        summary: "Codex / ChatGPT mobile",
        officialUrl: "https://openai.com/index/work-with-codex-from-anywhere/",
        source: "https://openai.com/index/work-with-codex-from-anywhere/",
        backupUrls: [
          {
            label: "Introducing the Codex app (공식 게시)",
            url: "https://openai.com/index/introducing-the-codex-app/",
          },
          {
            label: "OpenAI 공식 X",
            url: "https://x.com/OpenAI/status/2055016850849993072",
          },
          {
            label: "TechCrunch 데모 설명",
            url: "https://techcrunch.com/2026/05/14/openai-says-codex-is-coming-to-your-phone/",
          },
        ],
        tags: ["Codex", "ChatGPT mobile", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
      editorial: "Codex가 어디서나 도는 한 주",
    },
    {
      rank: 3,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Project Glasswing: An initial update",
        summary: "Anthropic reported early Project Glasswing results, including partner discovery of more than 10,000 high/critical vulnerabilities.",
        officialUrl: "https://www.anthropic.com/research/glasswing-initial-update",
        source: "https://www.anthropic.com/research/glasswing-initial-update",
        backupUrls: [
          {
            label: "Project Glasswing 원본",
            url: "https://www.anthropic.com/research/glasswing-initial-update",
          },
          {
            label: "The Ringer 보도 (사회적 맥락)",
            url: "https://www.theringer.com/2026/05/06/tech/claude-mythos-anthropic-project-glasswing-cybersecurity-threat-ai",
          },
        ],
        tags: ["Project Glasswing", "security", "Claude Mythos Preview", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
      editorial: "보안 milestone + 10,000+ 취약점",
    },
    {
      rank: 4,
      tier: "hero",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "Vera Arrives: NVIDIA's First CPU Built for Agents Lands at Top AI Labs",
        summary: "NVIDIA Vera CPU / Vera Rubin NVL72 / agentic AI infrastructure",
        officialUrl: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
        source: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
        backupUrls: [
          {
            label: "NVIDIA Dell Tech World 키노트",
            url: "https://blogs.nvidia.com/blog/dell-technologies-agent-enterprise-ai/",
          },
          {
            label: "Vera CPU delivery 본문",
            url: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
          },
        ],
        tags: ["NVIDIA Vera CPU", "Vera Rubin NVL72", "agentic AI infrastructure", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "NVIDIA",
      editorial: "에이전트 인프라 첫 출하",
    },
    {
      rank: 5,
      tier: "hero",
      post: {
        date: "5/20",
        platform: "X+Threads",
        title: "NVIDIA Announces Financial Results for First Quarter Fiscal 2027",
        summary: "NVIDIA Data Center / AI factories / Blackwell",
        officialUrl: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
        source: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
        backupUrls: [
          {
            label: "NVIDIA Newsroom IR 발표",
            url: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
          },
          {
            label: "GTC Taipei 라이브 업데이트",
            url: "https://blogs.nvidia.com/blog/nvidia-gtc-taipei-computex-2026-news/",
          },
        ],
        tags: ["NVIDIA Data Center", "AI factories", "Blackwell", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "NVIDIA",
      editorial: "시장 수치로 흐름 정당화",
    },
    {
      rank: 6,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Introducing Managed Agents in the Gemini API",
        summary: "Google introduced Gemini API Managed Agents running Antigravity-based agents inside secure cloud Linux sandboxes.",
        officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
        source: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
        backupUrls: [
          {
            label: "Managed Agents 공식 발표",
            url: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
          },
          {
            label: "Developer highlights / Antigravity 2.0",
            url: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
          },
        ],
        tags: ["Gemini API", "Managed Agents", "Antigravity", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      editorial: "개발자 paradigm 변경",
    },
    {
      rank: 7,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Grok Build 0.1 added to xAI release notes",
        summary: "xAI API / Grok Build / coding agent model",
        officialUrl: "https://docs.x.ai/developers/release-notes",
        source: "https://docs.x.ai/developers/release-notes",
        backupUrls: [
          {
            label: "Grok Build 0.1 model docs",
            url: "https://docs.x.ai/developers/models/grok-build-0.1",
          },
          {
            label: "xAI Release Notes",
            url: "https://docs.x.ai/developers/release-notes",
          },
          {
            label: "Vercel AI Gateway Grok Build 0.1",
            url: "https://vercel.com/changelog/grok-build-0-1-now-available-on-vercel-ai-gateway",
          },
        ],
        tags: ["xAI API", "Grok Build", "coding agent model", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "xAI",
      editorial: "agentic coding 전용 모델",
    },
    {
      rank: 8,
      tier: "hero",
      post: {
        date: "5/25",
        platform: "X+Threads",
        title: "Thinking Machines Interaction Models — official demo + blog",
        summary: "Thinking Machines / interaction models",
        officialUrl: "https://thinkingmachines.ai/blog/interaction-models/",
        source: "https://thinkingmachines.ai/blog/interaction-models/",
        backupUrls: [
          {
            label: "Interaction Models 공식 블로그 + 데모",
            url: "https://thinkingmachines.ai/blog/interaction-models/",
          },
        ],
        tags: ["Thinking Machines", "interaction models", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
      editorial: "신생사 첫 공식 데모 (시각 자료 강함)",
    },
    {
      rank: 9,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Qwen3.7-Max official benchmark / model card",
        summary: "Qwen / Alibaba / frontier model",
        officialUrl: "https://qwen.ai/blog?id=qwen3.7",
        source: "https://qwen.ai/blog?id=qwen3.7",
        backupUrls: [
          {
            label: "Qwen 3.7 Max 공식 모델 카드 (qwen.ai)",
            url: "https://qwen.ai/blog?id=qwen3.7",
          },
          {
            label: "Vercel AI Gateway 추가 (사용성)",
            url: "https://vercel.com/changelog/qwen-3-7-max-now-available-on-vercel-ai-gateway",
          },
        ],
        tags: ["Qwen", "Alibaba", "frontier model", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
      editorial: "Qwen 본체 + 벤치마크 차트",
    },
    {
      rank: 10,
      tier: "hero",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "Krea 2 is live for everyone",
        summary: "Krea 2 전체 사용자 공개. 한 주 동안 모든 가입자에게 무제한 Krea 2 생성을 제공.",
        officialUrl: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
        source: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
        backupUrls: [
          {
            label: "Krea 2 전체 공개",
            url: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
          },
          {
            label: "Krea 2 LoRA training",
            url: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
          },
          {
            label: "Krea 2 deep dive 가이드",
            url: "https://www.krea.ai/release-notes/krea-2-deep-dive",
          },
          {
            label: "Krea at Cannes Film Festival",
            url: "https://www.krea.ai/release-notes/krea-at-cannes-film-festival",
          },
        ],
        tags: ["Krea 2", "공식", "hero"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Krea",
      editorial: "창작 vertical + 이미지/영상 데모",
    },
  ],
  editorsPicks: [
    {
      title: "tw93/Mole",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/tw93/Mole",
      sourceLabel: "GitHub →",
      summary: "macOS deep clean & optimize CLI. 2026-05 업데이트로 Claude Code, Cursor Agent, GitHub Copilot CLI, Codex CLI 등 AI agent CLI 런",
      body: "macOS deep clean & optimize CLI. 2026-05 업데이트로 Claude Code, Cursor Agent, GitHub Copilot CLI, Codex CLI 등 AI agent CLI 런타임/세션 로그 정리 커버리지 추가. tw93 작가의 다른 작품(이미 사용 중인 tw93/kami)과 같은 라인. AI 개발자에게 실용적인 cleanup 도구.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "Nutlope/hallmark",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/Nutlope/hallmark",
      sourceLabel: "GitHub →",
      summary: "anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
      body: "anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "jamiepine/voicebox",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/jamiepine/voicebox",
      sourceLabel: "GitHub →",
      summary: "오픈소스 음성 도구.",
      body: "오픈소스 음성 도구.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "manaflow-ai/cmux",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/manaflow-ai/cmux",
      sourceLabel: "GitHub →",
      summary: "Peter Steinberger가 소개한 Codex CLI 워크플로우 분할용 tmux 보조 도구. 본인이 cmux/cmuxr 하네스 사용자라 직접 와닿는 후보.",
      body: "Peter Steinberger가 소개한 Codex CLI 워크플로우 분할용 tmux 보조 도구. 본인이 cmux/cmuxr 하네스 사용자라 직접 와닿는 후보.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "builderpepc/agent-migrator",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/builderpepc/agent-migrator",
      sourceLabel: "GitHub →",
      summary: "AI 코딩 세션을 도구 간 마이그레이션하는 오픈소스. Claude Code/Codex/Cursor 사이 컨텍스트 이전 시나리오.",
      body: "AI 코딩 세션을 도구 간 마이그레이션하는 오픈소스. Claude Code/Codex/Cursor 사이 컨텍스트 이전 시나리오.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "allenai/OlmoEarth v1.1",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/allenai/olmoearth-v1-1",
      sourceLabel: "GitHub →",
      summary: "Earth observation을 위한 경량 오픈 모델.",
      body: "Earth observation을 위한 경량 오픈 모델.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "IBM Granite 4.1",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/ibm-granite/granite-4-1",
      sourceLabel: "GitHub →",
      summary: "IBM의 오픈 LLM 라인업 4.1 학습 파이프라인 공개.",
      body: "IBM의 오픈 LLM 라인업 4.1 학습 파이프라인 공개.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "vLLM RL backend correctness (ServiceNow)",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/ServiceNow-AI/correctness-before-corrections",
      sourceLabel: "GitHub →",
      summary: "vLLM RL 학습 backend의 V0→V1 정합성 정리.",
      body: "vLLM RL 학습 backend의 V0→V1 정합성 정리.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "HF continuous async batching",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/continuous_async",
      sourceLabel: "GitHub →",
      summary: "HF inference 비동기 연속 배치 처리 가이드.",
      body: "HF inference 비동기 연속 배치 처리 가이드.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "IBM Granite Embedding Multilingual R2",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/ibm-granite/granite-embedding-multilingual-r2",
      sourceLabel: "GitHub →",
      summary: "오픈 다국어 임베딩 모델 R2.",
      body: "오픈 다국어 임베딩 모델 R2.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "PaddleOCR 3.5 Transformers",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/PaddlePaddle/paddleocr-transformers",
      sourceLabel: "GitHub →",
      summary: "PaddleOCR을 Transformers 백엔드로 실행하는 가이드.",
      body: "PaddleOCR을 Transformers 백엔드로 실행하는 가이드.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "Anthropic Claude Code Agent View",
      category: "AI 개발 도구 / Anthropic",
      sourceUrl: "https://www.testingcatalog.com/anthropic-adds-agent-view-for-claude-code-for-parralel-work/",
      sourceLabel: "공식 링크 →",
      summary: "Claude Code 2.1.139부터 모든 병렬 세션을 한 화면에서 관리. 본 발표 hero에서는 빠졌지만 사용자 워크플로 직격이라 보조 트랙에 둠.",
      body: "Claude Code 2.1.139부터 모든 병렬 세션을 한 화면에서 관리. 본 발표 hero에서는 빠졌지만 사용자 워크플로 직격이라 보조 트랙에 둠.",
      editorial: "hero에서는 빠졌지만 본 회차 맥락상 중요 항목 — 보조 트랙으로 보존.",
      tags: ["hero제외", "보조"],
      tier: "normal",
    },
    {
      title: "OpenAI Codex app · Skills · Automations",
      category: "AI 개발 도구 / OpenAI",
      sourceUrl: "https://openai.com/index/introducing-the-codex-app/",
      sourceLabel: "공식 링크 →",
      summary: "Codex mobile과 같은 묶음. hero 카드 2번에서 일부 다루므로 보조 카드로 분리.",
      body: "Codex mobile과 같은 묶음. hero 카드 2번에서 일부 다루므로 보조 카드로 분리.",
      editorial: "hero에서는 빠졌지만 본 회차 맥락상 중요 항목 — 보조 트랙으로 보존.",
      tags: ["hero제외", "보조"],
      tier: "normal",
    },
    {
      title: "Anthropic Stainless 인수",
      category: "AI 플랫폼 / Anthropic",
      sourceUrl: "https://www.anthropic.com/news/anthropic-acquires-stainless",
      sourceLabel: "공식 링크 →",
      summary: "SDK/CLI/MCP 개발자 경험 강화를 위한 인수. 시각 자료가 약해 hero에서 보조 트랙으로 이동.",
      body: "SDK/CLI/MCP 개발자 경험 강화를 위한 인수. 시각 자료가 약해 hero에서 보조 트랙으로 이동.",
      editorial: "hero에서는 빠졌지만 본 회차 맥락상 중요 항목 — 보조 트랙으로 보존.",
      tags: ["hero제외", "보조"],
      tier: "normal",
    },
  ],
  demoCards: [
    {
      title: "Claude Code context management — /compact vs /clear",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=eW3oTyfeWZ0",
      label: "원문 →",
      summary: "세션 컨텍스트 관리 실전 팁.",
      body: "세션 컨텍스트 관리 실전 팁.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "Peter Steinberger cmux + Codex CLI workflow split",
      category: "실전 팁",
      url: "https://github.com/manaflow-ai/cmux",
      label: "원문 →",
      summary: "cmux 다중 pane + Codex CLI 작업 분할 패턴.",
      body: "cmux 다중 pane + Codex CLI 작업 분할 패턴.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "AI prompt usage: method-first prompting",
      category: "실전 팁",
      url: "https://www.instagram.com/p/DYCDIvelD5p/",
      label: "원문 →",
      summary: "방법론을 먼저 제시하는 프롬프트 스타일.",
      body: "방법론을 먼저 제시하는 프롬프트 스타일.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "YC Diana Hu — AI-native company 구성 방식",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=EN7frwQIbKc",
      label: "원문 →",
      summary: "YC 파트너 관점에서 AI-native 회사가 갖춰야 할 구조.",
      body: "YC 파트너 관점에서 AI-native 회사가 갖춰야 할 구조.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "Jensen Huang CMU commencement — AI jobs message",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=uSs7PPAJR20",
      label: "원문 →",
      summary: "AI 시대 일자리에 대한 NVIDIA CEO 졸업 연설.",
      body: "AI 시대 일자리에 대한 NVIDIA CEO 졸업 연설.",
      tags: ["실전팁", "워크플로"],
    },
  ],
};
