import type { ABEdition, ABEditorPick } from "../data";
import type { Post } from "../../data";

// 2026-08b — user-selected VIP set. Editorial cutoff: 2026-08-26 21:48 KST.
function post(input: Post): Post { return input; }

const vip1 = post({
  date: "8/17",
  platform: "X+Threads",
  title: "Claude Code, GitLab MR 상태 배지와 사용량 제한 자동 재개 추가",
  featured: true,
  deck: "GitLab remote와 인증된 glab CLI가 있으면 footer/statusline에 MR !N 상태 표시",
  summary: "GitLab remote와 인증된 glab CLI가 있으면 footer/statusline에 MR !N 상태 표시 claude.ai 사용량 제한 초기화 시 세션 자동 계속 Windows NT namespace 경로를 사전승인 파일 접근 경계에서 거부",
  content: "**운영 화면에 상태가 들어왔습니다**\n\nClaude Code 2.1.234는 GitLab remote와 인증된 glab CLI가 있으면 footer와 status line에 merge request 번호와 상태를 표시합니다. 사용량 제한이 초기화되면 세션을 자동으로 이어가며, Windows NT namespace 경로를 사전 승인 파일 접근 경계에서 거부합니다.\n\n**같은 문제를 다루는 오픈소스**\n\n사용량 제한으로 멈춘 작업을 다시 잇는 일은 그동안 각자 스크립트로 해결하던 영역이었습니다. 제가 만들어 공개한 nightguardian도 그중 하나입니다. tmux 패널을 지켜보다가 제한이 풀리면 멈춘 Claude Code 세션을 안전하게 재개하는 fail-closed 워치독이고, MIT 라이선스에 셸 스크립트로 되어 있습니다. 이번 업데이트로 같은 기능이 도구 안으로 들어왔으니, 두 방식을 비교하면서 어디까지 도구에 맡기고 어디부터 직접 통제할지 정하시면 됩니다.\n\n**직접 확인할 것**\n\n팀이 GitLab을 사용한다면 상태 표시가 실제 인증과 remote 설정을 읽는지 확인하십시오. 자동 재개는 성공 판정이 아니라 사용량 제한 이후의 실행 재개입니다.",
  source: "https://github.com/anthropics/claude-code/releases/tag/v2.1.234",
  officialUrl: "https://github.com/anthropics/claude-code/releases/tag/v2.1.234",
  verifiedAt: "2026-08-26",
  backupUrls: [{ label: "nightguardian — 같은 문제를 다루는 오픈소스", url: "https://github.com/VoidLight00/nightguardian" }],
  slug: "claude-code-20260817-v2-1-234",
  tags: ["AI", "2026-08b", "Anthropic"],
  en: {
    title: "Claude Code adds GitLab MR status and automatic usage-limit resume",
    deck: "GitLab merge-request state now appears in the footer and status line.",
    summary: "Claude Code 2.1.234 displays authenticated GitLab merge-request status, resumes sessions after claude.ai usage limits reset, and rejects Windows NT namespace paths at the pre-approved file boundary.",
    content: "Claude Code 2.1.234 displays authenticated GitLab merge-request status, resumes sessions after claude.ai usage limits reset, and rejects Windows NT namespace paths at the pre-approved file boundary.",
  },
  thumbnail: {
    src: "/og-cache/claude-code-gitlab-mr-상태-배지와-사용량-제한-자동-재-bbeb623c.png",
    alt: "Claude Code, GitLab MR 상태 배지와 사용량 제한 자동 재개 추가",
  },
});

const vip2 = post({
  date: "8/17",
  platform: "X+Threads",
  title: "AI가 공동 작성한 CI 변경, Snowflake Jira 자격 증명 노출 경로 만들었다",
  featured: true,
  deck: "이슈 제목의 직접 셸 보간으로 인증 없는 명령 실행 가능",
  summary: "이슈 제목의 직접 셸 보간으로 인증 없는 명령 실행 가능 러너의 Jira 읽기 자격 증명 접근 가능 Snowflake가 6월 23일 수정하고 6월 24일 토큰 교체 감사 로그에서 제3자 접근 증거 없음 주의: 취약점 사건 발생은 6월이며 8월 17일은 연구 공개일 Copilot이 코드 자체를 생성했는지는 불명확",
  content: "**AI 작성 여부보다 실행 경계가 문제였습니다**\n\nWiz는 Snowflake GitHub Actions 흐름에서 이슈 제목이 셸에 직접 보간돼 인증 없는 명령 실행 경로가 생겼다고 공개했습니다. 러너가 Jira 읽기 자격 증명에 접근할 수 있었고, Snowflake는 6월 23일 수정하고 6월 24일 토큰을 교체했습니다.\n\n연구 공개일은 8월 17일이지만 사건 자체는 6월입니다. Copilot이 취약한 코드를 직접 생성했는지는 확인되지 않았습니다.\n\n**직접 확인할 것**\n\nAI가 공동 작성한 CI 변경도 외부 입력의 셸 보간, 러너 토큰 권한, 감사 로그를 별도 게이트로 검토하십시오.",
  source: "https://www.wiz.io/blog/red-agent-snowflake-copilot-cicd-bug",
  officialUrl: "https://www.wiz.io/blog/red-agent-snowflake-copilot-cicd-bug",
  verifiedAt: "2026-08-26",
  backupUrls: [],
  slug: "wiz-20260817-snowflake-cicd",
  tags: ["AI", "2026-08b", "Wiz"],
  en: {
    title: "A CI change exposed a Snowflake Jira credential path",
    deck: "Issue-title shell interpolation enabled unauthenticated command execution.",
    summary: "Wiz disclosed a Snowflake GitHub Actions flaw where issue titles reached a shell and exposed a path to Jira read credentials. The incident was fixed in June; the research was published August 17.",
    content: "Wiz disclosed a Snowflake GitHub Actions flaw where issue titles reached a shell and exposed a path to Jira read credentials. The incident was fixed in June; the research was published August 17.",
  },
  thumbnail: {
    src: "/og-cache/ai가-공동-작성한-ci-변경-snowflake-jira-자격-증명-노출-64d3338b.webp",
    alt: "AI가 공동 작성한 CI 변경, Snowflake Jira 자격 증명 노출 경로 만들었다",
  },
});

const vip3 = post({
  date: "8/26",
  platform: "X+Threads",
  title: "GLM-5.3-Flash 공개, OpenRouter 익명 모델 Ox Alpha의 정체였다",
  featured: true,
  deck: "320B 중 18B만 활성화하고 100만 토큰 컨텍스트를 제공하는 네이티브 멀티모달 모델",
  summary: "Z.ai GLM-5.3-Flash는 320B total·18B active MoE와 이미지·영상 입력, 1,048,576토큰 컨텍스트를 제공 OpenRouter가 stealth model Ox Alpha의 정체가 GLM-5.3-Flash였다고 공식 FAQ에서 확인 입력 $0.075/M·출력 $0.25/M·캐시 읽기 $0.015/M 주의: 벤치마크·10분의 1 가격 주장은 Z.ai 자체 보고",
  content: "**Ox Alpha의 정체가 공개됐습니다**\n\nZ.ai는 8월 26일 GLM-5.3-Flash를 공개했습니다. 공식 가중치는 총 3,200억 파라미터 가운데 토큰당 180억을 활성화하고, 텍스트·이미지·영상을 입력받는 네이티브 멀티모달 구조와 MIT 라이선스를 사용합니다. OpenRouter는 모델 FAQ에서 이전 stealth model인 Ox Alpha가 GLM-5.3-Flash였다고 명시했습니다.\n\nOpenRouter 제공 사양은 1,048,576토큰 컨텍스트와 최대 131,072토큰 출력입니다. 50% 할인 가격은 100만 토큰당 입력 0.075달러, 출력 0.25달러, 캐시 읽기 0.015달러입니다.\n\n**검증 한계**\n\nGLM-5.2보다 전반적으로 높고 Claude Opus 4.8에 접근한다는 벤치마크 및 10분의 1 가격 주장은 Z.ai 공식 문서의 자체 평가입니다. OpenRouter의 Ox Alpha 확인은 공식 플랫폼 FAQ 근거이지만, Z.ai GitHub와 Hugging Face에는 Ox Alpha 명칭이 없습니다.\n\n**직접 확인할 것**\n\nOpenRouter의 `z-ai/glm-5.3-flash`로 실제 코딩·장기 에이전트 작업을 시험하고, 기존 Ox Alpha 사용 기록이 있다면 같은 프롬프트의 결과와 비용을 비교하십시오.",
  thumbnail: {
    src: "/og-cache/glm-5-3-flash-openrouter-official.png",
    alt: "OpenRouter 공식 모델 페이지의 GLM-5.3-Flash 사양과 가격 화면",
  },
  source: "https://docs.z.ai/guides/llm/glm-5.3-flash",
  officialUrl: "https://docs.z.ai/guides/llm/glm-5.3-flash",
  verifiedAt: "2026-08-27",
  backupUrls: [{ label: "OpenRouter 공식 모델 페이지 · Ox Alpha 확인", url: "https://openrouter.ai/z-ai/glm-5.3-flash" }, { label: "Z.ai GLM-5 공식 저장소", url: "https://github.com/zai-org/GLM-5" }, { label: "Hugging Face 공식 가중치", url: "https://huggingface.co/zai-org/GLM-5.3-Flash" }, { label: "Artificial Analysis 독립 지능 지수 비교", url: "https://artificialanalysis.ai/#intelligence" }, { label: "Choi GLM-5.3-Flash 벤치마크 스레드", url: "https://www.threads.com/@choi.openai/post/Dcgb7pgDxYv" }, { label: "OddSVG GLM 시각 비교", url: "https://www.threads.com/@transurfer.ai/post/DcghJPLGudB" }],
  visualComparisons: [
    {
      title: "GLM-5.3-Flash 공개와 Ox Alpha 정체·비용·벤치마크",
      model: "GLM-5.3-Flash / Ox Alpha",
      task: "Terminal-Bench·DeepSWE·Artificial Analysis 수치와 모델 구조를 설명하는 큐레이터 브리핑",
      comparisonClass: "context",
      comparisonLabel: "벤치마크 맥락",
      sourceUrl: "https://www.threads.com/@choi.openai/post/Dcgb7pgDxYv",
      embedUrl: "https://www.threads.net/@choi.openai/post/Dcgb7pgDxYv/embed",
      promptStatus: "해당 없음 — 제작 과제 실행물이 아니라 지표 설명",
      runtimeStatus: "해당 없음",
      toolStatus: "Choi 큐레이션이며 수치는 Z.ai·Artificial Analysis 원자료 재확인 필요",
      benchmarkNote: "Terminal-Bench 2.1 84.3, DeepSWE 1.1 63.4, Artificial Analysis Intelligence Index 57·task cost $0.045라는 큐레이터 요약. 독립 재측정이 아닙니다.",
      caveat: "Choi님의 해설 화면은 비교 맥락용입니다. 벤더·평가기관 수치를 VoidNews가 다시 실행한 결과로 해석하면 안 됩니다.",
    },
    {
      title: "OddSVG 결과로 본 GLM-5.3과 GLM-5.3-Flash",
      model: "GLM-5.3 vs GLM-5.3-Flash",
      task: "SVG 생성 결과의 시각 품질 비교",
      comparisonClass: "showcase",
      comparisonLabel: "시연 비교 · 동일 조건 미확인",
      sourceUrl: "https://www.threads.com/@transurfer.ai/post/DcghJPLGudB",
      embedUrl: "https://www.threads.net/@transurfer.ai/post/DcghJPLGudB/embed",
      promptStatus: "원게시물에 정확한 프롬프트 전문이 공개되지 않음",
      runtimeStatus: "모델별 실행 시간·재시도 횟수 미공개",
      toolStatus: "OddSVG 사용은 명시됐으나 시작 자산·후처리·샘플 선택 기준 미공개",
      benchmarkNote: "게시자는 성능이 비슷하고 Flash 가격이 낮아졌다고 평가합니다. 정량 점수나 블라인드 판정은 제공되지 않았습니다.",
      caveat: "선별된 결과를 보여주는 showcase입니다. 같은 프롬프트·시간·도구·샘플링을 통제한 decisive experiment가 아닙니다.",
    },
    {
      title: "큐레이터 시연 영상으로 본 모델별 제작 결과",
      model: "GLM-5.3-Flash 포함 복수 모델 · 원게시물 표기 기준",
      task: "동일 과제를 여러 모델에 시켰을 때의 결과 화면 비교",
      comparisonClass: "showcase",
      comparisonLabel: "시연 비교 · 조건 미확인",
      sourceUrl: "https://www.threads.com/@aiwithgenzofficial/post/DcU1BlZCZ2I",
      embedUrl: "https://www.threads.net/@aiwithgenzofficial/post/DcU1BlZCZ2I/embed",
      promptStatus: "원게시물에 프롬프트 전문이 공개되지 않음",
      runtimeStatus: "모델별 실행 시간·재시도 횟수 미공개",
      toolStatus: "사용 도구와 시작 자산, 샘플 선택 기준 미공개",
      benchmarkNote: "게시자가 고른 결과 화면을 이어 붙인 영상입니다. 점수나 블라인드 판정은 제공되지 않습니다.",
      caveat: "@aiwithgenzofficial 계정의 큐레이션 영상이며 VoidNews가 재현한 결과가 아닙니다. 어떤 모델이 우월하다는 판정 근거로 쓰지 않습니다.",
    },
  ],
  slug: "zai-20260826-glm-5-3-flash-ox-alpha",
  tags: ["AI", "2026-08b", "Z.ai", "OpenRouter", "GLM"],
  en: {
    title: "GLM-5.3-Flash launches as the model behind OpenRouter's Ox Alpha",
    deck: "The native multimodal MoE activates 18B of 320B parameters with a one-million-token context.",
    summary: "Z.ai released GLM-5.3-Flash on August 26. OpenRouter identifies it as the former stealth model Ox Alpha and lists a 1,048,576-token context at discounted pricing of $0.075/M input and $0.25/M output tokens.",
    content: "Z.ai released GLM-5.3-Flash on August 26. OpenRouter identifies it as the former stealth model Ox Alpha and lists a 1,048,576-token context at discounted pricing of $0.075/M input and $0.25/M output tokens. Benchmark comparisons remain vendor-reported.",
  },
});

const vip4 = post({
  date: "8/18",
  platform: "X+Threads",
  title: "Pika, 음악·효과음·음성·영상 사운드 모델 4종 동시 공개",
  featured: true,
  deck: "Soundtrack은 영상에서 동기화된 음향 장면 생성",
  summary: "Soundtrack은 영상에서 동기화된 음향 장면 생성 Music은 최대 90초 곡을 평균 6.21초에 생성한다고 주장 SFX는 1~20초 MP3 효과음을 실시간 수준으로 생성 Speech는 5초 참조 음성 복제·최대 5분 생성·RTF 0.02 제시 주의: 성능 수치는 Pika 자체 주장 한국어 지원은 명시되지 않음",
  content: "**영상 서비스가 오디오 전체로 확장됐습니다**\n\nPika는 8월 18일 Soundtrack, Music, SFX, Speech를 함께 공개했습니다. Soundtrack은 영상 장면에 맞춘 음향을 만들고, Music은 최대 90초 곡, SFX는 1초에서 20초 효과음, Speech는 5초 참조 음성으로 최대 5분 음성을 생성한다고 설명합니다.\n\n성능과 속도 수치는 Pika 자체 주장이고 한국어 지원은 명시되지 않았습니다.\n\n**직접 확인할 것**\n\n영상 생성 비용과 별도로 음원 권리, 음성 복제 동의, 후반 편집 가능성을 확인하십시오.",
  source: "https://pika.art/blog/pika-soundtrack",
  officialUrl: "https://pika.art/blog/pika-soundtrack",
  verifiedAt: "2026-08-26",
  backupUrls: [],
  slug: "pika-20260818-audio-suite",
  tags: ["AI", "2026-08b", "Pika"],
  en: {
    title: "Pika launches models for music, effects, speech and video sound",
    deck: "The video platform expands across the full audio layer.",
    summary: "Pika announced Soundtrack, Music, SFX and Speech together on August 18. Performance figures are vendor claims, and Korean-language support was not specified.",
    content: "Pika announced Soundtrack, Music, SFX and Speech together on August 18. Performance figures are vendor claims, and Korean-language support was not specified.",
  },
  thumbnail: {
    src: "/og-cache/pika-음악-효과음-음성-영상-사운드-모델-4종-동시-공개-0c5fac65.jpg",
    alt: "Pika, 음악·효과음·음성·영상 사운드 모델 4종 동시 공개",
  },
});

const vip5 = post({
  date: "8/22",
  platform: "X+Threads",
  title: "휴머노이드 로봇이 100m를 9.39초에 — 볼트의 9.58초보다 빨랐습니다",
  featured: true,
  deck: "작년 대회 최고 기록 21.50초가 1년 만에 9.39초가 됐습니다",
  summary: "2nd World Humanoid Robot Games 100m 예선에서 Tianzhuo 팀 로봇이 9.39초로 1위 우사인 볼트의 인간 세계기록 9.58초보다 0.19초 빠른 기록 작년 같은 종목 최고 기록은 21.50초 주의: 예선 기록이며 로봇 경기 규정은 인간 육상과 달라 같은 조건의 기록 경신이 아님",
  content: "**1년 만에 21.50초가 9.39초가 됐습니다**\n\n8월 22일 저녁 베이징 아이스리본 경기장에서 열린 2nd World Humanoid Robot Games 100m 예선에서, Tianzhuo 팀이 개발한 휴머노이드 로봇이 9.39초로 결승선을 통과했습니다. Wind-Fire Lightning 팀 로봇과 끝까지 접전이었고 한 몸 길이 차로 앞섰습니다.\n\n이 숫자가 화제가 된 이유는 우사인 볼트의 인간 100m 세계기록 9.58초보다 0.19초 빠르기 때문입니다. 다만 진짜로 눈여겨볼 숫자는 따로 있습니다. 작년 같은 대회 이 종목 최고 기록은 21.50초였습니다. 1년 만에 절반 이하로 줄어든 셈입니다.\n\n**검증 한계**\n\n이 기록은 결승이 아니라 예선에서 나왔습니다. 그리고 로봇 경기의 출발 방식, 트랙 규정, 기체 조건은 인간 육상 공식 규정과 다릅니다. 볼트의 기록과 나란히 놓을 수는 있어도 같은 조건에서 이겼다고 말할 수는 없습니다. 제어 방식이 완전 자율인지, 원격 개입이 있었는지도 공개 자료에 명시되지 않았습니다.\n\n**직접 확인할 것**\n\n로봇 기록 뉴스를 볼 때는 기록 하나보다 다음을 함께 보십시오. 예선인지 결승인지, 넘어짐과 재시도가 있었는지, 배터리와 트랙 조건은 무엇이었는지, 여러 경기에서 같은 기체를 썼는지입니다. 같은 대회 400m 결과는 아래 \u2018Top 10 밖에서 추가로 볼 모델\u2019 카드에서 이어서 보시면 됩니다.",
  source: "https://www.globaltimes.cn/page/202608/1368761.shtml",
  officialUrl: "https://www.globaltimes.cn/page/202608/1368761.shtml",
  verifiedAt: "2026-08-27",
  backupUrls: [{ label: "Al Jazeera 영상 보도", url: "https://www.aljazeera.com/video/newsfeed/2026/8/23/chinese-robot-beats-usain-bolts-100m-world-record-at-humanoid-games" }, { label: "BBC News 영상", url: "https://www.youtube.com/watch?v=FGBLzMESBAo" }, { label: "World Humanoid Robot Games 개요", url: "https://en.wikipedia.org/wiki/World_Humanoid_Robot_Games" }],
  thumbnail: {
    src: "/og-cache/tiangong-omni-cgtn-race.jpg",
    alt: "2nd World Humanoid Robot Games 100m 트랙을 달리는 휴머노이드 로봇",
  },
  videoUrl: "https://www.youtube.com/embed/B8DyUJagc2M",
  videoCaption: "CGTN · 100m 경기 전체 영상",
  slug: "physical-ai-20260822-humanoid-100m-9-39",
  tags: ["AI", "2026-08b", "Physical AI", "휴머노이드", "로봇"],
  en: {
    title: "A humanoid robot ran 100 m in 9.39 seconds, faster than Bolt's 9.58",
    deck: "Last year's best in the same event was 21.50 seconds.",
    summary: "At a 100 m preliminary of the 2nd World Humanoid Robot Games on August 22, a robot from the Tianzhuo team finished in 9.39 seconds, 0.19 faster than Usain Bolt's human world record. Last year's best in the event was 21.50 seconds.",
    content: "At a 100 m preliminary of the 2nd World Humanoid Robot Games in Beijing on August 22, a robot built by the Tianzhuo team won in 9.39 seconds, ahead of Usain Bolt's 9.58 second human world record. The more telling number is the year-over-year jump: the same event topped out at 21.50 seconds last year. Robot race rules differ from human athletics, and this was a preliminary, so the times are not a like-for-like comparison.",
  },
});

const vip6 = post({
  date: "8/25",
  platform: "X+Threads",
  title: "Apple, 첫 2nm M6와 최대 512GB 메모리 M5 Ultra 공개",
  featured: true,
  deck: "M6는 Apple 첫 2nm 칩으로 12코어 CPU·12코어 GPU·듀얼 16코어 Neural Engine·최대 32GB 통합 메모리를 제공",
  summary: "M6는 Apple 첫 2nm 칩으로 12코어 CPU·12코어 GPU·듀얼 16코어 Neural Engine·최대 32GB 통합 메모리를 제공 M5 Ultra는 최대 80코어 GPU·32코어 Neural Engine·최대 512GB 통합 메모리·1.2TB/s 대역폭 제공 Apple 자체 테스트로 M6 AI GPU 연산은 M5 대비 약 30%, M5 Ultra는 M3 Ultra 대비 최대 4.5배 향상 주장 새 Mac mini와 Mac Studio에 각각 탑재 주의: 성능 수치는 Apple 자체 테스트 가격·판매 개시일은 공식 본문에서 미확인",
  content: "**로컬 AI 하드웨어의 메모리 상한이 올라갔습니다**\n\nApple은 8월 25일 첫 2나노미터 M6와 M5 Ultra를 공개했습니다. M6는 12코어 CPU와 12코어 GPU, 듀얼 16코어 Neural Engine, 최대 32GB 통합 메모리를 제공합니다. M5 Ultra는 최대 80코어 GPU, 32코어 Neural Engine, 최대 512GB 통합 메모리와 1.2TB/s 대역폭을 제시합니다.\n\nApple 자체 테스트로 M6의 AI GPU 연산은 M5보다 약 30%, M5 Ultra는 M3 Ultra보다 최대 4.5배 높다고 주장합니다. 가격과 판매 개시일은 공식 본문에서 확인되지 않았습니다.\n\n**직접 확인할 것**\n\n로컬 모델을 고를 때 파라미터 수보다 실제 메모리 점유, 양자화, 대역폭과 전력 예산을 함께 계산하십시오.",
  source: "https://www.apple.com/newsroom/2026/08/apple-introduces-m6-and-m5-ultra-for-a-big-leap-in-performance-and-ai-compute/",
  officialUrl: "https://www.apple.com/newsroom/2026/08/apple-introduces-m6-and-m5-ultra-for-a-big-leap-in-performance-and-ai-compute/",
  verifiedAt: "2026-08-26",
  backupUrls: [],
  slug: "apple-20260825-m6-m5-ultra",
  tags: ["AI", "2026-08b", "Apple"],
  en: {
    title: "Apple unveils its first 2 nm M6 and an M5 Ultra with up to 512 GB",
    deck: "Local AI hardware expands in the Mac mini and Mac Studio.",
    summary: "Apple announced M6 for Mac mini and M5 Ultra for Mac Studio. Vendor specifications include up to 512 GB unified memory and 1.2 TB/s bandwidth; performance comparisons are Apple tests.",
    content: "Apple announced M6 for Mac mini and M5 Ultra for Mac Studio. Vendor specifications include up to 512 GB unified memory and 1.2 TB/s bandwidth; performance comparisons are Apple tests.",
  },
  thumbnail: {
    src: "/og-cache/apple-첫-2nm-m6와-최대-512gb-메모리-m5-ultra-공개-9e0dcfcc.jpg",
    alt: "Apple, 첫 2nm M6와 최대 512GB 메모리 M5 Ultra 공개",
  },
});

const lateNewsWatch: ABEditorPick[] = [
  {
    title: "OpenAI가 프런티어 RL 학습을 멈췄습니다 — 'GPT-6 연기'는 아직 추측입니다",
    slug: "openai-20260827-gpt6-training-stop-unverified",
    deck: "중단은 사실이고, 대상 모델 이름은 Astra이며, GPT-6는 어디에도 나오지 않습니다.",
    category: "AI 팩트체크",
    sourceUrl: "https://openai.com/index/pacing-model-development-cyber-capabilities/",
    sourceLabel: "OpenAI 공식 발표 →",
    guideUrl: "https://x.com/sama/status/2089787807611195475",
    guideLabel: "샘 알트먼 원문 게시물 →",
    summary: "샘 알트먼은 8월 18일 X에서 일부 프런티어 RL 학습을 중단했다고 직접 밝혔고 OpenAI 공식 문서도 배포 예정 최신 모델의 RL 학습 2주 중단과 최대 규모 학습 보류를 설명합니다. 다만 알트먼도 공식 문서도 그 모델을 GPT-6라고 부르지 않았습니다.",
    body: "**확인된 사실**\n\n샘 알트먼은 8월 18일 X에서 \u201c앞에 놓인 새로운 수준의 역량에 맞는 정렬·보안·모니터링 기준을 충족하기 위해 일부 프런티어 RL 학습을 중단했다\u201d고 직접 밝혔습니다. OpenAI 공식 문서도 같은 내용을 설명합니다. 배포를 앞둔 최신 모델의 강화학습을 2주간 멈추고 연구 환경을 다시 점검했으며, 계획했던 최대 규모 학습은 종료 시점을 정하지 않은 채 보류했습니다.\n\n중단의 계기도 공개돼 있습니다. 내부 평가에서 Astra라는 모델이 OpenAI 자체 Preparedness Framework의 사이버보안 Critical 임계값에 도달할 수 있다는 예비 증거가 나왔습니다. 에이전트형 코딩과 사이버 역량에서 눈에 띄는 진전이 확인됐고, 강화된 보안 통제 요건을 충족하지 못한 Astra 관련 내부 활동도 함께 멈췄습니다.\n\n**확인되지 않은 것**\n\n이 사건이 \u2018GPT-6 출시 연기\u2019로 옮겨 적히는 경우가 많은데, 그 이름은 어느 원문에도 없습니다. 알트먼의 게시물에도, OpenAI 공식 문서에도 GPT-6는 등장하지 않습니다. 문서가 지목하는 모델명은 Astra입니다. 중단된 학습이 다음 세대 주력 모델인지, 그 모델이 어떤 이름으로 나올지는 공개 자료로 확인할 수 없습니다.\n\n**어떻게 읽을까**\n\n\u2018OpenAI가 GPT-6를 연기했다\u2019가 아니라 \u2018OpenAI가 사이버 역량 임계에 걸린 모델의 학습을 스스로 멈췄다\u2019가 확인된 문장입니다. 뒤쪽이 오히려 더 중요한 소식입니다. 회사가 자체 안전 기준을 근거로 학습을 멈추고 그 사실을 공개했다는 선례이기 때문입니다. 모델 이름을 붙이는 순간 추측이 사실처럼 굳으니, 발표에서도 이 두 문장을 분리해서 말하겠습니다.",
    editorial: "사건은 사실이고 이름만 추측입니다. 둘을 한 문장에 섞으면 확인된 소식까지 루머로 보이게 됩니다.",
    tags: ["OpenAI", "Astra", "팩트체크", "AI 안전"],
    tier: "feature",
  },
  {
    title: "같은 대회 400m — 로봇이 스스로 찾아낸 '부끄러운 달리기'",
    slug: "physical-ai-20260827-tiangong-omni-400m",
    deck: "손을 얼굴에 든 자세는 설계가 아니라 강화학습이 찾은 열 관리 해법이었습니다.",
    category: "Physical AI",
    sourceUrl: "https://www.globaltimes.cn/page/202608/1368875.shtml",
    sourceLabel: "Global Times 제작사 인터뷰 →",
    summary: "8월 23일 400m 소그룹 결승에서 X-Humanoid의 Tien Kung Omni가 45.66초로 우승했습니다. 대그룹 결승에서는 같은 회사의 Tien Kung Ultra가 38.15초를 기록해 남자 400m 세계기록 43.03초보다 빨랐습니다.",
    body: "100m가 속도의 도약을 보여줬다면, 400m는 그 속도를 어떻게 400미터 동안 버티느냐의 문제입니다.\n\n소그룹 결승 우승 기체인 Tien Kung Omni는 팔을 얼굴 가까이 든 채 상체를 기울이고 허리를 크게 비트는 자세로 달려 '부끄러운 달리기'라는 별명을 얻었습니다. 제작사 X-Humanoid에서 모션 제어 알고리즘을 담당하는 Han Gang은 Global Times 인터뷰에서, 처음에는 사람처럼 팔을 앞뒤로 흔드는 보행으로 설계했지만 시뮬레이션 학습에서 보상을 반복해 주자 로봇이 이 자세로 수렴했다고 밝혔습니다.\n\n이유는 물리적 제약입니다. 팔을 빠르게 흔들면 어깨 관절에 부하가 걸려 열이 오르고 전력 소비가 늘어, 그 상태로는 400m를 완주하지 못합니다. 손을 얼굴 근처에 두면 다리 출력을 유지하면서 팔 부하를 낮출 수 있습니다. 사람 눈에 이상한 자세가 로봇에게는 완주의 해답이었던 셈입니다.\n\n같은 날 대그룹 400m 결승에서는 Tien Kung Ultra가 38.15초로 우승했습니다. 남자 400m 세계기록인 43.03초보다 약 5초 빠른 숫자이지만, 로봇 경기의 출발 방식과 트랙 규정, 체급 구분은 인간 육상과 다릅니다. 기록 경신이 아니라 이동 제어의 진척을 보여주는 지표로 읽는 편이 정확합니다.",
    videoUrl: "https://www.youtube.com/embed/zYhyHqLlktg",
    videoCaption: "CGTN · Tien Kung Omni의 400m 경기 영상",
    thumbnail: {
      src: "/og-cache/tiangong-omni-400m-cgtn.jpg",
      alt: "World Humanoid Robot Games 400m 트랙을 달리는 Tien Kung Omni",
    },
    editorial: "기록 숫자보다 '왜 저 자세인가'에 답이 있는 카드입니다. 발열과 전력이 로봇 달리기의 진짜 제약입니다.",
    tags: ["Physical AI", "Tien Kung Omni", "X-Humanoid", "강화학습"],
    tier: "feature",
  },
];

const editorsPicks: ABEditorPick[] = [
  {
    title: "fluent-korean — Claude Code의 한국어 문장 품질을 다듬는 output style",
    slug: "fluent-korean",
    deck: "조사·어미 생략과 기계적인 명사 나열을 줄이는 한국어 출력 규칙입니다.",
    category: "한국어 AI 글쓰기",
    sourceUrl: "https://github.com/snflkd/fluent-korean",
    sourceLabel: "GitHub에서 보기 →",
    summary: "Claude Code가 조사와 어미를 생략하거나 명사구를 나열하는 문제를 줄이도록 설계된 한국어 output-style 플러그인입니다. MIT 라이선스이며 8월 21일 v1.0.2가 공개됐습니다.",
    body: "Claude Code의 코딩 지침을 유지하는 버전과 글쓰기 규칙만 제공하는 버전을 함께 제공합니다. `/plugin install fluent-korean@fluent-korean`으로 설치할 수 있고, 규칙 본문을 다른 AI 환경의 글쓰기 지침으로 활용할 수도 있습니다.\n\n실측(2026-08-26): ★905 · MIT · v1.0.2. 별 수는 시점에 따라 변합니다.",
    editorial: "한국어 사용자에게 직접 유용하고 설치가 간단합니다. 문장 품질을 개선하는 규칙이지 사실 정확도나 내용 검증을 대신하는 도구는 아닙니다.",
    tags: ["Claude Code", "한국어", "output style", "MIT"],
    tier: "feature",
    thumbnail: {
      src: "/og-cache/fluent-korean-claude-code의-한국어-문장-품질을-다듬-a514f629.png",
      alt: "fluent-korean — Claude Code의 한국어 문장 품질을 다듬는 output style",
    },
  },
  {
    title: "lexicon-harness — 모호한 요청을 검증 가능한 실행 프롬프트로",
    slug: "voidlight-lexicon-harness",
    deck: "정확한 용어를 구속하고 EN–KO 지시문과 fail-closed 게이트로 실행까지 잇습니다.",
    category: "프롬프트 하네스",
    sourceUrl: "https://github.com/VoidLight00/lexicon-harness",
    thumbnail: {
      src: "/og-cache/lexicon-harness-github-og.png",
      alt: "lexicon-harness GitHub 저장소 카드",
    },
    sourceLabel: "GitHub에서 보기 →",
    guideUrl: "https://voidlight00.github.io/lexicon-harness",
    guideLabel: "12분 학습 가이드 →",
    summary: "사용자님께서 만든 하네스로, 해상도가 낮은 요청에서 정확한 도메인 용어를 선정하고 영어 실행 지시문과 한국어 해석을 작성한 뒤 HARD 게이트를 통과시켜 실제 작업까지 이어갑니다.",
    body: "결정론 엔진은 후보 용어를 순위화하고 브리프 스캐폴드를 만들며, `/lexicon` 스킬은 3~8개의 구속 용어를 채택해 EN–KO 실행 프롬프트를 작성합니다. `verify_lexicon.sh`가 브리프·엔진·비밀정보 검사를 fail-closed로 판정하고 exit 0일 때만 실행 경로가 열립니다.\n\n설치: `git clone https://github.com/VoidLight00/lexicon-harness.git ~/.claude/lexicon` 후 skill 파일을 `~/.claude/skills/lexicon/`에 복사합니다. Claude Code 없이도 `lex.py` CLI와 게이트를 직접 사용할 수 있습니다.\n\n실측(2026-08-26): Python · MIT · 공개 저장소. 별 수 0은 공개 직후 시점의 값이며 품질 지표로 사용하지 않습니다.",
    editorial: "이번 VoidNews 작업에도 실제로 적용한 사용자님 제작 오픈소스입니다. 프롬프트를 문서로 만드는 데서 끝나지 않고, 검증된 프롬프트로 요청 작업을 완료하는 것까지 계약에 포함합니다.",
    tags: ["VoidLight", "Lexicon", "프롬프트 엔지니어링", "fail-closed", "MIT"],
    tier: "feature",
  },
];

export const edition2026_08b: ABEdition = {
  slug: "2026-08b",
  volume: 11,
  title: "GLM-5.3-Flash·Ox Alpha 공개부터 에이전트 보안과 로컬 AI까지",
  theme: "운영 · 보안 · 오픈 모델 · 생성형 미디어 · 피지컬 AI · 로컬 AI",
  period: "2026-08-17 ~ 2026-08-26",
  coveredWeeks: [{ slug: "2026-w34", period: "8/17 ~ 8/23" }, { slug: "2026-w35", period: "8/24 ~ 8/30" }],
  announceDate: "2026-08-27",
  nextEditionDate: "2026-09-10",
  sourceCounts: { youtube: 96, x: 0, web: 54, "community-hn": 129, "community-reddit": 0 },
  intro: "8월 하반기에는 에이전트의 기능보다 운영 경계가 더 선명해졌습니다. 세션과 MR 상태를 이어 보고, AI가 공동 작성한 CI를 다시 검증해야 합니다. 편집 마감 뒤에는 OpenRouter 익명 모델 Ox Alpha의 정체가 GLM-5.3-Flash로 확인됐습니다. 생성형 미디어는 음향 제작으로 넓어졌고, 로컬 AI 하드웨어는 512GB 통합 메모리까지 올라갔습니다.",
  closing: "도입 전에 세 가지를 확인하십시오. 공식 날짜와 사건 정체성, 에이전트 권한과 사람 검토 경계, 그리고 벤더 자체 수치와 독립 검증의 차이입니다.",
  coreFlow: ["에이전트 운영", "CI 보안", "프런티어 오픈 모델", "생성형 미디어", "피지컬 AI", "로컬 AI 하드웨어"],
  highlights: [
    { rank: 1, tier: "hero", post: vip1, sourceWeek: "2026-w34", sourceCompany: "Anthropic", editorial: "사용자님께서 직접 선택한 최종 VIP 카드입니다." },
    { rank: 2, tier: "feature", post: vip2, sourceWeek: "2026-w34", sourceCompany: "Wiz", editorial: "사용자님께서 직접 선택한 최종 VIP 카드입니다." },
    { rank: 3, tier: "feature", post: vip3, sourceWeek: "2026-w35", sourceCompany: "Z.ai / OpenRouter", editorial: "OpenRouter 공식 FAQ가 Ox Alpha의 정체라고 확인하며, 성능 비교는 Z.ai 자체 평가로 구분합니다." },
    { rank: 4, tier: "feature", post: vip4, sourceWeek: "2026-w34", sourceCompany: "Pika", editorial: "생성형 미디어의 오디오 제작 확장을 대표하는 최종 VIP 카드입니다." },
    { rank: 5, tier: "feature", post: vip5, sourceWeek: "2026-w35", sourceCompany: "Physical AI", editorial: "인간 기록과의 비교보다 작년 21.50초에서 올해 9.39초로 줄어든 폭이 이 카드의 요점입니다." },
    { rank: 6, tier: "feature", post: vip6, sourceWeek: "2026-w35", sourceCompany: "Apple", editorial: "로컬 AI 하드웨어와 통합 메모리 상한을 다루는 최종 VIP 카드입니다." }
  ],
  modelWatch: lateNewsWatch,
  editorsPicks,
};
