import type { ABEdition } from "../data";

// 2026-05b — 격주 AB 발표 (2026-05-15 ~ 2026-05-25)
// highlights: Tier S+A 20개 후보 풀 (사용자가 top10 직접 선정 후 13개 제거 예정)
// editorsPicks: 오픈소스 공유 후보 11개 (Mole, hallmark 포함)
// demoCards: 실전 팁 후보 5개

export const edition2026_05b: ABEdition = {
  slug: "2026-05b",
  volume: 4,
  title: "Codex 모바일·Gemini agentic·Vera CPU·Glasswing — AI가 운영체제로 굳는 한 주",
  theme: "2026-05-15 ~ 2026-05-25 — Codex가 모바일/AWS/Dell로 확장되고, Google I/O 2026이 Gemini를 agentic platform으로 재정의했으며, NVIDIA Vera CPU가 첫 출하되고, Anthropic Project Glasswing이 1만+ 취약점을 발견한 구간",
  period: "2026-05-15 ~ 2026-05-25",
  coveredWeeks: ["2026-w21", "2026-w22"],
  announceDate: "2026-05-25",
  intro: `이번 11일은 한 회사의 단일 발표가 아니라, 네 가지 흐름이 동시에 굳어진 구간이었습니다.\n\n첫째, OpenAI는 Codex를 ChatGPT 모바일·Skills·Automations·AWS Bedrock·Dell 하이브리드까지 일주일 안에 풀며 "Codex가 어디서나 돈다"는 그림을 완성했습니다. 둘째, Google I/O 2026은 Gemini 3.5/Spark/Omni와 Managed Agents, Antigravity 2.0, AI Studio로 Gemini를 단순 챗봇이 아니라 agentic platform으로 다시 정의했습니다. 셋째, NVIDIA는 Vera CPU 첫 출하 + Q1 FY27 Data Center 752억$로 "에이전트를 굴리는 인프라"가 산업 코어임을 수치로 증명했습니다. 넷째, Anthropic은 Stainless 인수, KPMG 27.6만명 도입, Project Glasswing 1만+ 취약점 발견, Claude Code Agent View로 모델·플랫폼·기업 운영체제 세 축을 동시에 밀었습니다.\n\n이 풀은 4라운드 교차 검증(공식 출처 91 + 오픈소스 공유 후보 11 + 실전 팁 5)에서 추려진 Tier S+A 20개 후보입니다. 발표 진행자가 top10을 직접 선정한 뒤 본문·이미지를 보강하는 단계에 있습니다.`,
  closing: `한 줄로 묶으면, AI는 이번 11일 사이에 "어디서나 돌고, 인프라를 정당화하며, 기업 운영체제로 들어가는" 단계로 굳었습니다.\n\n오픈소스 섹션에서는 tw93/Mole(macOS deep clean + AI CLI 잔재 정리), Nutlope/hallmark(anti-AI-slop design skill), manaflow-ai/cmux(Codex CLI 분할 워크플로)처럼 본인 작업 환경과 직접 맞물리는 도구를 골라뒀습니다. 실전 팁 섹션은 Claude Code /compact vs /clear, cmux + Codex CLI split 같이 발표 후 바로 따라할 수 있는 워크플로 중심입니다.\n\n— VoidLight`,
  highlights: [
    {
      rank: 1,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Gemini Omni — 텍스트·이미지·오디오·영상을 입력으로 받는 영상 생성·편집 통합 모델",
        summary: "Google이 I/O 2026에서 Gemini Omni를 공개했다. 영상을 단순 생성하는 모델이 아니라 \"추론하는 영상 모델\"로, 시네마틱 줌·배경 교체·등장인물 일관성 유지를 대화형으로 처리한다. 첫 모델 Gemini Omni Flash는 5/19부터 전 세계 Google AI Plus·Pro·Ultra 구독자, Google Flow, YouTube Shorts(무료)에서 즉시 사용 가능.",
        content: "**이게 뭐예요?**\n\nGemini Omni는 Google이 2026년 5월 19일 I/O 2026에서 공개한 새 영상 모델 패밀리입니다. DeepMind CEO Demis Hassabis는 이걸 \"어떤 입력에서든 무엇이든 만들 수 있는 새 모델\"이라고 소개했고, Google은 기존 Veo 라인을 핵심 Gemini 시스템 안으로 통합했다고 설명했습니다. 첫 모델은 **Gemini Omni Flash**입니다.\n\n**무엇이 달라졌나?**\n\n- 입력: 텍스트 + 이미지 + 오디오 + 영상 (멀티모달 입력)\n- 출력: 약 10초짜리 짧은 영상 클립 + 동기화된 오디오\n- \"영상을 만드는 모델\"이 아니라 \"영상을 만드는 추론 모델\" — 맥락·물리·의도를 이해해서 다중 턴 편집을 처음부터 다시 생성하지 않고 유지\n- 등장 인물·배경·움직임을 편집 후에도 일관되게 유지 (기존 AI 영상 모델의 약점)\n- 아키텍처: Gemini의 추론 엔진 + Veo의 렌더링 + DeepMind의 Genie 월드 시뮬레이션 + Nano Banana 이미지 편집 레이어 결합\n\n**왜 중요한가요?**\n\nOmni는 별도 제품이 아니라 Gemini 앱·Google Flow·YouTube Shorts·검색에 바로 들어가는 것이 핵심입니다. ByteDance Seedance 2.0이 공개 벤치마크 1위이고 Kling 3.0이 중국 시장을 잡고 있는데, Google의 차별점은 모델 단독 품질이 아니라 \"이미 사용 중인 제품에 통합되어 있다\"는 배포 우위입니다. 또 \"대화형 영상 편집\"이 새 패러다임을 만듭니다 — 시네마틱 줌, 배경 교체를 프롬프트 한 줄로 처리.\n\n**가격·접근**\n\n- YouTube Shorts / YouTube Create: 무료\n- Google AI Plus: 월 $7.99\n- AI Pro: 월 $19.99\n- AI Ultra: 월 $99.99 / $199.99\n- 개발자·기업 API는 \"수주 안에 공개 예정\"\n\n**읽을 때 볼 점**\n\n- Flash 클립 10초 제한은 모델 한계가 아니라 컴퓨트 수요 분산을 위한 배포 결정 (Google DeepMind 제품 책임자 Nicole Brichtova)\n- 모든 영상에 SynthID 비가시 워터마크 + C2PA Content Credentials 강제 — API 플래그로 제거 불가\n- 음성·대사 \"교체\" 편집은 의도적으로 막아둠. Google이 \"가장 위험한 기능\"으로 정의\n- 발표 동시기에 Gemini 3.5 Flash, Gemini Spark agent도 같이 공개됨 (agentic Gemini 흐름의 일부)",
        officialUrl: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
        source: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
        backupUrls: [
          { label: "Google I/O 2026 — agentic Gemini era keynote", url: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/" },
          { label: "Google AI Studio — Gemini Omni 사용", url: "https://aistudio.google.com" },
          { label: "Decrypt — 'Simulate the World' 분석", url: "https://decrypt.co/368393/google-unveils-gemini-omni-next-gen-ai-video-builder-simulate-world" },
          { label: "TechTimes — 가장 위험한 기능을 막아둔 이유", url: "https://www.techtimes.com/articles/316859/20260519/google-launches-gemini-omni-video-model-holds-back-its-riskiest-feature.htm" },
          { label: "큐레이터 스레드 (@choi.openai)", url: "https://www.threads.com/@choi.openai/post/DYuVvqtj8Av" },
        ],
        tags: ["Google DeepMind", "Gemini Omni", "video generation", "multimodal", "공식", "hero"],
        featured: true,
        slug: "gemini-omni-google-io-2026-video-model",
        readMinutes: 5,
        thumbnail: {
          src: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Geminiapp_Bento_hero.width-1600.format-webp.webp",
          alt: "Gemini Omni 공식 hero",
        },
        videoUrl: "https://www.youtube.com/embed/GfTDA_TbVQI",
        threadsEmbedUrl: "https://www.threads.com/embed/@choi.openai/post/DYuVvqtj8Av/",
        galleryImages: [
          { src: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/IOCollection_social.width-2000.format-webp.webp", alt: "Google I/O 2026 컬렉션", caption: "Google I/O 2026 — Gemini Omni가 공개된 키노트 컬렉션" },
          { src: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Gemini_Spark_Partners.width-2000.format-webp.webp", alt: "Gemini Spark 파트너", caption: "함께 발표된 Gemini Spark 에이전트 파트너" },
        ],
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      keyQuote: "어떤 입력에서든 무엇이든 만들 수 있는 새 모델 — Demis Hassabis (DeepMind CEO)",
      editorial: "메인 hero — 사용자 결정. Gemini Omni가 Google I/O 2026의 가장 큰 발표이자 본 회차의 첫 카드.",
    },
    {
      rank: 2,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Work with Codex from anywhere — Codex in ChatGPT mobile",
        summary: "Codex / ChatGPT mobile",
        officialUrl: "https://openai.com/index/work-with-codex-from-anywhere/",
        source: "https://openai.com/index/work-with-codex-from-anywhere/",
        tags: ["Codex", "ChatGPT mobile", "공식", "hero후보"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
      editorial: "Tier HERO 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 2,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Introducing the Codex app, Skills, and Automations",
        summary: "Codex app / Skills / Automations",
        officialUrl: "https://openai.com/index/introducing-the-codex-app/",
        source: "https://openai.com/index/introducing-the-codex-app/",
        tags: ["Codex app", "Skills", "Automations", "공식", "hero후보"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
      editorial: "Tier HERO 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 3,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "I/O 2026: Welcome to the agentic Gemini era",
        summary: "Google summarized I/O 2026 AI announcements including Gemini 3.5 Flash, Spark, agentic Search, TPU 8, Gemini Omni, and SynthID expansion.",
        officialUrl: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        source: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
        tags: ["Gemini", "Search", "Workspace", "Cloud", "Android", "TPU", "공식", "hero후보"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      editorial: "Tier HERO 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 4,
      tier: "hero",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Introducing Managed Agents in the Gemini API",
        summary: "Google introduced Gemini API Managed Agents running Antigravity-based agents inside secure cloud Linux sandboxes.",
        officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
        source: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
        tags: ["Gemini API", "Managed Agents", "Antigravity", "공식", "hero후보"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      editorial: "Tier HERO 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 5,
      tier: "hero",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "Vera Arrives: NVIDIA's First CPU Built for Agents Lands at Top AI Labs",
        summary: "NVIDIA Vera CPU / Vera Rubin NVL72 / agentic AI infrastructure",
        officialUrl: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
        source: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
        tags: ["NVIDIA Vera CPU", "Vera Rubin NVL72", "agentic AI infrastructure", "공식", "hero후보"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "NVIDIA",
      editorial: "Tier HERO 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 6,
      tier: "hero",
      post: {
        date: "5/20",
        platform: "X+Threads",
        title: "NVIDIA Announces Financial Results for First Quarter Fiscal 2027",
        summary: "NVIDIA Data Center / AI factories / Blackwell",
        officialUrl: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
        source: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
        tags: ["NVIDIA Data Center", "AI factories", "Blackwell", "공식", "hero후보"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "NVIDIA",
      editorial: "Tier HERO 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 7,
      tier: "hero",
      post: {
        date: "5/22",
        platform: "X+Threads",
        title: "Project Glasswing: An initial update",
        summary: "Anthropic reported early Project Glasswing results, including partner discovery of more than 10,000 high/critical vulnerabilities.",
        officialUrl: "https://www.anthropic.com/research/glasswing-initial-update",
        source: "https://www.anthropic.com/research/glasswing-initial-update",
        tags: ["Project Glasswing", "security", "Claude Mythos Preview", "공식", "hero후보"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
      editorial: "Tier HERO 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 8,
      tier: "feature",
      post: {
        date: "5/11",
        platform: "X+Threads",
        title: "Claude Code Agent View (Research Preview)",
        summary: "Anthropic이 Claude Code 2.1.139부터 모든 병렬 세션을 한 화면에서 관리하는 Agent View를 Research Preview로 공개했다. 이후 `claude agents --cwd <path>`와 pinned background sessions 같은 후속 업데이트가 같은 주에 추가되며 5월 15일 이후에도 영향이 이어졌다.",
        officialUrl: "https://www.anthropic.com/news",
        source: "https://www.anthropic.com/news",
        tags: ["Claude Code", "Agent View", "multi-agent CLI", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 9,
      tier: "feature",
      post: {
        date: "5/23",
        platform: "X+Threads",
        title: "OpenAI Codex Goal mode generally available",
        summary: "Codex / Goal mode",
        officialUrl: "https://help.openai.com/en/articles/6825453-chatgpts-release-notes",
        source: "https://help.openai.com/en/articles/6825453-chatgpts-release-notes",
        tags: ["Codex", "Goal mode", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 10,
      tier: "feature",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "Anthropic acquires Stainless",
        summary: "Anthropic acquired Stainless to strengthen Claude developer experience, SDK generation, CLI and MCP-connected tooling.",
        officialUrl: "https://www.anthropic.com/news/anthropic-acquires-stainless",
        source: "https://www.anthropic.com/news/anthropic-acquires-stainless",
        tags: ["Claude Platform", "Stainless", "SDK", "MCP", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 11,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "KPMG integrates Claude across its core business and workforce of more than 276,000 in strategic alliance",
        summary: "KPMG announced Claude integration across core business workflows and a 276,000+ workforce through a strategic alliance with Anthropic.",
        officialUrl: "https://www.anthropic.com/news/anthropic-kpmg",
        source: "https://www.anthropic.com/news/anthropic-kpmg",
        tags: ["Claude", "Enterprise AI", "Managed Agents", "Claude Code", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Anthropic",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 12,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Grok Build — xAI의 터미널 기반 parallel coding agent (early beta)",
        summary: "xAI가 5/14 공개한 Grok Build CLI/TUI는 풀스크린 터미널 UI, 최대 8개 parallel sub-agent, Plan Mode, 131K~2M 컨텍스트를 지원한다. SuperGrok Heavy 구독자(월 $300, 프로모션 $99) 전용 early beta.",
        content: "**이게 뭐예요?**\n\nGrok Build는 xAI가 2026년 5월 14일 early beta로 공개한 터미널 기반 AI 코딩 에이전트입니다. CLI와 TUI 양쪽으로 동작하며, 자연어 명령으로 계획→검색→코드 작성/편집→실행→테스트까지 자동화합니다. 설치는 한 줄: `curl -fsSL https://x.ai/cli/install.sh | bash`\n\n**주요 기능 (공식 검증)**\n\n- TUI: 풀스크린, 마우스 지원, Vim-like 단축키, 실시간 diff, 멀티 창\n- Plan Mode: 작업 계획을 먼저 제시, 개발자가 수정·승인 후 실행\n- Parallel Sub-agent: 최대 8개 에이전트 동시 독립 작업\n- 컨텍스트: 131K~2M 토큰 범위 (자료별 편차)\n- Git 통합 / 멀티 파일 편집 / Shell 실행 / X 실시간 검색\n\n**접근성·가격**\n\nSuperGrok Heavy 구독자 전용 early beta. 월 $300, 6개월 프로모션 시 $99.\n\n**Claude Code · Codex CLI와의 비교 (해외 리뷰 기준)**\n\n| 항목 | Grok Build | Claude Code | Codex CLI |\n|---|---|---|---|\n| 인터페이스 | Terminal-first TUI (최고 평가) | Terminal + IDE | Terminal shell |\n| 병렬 에이전트 | 최대 8개 (강점) | 1~2개 | 제한적 |\n| Plan Mode | 그래프 + 직접 편집 | 선형 텍스트 | 기본 |\n| 실행 속도 | 가장 빠름 | 계획에서 상대적 느림 | 중간 |\n| Reasoning | 빠른 실행 중심 | 가장 우수 (deep reasoning) | 중간~좋음 |\n| 대형 코드베이스 | 모듈러 강함 | monorepo / legacy 최고 | 중간 |\n| SWE-Bench | ~51% | ~57% | ~54% |\n| Best For | 빠른 prototyping, 대형 리팩토링 | 복잡한 refactoring, 코드 품질 | OpenAI 생태계, 가성비 |\n\n**현재 평가 · 한계**\n\n긍정: \"지금까지 본 AI CLI 중 최고의 TUI\", \"parallel agent로 대형 작업 속도가 압도적\". 한계: early beta 단계 + 접근성 제한 + 일부 reasoning depth에서 Claude Code에 뒤처진다는 의견 다수.\n\n**한 줄 요약**\n\n터미널 중심 parallel agentic 코딩 도구로 TUI·속도가 차별점이지만, early beta이며 복잡한 reasoning은 Claude Code가 앞선다는 평가가 지배적.",
        officialUrl: "https://x.ai/news/grok-build-cli",
        source: "https://docs.x.ai/developers/release-notes",
        backupUrls: [
          { label: "xAI 공식 — Grok Build CLI 발표", url: "https://x.ai/news/grok-build-cli" },
          { label: "xAI 공식 — x.ai/cli", url: "https://x.ai/cli" },
          { label: "xAI Release Notes", url: "https://docs.x.ai/developers/release-notes" },
          { label: "Grok Build 0.1 model docs", url: "https://docs.x.ai/developers/models/grok-build-0.1" },
          { label: "eigent.ai — 비교 리뷰", url: "https://eigent.ai/blog/grok-build-cli" },
          { label: "rejoicehub — 비교 리뷰", url: "https://rejoicehub.com/blogs/grok-build-vs-claude-code-vs-codex-cli" },
          { label: "Vercel AI Gateway 추가", url: "https://vercel.com/changelog/grok-build-0-1-now-available-on-vercel-ai-gateway" },
        ],
        tags: ["xAI", "Grok Build", "CLI", "TUI", "parallel agent", "공식", "hero후보"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "xAI",
      editorial: "Grok Build 발표용 정리 — 공식 + 해외 비교 리뷰 통합, 발표 슬라이드 그대로 사용 가능.",
    },
    {
      rank: 13,
      tier: "feature",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "Krea 2 is live for everyone",
        summary: "Krea 2 전체 사용자 공개. 한 주 동안 모든 가입자에게 무제한 Krea 2 생성을 제공.",
        officialUrl: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
        source: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
        tags: ["Krea 2", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Krea",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 14,
      tier: "feature",
      post: {
        date: "5/21",
        platform: "X+Threads",
        title: "Krea 2 LoRA training is here",
        summary: "소수 이미지에서 스타일/캐릭터/오브젝트를 학습하는 LoRA를 Krea 2에 직접 학습·강도 조절·다중 LoRA 스택까지 지원.",
        officialUrl: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
        source: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
        tags: ["Krea 2", "LoRA training", "multi-LoRA stacking", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Krea",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 15,
      tier: "feature",
      post: {
        date: "5/25",
        platform: "X+Threads",
        title: "Thinking Machines Interaction Models — official demo + blog",
        summary: "Thinking Machines / interaction models",
        officialUrl: "https://thinkingmachines.ai/blog/interaction-models/",
        source: "https://thinkingmachines.ai/blog/interaction-models/",
        tags: ["Thinking Machines", "interaction models", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 16,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "The Gemini app becomes more agentic, delivering proactive, 24/7 help",
        summary: "Google announced more proactive Gemini app experiences, Daily Brief, Omni video generation, Spark agent functions, and macOS improvements.",
        officialUrl: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
        source: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
        tags: ["Gemini app", "Gemini 3.5 Flash", "Omni", "Daily Brief", "Spark", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 17,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Bring any idea to life: Google AI Studio at I/O 2026",
        summary: "Google announced AI Studio updates for Workspace integration, Android app building, mobile pre-registration, Antigravity export, and no-cost deployment.",
        officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026/",
        source: "https://blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026/",
        tags: ["Google AI Studio", "Android", "Workspace", "Antigravity", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 18,
      tier: "feature",
      post: {
        date: "5/19",
        platform: "X+Threads",
        title: "Building the agentic future: Developer highlights from I/O 2026",
        summary: "Google summarized I/O 2026 developer announcements around Antigravity 2.0, Gemini API Managed Agents, AI Studio integrations, and Build with Gemini XPRIZE Hackathon.",
        officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
        source: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
        tags: ["Antigravity 2.0", "Gemini API", "Managed Agents", "Google AI Studio", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "Google",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 19,
      tier: "feature",
      post: {
        date: "5/23",
        platform: "X+Threads",
        title: "OpenAI models, Codex, and Managed Agents on Amazon Bedrock",
        summary: "OpenAI / AWS Bedrock / Managed Agents",
        officialUrl: "https://openai.com/index/openai-on-aws/",
        source: "https://openai.com/index/openai-on-aws/",
        tags: ["OpenAI", "AWS Bedrock", "Managed Agents", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "AI Industry",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
    {
      rank: 20,
      tier: "feature",
      post: {
        date: "5/18",
        platform: "X+Threads",
        title: "One-click fixes for failing Actions with Copilot cloud agent",
        summary: "GitHub added one-click Copilot cloud agent fixes for failing GitHub Actions workflows.",
        officialUrl: "https://github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
        source: "https://github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
        tags: ["GitHub Actions", "Copilot cloud agent", "공식"],
        featured: true,
      },
      sourceWeek: "2026-w21",
      sourceCompany: "GitHub",
      editorial: "Tier FEATURE 후보 풀 — 사용자가 top10 선정 후 본문/이미지 보강 예정.",
    },
  ],
  editorsPicks: [
    {
      title: "tw93/Mole",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/tw93/Mole",
      sourceLabel: "GitHub →",
      summary: "macOS deep clean & optimize CLI. 2026-05 업데이트로 Claude Code, Cursor Agent, GitHub Copilot CLI, Codex CLI 등 AI agent CLI 런",
      body: "macOS deep clean & optimize CLI. 2026-05 업데이트로 Claude Code, Cursor Agent, GitHub Copilot CLI, Codex CLI 등 AI agent CLI 런타임/세션 로그 정리 커버리지 추가. tw93 작가의 다른 작품(이미 사용 중인 tw93/kami)과 같은 라인. AI 개발자에게 실용적인 cleanup 도구.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "Nutlope/hallmark",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/Nutlope/hallmark",
      sourceLabel: "GitHub →",
      summary: "anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
      body: "anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "jamiepine/voicebox",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/jamiepine/voicebox",
      sourceLabel: "GitHub →",
      summary: "오픈소스 음성 도구.",
      body: "오픈소스 음성 도구.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "manaflow-ai/cmux",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/manaflow-ai/cmux",
      sourceLabel: "GitHub →",
      summary: "Peter Steinberger가 소개한 Codex CLI 워크플로우 분할용 tmux 보조 도구. 본인이 cmux/cmuxr 하네스 사용자라 직접 와닿는 후보.",
      body: "Peter Steinberger가 소개한 Codex CLI 워크플로우 분할용 tmux 보조 도구. 본인이 cmux/cmuxr 하네스 사용자라 직접 와닿는 후보.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "builderpepc/agent-migrator",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://github.com/builderpepc/agent-migrator",
      sourceLabel: "GitHub →",
      summary: "AI 코딩 세션을 도구 간 마이그레이션하는 오픈소스. Claude Code/Codex/Cursor 사이 컨텍스트 이전 시나리오.",
      body: "AI 코딩 세션을 도구 간 마이그레이션하는 오픈소스. Claude Code/Codex/Cursor 사이 컨텍스트 이전 시나리오.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "allenai/OlmoEarth v1.1",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/allenai/olmoearth-v1-1",
      sourceLabel: "GitHub →",
      summary: "Earth observation을 위한 경량 오픈 모델.",
      body: "Earth observation을 위한 경량 오픈 모델.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "IBM Granite 4.1",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/ibm-granite/granite-4-1",
      sourceLabel: "GitHub →",
      summary: "IBM의 오픈 LLM 라인업 4.1 학습 파이프라인 공개.",
      body: "IBM의 오픈 LLM 라인업 4.1 학습 파이프라인 공개.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "vLLM RL backend correctness (ServiceNow)",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/ServiceNow-AI/correctness-before-corrections",
      sourceLabel: "GitHub →",
      summary: "vLLM RL 학습 backend의 V0→V1 정합성 정리.",
      body: "vLLM RL 학습 backend의 V0→V1 정합성 정리.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "HF continuous async batching",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/continuous_async",
      sourceLabel: "GitHub →",
      summary: "HF inference 비동기 연속 배치 처리 가이드.",
      body: "HF inference 비동기 연속 배치 처리 가이드.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "IBM Granite Embedding Multilingual R2",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/ibm-granite/granite-embedding-multilingual-r2",
      sourceLabel: "GitHub →",
      summary: "오픈 다국어 임베딩 모델 R2.",
      body: "오픈 다국어 임베딩 모델 R2.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
    {
      title: "PaddleOCR 3.5 Transformers",
      category: "AI 개발 도구 / 오픈소스",
      sourceUrl: "https://huggingface.co/blog/PaddlePaddle/paddleocr-transformers",
      sourceLabel: "GitHub →",
      summary: "PaddleOCR을 Transformers 백엔드로 실행하는 가이드.",
      body: "PaddleOCR을 Transformers 백엔드로 실행하는 가이드.",
      editorial: "오픈소스 공유 후보 — cokacdir 봇 publish_log + YouTube AI뉴스 교차 검증으로 추출.",
      tags: ["오픈소스", "공유후보"],
      tier: "feature",
    },
  ],
  demoCards: [
    {
      title: "Claude Code context management — /compact vs /clear",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=eW3oTyfeWZ0",
      label: "원문 →",
      summary: "세션 컨텍스트 관리 실전 팁.",
      body: "세션 컨텍스트 관리 실전 팁.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "Peter Steinberger cmux + Codex CLI workflow split",
      category: "실전 팁",
      url: "https://github.com/manaflow-ai/cmux",
      label: "원문 →",
      summary: "cmux 다중 pane + Codex CLI 작업 분할 패턴.",
      body: "cmux 다중 pane + Codex CLI 작업 분할 패턴.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "AI prompt usage: method-first prompting",
      category: "실전 팁",
      url: "https://www.instagram.com/p/DYCDIvelD5p/",
      label: "원문 →",
      summary: "방법론을 먼저 제시하는 프롬프트 스타일.",
      body: "방법론을 먼저 제시하는 프롬프트 스타일.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "YC Diana Hu — AI-native company 구성 방식",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=EN7frwQIbKc",
      label: "원문 →",
      summary: "YC 파트너 관점에서 AI-native 회사가 갖춰야 할 구조.",
      body: "YC 파트너 관점에서 AI-native 회사가 갖춰야 할 구조.",
      tags: ["실전팁", "워크플로"],
    },
    {
      title: "Jensen Huang CMU commencement — AI jobs message",
      category: "실전 팁",
      url: "https://www.youtube.com/watch?v=uSs7PPAJR20",
      label: "원문 →",
      summary: "AI 시대 일자리에 대한 NVIDIA CEO 졸업 연설.",
      body: "AI 시대 일자리에 대한 NVIDIA CEO 졸업 연설.",
      tags: ["실전팁", "워크플로"],
    },
  ],
};
