import type { WeeklyData } from "../data";

// 2026-w33 (8/10 ~ 8/16)
// AB run 20260812-075051-ab-20260731-20260812 (edition 2026-08a) 의 검증·정규화 산출물.
// 모든 카드의 officialUrl 은 수집 단계에서 직접 fetch 해 본문·발행일을 확인했다.
// 근거: _workspace/ab/20260812-075051-ab-20260731-20260812/01_collected_sources.json (fetchEvidence 필드)

export const week33: WeeklyData = {
  week: 33,
  year: 2026,
  slug: "2026-w33",
  period: "8/10 ~ 8/16",
  totalPosts: 32,
  companies: [
    {
      name: "Anthropic",
      color: "#E87040",
      posts: [
        {
          date: "8/10",
          platform: "X+Threads",
          title: "클로드가 리만 제타 함수 하한을 41.6%에서 67.2%로 올렸다",
          deck: "Claude Code 두 세션에 출력 토큰 3,100만 개를 썼습니다.",
          summary: "Anthropic이 8월 10일, 미공개 연구용 Claude가 리만 가설을 만족하는 리만 제타 함수 영점의 하한을 41.6%에서 67.2%로 올렸다고 밝혔어요. Claude Code로 두 세션에 걸쳐 출력 토큰 3,100만 개를 썼고, Anthropic 소속 수학자 2명이 논문을 검토했으며 Lean으로 형식 검증 가능한 증명도 만들었어요. 외부 전문가 Brian Conrey와 Dan Goldston이 검토했어요. 다만 Anthropic은 \"Claude가 쓴 기법이 리만 가설 증명으로 이어지리라 기대하지 않는다\"고 명시했어요.",
          source: "https://www.anthropic.com/research/riemann-zeta",
          officialUrl: "https://www.anthropic.com/research/riemann-zeta",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "OpenAI — 같은 창의 수학 10개 진전 발표 (비교용)", url: "https://openai.com/index/ten-advances-in-mathematics" },
          ],
          tags: ["Anthropic", "Claude", "수학", "형식검증", "연구"],
          slug: "anthropic-20260810-claude-improved-a-longstanding-lower-bound-o",
          en: {
            title: "Claude improved a longstanding lower bound on the Riemann zeta function",
            deck: "Two Claude Code sessions and 31 million output tokens.",
            summary: "On August 10 Anthropic reported that an unreleased research version of Claude raised the longstanding lower bound for zeros of the Riemann zeta function satisfying the Riemann hypothesis from 41.6% to 67.2%, working through Claude Code across two sessions using 31 million output tokens. Two Anthropic mathematicians validated the paper, Claude also produced a Lean-verifiable proof, and Brian Conrey and Dan Goldston reviewed the work. Anthropic states it does not expect these techniques to lead to proving the Riemann hypothesis.",
          },
          thumbnail: {
            src: "/og-cache/클로드가-리만-제타-함수-하한을-41-6-에서-67-2-로-올렸다-e38c742d.jpg",
            alt: "클로드가 리만 제타 함수 하한을 41.6%에서 67.2%로 올렸다",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "클로드 출력물에 워터마크와 C2PA 표식이 붙는다",
          featured: true,
          deck: "8월 2일 이후 출시 모델은 처음부터 표식을 답니다.",
          summary: "Anthropic이 Claude 출력물에 기계 판독 가능한 표식을 넣는 방식을 공개했어요. 텍스트에는 읽기에 영향을 주지 않고 복사·붙여넣기에도 남는 비가시 워터마크를 심고, 파일에는 C2PA 개방 표준을 따르는 서명된 출처 메타데이터를 붙여요. 적용 범위는 Claude Platform(API), Claude, Claude Code, Claude Cowork, Claude Tag이고 AWS·Google Cloud·Microsoft Foundry를 포함해 전 세계에 적용돼요. 2026년 8월 2일 이후 출시되는 모델은 출시 시점부터 지원하고, 그 이전 모델은 전환 기간에 순차 적용해요. 다만 Anthropic은 탐지 결과가 \"완전히 결정적이지는 않다\"고 명시했어요.",
          source: "https://support.claude.com/en/articles/16266773-how-claude-marks-ai-generated-content",
          officialUrl: "https://support.claude.com/en/articles/16266773-how-claude-marks-ai-generated-content",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "EU AI법 투명성 의무 8월 2일 시행 (같은 날짜 기준)", url: "https://digital-strategy.ec.europa.eu/en/news/commission-starts-enforcing-ai-act-rules-and-new-transparency-requirements-2-august" },
            { label: "C2PA 개방 표준", url: "https://c2pa.org/" },
          ],
          tags: ["Anthropic", "워터마크", "C2PA", "규제", "투명성"],
          slug: "anthropic-20260811-how-claude-marks-ai-generated-content",
          en: {
            title: "How Claude marks AI-generated content",
            deck: "Models launched on or after August 2 carry the marking from day one.",
            summary: "Anthropic documented how Claude marks its output: an imperceptible watermark embedded directly in text that survives copy-paste, and signed provenance metadata on files following the C2PA open standard. Coverage spans Claude Platform (API), Claude, Claude Code, Claude Cowork and Claude Tag, worldwide including AWS, Google Cloud and Microsoft Foundry. Models launched on or after August 2, 2026 support machine-readable marking at launch, with earlier models added during a transition. Anthropic notes detection is not fully conclusive.",
          },
          thumbnail: {
            src: "/og-cache/클로드-출력물에-워터마크와-c2pa-표식이-붙는다-60f27f51.png",
            alt: "클로드 출력물에 워터마크와 C2PA 표식이 붙는다",
          },
        },
      ],
    },
    {
      name: "OpenAI",
      color: "#10A37F",
      posts: [
        {
          date: "8/10",
          platform: "X+Threads",
          title: "Daybreak 확대와 GPT-5.6-Cyber 공개",
          deck: "신원 확인과 법적 서약을 통과한 곳만 쓸 수 있습니다.",
          summary: "OpenAI가 보안 전용 프로그램 Daybreak를 확대하고 GPT-5.6 Sol 기반의 GPT-5.6-Cyber를 공개했어요. 일반 모델에 접근하는 Daybreak Blue와 사이버 전용 모델에 접근하는 Daybreak Red로 나뉘며, 신원 확인과 법적 서약을 거친 승인된 개인·조직만 쓸 수 있어요. 벤더 자체 수치로 Advanced Cybersecurity Completion Rate에서 GPT-5.6-Cyber는 95.0%, GPT-5.5-Cyber는 57.3%, GPT-5.6 Sol은 1.5%를 기록했다고 밝혔어요.",
          source: "https://openai.com/index/expanding-daybreak-as-the-cyber-defense-window-narrows",
          officialUrl: "https://openai.com/index/expanding-daybreak-as-the-cyber-defense-window-narrows",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "OpenAI — 신뢰할 수 있는 파트너에 프런티어 사이버 모델 제공 (같은 날)", url: "https://openai.com/index/putting-frontier-cyber-models-in-more-trusted-hands" },
          ],
          tags: ["cybersecurity", "daybreak", "gpt-5.6-cyber", "gated-access", "dual-use"],
          slug: "openai-20260810-expanding-daybreak-as-the-cyber-defense-wind",
          en: {
            title: "Expanding Daybreak as the Cyber Defense Window Narrows",
            deck: "Only vetted individuals and organizations get access.",
            summary: "OpenAI expanded its Daybreak program and introduced GPT-5.6-Cyber, built on GPT-5.6 Sol. Daybreak Blue gives access to frontier general-purpose models; Daybreak Red gives access to purpose-trained cybersecurity models, restricted to approved individuals and organizations. Per OpenAI's own numbers, GPT-5.6-Cyber completes 95.0% of Advanced Cybersecurity requests versus 57.3% for GPT-5.5-Cyber and 1.5% for GPT-5.6 Sol.",
          },
          thumbnail: {
            src: "/og-cache/gpt-5-3-codex-is-now-the-base-model-for--d3b67286.webp",
            alt: "Daybreak 확대와 GPT-5.6-Cyber 공개",
          },
        },
        {
          date: "8/10",
          platform: "X+Threads",
          title: "ChatGPT Business에 Premium 시트 도입",
          deck: "팀 안에서 좌석 등급을 나눠 배정할 수 있습니다.",
          summary: "OpenAI가 ChatGPT Business에 Premium 시트를 도입했어요. 가격은 사용자당 월 125달러이고 연간 결제 시 월 100달러이며, 기존 Standard 시트는 사용자당 월 25달러, 연간 결제 시 월 20달러예요. Premium 시트는 Standard 대비 5배 사용량을 제공하고 5시간 사용 제한을 없앤다고 밝혔어요. 한 워크스페이스 안에서 두 시트 유형을 섞어 쓸 수 있어요.",
          source: "https://openai.com/index/premium-seats-chatgpt-business",
          officialUrl: "https://openai.com/index/premium-seats-chatgpt-business",
          verifiedAt: "2026-08-12",
          backupUrls: [],
          tags: ["pricing", "chatgpt-business", "enterprise", "seats"],
          slug: "openai-20260810-premium-seats-are-coming-to-chatgpt-business",
          en: {
            title: "Premium seats are coming to ChatGPT Business",
            deck: "Teams can now assign tiered seats.",
            summary: "OpenAI introduced Premium seats for ChatGPT Business at $125 per user per month, or $100 per user per month billed annually, alongside Standard seats at $25/$20. Premium seats provide 5x more usage than Standard seats and remove the five-hour usage limit. Both seat types can be mixed in one workspace.",
          },
          thumbnail: {
            src: "/og-cache/gpt-5-3-codex-is-now-the-base-model-for--d3b67286.webp",
            alt: "ChatGPT Business에 Premium 시트 도입",
          },
        },
        {
          date: "8/10",
          platform: "X+Threads",
          title: "프런티어 사이버 모델, 보안 파트너사에 개방",
          deck: "방어 쪽 파트너에게만 사이버 전용 모델을 엽니다.",
          summary: "OpenAI가 Daybreak Cyber Partner 프로그램을 확대해 보안 파트너사가 자사 제품에 프런티어 사이버 모델을 통합할 수 있게 했어요. 보안·서비스 파트너로 Accenture, IBM, Capgemini, Cognizant, EY, KPMG, PwC, NCC Group, SpecterOps가, 기술 파트너로 Palo Alto Networks, CrowdStrike, Cisco, Sophos, Akamai, Fortinet, Cloudflare가 명시됐어요. 파트너는 필요에 따라 Daybreak Blue 또는 Daybreak Red를 선택해 접근해요.",
          source: "https://openai.com/index/putting-frontier-cyber-models-in-more-trusted-hands",
          officialUrl: "https://openai.com/index/putting-frontier-cyber-models-in-more-trusted-hands",
          verifiedAt: "2026-08-12",
          backupUrls: [],
          tags: ["cybersecurity", "daybreak", "partners", "enterprise"],
          slug: "openai-20260810-putting-frontier-cyber-models-in-more-truste",
          en: {
            title: "Putting frontier cyber models in more trusted hands",
            deck: "The cyber-specialized models open to defensive partners only.",
            summary: "OpenAI expanded its Daybreak Cyber Partner program so security partners can integrate frontier cyber models into their own products. Named partners include Accenture, IBM, Capgemini, Cognizant, EY, KPMG, PwC, NCC Group, SpecterOps, Palo Alto Networks, CrowdStrike, Cisco, Sophos, Akamai, Fortinet, and Cloudflare.",
          },
          thumbnail: {
            src: "/og-cache/gpt-5-3-codex-is-now-the-base-model-for--d3b67286.webp",
            alt: "프런티어 사이버 모델, 보안 파트너사에 개방",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "ChatGPT 광고, 한국 포함 5개국 출시",
          deck: "무료와 Go 요금제에만 붙고 한국이 1차 5개국에 들었습니다.",
          summary: "OpenAI가 ChatGPT 광고를 영국, 멕시코, 브라질, 일본, 한국에 출시했다고 2026년 8월 11일 업데이트로 밝혔어요. 광고는 로그인한 성인 사용자 중 Free와 Go 요금제에만 노출되고 Pro, Business, Enterprise, Education 요금제에는 표시되지 않아요. OpenAI는 광고가 ChatGPT의 답변에 영향을 주지 않으며 광고주에게는 집계된 성과 정보만 제공된다고 설명했어요. 원 게시물은 2026년 2월 9일자이고 이번 건은 해당 페이지의 업데이트예요.",
          source: "https://openai.com/index/testing-ads-in-chatgpt",
          officialUrl: "https://openai.com/index/testing-ads-in-chatgpt",
          verifiedAt: "2026-08-12",
          backupUrls: [],
          tags: ["ads", "monetization", "korea-launch", "chatgpt", "free-tier"],
          slug: "openai-20260811-testing-ads-in-chatgpt-august-11-2026-update",
          en: {
            title: "Testing ads in ChatGPT (August 11, 2026 update)",
            deck: "Ads land on Free and Go plans only, with Korea in the first five countries.",
            summary: "In an August 11, 2026 update, OpenAI said ChatGPT Ads launched in the United Kingdom, Mexico, Brazil, Japan, and South Korea. Ads appear only for logged-in adult users on the Free and Go tiers; Pro, Business, Enterprise, and Education tiers have no ads. OpenAI states ads do not influence ChatGPT's answers and advertisers receive only aggregate performance data. The base page was originally published February 9, 2026.",
          },
          thumbnail: {
            src: "/og-cache/gpt-5-3-codex-is-now-the-base-model-for--d3b67286.webp",
            alt: "ChatGPT 광고, 한국 포함 5개국 출시",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "Daybreak 모델, AWS Bedrock에서 제공",
          deck: "Bedrock에서도 승인된 조직이 쓸 수 있게 됐습니다.",
          summary: "OpenAI가 Daybreak 모델을 AWS에서 사용할 수 있게 했다고 발표했어요. Amazon Bedrock 콘솔이나 bedrock-mantle 엔드포인트를 쓰는 Responses API로 접근하며, Daybreak Blue와 Daybreak Red 모두 Daybreak Access 프로그램 등록과 승인을 거쳐야 써요. 올해 초 OpenAI 프런티어 모델과 Codex가 AWS에서 정식 제공된 데 이어지는 확장이에요.",
          source: "https://openai.com/index/daybreak-models-are-now-available-on-aws",
          officialUrl: "https://openai.com/index/daybreak-models-are-now-available-on-aws",
          verifiedAt: "2026-08-12",
          backupUrls: [],
          tags: ["cloud", "aws", "bedrock", "daybreak", "distribution"],
          slug: "openai-20260811-daybreak-models-are-now-available-on-aws",
          en: {
            title: "Daybreak models are now available on AWS",
            deck: "Approved organizations can now reach the models through Bedrock.",
            summary: "OpenAI announced Daybreak models are available on AWS via the Amazon Bedrock console or the Responses API using the bedrock-mantle endpoint. Enrollment and approval in the Daybreak Access program is required for both Daybreak Blue and Daybreak Red. This follows OpenAI frontier models and Codex becoming generally available on AWS earlier this year.",
          },
          thumbnail: {
            src: "/og-cache/gpt-5-3-codex-is-now-the-base-model-for--d3b67286.webp",
            alt: "Daybreak 모델, AWS Bedrock에서 제공",
          },
        },
      ],
    },
    {
      name: "Google",
      color: "#4285F4",
      posts: [
        {
          date: "8/11",
          platform: "X+Threads",
          title: "Gemini 앱 월 사용자 10억 명 돌파",
          deck: "구글 역사상 가장 빠르게 자란 제품이라고 밝혔습니다.",
          summary: "구글이 2026년 8월 11일 Gemini 앱 월간 사용자가 10억 명을 넘었고 자사 역사상 가장 빠르게 성장한 제품이라고 밝혔어요. 함께 공개한 수치로는 사용자의 63%가 Gemini에 음성으로 말을 걸고, 하루 1억 5천만 장 이상 이미지를 생성하며, iOS 활성 사용자가 1억 명 이상이에요. 모두 구글이 발표한 벤더 자체 수치이고 독립 측정 기관의 집계가 아니에요.",
          source: "https://blog.google/innovation-and-ai/products/gemini-app/one-billion-monthly-users/",
          officialUrl: "https://blog.google/innovation-and-ai/products/gemini-app/one-billion-monthly-users/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "blog.google 공식 RSS(발행일 근거)", url: "https://blog.google/rss/" },
          ],
          tags: ["Google", "Gemini", "사용자지표", "벤더자체수치"],
          slug: "google-20260811-gemini-app-passes-1-billion-monthly-users",
          en: {
            title: "Gemini app passes 1 billion monthly users",
            deck: "Google calls it the fastest-growing product in its history.",
            summary: "On August 11, 2026 Google said the Gemini app has surpassed 1 billion monthly users, calling it the fastest-growing product in Google's history. Google-reported figures include 63% of users talking directly to Gemini, 150 million+ images generated per day, and 100 million+ active users on iOS. These are vendor-reported numbers, not third-party measurements.",
          },
          thumbnail: {
            src: "/og-cache/gemini-앱-월-사용자-10억-명-돌파-51a979e4.jpg",
            alt: "Gemini 앱 월 사용자 10억 명 돌파",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "AMIE, 실시간 화상 진료 연구 공개",
          deck: "실시간 화상 문진까지 다루는 연구 결과입니다.",
          summary: "구글 리서치가 2026년 8월 11일 의료 AI 시스템 AMIE의 실시간 화상 상담 연구를 공개했어요. 환자 역할 배우와 1차 진료 의사를 무작위 배정해 비교한 연구에서 임상 평가자들은 병력 청취 충실도, 진단 정확도, 처치 적절성, 의사소통 품질 전반을 긍정적으로 평가했고 환자 역할 배우들은 텍스트 채팅보다 화상 방식을 선호했어요. 실제 환자 진료가 아니라 시뮬레이션 기반 연구 단계예요.",
          source: "https://blog.google/innovation-and-ai/models-and-research/google-research/amie-video-consultations/",
          officialUrl: "https://blog.google/innovation-and-ai/models-and-research/google-research/amie-video-consultations/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "blog.google 공식 RSS(발행일 근거)", url: "https://blog.google/rss/" },
          ],
          tags: ["Google", "AMIE", "의료AI", "연구"],
          slug: "google-20260811-amie-demonstrates-real-time-clinical-video-c",
          en: {
            title: "AMIE demonstrates real-time clinical video consultations",
            deck: "Research extending AMIE into live video consultations.",
            summary: "On August 11, 2026 Google Research published a study on AMIE conducting real-time clinical video consultations. In a randomized design with patient actors and primary care physicians, clinical evaluators rated AMIE favorably on history-taking thoroughness, diagnostic accuracy, management appropriateness and communication quality, and patient actors preferred video over text chat. This is a simulated-consultation research study, not a deployed clinical product.",
          },
          thumbnail: {
            src: "/og-cache/amie-실시간-화상-진료-연구-공개-af6b5661.jpg",
            alt: "AMIE, 실시간 화상 진료 연구 공개",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "구글 AI 자격증에 바이브 코딩 과정 추가",
          deck: "자격증 과정에 바이브 코딩 트랙이 붙었습니다.",
          summary: "구글이 2026년 8월 11일 Google AI Professional Certificate에 바이브 코딩 과정을 추가해 Coursera에 열었어요. 코딩 경험 없이 일상 언어로 앱을 계획·테스트·디버깅·배포하도록 가르치는 과정이에요. 구글은 이 자격증이 2월 출시 이후 Coursera 역대 최다 수강 생성형 AI 자격증이 됐고 딜로이트·버라이즌·리프트·월마트 등이 도입했다고 밝혔는데, 이는 구글 자체 발표 수치예요.",
          source: "https://blog.google/company-news/outreach-and-initiatives/grow-with-google/vibe-coding-course/",
          officialUrl: "https://blog.google/company-news/outreach-and-initiatives/grow-with-google/vibe-coding-course/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "blog.google 공식 RSS(발행일 근거)", url: "https://blog.google/rss/" },
          ],
          tags: ["Google", "교육", "바이브코딩", "Coursera", "자격증"],
          slug: "google-20260811-google-adds-a-vibe-coding-course-to-its-ai-p",
          en: {
            title: "Google adds a vibe coding course to its AI Professional Certificate",
            deck: "A vibe-coding track joins the certificate.",
            summary: "On August 11, 2026 Google launched a vibe coding course on Coursera as part of the Google AI Professional Certificate, teaching learners with no coding experience to plan, test, debug and deploy apps using everyday language. Google says the certificate has become the most popular generative AI certificate of all time on Coursera since its February launch, with adopters including Deloitte, Verizon, Lyft and Walmart — vendor-reported claims.",
          },
          thumbnail: {
            src: "/og-cache/구글-ai-자격증에-바이브-코딩-과정-추가-3a9d406d.png",
            alt: "구글 AI 자격증에 바이브 코딩 과정 추가",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "구글, Go가 AI 코딩에 맞는 이유 정리",
          deck: "단순한 문법과 표준 도구가 에이전트에 유리하다는 주장입니다.",
          summary: "구글 개발자 블로그가 2026년 8월 11일 Go 언어가 AI 보조 소프트웨어 공학에 적합한 이유를 정리한 글을 냈어요. 저자들은 사람이 코드를 쓰는 속도는 더 이상 중요하지 않고 검토·검증·유지보수가 중요해졌다고 주장해요. LLM이 파일 간 구조 경계와 타입 정합성에서 자주 실패하는데 Go 컴파일러가 이를 즉시 걸러내 에이전트의 자기 수정 루프를 효율적으로 만든다는 설명이고, 벤치마크 수치 없이 구글 측 주장으로 제시된 글이에요.",
          source: "https://developers.googleblog.com/why-go-is-an-ideal-language-for-ai-assisted-software-engineering/",
          officialUrl: "https://developers.googleblog.com/why-go-is-an-ideal-language-for-ai-assisted-software-engineering/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Google Developers Blog RSS", url: "https://developers.googleblog.com/feeds/posts/default?alt=rss" },
          ],
          tags: ["Google", "Go", "AI코딩", "개발자도구", "의견글"],
          slug: "google-20260811-google-argues-go-is-an-ideal-language-for-ai",
          en: {
            title: "Google argues Go is an ideal language for AI-assisted software engineering",
            deck: "Simple syntax and standard tooling, argued as an advantage for agents.",
            summary: "On August 11, 2026 Google's Developers Blog published an argument that Go suits AI-assisted software engineering. The authors contend the rate at which a human writes code no longer matters much — reviewing, verifying and maintaining it does — and that Go's compiler immediately rejects the structural and type errors LLMs commonly produce, enabling efficient agent self-correction. It is a Google position piece rather than a benchmarked evaluation.",
          },
          thumbnail: {
            src: "/og-cache/구글-go가-ai-코딩에-맞는-이유-정리-1b2b7dc6.png",
            alt: "구글, Go가 AI 코딩에 맞는 이유 정리",
          },
        },
      ],
    },
    {
      name: "Meta",
      color: "#0064E0",
      posts: [
        {
          date: "8/10",
          platform: "X+Threads",
          title: "메타, 30B 오픈 에이전틱 모델 Muse Glimmer 공개",
          featured: true,
          deck: "Apache 2.0에 4비트로 20GB 아래, 소비자 GPU 한 장이면 돕니다.",
          summary: "메타가 2026년 8월 10일 Muse Glimmer를 Apache 2.0 라이선스로 공개했어요. 파라미터는 약 29.6B(1.8B 비전 인코더 포함)이고 컨텍스트는 131,072 토큰 이상이며, 4비트 양자화 시 20GB 미만으로 줄어 소비자용 GPU 한 장에서 돌아가요. 메타 자체 수치로 DFlash 추측 디코딩 적용 시 RTX 5090에서 3.1배, M5-Max에서 1.8배 빠른 생성 속도를 제시했고, 모델 카드 벤치마크는 SWE-Bench Verified 76.0, TerminalBench 2.1 51.7, AIME 2026 94.7이에요.",
          source: "https://research.meta.ai/blog/introducing-muse-glimmer-open-agentic-model",
          officialUrl: "https://research.meta.ai/blog/introducing-muse-glimmer-open-agentic-model",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Hugging Face 모델 카드 (fetch 200, 벤치마크 표 출처)", url: "https://huggingface.co/meta-models/Muse-Glimmer-30B" },
            { label: "Meta AI Research 블로그 인덱스 (fetch 200, 날짜 교차확인)", url: "https://research.meta.ai/blog/" },
          ],
          tags: ["Meta", "오픈웨이트", "에이전틱", "온디바이스", "Apache 2.0"],
          slug: "meta-20260810-meta-releases-muse-glimmer-a-30b-open-agenti",
          en: {
            title: "Meta releases Muse Glimmer, a 30B open agentic model that runs on-device",
            deck: "Apache 2.0, under 20GB at 4-bit, and it runs on a single consumer GPU.",
            summary: "On August 10, 2026 Meta released Muse Glimmer under a permissive Apache 2.0 license — a ~29.6B parameter dense causal transformer with a Perception Encoder, 131,072+ token context, optimized for always-on local agent workflows on a single consumer GPU. Vendor-reported figures include 3.1x faster decoding on RTX 5090 and 1.8x on M5-Max via DFlash speculative decoding; the model card lists SWE-Bench Verified 76.0, TerminalBench 2.1 51.7, and AIME 2026 94.7.",
          },
          thumbnail: {
            src: "/og-cache/meta-muse-spark-첫-모델-출시-9fdff4e0.jpg",
            alt: "메타, 30B 오픈 에이전틱 모델 Muse Glimmer 공개",
          },
        },
        {
          date: "8/10",
          platform: "X+Threads",
          title: "저커버그, 오픈소스 AI 옹호 에세이 공개",
          deck: "널리 퍼진 오픈소스가 더 안전하다는 주장을 폈습니다.",
          summary: "마크 저커버그가 2026년 8월 10일 메타 공식 사이트에 'The Future is for Everyone' 에세이를 올렸어요. 오픈소스가 권력 집중을 막는 힘이며 널리 배포된 오픈소스 시스템이 더 안전하다는 주장을 폈고, 현재의 오픈소스 생태계를 제한하는 것은 실수라고 밝혔어요. 같은 날 Muse Glimmer 오픈웨이트 공개와 함께 나온 발표예요.",
          source: "https://www.meta.com/thefutureisforeveryone/",
          officialUrl: "https://www.meta.com/thefutureisforeveryone/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Muse Glimmer 공개 블로그 (같은 날 동반 발표)", url: "https://research.meta.ai/blog/introducing-muse-glimmer-open-agentic-model" },
          ],
          tags: ["Meta", "오픈소스", "AI정책", "저커버그"],
          slug: "meta-20260810-zuckerberg-publishes-the-future-is-for-every",
          en: {
            title: "Zuckerberg publishes \"The Future is for Everyone\", arguing for open source AI",
            deck: "His argument: widely distributed open source is the safer system.",
            summary: "On August 10, 2026 Mark Zuckerberg published \"The Future is for Everyone\" on Meta's official site, arguing that open source prevents concentration of AI power, that widely deployed open source systems have proven more secure, and that restricting the current open source ecosystem would be a mistake. It was published alongside the Muse Glimmer open-weights release.",
          },
          thumbnail: {
            src: "/og-cache/meta-muse-spark-첫-모델-출시-9fdff4e0.jpg",
            alt: "저커버그, 오픈소스 AI 옹호 에세이 공개",
          },
        },
      ],
    },
    {
      name: "Microsoft AI",
      color: "#0078D4",
      posts: [
        {
          date: "8/10",
          platform: "X+Threads",
          title: "MS MAI-Image-2.6, 이미지 아레나 2위 기록",
          deck: "공개 이미지 아레나에서 2위에 올랐습니다.",
          summary: "마이크로소프트가 2026년 8월 10일 MAI-Image-2.6을 공개했어요. Arena 텍스트-투-이미지 리더보드에서 2위로 올랐고, 전작 MAI-Image-2.5 대비 종합 Elo가 79점, 텍스트 렌더링 부문은 91점 높아졌다고 밝혔어요. 텍스트 렌더링, 인물과 3D 이미지, 상업용·실사 이미지 품질이 개선됐어요. 현재 Arena에서 써볼 수 있고, 이번 주 중 MAI Playground, 이후 Microsoft Foundry 등으로 확대될 예정이에요.",
          source: "https://microsoft.ai/news/mai-image-2-6-launches-at-no-2-on-arena-ahead-of-google-meta-and-xai/",
          officialUrl: "https://microsoft.ai/news/mai-image-2-6-launches-at-no-2-on-arena-ahead-of-google-meta-and-xai/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Microsoft AI 뉴스 인덱스 (fetch 200, 2026-08 models 항목 확인)", url: "https://microsoft.ai/news/" },
          ],
          tags: ["Microsoft", "MAI", "이미지생성", "Arena", "Elo"],
          slug: "microsoft-ai-20260810-microsofts-mai-image-26-debuts-at-no-2-on-th",
          en: {
            title: "Microsoft's MAI-Image-2.6 debuts at No. 2 on the Arena text-to-image leaderboard",
            deck: "It placed second on a public image arena.",
            summary: "On August 10, 2026 Microsoft released MAI-Image-2.6, which ranks second on the Arena text-to-image leaderboard with +79 Elo over MAI-Image-2.5 overall and +91 Elo on text rendering, ahead of models from Meta, Google and xAI. Improvements cover text rendering, portraits and 3D imagery, and commercial and photorealistic output. It is available on Arena now, with MAI Playground later that week and Microsoft Foundry rolling out soon.",
          },
          thumbnail: {
            src: "/og-cache/ms-mai-image-2-6-이미지-아레나-2위-기록-f8550524.webp",
            alt: "MS MAI-Image-2.6, 이미지 아레나 2위 기록",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "MS, MAI-Code-1.1-Flash 공개·비용 4분의 1",
          deck: "이전 세대에 비전 지원을 더하고 값을 4분의 1로 낮췄습니다.",
          summary: "마이크로소프트가 2026년 8월 11일 MAI-Code-1.1-Flash를 공개했어요. 6월 Build에서 낸 MAI-Code-1-Flash 대비 비용이 4분의 1이고 토큰 효율은 25% 높으며, 토큰 스트리밍도 25% 빨라졌다고 밝혔어요. MS 자체 수치로 GitHub Copilot CLI에서 Terminal-Bench 2.1이 22%, .NET 과제가 15% 개선됐고 코드 생존율은 4% 올랐어요. GitHub Copilot에 이미 적용됐고, Free·Student는 자동 모델 선택으로, Pro·Pro+·Max·Business·Enterprise는 수동 선택으로 쓸 수 있어요.",
          source: "https://microsoft.ai/news/mai-code-1-1-flash-br-better-faster-at-a-quarter-of-the-cost/",
          officialUrl: "https://microsoft.ai/news/mai-code-1-1-flash-br-better-faster-at-a-quarter-of-the-cost/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "GitHub Changelog 2026-08-11 (fetch 200, 요금 배수·플랜 확인)", url: "https://github.blog/changelog/2026-08-11-mai-code-1-1-flash-available-in-github-copilot/" },
            { label: "Microsoft AI 뉴스 인덱스 (fetch 200)", url: "https://microsoft.ai/news/" },
          ],
          tags: ["Microsoft", "MAI", "코딩모델", "GitHub Copilot", "비용절감"],
          slug: "microsoft-ai-20260811-microsoft-ships-mai-code-11-flash-at-a-quart",
          en: {
            title: "Microsoft ships MAI-Code-1.1-Flash at a quarter of the cost",
            deck: "Native vision added, at a quarter of the previous cost.",
            summary: "On August 11, 2026 Microsoft released MAI-Code-1.1-Flash, at a quarter of the cost of the June Build-era MAI-Code-1-Flash with 25% greater token efficiency and 25% faster token streaming. Vendor-reported gains include a 22% improvement on Terminal-Bench 2.1 in GitHub Copilot CLI, 15% on .NET tasks, and 4% higher code survival. It is in production in GitHub Copilot, auto-selected for Free and Student users and manually selectable on paid SKUs at a 0.25x premium request multiplier.",
          },
          thumbnail: {
            src: "/og-cache/ms-mai-code-1-1-flash-공개-비용-4분의-1-2d6e469f.webp",
            alt: "MS, MAI-Code-1.1-Flash 공개·비용 4분의 1",
          },
        },
      ],
    },
    {
      name: "xAI",
      color: "#000000",
      posts: [
        {
          date: "8/12",
          platform: "X+Threads",
          title: "그록 4.6, 종합 지능 지수에서 GPT-5.6 Sol과 동률",
          featured: true,
          deck: "5주 만에 56점에서 61점. 코딩 벤치는 아직 뒤집니다.",
          summary: "SpaceXAI가 8월 12일 Grok 4.6을 공개했어요. 긴 작업을 여러 단계에 걸쳐 끝까지 끌고 가는 능력과 스스로 결과를 점검하는 동작에 초점을 맞췄어요. 자사 공개 표 기준 Artificial Analysis 지능 지수 61점으로 GPT-5.6 Sol Max와 같고, 5주 전 Grok 4.5의 56점에서 5점 올랐어요. 다만 같은 표에서 DeepSWE는 65.9%로 Sol Max 73%·Fable 5 Max 70%보다 낮고, Terminal-Bench v3.0도 26%로 Sol 34.6%·Fable 34.1%에 못 미쳐요. 가격은 100만 토큰당 입력 2달러·출력 6달러이고 빠른 변형은 두 배예요.",
          content: `**무엇이 나왔나**\n8월 12일 SpaceXAI가 **Grok 4.6**을 공개했습니다. 공식 발표문의 초점은 성능 숫자가 아니라 지속성입니다. "여러 단계에 걸친 복잡한 작업을 끝까지 붙들고 간다"는 표현을 썼고, 긴 작업에서 모델이 다음으로 넘어가기 전에 자기 결과를 점검하는 동작이 더 자주 관측됐다고 밝혔습니다.\n\n**자사 공개 표 (Grok 4.6 High 기준)**\n- AA 지능 지수 **61** — Grok 4.5는 56, GPT-5.6 Sol Max도 **61**, Fable 5 Max는 **62**\n- GDPVal-AA v2 **1753** — 4.5는 1526, Sol Max 1728, Fable 5 Max 1741\n- CursorBench v3.2 **69.9%** — 4.5는 66.7%, Sol Max 67.2%, Fable 5 Max 70.5%\n- DeepSWE v1.1 **65.9%** — 4.5는 54%, Sol Max **73%**, Fable 5 Max **70%**\n- Terminal-Bench v3.0 **26%** — 4.5는 15.7%, Sol Max **34.6%**, Fable 5 Max **34.1%**\n\n**어디까지가 사실인가**\n"GPT-5.6 Sol을 따라잡았다"가 성립하는 건 **AA 지능 지수 한 줄**입니다. 아홉 개 벤치마크를 합산한 종합 점수라 개별 능력을 가리지 못합니다. 같은 표에서 코딩(DeepSWE)과 터미널 작업(Terminal-Bench)은 Sol과 Fable 5가 여전히 앞섭니다. 상승 폭이 큰 건 분명합니다 — 5주 만에 DeepSWE가 54%에서 65.9%로 올랐습니다.\n\n**쓸 수 있는 곳과 값**\nCursor, Grok Build, API에서 바로 쓸 수 있고 OpenRouter·Vercel·Cloudflare에도 올라갔습니다. 100만 토큰당 입력 2달러, 출력 6달러이고 빠른 변형은 두 배입니다. 첫 주에는 Grok Build와 Cursor에서 포함 사용량을 두 배로 줍니다.\n\n**직접 확인할 것**\n종합 지수만 보고 갈아타지 마십시오. 본인이 실제로 시키는 일이 코드 수정이면 DeepSWE·Terminal-Bench 쪽을, 긴 리서치나 문서 작업이면 GDPVal-AA 쪽을 보는 게 맞습니다. 첫 주 무료 사용량이 있으니 같은 과제를 두 모델에 돌려 비교하는 비용이 지금은 거의 없습니다.`,
          source: "https://x.ai/news/grok-4-6",
          officialUrl: "https://x.ai/news/grok-4-6",
          verifiedAt: "2026-08-13",
          backupUrls: [
            { label: "Artificial Analysis 독립 집계", url: "https://artificialanalysis.ai/models/grok-4-6" },
            { label: "The Decoder 보도", url: "https://the-decoder.com/spacexais-grok-4-6-matches-openais-best-model-and-undercuts-it-on-price/" },
          ],
          tags: ["xAI", "SpaceXAI", "Grok", "프런티어 모델", "코딩"],
          slug: "xai-20260812-grok-4-6",
          en: {
            title: "Grok 4.6 ties GPT-5.6 Sol on the composite intelligence index",
            deck: "56 to 61 in five weeks, though coding benchmarks still trail.",
            summary: "SpaceXAI released Grok 4.6 on August 12, focused on long-running agents and self-verification. Its own published table puts it at 61 on the Artificial Analysis Intelligence Index, level with GPT-5.6 Sol Max and up from Grok 4.5's 56 five weeks earlier. In the same table DeepSWE (65.9%) and Terminal-Bench v3.0 (26%) still trail Sol Max and Fable 5 Max. Pricing is $2 per million input tokens and $6 per million output.",
            content: `**What shipped**\nSpaceXAI released **Grok 4.6** on August 12. The announcement leads with persistence rather than raw scores: the model "stays with complex tasks across many steps", and on longer trajectories the team saw more self-testing and verification before moving on.\n\n**Vendor's own table (Grok 4.6 High)**\n- AA Intelligence Index **61** — Grok 4.5 scored 56, GPT-5.6 Sol Max also **61**, Fable 5 Max **62**\n- GDPVal-AA v2 **1753** — 4.5 at 1526, Sol Max 1728, Fable 5 Max 1741\n- CursorBench v3.2 **69.9%** — 4.5 at 66.7%, Sol Max 67.2%, Fable 5 Max 70.5%\n- DeepSWE v1.1 **65.9%** — 4.5 at 54%, Sol Max **73%**, Fable 5 Max **70%**\n- Terminal-Bench v3.0 **26%** — 4.5 at 15.7%, Sol Max **34.6%**, Fable 5 Max **34.1%**\n\n**How far "caught up" goes**\nThe tie with GPT-5.6 Sol holds on **one line**: the composite intelligence index, a blend of nine benchmarks that averages away individual strengths. On coding (DeepSWE) and terminal work in the same table, Sol and Fable 5 remain ahead. The jump itself is real — DeepSWE moved from 54% to 65.9% in five weeks.\n\n**Where and what it costs**\nAvailable in Cursor, Grok Build and the API, plus OpenRouter, Vercel and Cloudflare. Pricing starts at $2 per million input tokens and $6 per million output, with a fast variant at twice the price. Grok Build and Cursor include 2x usage for the first week.\n\n**What to check**\nDon't switch on the composite score alone. If the work is code edits, read DeepSWE and Terminal-Bench; if it is long research or document work, read GDPVal-AA. With the first-week bonus usage, running the same task through both models costs almost nothing right now.`
          },
          thumbnail: {
            src: "/og-cache/그록-4-6-종합-지능-지수에서-gpt-5-6-sol과-동률-692c0339.png",
            alt: "그록 4.6, 종합 지능 지수에서 GPT-5.6 Sol과 동률",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "xAI, 상시 구동 AI 에이전트 Grok Bot 출시",
          deck: "브라우저·파일시스템·터미널을 갖춘 VM에서 상시 돌아갑니다.",
          summary: "xAI가 2026년 8월 Grok Bot을 공개했어요. 각 Bot이 브라우저·파일시스템·터미널을 갖춘 persistent 클라우드 VM 위에서 돌아가고, 여러 Bot이 하나의 사용자 단위 컴퓨터를 공유하며 병렬로 작동하고 서로 메시지를 주고받거나 소유권을 넘길 수 있어요. 다단계 작업을 한 번 따라 하게 하면 루틴으로 저장해 일정에 맞춰 재실행하고, 메모리·파일·브라우저 세션이 턴을 넘어 유지돼요. xAI 공식 릴리스 노트에는 월 단위(August)만 적혀 있고 일자는 표기돼 있지 않아요.",
          source: "https://docs.x.ai/grok-bot/overview",
          officialUrl: "https://docs.x.ai/grok-bot/overview",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "xAI 공식 릴리스 노트 (fetch 200, August 항목)", url: "https://docs.x.ai/docs/release-notes" },
            { label: "Grok Bot 시작 가이드 (공식 docs)", url: "https://docs.x.ai/grok-bot/get-started" },
          ],
          tags: ["xAI", "에이전트", "Grok", "클라우드VM"],
          slug: "xai-20260811-xai-launches-grok-bot-persistent-ai-teammate",
          en: {
            title: "xAI launches Grok Bot — persistent AI teammates with their own cloud computer",
            deck: "Each bot runs nonstop on a VM with a browser, filesystem and terminal.",
            summary: "xAI released Grok Bot in August 2026. Each Bot runs on a persistent cloud VM with a browser, filesystem, and terminal; multiple Bots share one user-scoped computer, run in parallel, message each other and pass ownership. A Bot can be walked through a multi-step path once and persists it as a re-runnable routine, retaining memory, files and browser sessions across turns. xAI's own release notes list only the month, not the day.",
          },
          thumbnail: {
            src: "/og-cache/xai-상시-구동-ai-에이전트-grok-bot-출시-556eab4f.png",
            alt: "xAI, 상시 구동 AI 에이전트 Grok Bot 출시",
          },
        },
      ],
    },
    {
      name: "GitHub",
      color: "#24292F",
      posts: [
        {
          date: "8/11",
          platform: "X+Threads",
          title: "Copilot에 MAI-Code-1.1-Flash 추가, 가격 73% 인하",
          deck: "무료·학생 사용자에게는 자동으로 선택됩니다.",
          summary: "GitHub이 Microsoft의 소형 코딩 모델 MAI-Code-1.1-Flash를 Copilot에 순차 배포했어요. 이전 MAI-Code-1-Flash에 이미지 이해를 위한 네이티브 비전 지원을 더했고 코드 품질, 지시 따르기, 도구 사용, 성능이 개선됐다고 밝혔어요. GitHub 발표 기준 정가는 MAI-Code-1-Flash 대비 73% 낮고, 연간 구독자에게는 프리미엄 요청 배수 0.25배로 과금돼요. VS Code, Visual Studio, JetBrains IDE 등에서 쓸 수 있고 무료·학생 사용자에게는 자동 선택돼요.",
          source: "https://github.blog/changelog/2026-08-11-mai-code-1-1-flash-available-in-github-copilot/",
          officialUrl: "https://github.blog/changelog/2026-08-11-mai-code-1-1-flash-available-in-github-copilot/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "GitHub Changelog", url: "https://github.blog/changelog/" },
          ],
          tags: ["Copilot", "GitHub", "모델가격", "비전", "MAI-Code"],
          slug: "github-20260811-mai-code-11-flash-arrives-in-github-copilot",
          en: {
            title: "MAI-Code-1.1-Flash arrives in GitHub Copilot at 73% lower list price",
            deck: "It is auto-selected for free and student users.",
            summary: "GitHub is rolling out Microsoft's MAI-Code-1.1-Flash in Copilot. It adds native vision on top of MAI-Code-1-Flash with improvements to coding quality, instruction following, tool use and performance, at a 73% lower list price than its predecessor and a 0.25x premium request multiplier for annual subscribers. It is available across VS Code, Visual Studio, JetBrains IDEs and more.",
          },
          thumbnail: {
            src: "/og-cache/copilot에-mai-code-1-1-flash-추가-가격-73-인하-41baf278.png",
            alt: "Copilot에 MAI-Code-1.1-Flash 추가, 가격 73% 인하",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "JetBrains용 Copilot에 메모리·Ollama 지원 추가",
          deck: "세션을 넘겨 기억하고 로컬 모델도 붙일 수 있습니다.",
          summary: "GitHub이 JetBrains IDE용 Copilot에 세 가지를 추가했어요. 에이전트 채팅 세션 사이에 유용한 정보를 기억하고 다시 불러오는 Copilot 메모리, 로컬 모델을 쓸 수 있는 Ollama BYOK 제공자 지원, 그리고 플러그인 사용 가능 여부·MCP 서버 접근·권한 우회 동작·OpenTelemetry 설정을 서버에서 관리하는 기업용 제어예요. 통합 터미널에서 Copilot CLI를 자동 설치하는 기능도 들어갔어요.",
          source: "https://github.blog/changelog/2026-08-11-copilot-memory-and-ollama-in-github-copilot-for-jetbrains/",
          officialUrl: "https://github.blog/changelog/2026-08-11-copilot-memory-and-ollama-in-github-copilot-for-jetbrains/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "GitHub Changelog", url: "https://github.blog/changelog/" },
          ],
          tags: ["Copilot", "JetBrains", "Ollama", "BYOK", "MCP"],
          slug: "github-20260811-copilot-memory-and-ollama-land-in-github-cop",
          en: {
            title: "Copilot memory and Ollama land in GitHub Copilot for JetBrains",
            deck: "Memory persists across sessions, and local models can be plugged in.",
            summary: "GitHub added three things to Copilot for JetBrains: Copilot memory that retains and recalls information across agent chat sessions, Ollama as a BYOK provider for local models, and expanded server-side enterprise controls over plugin availability, MCP server access, permission bypass behavior and OpenTelemetry settings. Copilot CLI can now auto-install from the integrated terminal.",
          },
          thumbnail: {
            src: "/og-cache/jetbrains용-copilot에-메모리-ollama-지원-추가-4a8a669e.jpg",
            alt: "JetBrains용 Copilot에 메모리·Ollama 지원 추가",
          },
        },
      ],
    },
    {
      name: "Vercel",
      color: "#000000",
      posts: [
        {
          date: "8/10",
          platform: "X+Threads",
          title: "Vercel Sandbox, 오픈소스 관리형 이미지로 전환",
          deck: "기반 이미지가 공개 저장소로 옮겨가고 OS는 우분투가 됩니다.",
          summary: "Vercel이 Sandbox의 기반을 Vercel Managed Images(VMI)로 바꿨어요. 버전이 매겨진 오픈소스 베이스 이미지이고 모든 이미지 소스는 공개 저장소 vercel/sandbox에 있어요. 기존 Sandbox 런타임은 폐기 예정이고, Sandbox SDK 3버전부터 새 샌드박스는 vercel/sandbox/universal:latest를 기본값으로 써요. universal 이미지는 기본 OS를 Amazon Linux에서 Ubuntu로 바꿨고 Node.js, Python, 주요 코딩 에이전트를 포함해요. 모든 관리형 이미지는 매일 밤 릴리스돼요.",
          source: "https://vercel.com/changelog/vercel-sandbox-managed-images",
          officialUrl: "https://vercel.com/changelog/vercel-sandbox-managed-images",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Vercel Changelog", url: "https://vercel.com/changelog" },
            { label: "GitHub vercel/sandbox", url: "https://github.com/vercel/sandbox" },
          ],
          tags: ["Vercel", "샌드박스", "오픈소스이미지", "에이전트실행", "Ubuntu"],
          slug: "vercel-20260810-vercel-sandbox-now-runs-on-vercel-managed-im",
          en: {
            title: "Vercel Sandbox now runs on Vercel Managed Images",
            deck: "Base images move to a public repo, and the OS switches to Ubuntu.",
            summary: "Vercel moved Sandbox onto Vercel Managed Images, versioned open-source base images whose sources live in the public vercel/sandbox repo. Managed images replace the now-deprecated Sandbox runtimes; from Sandbox SDK v3 new sandboxes default to vercel/sandbox/universal:latest, which switches the default OS from Amazon Linux to Ubuntu. Every managed image gets a nightly release.",
          },
          thumbnail: {
            src: "/og-cache/vercel-sandbox-오픈소스-관리형-이미지로-전환-2e7a8f8d.png",
            alt: "Vercel Sandbox, 오픈소스 관리형 이미지로 전환",
          },
        },
      ],
    },
    {
      name: "Mistral AI",
      color: "#FA520F",
      posts: [
        {
          date: "8/11",
          platform: "X+Threads",
          title: "미스트랄, 지역 엔드포인트 정식 출시·2030년 1GW 계획",
          deck: "데이터를 유럽 안에 두는 지역 추론이 정식 출시됐습니다.",
          summary: "미스트랄이 2026년 8월 11일 지역 엔드포인트를 정식 출시했어요. 고객이 추론 처리 지역을 유럽 또는 미국 중에서 고를 수 있고, 맞춤 레이트 리밋과 가동률 SLA가 붙는 Priority Tier는 퍼블릭 프리뷰예요. 자사 플랫폼에서 서드파티 오픈 모델도 호스팅하기 시작하는데 첫 대상은 Z.ai의 GLM-5.2예요. 유럽 컴퓨트 유닛(ECU)을 통해 2030년까지 1GW 확보를 목표로 하며, 연합 참여사로 ASML·CMA CGM·Amadeus·Caisse des Dépôts를 밝혔어요.",
          source: "https://mistral.ai/news/regional-inference-open-models-new-compute/",
          officialUrl: "https://mistral.ai/news/regional-inference-open-models-new-compute/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Mistral 뉴스 인덱스 (fetch 200, 2026-08-11 Company 항목 확인)", url: "https://mistral.ai/news/" },
          ],
          tags: ["Mistral", "데이터주권", "인프라", "리전", "SLA"],
          slug: "mistral-ai-20260811-mistral-ships-regional-endpoints-ga-and-sets",
          en: {
            title: "Mistral ships regional endpoints GA and sets a 1 GW European compute roadmap",
            deck: "In-region inference goes GA, keeping data inside Europe.",
            summary: "On August 11, 2026 Mistral made Regional Endpoints generally available, letting customers pin inference processing to Europe or the US, with a Priority Tier in public preview offering custom rate limits and an uptime SLA. Mistral will host third-party open models on its platform starting with Z.ai's GLM-5.2, and targets 1 GW of capacity by 2030 via European Compute Units, with ASML, CMA CGM, Amadeus and Caisse des Dépôts named as coalition partners.",
          },
          thumbnail: {
            src: "/og-cache/미스트랄-지역-엔드포인트-정식-출시-2030년-1gw-계획-d1598b19.png",
            alt: "미스트랄, 지역 엔드포인트 정식 출시·2030년 1GW 계획",
          },
        },
      ],
    },
    {
      name: "Cactus Compute",
      color: "#22C55E",
      posts: [
        {
          date: "8/11",
          platform: "X+Threads",
          title: "Cactus, 14MB짜리 45M 파라미터 에이전트 모델 공개",
          deck: "단일 14MB 바이너리에 세션 하나가 RAM 28MB입니다.",
          summary: "Cactus Compute가 도구 호출, 기기 조작, 구조화 추출용 오픈 모델 Needle 2를 Apache-2.0으로 공개했어요. 전체가 단일 14MB 바이너리이고 세션 하나가 RAM 28MB로 돌아가요. Cactus 자체 측정 수치로 Raspberry Pi 5에서 초당 500토큰 이상, Meta Quest 3S와 Apple Vision Pro 같은 VR 기기에서 400~1,500토큰, 20만원대 저가 안드로이드 폰에서 300~700토큰을 낸다고 해요. 벤치마크는 Mobile Actions 63.7%, BFCL v4 종합 42.6%, Seal-Tools in-domain 32.6%, DroidCall 17.0%로 편차가 커요.",
          source: "https://cactuscompute.com/needle",
          officialUrl: "https://cactuscompute.com/needle",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Hugging Face Cactus-Compute/needle2", url: "https://huggingface.co/Cactus-Compute/needle2" },
            { label: "GitHub cactus-compute/needle", url: "https://github.com/cactus-compute/needle" },
          ],
          tags: ["온디바이스", "초소형모델", "도구호출", "엣지", "Apache-2.0"],
          slug: "cactus-compute-20260811-cactus-compute-releases-needle-2-a-14-mb-45m",
          en: {
            title: "Cactus Compute releases Needle 2, a 14 MB 45M-parameter agentic LLM",
            deck: "A single 14MB binary, with one session in 28MB of RAM.",
            summary: "Cactus Compute released Needle 2 under Apache-2.0: an open 45M-parameter model for tool calling, device use and structured extraction, shipped as a single 14 MB binary running a full session in 28 MB of RAM. Vendor-reported throughput is 500+ tok/s on a Raspberry Pi 5, 400-1,500 tok/s on VR devices and 300-700 tok/s on budget phones. Benchmarks: Mobile Actions 63.7%, BFCL v4 overall 42.6%, Seal-Tools in-domain 32.6%, DroidCall 17.0%.",
          },
          thumbnail: {
            src: "/og-cache/cactus-14mb짜리-45m-파라미터-에이전트-모델-공개-dc264893.png",
            alt: "Cactus, 14MB짜리 45M 파라미터 에이전트 모델 공개",
          },
        },
      ],
    },
    {
      name: "NVIDIA",
      color: "#76B900",
      posts: [
        {
          date: "8/10",
          platform: "X+Threads",
          title: "엔비디아, 6개 금융사와 5000억 달러 조달 구조",
          deck: "MOU 단계이고 최종 계약 체결은 아직 남아 있습니다.",
          summary: "엔비디아가 2026년 8월 10일 아폴로, 블랙록, 블랙스톤, 브룩필드, 골드만삭스, KKR 등 6개 금융기관과 양해각서(MOU)를 맺고 5000억 달러 이상의 제3자 자본을 AI 인프라 구축에 동원하는 컴퓨트 금융 플랫폼을 만들겠다고 밝혔어요. 다만 공식 발표문에도 \"최종 계약 체결을 조건으로 한다\"고 적혀 있어 아직 구속력 있는 계약은 아니에요. GPU 구매 자금을 벤더가 아닌 외부 자본시장에서 조달하는 구조를 제도화하려는 시도예요.",
          source: "https://nvidianews.nvidia.com/news/nvidia-partners-with-apollo-blackrock-blackstone-brookfield-goldman-sachs-and-kkr-to-establish-ai-compute-infrastructure-financing-platforms-to-mobilize-over-500-billion-of-third-party-capital",
          officialUrl: "https://nvidianews.nvidia.com/news/nvidia-partners-with-apollo-blackrock-blackstone-brookfield-goldman-sachs-and-kkr-to-establish-ai-compute-infrastructure-financing-platforms-to-mobilize-over-500-billion-of-third-party-capital",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "NVIDIA Investor Relations", url: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Partners-With-Apollo-BlackRock-Blackstone-Brookfield-Goldman-Sachs-and-KKR-to-Establish-AI-Compute-Infrastructure-Financing-Platforms-to-Mobilize-Over-500-Billion-of-Third-Party-Capital/default.aspx" },
            { label: "SiliconANGLE (2026-08-10)", url: "https://siliconangle.com/2026/08/10/nvidia-taps-wall-street-half-trillion-dollars-fuel-global-ai-infrastructure-buildout/" },
          ],
          tags: ["인프라", "자금조달", "엔비디아", "데이터센터", "사모펀드"],
          slug: "nvidia-20260810-nvidia-partners-with-apollo-blackrock-blacks",
          en: {
            title: "NVIDIA Partners With Apollo, BlackRock, Blackstone, Brookfield, Goldman Sachs and KKR to Mobilize Over $500 Billion",
            deck: "Still memorandums of understanding, subject to final agreements.",
            summary: "On August 10, 2026, NVIDIA announced memorandums of understanding with Apollo, BlackRock, Blackstone, Brookfield, Goldman Sachs and KKR to establish compute financing platforms mobilizing over $500 billion of third-party capital for AI infrastructure buildout. NVIDIA stated the partnerships remain subject to execution of final agreements.",
          },
          thumbnail: {
            src: "/og-cache/엔비디아-6개-금융사와-5000억-달러-조달-구조-c4bf2b3b.jpg",
            alt: "엔비디아, 6개 금융사와 5000억 달러 조달 구조",
          },
        },
      ],
    },
    {
      name: "Intel",
      color: "#0071C5",
      posts: [
        {
          date: "8/11",
          platform: "X+Threads",
          title: "인텔, 200억 달러 유상증자로 AI 투자 조달",
          deck: "150억에서 200억으로 늘려 주당 95달러에 확정했습니다.",
          summary: "인텔이 2026년 8월 10일 150억 달러 규모 보통주 공모를 발표한 뒤, 8월 11일 이를 200억 달러로 확대하고 주당 95달러에 2억 526만 주로 가격을 확정했어요. 순조달액은 약 197억 달러이고 8월 12일 마감 예정이며, 용도는 설비투자와 운전자본을 포함한 일반 기업 목적이라고 밝혔어요. 인텔은 AI 컴퓨트 투자에 따른 수요를 이유로 들었는데, 이는 회사 자체 설명이에요.",
          source: "https://www.intc.com/news-events/press-releases/detail/1779/intel-announces-upsize-and-pricing-of-20-billion-common",
          officialUrl: "https://www.intc.com/news-events/press-releases/detail/1779/intel-announces-upsize-and-pricing-of-20-billion-common",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Intel Newsroom — $15B 최초 발표(2026-08-10)", url: "https://newsroom.intel.com/corporate/intel-announces-proposed-15-billion-common-stock-offering" },
            { label: "Intel Newsroom — 증액·가격 확정", url: "https://newsroom.intel.com/corporate/intel-announces-upsize-and-pricing-of-20-billion-common-stock-offering" },
            { label: "SEC Form FWP (fetch 403)", url: "https://www.sec.gov/Archives/edgar/data/0000050863/000119312526341325/d82791dfwp.htm" },
          ],
          tags: ["반도체", "파운드리", "자금조달", "인텔"],
          slug: "intel-20260811-intel-announces-upsize-and-pricing-of-20-bil",
          en: {
            title: "Intel Announces Upsize and Pricing of $20 Billion Common Stock Offering",
            deck: "Upsized from $15B to $20B and priced at $95 a share.",
            summary: "Intel announced a $15 billion common stock offering on August 10, 2026, then on August 11 upsized it to $20 billion, pricing 210,526,315 shares at $95 per share for approximately $19.7 billion in net proceeds. The offering was expected to close on August 12, 2026, with proceeds designated for general corporate purposes including capital expenditures and working capital.",
          },
          thumbnail: {
            src: "/og-cache/인텔-200억-달러-유상증자로-ai-투자-조달-2c5b0f54.jpg",
            alt: "인텔, 200억 달러 유상증자로 AI 투자 조달",
          },
        },
      ],
    },
    {
      name: "네이버",
      color: "#03C75A",
      posts: [
        {
          date: "8/10",
          platform: "X+Threads",
          title: "네이버, 시니어 맞춤 AI 교과서 공동 개발",
          deck: "국가평생교육진흥원과 디지털 문해 교과서를 만듭니다.",
          summary: "네이버가 8월 10일 국가평생교육진흥원과의 업무협약을 알렸어요. 협약은 8월 7일 네이버 1784에서 체결했고, 두 기관은 AI·디지털 평생교육 콘텐츠를 공동 개발하고 보급하기로 했어요. 웨일 브라우저 기반 디지털 문해 교과서를 만들어 네이버 쇼핑 이용법과 웨일 기능 사용법 등을 시니어와 디지털 취약 계층에 제공할 계획이에요.",
          source: "https://www.navercorp.com/media/pressReleasesDetail?seq=10034580",
          officialUrl: "https://www.navercorp.com/media/pressReleasesDetail?seq=10034580",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "NAVER 보도자료 목록", url: "https://www.navercorp.com/media/pressReleases" },
          ],
          tags: ["AI리터러시", "교육", "네이버", "디지털포용"],
          slug: "item-20260810-naver-and-koreas-lifelong-education-institut",
          en: {
            title: "NAVER and Korea's lifelong education institute to co-develop senior AI textbooks",
            deck: "A digital-literacy textbook, built with the national lifelong education institute.",
            summary: "On August 10, NAVER announced an MOU with Korea's National Institute for Lifelong Education, signed August 7 at NAVER 1784. The two will jointly develop and distribute AI and digital lifelong-education content, including a Whale-browser-based digital literacy textbook covering everyday NAVER services for seniors and digitally underserved groups.",
          },
          thumbnail: {
            src: "/og-cache/네이버-시니어-맞춤-ai-교과서-공동-개발-d8a8aa3d.png",
            alt: "네이버, 시니어 맞춤 AI 교과서 공동 개발",
          },
        },
      ],
    },
    {
      name: "업스테이지",
      color: "#7C3AED",
      posts: [
        {
          date: "8/11",
          platform: "X+Threads",
          title: "업스테이지, 에이전트형 Solar Pro 4 공개",
          deck: "512K 컨텍스트에 한·영·일을 지원하고 9월 10일까지 90% 할인입니다.",
          summary: "업스테이지가 8월 11일 에이전트 작업에 맞춘 Solar Pro 4를 공개했어요. 컨텍스트는 512K, 최대 출력은 128K 토큰이고 영어·한국어·일본어 입출력을 지원해요. 가격은 100만 토큰당 입력 0.30달러, 캐시 입력 0.06달러, 출력 1.20달러이며 9월 10일까지 Upstage Console과 OpenRouter에서 90% 할인을 적용해요. 벤더 자체 수치로 Terminal-Bench v2.1 57점, τ³-Banking 23점, AA-LCR 71점, GPQA Diamond 89.0점을 제시했어요.",
          source: "https://www.upstage.ai/blog/en/solar-pro-4",
          officialUrl: "https://www.upstage.ai/blog/en/solar-pro-4",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Upstage Console 문서", url: "https://console.upstage.ai/docs/models" },
            { label: "OpenRouter 모델 페이지", url: "https://openrouter.ai/upstage/solar-pro4" },
          ],
          tags: ["LLM", "에이전트", "업스테이지", "한국", "Solar"],
          slug: "item-20260811-upstage-launches-solar-pro-4-an-agentic-mode",
          en: {
            title: "Upstage launches Solar Pro 4, an agentic model with a 512K context window",
            deck: "A 512K context across Korean, English and Japanese, at 90% off until September 10.",
            summary: "On August 11, Upstage released Solar Pro 4, an agentic LLM with a 512K context window and up to 128K output tokens, supporting English, Korean and Japanese. Pricing is $0.30 input / $0.06 cached input / $1.20 output per 1M tokens, with 90% off on Upstage Console and OpenRouter through September 10. Vendor-reported benchmarks: Terminal-Bench v2.1 57, τ³-Banking 23, AA-LCR 71, GPQA Diamond 89.0.",
          },
          thumbnail: {
            src: "/og-cache/업스테이지-에이전트형-solar-pro-4-공개-4c658132.png",
            alt: "업스테이지, 에이전트형 Solar Pro 4 공개",
          },
        },
      ],
    },
    {
      name: "과학기술정보통신부",
      color: "#003478",
      posts: [
        {
          date: "8/11",
          platform: "X+Threads",
          title: "독파모 4개팀 모두 Epoch AI 주목 모델 등재",
          deck: "LG·SKT·업스테이지·모티프 네 팀이 모두 올랐습니다.",
          summary: "과기정통부가 8월 11일 독자 AI 파운데이션 모델 프로젝트 4개 정예팀의 모델이 모두 미국 Epoch AI의 '주목할 만한 인공지능 모델'로 등재됐다고 밝혔어요. 4개 정예팀은 LG AI연구원, SK텔레콤, 업스테이지, 모티프테크놀로지스예요. 이 지표는 스탠퍼드 HAI의 AI Index 보고서에서도 쓰이는 지표예요.",
          source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156774084",
          officialUrl: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156774084",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "디지털데일리 보도", url: "https://www.ddaily.co.kr/page/view/2026081113510345599" },
            { label: "아시아경제 보도", url: "https://www.asiae.co.kr/article/2026081114504825357" },
          ],
          tags: ["정책", "과기정통부", "독자AI파운데이션모델", "벤치마크", "한국"],
          slug: "item-20260811-all-four-korean-sovereign-ai-foundation-mode",
          en: {
            title: "All four Korean sovereign AI foundation model teams listed as Epoch AI Notable Models",
            deck: "All four teams — LG, SKT, Upstage and Motif — made the list.",
            summary: "On August 11, Korea's Ministry of Science and ICT announced that models from all four elite teams in the sovereign AI foundation model project — LG AI Research, SK Telecom, Upstage and Motif Technologies — were listed as Epoch AI Notable Models. The metric is also used in Stanford HAI's AI Index report.",
          },
          thumbnail: {
            src: "/og-cache/독파모-4개팀-모두-epoch-ai-주목-모델-등재-1635b227.jpg",
            alt: "독파모 4개팀 모두 Epoch AI 주목 모델 등재",
          },
        },
      ],
    },
    {
      name: "Financial Times",
      color: "#990F3D",
      posts: [
        {
          date: "8/11",
          platform: "X+Threads",
          title: "오픈AI 윤리 총괄 퇴사, 후임 없어",
          deck: "후임을 두지 않는다고 회사가 확인했습니다.",
          summary: "파이낸셜타임스가 2026년 8월 11일 오픈AI의 윤리 총괄 클로에 바칼라(Chloé Bakalar)가 합류 1년이 되지 않은 시점인 7월에 퇴사했다고 보도했어요. 오픈AI 대변인은 후임을 두지 않는다고 확인하면서 \"AI 윤리는 오픈AI에서 한 사람이나 한 팀의 소유가 아니\"라고 밝혔어요. 같은 기간 안전 시스템 책임자 요하네스 하이데케와 미션 정렬 책임자였던 조슈아 아키암도 회사를 떠났어요.",
          source: "https://www.irishtimes.com/technology/big-tech/2026/08/11/openais-head-of-ethics-leaves-start-up-less-than-a-year-after-joining/",
          officialUrl: "https://www.irishtimes.com/technology/big-tech/2026/08/11/openais-head-of-ethics-leaves-start-up-less-than-a-year-after-joining/",
          verifiedAt: "2026-08-12",
          backupUrls: [
            { label: "Decrypt", url: "https://decrypt.co/375315/openais-only-dedicated-ethicist-has-left-with-no-replacement-ft" },
            { label: "Gizmodo", url: "https://gizmodo.com/openais-only-ethicist-reportedly-left-last-month-she-wasnt-replaced-2000796883" },
            { label: "American Bazaar (2026-08-11)", url: "https://americanbazaaronline.com/2026/08/11/openai-head-of-ethics-chloe-bakalar-departs-after-brief-tenure-486215/" },
          ],
          tags: ["오픈AI", "AI안전", "인사", "거버넌스"],
          slug: "financial-times-20260811-openais-head-of-ethics-leaves-start-up-less",
          en: {
            title: "OpenAI's Head of Ethics Leaves Start-up Less Than a Year After Joining",
            deck: "The company confirms there is no replacement.",
            summary: "The Financial Times reported on August 11, 2026 that Chloé Bakalar, OpenAI's head of ethics, left the company in July, less than a year after joining. An OpenAI spokesperson confirmed there is no replacement, saying \"AI ethics doesn't live with one owner or team at OpenAI.\" Johannes Heidecke, head of safety systems, and Joshua Achiam, chief futurist and former head of mission alignment, also departed in recent weeks.",
          },
          thumbnail: {
            src: "/og-cache/오픈ai-윤리-총괄-퇴사-후임-없어-46e74120.jpg",
            alt: "오픈AI 윤리 총괄 퇴사, 후임 없어",
          },
        },
      ],
    },
    {
      name: "생성 미디어",
      color: "#8B5CF6",
      posts: [
        {
          date: "8/6",
          platform: "X+Threads",
          title: "Luma에 Seedance 2.5 탑재, 오디오 포함 30초를 한 번에 생성",
          featured: true,
          deck: "짧은 조각을 잇지 않고 최대 50개 레퍼런스를 함께 씁니다.",
          summary: "Luma가 8월 6일 Seedance 2.5를 서비스에 추가했어요. Luma 공식 발표 기준 최대 30초 클립을 단일 패스로 만들고, 동기화 오디오와 최대 50개 참조 입력, 앞뒤 확장과 국소 편집을 지원해요. ByteDance 제품 페이지에는 게시일이 없어 이 카드는 원개발사의 출시일이 아니라 Luma 내 제공 시작일만 확정해요.",
          content: `**무엇이 바뀌었나**\nLuma가 Seedance 2.5를 서비스에 추가했습니다. Luma 공식 발표 기준 최대 30초 분량의 오디오·비디오를 한 번에 만들고, 최대 50개의 이미지·영상·오디오 참조 입력과 앞뒤 확장, 국소 편집을 지원합니다.\n\n**왜 중요한가**\n기존 영상 생성은 몇 초짜리 조각을 여러 번 만든 뒤 이어 붙이는 경우가 많았습니다. 단일 패스 30초 생성은 인물·조명·동작이 조각 경계에서 흔들리는 문제를 줄일 가능성이 있습니다.\n\n**날짜 경계**\nByteDance의 Seedance 2.5 제품 페이지에서는 기능은 확인되지만 게시일과 API 공개일을 검증하지 못했습니다. 따라서 여기서 확정하는 사건은 **8월 6일 Luma 내 제공 시작**입니다. 원개발사 출시일을 7월 31일로 단정하지 않습니다.`,
          source: "https://lumalabs.ai/news/seedance-2.5-live-in-luma",
          officialUrl: "https://lumalabs.ai/news/seedance-2.5-live-in-luma",
          verifiedAt: "2026-08-13",
          backupUrls: [
            { label: "ByteDance Seedance 2.5 제품 페이지 — 게시일 미표기", url: "https://seed.bytedance.com/en/seedance2_5" },
          ],
          tags: ["Luma", "Seedance", "영상 생성", "멀티모달"],
          slug: "luma-20260806-seedance-2-5-live",
          en: {
            title: "Seedance 2.5 goes live in Luma with 30-second single-pass generation",
            deck: "Up to 50 references and synchronized audio in one generation.",
            summary: "Luma added Seedance 2.5 on August 6. Luma says it generates clips up to 30 seconds in a single pass with synchronized audio, up to 50 references, extensions and localized edits. ByteDance's product page does not expose a verifiable publication date, so this card confirms Luma availability rather than an original model-launch date.",
            content: `**What changed**\nLuma added Seedance 2.5 with up to 30 seconds of audio and video in a single generation, as many as 50 image, video and audio references, extensions and localized edits.\n\n**Why it matters**\nMany video workflows generate short fragments and stitch them together. A 30-second single pass can reduce discontinuities in people, lighting and motion at edit boundaries.\n\n**Date boundary**\nByteDance's product page verifies capabilities but not a publication or API-release date. This card therefore records **availability in Luma on August 6**, not an inferred July 31 model launch.`
          },
          thumbnail: {
            src: "/og-cache/luma에-seedance-2-5-탑재-오디오-포함-30초를-한-번에-생-23804445.jpg",
            alt: "Luma에 Seedance 2.5 탑재, 오디오 포함 30초를 한 번에 생성",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "Luma Scenes, 완성 영상을 뽑기 전에 키프레임부터 고친다",
          deck: "스토리보드·프레임·타이밍을 편집한 뒤 렌더합니다.",
          summary: "Luma가 텍스트와 참조 이미지로 영상을 설계하는 Scenes를 공개했어요. 렌더 전에 스토리보드와 키프레임을 수정하고, 특정 프레임만 다시 만들거나 교체하고 타이밍을 조절한 뒤 Ray 3.2 또는 Seedance 2로 렌더할 수 있어요.",
          content: `**완성본 재생성에서 설계 편집으로**\nScenes는 텍스트와 참조 이미지로 초안을 만든 뒤 스토리보드와 키프레임을 먼저 보여줍니다. 마음에 안 드는 프레임만 다시 만들거나 교체하고 타이밍을 조절한 뒤 전체 영상을 렌더합니다.\n\n**실무 변화**\n프롬프트를 조금씩 바꾸며 전체 영상을 반복 생성하는 대신, 사람이 장면 구조를 먼저 고정하고 생성 모델은 선택된 프레임과 전환을 채우는 방식입니다. 최종 렌더에는 Ray 3.2 또는 Seedance 2를 쓸 수 있습니다.`,
          source: "https://lumalabs.ai/news/introducing-luma-scenes",
          officialUrl: "https://lumalabs.ai/news/introducing-luma-scenes",
          verifiedAt: "2026-08-13",
          tags: ["Luma", "Scenes", "영상 생성", "스토리보드"],
          slug: "luma-20260811-scenes",
          en: {
            title: "Luma introduces Scenes, an editable storyboard-first video workflow",
            deck: "Edit storyboards, keyframes and timing before the final render.",
            summary: "Luma introduced Scenes, a storyboard-first workflow for video creation from text and reference images. Creators can edit keyframes, regenerate or replace individual frames, adjust timing, and then render with Ray 3.2 or Seedance 2.",
            content: `**From regenerating the final clip to editing the plan**\nScenes creates a draft storyboard and keyframes from text and reference images. Creators can regenerate or replace individual frames and adjust timing before rendering the full video.\n\n**Workflow change**\nInstead of repeatedly changing a prompt and regenerating everything, people lock the scene structure first and let the model fill selected frames and transitions. Final rendering supports Ray 3.2 or Seedance 2.`
          },
          thumbnail: {
            src: "/og-cache/luma-scenes-완성-영상을-뽑기-전에-키프레임부터-고친다-41a5ad70.jpg",
            alt: "Luma Scenes, 완성 영상을 뽑기 전에 키프레임부터 고친다",
          },
        },
        {
          date: "8/12",
          platform: "X+Threads",
          title: "Higgsfield Cinema Studio 4.0, 렌즈·조명까지 고르는 AI 영상 스튜디오",
          deck: "최대 30초·50개 레퍼런스, 촬영 조건을 직접 제어합니다.",
          summary: "Higgsfield가 Cinema Studio 4.0을 공개했어요. 공식 발표 기준 최대 30초·720p 출력, 최대 50개 참조 이미지, 렌즈·카메라·조명·색·움직임 제어와 팀 협업 기능을 제공해요. 기능과 품질 설명은 벤더 자체 발표예요.",
          content: `**프롬프트 밖의 촬영 조건**\nCinema Studio 4.0은 최대 30초·720p 출력과 최대 50개 참조 이미지를 지원한다고 밝힙니다. 렌즈, 카메라, 조명, 색, 움직임을 각각 조절하고 팀 단위로 프로젝트를 공유할 수 있습니다.\n\n**어디까지가 사실인가**\n위 기능 범위는 Higgsfield의 공식 제품 발표로 확인했습니다. 품질 우위나 영화 제작 혁신 같은 평가는 독립 비교 결과가 아니라 벤더 설명입니다.`,
          source: "https://higgsfield.ai/blog/cinema-studio-4-0",
          officialUrl: "https://higgsfield.ai/blog/cinema-studio-4-0",
          verifiedAt: "2026-08-13",
          tags: ["Higgsfield", "Cinema Studio", "영상 생성", "크리에이터"],
          slug: "higgsfield-20260812-cinema-studio-4",
          en: {
            title: "Higgsfield launches Cinema Studio 4.0 with camera and lighting controls",
            deck: "Up to 30 seconds, 50 references and explicit production controls.",
            summary: "Higgsfield launched Cinema Studio 4.0 with clips up to 30 seconds at up to 720p, as many as 50 reference images, controls for lens, camera, lighting, color and motion, and team collaboration. The capability and quality descriptions are vendor-reported.",
            content: `**Production controls beyond the prompt**\nCinema Studio 4.0 claims clips up to 30 seconds at 720p and as many as 50 reference images. It exposes controls for lens, camera, lighting, color and motion, plus team collaboration.\n\n**Evidence boundary**\nThe capability list is verified from Higgsfield's official product announcement. Claims of superior quality or transformed filmmaking remain vendor descriptions rather than independent comparisons.`
          },
          thumbnail: {
            src: "/og-cache/higgsfield-cinema-studio-4-0-렌즈-조명까지-고르는-e9624955.jpg",
            alt: "Higgsfield Cinema Studio 4.0, 렌즈·조명까지 고르는 AI 영상 스튜디오",
          },
        },
        {
          date: "8/11",
          platform: "X+Threads",
          title: "watermarks-remover, AI 출처 표식의 약한 고리를 드러내다",
          featured: true,
          deck: "Unicode·메타데이터는 지우지만 SynthID 픽셀 표식은 제거하지 않습니다.",
          summary: "MIT 오픈소스 watermarks-remover가 8월 11일 공개됐어요. 코드와 테스트로 확인되는 범위는 제로폭·양방향 제어문자 같은 Unicode 표식과 PNG·JPEG·SVG·PDF·DOCX·ODT·HTML·Markdown의 일부 C2PA·EXIF·XMP·문서 메타데이터 정리예요. 통계적 텍스트 표식은 재작성 기반 최선 노력이고, SynthID 픽셀 표식은 외부 도구로 점수화만 하며 제거하지 않아요. GitHub API 실측 8월 13일 별 2,981개예요.",
          content: `**무엇을 실제로 지우나**\n코드와 테스트가 직접 다루는 건 제로폭 문자·양방향 제어문자·Unicode 태그·특수 공백과, PNG·JPEG·SVG·PDF·DOCX·ODT·HTML·Markdown에 들어간 일부 C2PA·EXIF·XMP·문서 메타데이터입니다. 저장소는 8월 11일 만들어졌고 MIT 라이선스이며, 8월 13일 GitHub API 실측 별 2,981개였습니다.\n\n**과장하면 안 되는 부분**\n통계적 텍스트 워터마크에는 문장 재작성으로 신호를 약하게 만드는 최선 노력 방식을 쓸 뿐, 공식 탐지기를 통과한다고 보증하지 않습니다. SynthID 픽셀 표식은 외부 reverse-SynthID 도구로 점수화만 하고 **제거하지 않습니다**. 오디오·비디오·픽셀 워터마크와 소프트 바인딩도 지원 범위 밖입니다.\n\n**운영 교훈**\n생성물 감사 절차를 워터마크 한 종류에만 의존하면 안 됩니다. 서명된 원본 보관, 접근 로그, 생성 이력, C2PA, 내용 기반 탐지를 함께 써야 합니다.`,
          source: "https://github.com/guillaumemeyer/watermarks-remover",
          officialUrl: "https://github.com/guillaumemeyer/watermarks-remover",
          verifiedAt: "2026-08-13",
          backupUrls: [
            { label: "LinkedIn 발견 경로", url: "https://www.linkedin.com/feed/update/urn:li:share:7493403130831884289" },
            { label: "초기 릴리스 v0.0.1", url: "https://github.com/guillaumemeyer/watermarks-remover/releases/tag/v0.0.1" },
          ],
          tags: ["오픈소스", "워터마크", "C2PA", "콘텐츠 출처", "보안"],
          slug: "github-20260811-watermarks-remover",
          en: {
            title: "watermarks-remover exposes weak links in AI provenance marks",
            deck: "It cleans Unicode and metadata, but does not remove SynthID pixel marks.",
            summary: "The MIT-licensed watermarks-remover repository appeared on August 11. Its code and tests cover invisible Unicode cleanup and selected C2PA, EXIF, XMP and document metadata in PNG, JPEG, SVG, PDF, DOCX, ODT, HTML and Markdown. Statistical text marks are addressed through best-effort rewriting, while SynthID pixel marks are scored through an external tool and are not removed. GitHub showed 2,981 stars on August 13.",
            content: `**What it actually removes**\nThe code and tests directly handle zero-width and bidirectional controls, Unicode tags and unusual spaces, plus selected C2PA, EXIF, XMP and document metadata in PNG, JPEG, SVG, PDF, DOCX, ODT, HTML and Markdown. The MIT repository was created on August 11 and had 2,981 GitHub stars when measured on August 13.\n\n**Where the headline overreaches**\nFor statistical text watermarks it offers best-effort rewriting and does not guarantee that official detectors will fail. For SynthID pixels, an external reverse-SynthID tool provides scoring only and **does not remove the mark**. Audio, video, pixel watermarks and soft binding are outside scope.\n\n**Operational lesson**\nDo not base provenance audits on one watermark. Combine signed originals, access logs, generation history, C2PA and content-based detection.`
          },
          thumbnail: {
            src: "/og-cache/watermarks-remover-ai-출처-표식의-약한-고리를-드러내다-3c102972.png",
            alt: "watermarks-remover, AI 출처 표식의 약한 고리를 드러내다",
          },
        },
      ],
    },
  ],
};
