import type { WeeklyData } from "../data";

// 2026-w22 (5/22 ~ 5/28)
// 자동 생성: 4라운드 수집 + 5차 prune 기반 archive
// 주차 기준 목~수 (5/15 목 = 새 주차 시작)

export const week22: WeeklyData = {
  week: 22,
  year: 2026,
  slug: "2026-w22",
  period: "5/22 ~ 5/28",
  totalPosts: 45,
  companies: [
    {
      name: "OpenAI",
      color: "#10A37F",
      posts: [
        {
          date: "5/23",
          platform: "X+Threads",
          title: "OpenAI Codex Goal mode generally available",
          summary: "",
          officialUrl: "https://help.openai.com/en/articles/6825453-chatgpts-release-notes",
          source: "https://help.openai.com/en/articles/6825453-chatgpts-release-notes",
          tags: ["Codex", "Goal mode", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "OpenAI named a Leader in enterprise coding agents by Gartner",
          summary: "",
          officialUrl: "https://openai.com/index/gartner-2026-agentic-coding-leader",
          source: "https://openai.com/index/gartner-2026-agentic-coding-leader",
          tags: ["Codex", "Enterprise coding agents", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "How Virgin Atlantic ships faster with Codex",
          summary: "",
          officialUrl: "https://openai.com/index/virgin-atlantic",
          source: "https://openai.com/index/virgin-atlantic",
          tags: ["Codex", "enterprise adoption", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "Work with Codex from anywhere — Codex in ChatGPT mobile",
          summary: "3차 보고서에는 TechCrunch만 있었는데 OpenAI 공식 index 게시물이 정확히 있음. 공식 URL로 교체.",
          officialUrl: "https://openai.com/index/work-with-codex-from-anywhere/",
          source: "https://openai.com/index/work-with-codex-from-anywhere/",
          tags: ["Codex", "ChatGPT mobile", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "Introducing the Codex app, Skills, and Automations",
          summary: "",
          officialUrl: "https://openai.com/index/introducing-the-codex-app/",
          source: "https://openai.com/index/introducing-the-codex-app/",
          tags: ["Codex app", "Skills", "Automations", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "OpenAI Codex remote connections (official X post)",
          summary: "",
          officialUrl: "https://x.com/OpenAI/status/2055016850849993072",
          source: "https://x.com/OpenAI/status/2055016850849993072",
          tags: ["Codex", "remote connections", "공식"],
        },
      ],
    },
    {
      name: "Google",
      color: "#4285F4",
      posts: [
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Google Gemini Intelligence on Android",
          summary: "",
          officialUrl: "https://blog.google/products-and-platforms/platforms/android/gemini-intelligence/",
          source: "https://blog.google/products-and-platforms/platforms/android/gemini-intelligence/",
          tags: ["Gemini", "Android", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Google AI Mode ads: Gemini-built ad formats in Search",
          summary: "",
          officialUrl: "https://blog.google/products/ads-commerce/google-marketing-live-search-ads/",
          source: "https://blog.google/products/ads-commerce/google-marketing-live-search-ads/",
          tags: ["Google Search", "AI Mode", "Ads", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "Google Gemini in Chrome (YouTube help curation)",
          summary: "",
          officialUrl: "https://help.youtube.com/intl/en_sg/chrome/ai-innovations/",
          source: "https://help.youtube.com/intl/en_sg/chrome/ai-innovations/",
          tags: ["Gemini", "Chrome", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "Google DeepMind AI Pointer",
          summary: "",
          officialUrl: "https://deepmind.google/blog/ai-pointer/",
          source: "https://deepmind.google/blog/ai-pointer/",
          tags: ["Google DeepMind", "AI Pointer", "공식"],
        },
      ],
    },
    {
      name: "Anthropic / Claude",
      color: "#E87040",
      posts: [
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Claude for Creative Work — connectors",
          summary: "",
          officialUrl: "https://www.anthropic.com/news/claude-for-creative-work",
          source: "https://www.anthropic.com/news/claude-for-creative-work",
          tags: ["Claude", "creative", "connectors", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Anthropic Claude limits and SpaceX compute capacity",
          summary: "",
          officialUrl: "https://www.anthropic.com/news/higher-limits-spacex",
          source: "https://www.anthropic.com/news/higher-limits-spacex",
          tags: ["Claude", "compute capacity", "SpaceX", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "Project Glasswing: An initial update",
          summary: "Anthropic reported early Project Glasswing results, including partner discovery of more than 10,000 high/critical vulnerabilities.",
          officialUrl: "https://www.anthropic.com/research/glasswing-initial-update",
          source: "https://www.anthropic.com/research/glasswing-initial-update",
          tags: ["Project Glasswing", "security", "Claude Mythos Preview", "공식"],
        },
      ],
    },
    {
      name: "NVIDIA",
      color: "#76B900",
      posts: [
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Towards Speed-of-Light Text Generation with Nemotron-Labs Diffusion Language Models",
          summary: "NVIDIA introduced a diffusion language model approach for faster text generation through the Hugging Face Blog.",
          officialUrl: "https://huggingface.co/blog/nvidia/nemotron-labs-diffusion",
          source: "https://huggingface.co/blog/nvidia/nemotron-labs-diffusion",
          tags: ["NVIDIA Nemotron", "diffusion language models", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "NVIDIA Nemotron 3 Nano Omni long-context multimodal model",
          summary: "",
          officialUrl: "https://huggingface.co/blog/nvidia/nemotron-3-nano-omni-multimodal-intelligence",
          source: "https://huggingface.co/blog/nvidia/nemotron-3-nano-omni-multimodal-intelligence",
          tags: ["NVIDIA Nemotron", "multimodal", "long-context", "공식"],
        },
      ],
    },
    {
      name: "Cursor / Anysphere",
      color: "#374151",
      posts: [
        {
          date: "5/22",
          platform: "X+Threads",
          title: "Cursor 3.5.17 Keep/Undo community issue",
          summary: "공식 forum 스레드. 사용자 영향이 크지만 회사 공식 changelog는 아님.",
          officialUrl: "https://forum.cursor.com/t/cursor-3-5-17-removed-keep-undo-and-applies-agent-changes-directly/161325",
          source: "https://forum.cursor.com/t/cursor-3-5-17-removed-keep-undo-and-applies-agent-changes-directly/161325",
          tags: ["Cursor", "3.5.17", "UX regression", "공식"],
        },
      ],
    },
    {
      name: "Vercel",
      color: "#000000",
      posts: [
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Vercel AI Gateway production index — agentic workloads & multi-model routing",
          summary: "",
          officialUrl: "https://vercel.com/blog/ai-gateway-production-index",
          source: "https://vercel.com/blog/ai-gateway-production-index",
          tags: ["Vercel AI Gateway", "agentic workloads", "공식"],
        },
      ],
    },
    {
      name: "오픈소스 / 도구",
      color: "#6B7280",
      posts: [
        {
          date: "5/25",
          platform: "X+Threads",
          title: "Thinking Machines Interaction Models — official demo + blog",
          summary: "",
          officialUrl: "https://thinkingmachines.ai/blog/interaction-models/",
          source: "https://thinkingmachines.ai/blog/interaction-models/",
          tags: ["Thinking Machines", "interaction models", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/24",
          platform: "X+Threads",
          title: "builderpepc/agent-migrator — AI 코딩 세션을 도구 간 마이그레이션하는 오픈소스. Claude Code/Codex/Cursor 사이 컨텍스트 이전 시나리오.",
          summary: "AI 코딩 세션을 도구 간 마이그레이션하는 오픈소스. Claude Code/Codex/Cursor 사이 컨텍스트 이전 시나리오.",
          officialUrl: "https://github.com/builderpepc/agent-migrator",
          source: "https://github.com/builderpepc/agent-migrator",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/24",
          platform: "X+Threads",
          title: "Peter Steinberger cmux + Codex CLI workflow split",
          summary: "cmux 다중 pane + Codex CLI 작업 분할 패턴.",
          officialUrl: "https://github.com/manaflow-ai/cmux",
          source: "https://github.com/manaflow-ai/cmux",
          tags: ["실전 팁", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "OpenAI models, Codex, and Managed Agents on Amazon Bedrock",
          summary: "",
          officialUrl: "https://openai.com/index/openai-on-aws/",
          source: "https://openai.com/index/openai-on-aws/",
          tags: ["OpenAI", "AWS Bedrock", "Managed Agents", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "PaddleOCR 3.5 Transformers backend",
          summary: "",
          officialUrl: "https://huggingface.co/blog/PaddlePaddle/paddleocr-transformers",
          source: "https://huggingface.co/blog/PaddlePaddle/paddleocr-transformers",
          tags: ["PaddleOCR", "Transformers", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Dharma-AI specialization beats scale OCR benchmark",
          summary: "",
          officialUrl: "https://huggingface.co/blog/Dharma-AI/specialization-beats-scale",
          source: "https://huggingface.co/blog/Dharma-AI/specialization-beats-scale",
          tags: ["OCR", "specialization", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "DeepInfra on Hugging Face Inference Providers",
          summary: "",
          officialUrl: "https://huggingface.co/blog/inference-providers-deepinfra",
          source: "https://huggingface.co/blog/inference-providers-deepinfra",
          tags: ["Hugging Face", "DeepInfra", "Inference Providers", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "OlmoEarth v1.1 efficient Earth observation AI models",
          summary: "",
          officialUrl: "https://huggingface.co/blog/allenai/olmoearth-v1-1",
          source: "https://huggingface.co/blog/allenai/olmoearth-v1-1",
          tags: ["AllenAI", "Earth observation", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Granite Embedding Multilingual R2",
          summary: "",
          officialUrl: "https://huggingface.co/blog/ibm-granite/granite-embedding-multilingual-r2",
          source: "https://huggingface.co/blog/ibm-granite/granite-embedding-multilingual-r2",
          tags: ["IBM Granite", "embedding", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Hugging Face asynchronous continuous batching",
          summary: "",
          officialUrl: "https://huggingface.co/blog/continuous_async",
          source: "https://huggingface.co/blog/continuous_async",
          tags: ["Hugging Face", "inference", "batching", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "IBM Granite 4.1 LLMs training pipeline",
          summary: "",
          officialUrl: "https://huggingface.co/blog/ibm-granite/granite-4-1",
          source: "https://huggingface.co/blog/ibm-granite/granite-4-1",
          tags: ["IBM Granite 4.1", "training", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "AWS foundation model training and inference building blocks",
          summary: "",
          officialUrl: "https://huggingface.co/blog/amazon/foundation-model-building-blocks",
          source: "https://huggingface.co/blog/amazon/foundation-model-building-blocks",
          tags: ["AWS", "foundation model", "training", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "vLLM V0 to V1 RL backend correctness",
          summary: "",
          officialUrl: "https://huggingface.co/blog/ServiceNow-AI/correctness-before-corrections",
          source: "https://huggingface.co/blog/ServiceNow-AI/correctness-before-corrections",
          tags: ["vLLM", "RLHF", "correctness", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Open ASR Leaderboard private evaluation sets",
          summary: "",
          officialUrl: "https://huggingface.co/blog/open-asr-leaderboard-private-data",
          source: "https://huggingface.co/blog/open-asr-leaderboard-private-data",
          tags: ["Open ASR Leaderboard", "evaluation", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "manaflow-ai/cmux — Peter Steinberger가 소개한 Codex CLI 워크플로우 분할용 tmux 보조 도구. 본인이 cmux/cmuxr 하네스 사용자라 직",
          summary: "Peter Steinberger가 소개한 Codex CLI 워크플로우 분할용 tmux 보조 도구. 본인이 cmux/cmuxr 하네스 사용자라 직접 와닿는 후보.",
          officialUrl: "https://github.com/manaflow-ai/cmux",
          source: "https://github.com/manaflow-ai/cmux",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "allenai/OlmoEarth v1.1 — Earth observation을 위한 경량 오픈 모델.",
          summary: "Earth observation을 위한 경량 오픈 모델.",
          officialUrl: "https://huggingface.co/blog/allenai/olmoearth-v1-1",
          source: "https://huggingface.co/blog/allenai/olmoearth-v1-1",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "IBM Granite 4.1 — IBM의 오픈 LLM 라인업 4.1 학습 파이프라인 공개.",
          summary: "IBM의 오픈 LLM 라인업 4.1 학습 파이프라인 공개.",
          officialUrl: "https://huggingface.co/blog/ibm-granite/granite-4-1",
          source: "https://huggingface.co/blog/ibm-granite/granite-4-1",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "vLLM RL backend correctness (ServiceNow) — vLLM RL 학습 backend의 V0→V1 정합성 정리.",
          summary: "vLLM RL 학습 backend의 V0→V1 정합성 정리.",
          officialUrl: "https://huggingface.co/blog/ServiceNow-AI/correctness-before-corrections",
          source: "https://huggingface.co/blog/ServiceNow-AI/correctness-before-corrections",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "HF continuous async batching — HF inference 비동기 연속 배치 처리 가이드.",
          summary: "HF inference 비동기 연속 배치 처리 가이드.",
          officialUrl: "https://huggingface.co/blog/continuous_async",
          source: "https://huggingface.co/blog/continuous_async",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "IBM Granite Embedding Multilingual R2 — 오픈 다국어 임베딩 모델 R2.",
          summary: "오픈 다국어 임베딩 모델 R2.",
          officialUrl: "https://huggingface.co/blog/ibm-granite/granite-embedding-multilingual-r2",
          source: "https://huggingface.co/blog/ibm-granite/granite-embedding-multilingual-r2",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "PaddleOCR 3.5 Transformers — PaddleOCR을 Transformers 백엔드로 실행하는 가이드.",
          summary: "PaddleOCR을 Transformers 백엔드로 실행하는 가이드.",
          officialUrl: "https://huggingface.co/blog/PaddlePaddle/paddleocr-transformers",
          source: "https://huggingface.co/blog/PaddlePaddle/paddleocr-transformers",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "2026-05 (multiple)",
          platform: "X+Threads",
          title: "tw93/Mole — macOS deep clean & optimize CLI. 2026-05 업데이트로 Claude Code, Cursor Agent, GitHub",
          summary: "macOS deep clean & optimize CLI. 2026-05 업데이트로 Claude Code, Cursor Agent, GitHub Copilot CLI, Codex CLI 등 AI agent CLI 런타임/세션 로그 정리 커버리지 추가. tw93 작가의 다른 작품(이미 사용 중인 tw93/kami)과 같은 라인. AI 개발자에게 실용적인 cleanup 도구.",
          officialUrl: "https://github.com/tw93/Mole",
          source: "https://github.com/tw93/Mole",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Claude Code context management — /compact vs /clear",
          summary: "세션 컨텍스트 관리 실전 팁.",
          officialUrl: "https://www.youtube.com/watch?v=eW3oTyfeWZ0",
          source: "https://www.youtube.com/watch?v=eW3oTyfeWZ0",
          tags: ["실전 팁", "공식"],
        },
        {
          date: "5/23",
          platform: "X+Threads",
          title: "Jensen Huang CMU commencement — AI jobs message",
          summary: "AI 시대 일자리에 대한 NVIDIA CEO 졸업 연설.",
          officialUrl: "https://www.youtube.com/watch?v=uSs7PPAJR20",
          source: "https://www.youtube.com/watch?v=uSs7PPAJR20",
          tags: ["실전 팁", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "Qwen3.7-Max official benchmark / model card",
          summary: "3차 보고서는 Vercel AI Gateway 항목으로만 다뤘는데 Qwen 본체 공식 발표가 별도로 존재.",
          officialUrl: "https://qwen.ai/blog?id=qwen3.7",
          source: "https://qwen.ai/blog?id=qwen3.7",
          tags: ["Qwen", "Alibaba", "frontier model", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "GPT Image API: n parameter usage tip",
          summary: "",
          officialUrl: "https://platform.openai.com/docs/api-reference/images",
          source: "https://platform.openai.com/docs/api-reference/images",
          tags: ["OpenAI API", "Images", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "jamiepine/voicebox — 오픈소스 음성 도구.",
          summary: "오픈소스 음성 도구.",
          officialUrl: "https://github.com/jamiepine/voicebox",
          source: "https://github.com/jamiepine/voicebox",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/22",
          platform: "X+Threads",
          title: "AI prompt usage: method-first prompting",
          summary: "방법론을 먼저 제시하는 프롬프트 스타일.",
          officialUrl: "https://www.instagram.com/p/DYCDIvelD5p/",
          source: "https://www.instagram.com/p/DYCDIvelD5p/",
          tags: ["실전 팁", "공식"],
        },
      ],
    },
  ],
};
