// Week 16 (2026-04-13 ~ 2026-04-22)
// Generated from AI & Beyond Biweekly RAG Top32 (공식 출처 교차검증 완료)
// - 50건 수집 → 19건 제거(완전 불일치 6 + 검증 불가 13) → 16건 수정 → 1건 추가(GPT Image 2.0)
// - 최종 32건, 모두 공식 페이지 200 OK (i51만 TechCrunch 준공식)
// Source: /Users/voidlight/_workspace/ai-beyond-biweekly/config/top50_final_verified.yaml

import type { WeeklyData } from "../data";

export const week16: WeeklyData = {
  week: 16,
  year: 2026,
  slug: "2026-w16",
  period: "4/13 ~ 4/23",
  totalPosts: 37,
  companies: [
    {
      name: "Anthropic / Claude",
      color: "#E87040",
      posts: [
        {
          date: "4/18",
          platform: "X",
          title: "Built with Opus 4.7 — Claude Code 해커톤 (Cerebral Valley)",
          summary: "Cerebral Valley에서 주최하는 Claude Opus 4.7 중심 해커톤. 페이지에 구체 일자 미명시. 모델 활용이 주요 테마.",
          content: "Cerebral Valley에서 주최하는 Claude Opus 4.7 중심 해커톤. 페이지에 구체 일자 미명시. 모델 활용이 주요 테마.",
          officialUrl: "https://cerebralvalley.ai/e/built-with-4-7-hackathon",
          source: "https://cerebralvalley.ai/e/built-with-4-7-hackathon",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/claudeai/status/2045248224659644654" }],
          tags: ["수익화사례", "code", "anthropic"],
        },
        {
          date: "4/18",
          platform: "X",
          title: "Claude Design 시스템 프롬프트 유출 — 422줄·약 5천 단어 GitHub 공개",
          summary: "elder-plinius/CL4R1T4S 저장소에 ANTHROPIC/Claude-Design-Sys-Prompt.txt 공개. \"You are an expert designer working with the user as a manager\"로 시작. 422줄/약 71KB.",
          content: "elder-plinius/CL4R1T4S 저장소에 ANTHROPIC/Claude-Design-Sys-Prompt.txt 공개. \"You are an expert designer working with the user as a manager\"로 시작. 422줄/약 71KB.",
          officialUrl: "https://github.com/elder-plinius/CL4R1T4S/blob/main/ANTHROPIC/Claude-Design-Sys-Prompt.txt",
          source: "https://github.com/elder-plinius/CL4R1T4S/blob/main/ANTHROPIC/Claude-Design-Sys-Prompt.txt",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/elder_plinius/status/2045185728093921280" }, { label: "GitHub", url: "https://github.com/asgeirtj/system_prompts_leaks" }, { label: "GitHub", url: "https://github.com/Piebald-AI/claude-code-system-prompts" }],
          tags: ["프롬프트디자인", "text", "anthropic", "community"],
        },
        {
          date: "4/17",
          platform: "X",
          title: "Claude Design 공개 — 프롬프트로 프로토타입·슬라이드·원페이지 생성 + Claude Code 핸드오프",
          featured: true,
          summary: "Figma 주가 -7.28%, Adobe 동반 하락. 팀 디자인 시스템 자동 적용. Canva/PDF/PPTX/HTML 내보내기. Pro·Max·Team·Enterprise 리서치 프리뷰.",
          content: "Figma 주가 -7.28%, Adobe 동반 하락. 팀 디자인 시스템 자동 적용. Canva/PDF/PPTX/HTML 내보내기. Pro·Max·Team·Enterprise 리서치 프리뷰.",
          officialUrl: "https://www.anthropic.com/news/claude-design-anthropic-labs",
          source: "https://www.anthropic.com/news/claude-design-anthropic-labs",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/claudeai/status/2045156267690213649" }, { label: "venturebeat.com", url: "https://venturebeat.com/technology/anthropic-just-launched-claude-design-an-ai-tool-that-turns-prompts-into-prototypes-and-challenges-figma" }, { label: "techcrunch.com", url: "https://techcrunch.com/2026/04/17/anthropic-launches-claude-design-a-new-product-for-creating-quick-visuals/" }],
          tags: ["워크플로우", "text", "image", "code", "anthropic"],
        },
        {
          date: "4/16",
          platform: "X",
          title: "Claude Opus 4.7 정식 출시 — Agentic Coding step-change + xhigh/task budget/1M ctx/2576px 비전",
          featured: true,
          summary: "현존 가장 강력한 generally-available 모델 (API ID: claude-opus-4-7). 1M 토큰 컨텍스트·128k 출력·$5/$25 가격 동결. xhigh 노력 수준, task budget 베타, /ultrareview 슬래시 커맨드, 2576px 고해상도 비전. (공식 SWE-Bench 수치 미기재",
          content: "현존 가장 강력한 generally-available 모델 (API ID: claude-opus-4-7). 1M 토큰 컨텍스트·128k 출력·$5/$25 가격 동결. xhigh 노력 수준, task budget 베타, /ultrareview 슬래시 커맨드, 2576px 고해상도 비전. (공식 SWE-Bench 수치 미기재)",
          officialUrl: "https://www.anthropic.com/news/claude-opus-4-7",
          source: "https://www.anthropic.com/news/claude-opus-4-7",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/claudeai/status/2044785261393977612" }, { label: "Anthropic 공식", url: "https://platform.claude.com/docs/en/about-claude/models/whats-new-claude-4-7" }, { label: "Anthropic 공식", url: "https://www.anthropic.com/claude/opus" }],
          tags: ["도구릴리스", "text", "code", "anthropic"],
        },
        {
          date: "4/14",
          platform: "X",
          title: "Claude Code 데스크탑 앱 재설계 — 멀티 세션 사이드바 + 통합 터미널 + Diff 뷰어",
          featured: true,
          summary: "VS Code 플러그인 없이 IDE급. Cmd+; 사이드 챗, 드래그앤드롭 워크스페이스, HTML/PDF 프리뷰. Pro·Max·Team·Enterprise 롤아웃.",
          content: "VS Code 플러그인 없이 IDE급. Cmd+; 사이드 챗, 드래그앤드롭 워크스페이스, HTML/PDF 프리뷰. Pro·Max·Team·Enterprise 롤아웃.",
          officialUrl: "https://claude.com/blog/claude-code-desktop-redesign",
          source: "https://claude.com/blog/claude-code-desktop-redesign",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/claudeai/status/2044131493966909862" }, { label: "venturebeat.com", url: "https://venturebeat.com/orchestration/we-tested-anthropics-redesigned-claude-code-desktop-app-and-routines-heres-what-enterprises-should-know" }, { label: "Anthropic 공식", url: "https://code.claude.com/docs/en/whats-new" }],
          tags: ["도구릴리스", "code", "anthropic"],
        },
        {
          date: "4/14",
          platform: "X",
          title: "Claude Code Routines — 스케줄·API·GitHub 트리거 클라우드 자동화",
          featured: true,
          summary: "매일 PR 리뷰, 야간 테스트, GitHub 이벤트 기반 자동 실행. Pro 5/일, Max 15/일. 멤버 자동화 워크플로 핵심.",
          content: "매일 PR 리뷰, 야간 테스트, GitHub 이벤트 기반 자동 실행. Pro 5/일, Max 15/일. 멤버 자동화 워크플로 핵심.",
          officialUrl: "https://claude.com/blog/introducing-routines-in-claude-code",
          source: "https://claude.com/blog/introducing-routines-in-claude-code",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/claudeai/status/2044095086460309790" }, { label: "Anthropic 공식", url: "https://code.claude.com/docs/en/routines" }, { label: "findskill.ai", url: "https://findskill.ai/blog/claude-code-routines-setup-guide/" }],
          tags: ["에이전트자동화", "code", "anthropic"],
        },
      ],
    },
    {
      name: "OpenAI",
      color: "#10A37F",
      posts: [
        {
          date: "4/22",
          platform: "X",
          title: "GPT Image 2.0 (gpt-image-2) 출시 — Arena 1512점 1위 + \"구스 벤치마크\" 통과",
          featured: true,
          summary: "🧪 구스 벤치마크(Goose Benchmark): 제가 좋아하는 마블 캐릭터 \"구스(Goose)\"를 덕테이프로 감싼 실사 이미지 테스트. Captain Marvel에 등장하는 Flerken(외계 고양이)이라는 가상 생물인데, GPT Image 2.0이 처음으로 실사 스타일로 정확히 표현해냈습니다. 실존하지 않는 상상의 매",
          content: "🧪 구스 벤치마크(Goose Benchmark): 제가 좋아하는 마블 캐릭터 \"구스(Goose)\"를 덕테이프로 감싼 실사 이미지 테스트. Captain Marvel에 등장하는 Flerken(외계 고양이)이라는 가상 생물인데, GPT Image 2.0이 처음으로 실사 스타일로 정확히 표현해냈습니다. 실존하지 않는 상상의 매개체일수록 AI 이미지 모델이 취약해지는 약점을 일부러 겨냥한 프롬프트였는데, 이번 모델이 그 한계를 제대로 돌파했습니다. ── ChatGPT + Codex 전 사용자 공개. 2K 해상도, 텍스트·아이콘·UI 요소 렌더링 강화. 한국어·일본어·힌디어·벵골어 등 비라틴 문자 렌더링 개선. 【Text-to-Image Arena 2026-04-19】 gpt-image-2 (medium) 1512±8점 1위 (15,127 votes) — 2위 Gemini 3.1 Flash Image (1270) 대비 +242, 전임 gpt-image-1.5 (1241) 대비 +271.",
          officialUrl: "https://techcrunch.com/2026/04/21/chatgpts-new-images-2-0-model-is-surprisingly-good-at-generating-text/",
          source: "https://techcrunch.com/2026/04/21/chatgpts-new-images-2-0-model-is-surprisingly-good-at-generating-text/",
          backupUrls: [
            { label: "Arena 벤치마크", url: "https://arena.ai/leaderboard/text-to-image" },
            { label: "GPT Image 2.0 아카이브 (제작)", url: "https://gptimage2-0.vercel.app/" },
          ],
          tags: ["도구릴리스", "image", "text", "openai"],
        },
        {
          date: "4/19",
          platform: "X",
          title: "GPT-5.5 (코드네임 Spud) 출시 임박 — Polymarket 4/23 92% (2026-04-22 기준)",
          summary: "Polymarket \"GPT-5.5 released by...?\" 이벤트. 4/23 옵션 92%, 4/30 98%, 6/30 99%. 총 거래량 $932k. Spud 코드네임 사전학습 3/24 완료 루머.",
          content: "Polymarket \"GPT-5.5 released by...?\" 이벤트. 4/23 옵션 92%, 4/30 98%, 6/30 99%. 총 거래량 $932k. Spud 코드네임 사전학습 3/24 완료 루머.",
          officialUrl: "https://polymarket.com/event/gpt-5pt5-released-by",
          source: "https://polymarket.com/event/gpt-5pt5-released-by",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/Polymarket/status/2045616553308147936" }, { label: "tokenmix.ai", url: "https://tokenmix.ai/blog/gpt-5-5-release-date-spud" }],
          tags: ["도구릴리스", "text", "image", "audio", "openai", "polymarket"],
        },
      ],
    },
    {
      name: "Google / DeepMind",
      color: "#4285F4",
      posts: [
        {
          date: "4/23",
          platform: "X",
          title: "Google Gemini Enterprise Agent Platform — Vertex AI 진화판, 200+ 모델 에이전트 빌드/거버넌스 (Cloud Next '26, 4/23)",
          featured: true,
          summary: "Vertex AI의 진화판. Build(Agent Studio·ADK) + Scale(Agent Runtime·Memory Bank·멀티데이 워크플로우) + Govern(Agent Identity·Registry·Gateway·Model Armor) + Optimize(Simulation·Evaluation·Observa",
          content: "Vertex AI의 진화판. Build(Agent Studio·ADK) + Scale(Agent Runtime·Memory Bank·멀티데이 워크플로우) + Govern(Agent Identity·Registry·Gateway·Model Armor) + Optimize(Simulation·Evaluation·Observability) 4축 통합 플랫폼. Gemini 3.1 Pro, Gemma 4, Claude Opus/Sonnet/Haiku 등 200+ 모델 지원. Burns & McDonnell, Comcast, PayPal, L'Oréal 실제 배포. 저자: Michael Gerstenhaber (VP Cloud AI) & Michael Bachman.",
          officialUrl: "https://cloud.google.com/blog/products/ai-machine-learning/introducing-gemini-enterprise-agent-platform",
          source: "https://cloud.google.com/blog/products/ai-machine-learning/introducing-gemini-enterprise-agent-platform",
          backupUrls: [{ label: "Google Cloud", url: "https://console.cloud.google.com/agent-platform/overview" }, { label: "Google Cloud", url: "https://docs.cloud.google.com/gemini-enterprise-agent-platform" }],
          tags: ["에이전트자동화", "text", "code", "google"],
        },
        {
          date: "4/23",
          platform: "X",
          title: "Google Workspace Intelligence — 메일·채팅·파일·프로젝트 AI 맥락 통합 + Ask Gemini in Chat (Cloud Next '26, 4/23)",
          featured: true,
          summary: "Workspace 전반의 분산된 이메일·채팅·파일을 연결해 \"unified real-time understanding for agentic work\"를 제공하는 신규 레이어. Ask Gemini in Chat (태스크 관리), Sheets/Docs/Slides 자연어 생성, AI Inbox (이메일 우선순위 자동화). 데",
          content: "Workspace 전반의 분산된 이메일·채팅·파일을 연결해 \"unified real-time understanding for agentic work\"를 제공하는 신규 레이어. Ask Gemini in Chat (태스크 관리), Sheets/Docs/Slides 자연어 생성, AI Inbox (이메일 우선순위 자동화). 데이터는 사용자 소유, Workspace 인프라 내 처리, 관리자 거버넌스 통제. 일부 기능 수주 내 롤아웃, 일부는 프리뷰. 저자: Yulie Kwon Kim.",
          officialUrl: "https://workspace.google.com/blog/product-announcements/introducing-workspace-intelligence",
          source: "https://workspace.google.com/blog/product-announcements/introducing-workspace-intelligence",
          backupUrls: [{ label: "Workspace", url: "https://workspace.google.com/blog/" }],
          tags: ["워크플로우", "text", "google"],
        },
        {
          date: "4/17",
          platform: "X",
          title: "Gemini App for Mac 출시 — 네이티브 데스크탑 앱 (Option+Space 단축키)",
          summary: "Drive/NotebookLM/Photos 통합. 모든 지원 국가/언어 무료. macOS 15+. 크로스 디바이스 히스토리 동기화.",
          content: "Drive/NotebookLM/Photos 통합. 모든 지원 국가/언어 무료. macOS 15+. 크로스 디바이스 히스토리 동기화.",
          officialUrl: "https://blog.google/innovation-and-ai/products/gemini-app/gemini-app-now-on-mac-os/",
          source: "https://blog.google/innovation-and-ai/products/gemini-app/gemini-app-now-on-mac-os/",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/GeminiApp/status/2044445911716090212" }, { label: "gemini.google", url: "https://gemini.google/mac/" }, { label: "workspaceupdates.googleblog.com", url: "https://workspaceupdates.googleblog.com/2026/04/now-available-gemini-app-for-mac.html" }],
          tags: ["도구릴리스", "text", "image", "video", "audio", "google"],
        },
        {
          date: "4/15",
          platform: "X",
          title: "Gemini Robotics-ER 1.6 공개 — 계기판 판독 + 공간 추론 대폭 향상",
          summary: "Boston Dynamics Spot 협업. 아날로그 게이지, 문 열림, 온도 판독. agentic vision(시각추론+코드실행). Gemini API·AI Studio.",
          content: "Boston Dynamics Spot 협업. 아날로그 게이지, 문 열림, 온도 판독. agentic vision(시각추론+코드실행). Gemini API·AI Studio.",
          officialUrl: "https://deepmind.google/blog/gemini-robotics-er-1-6/",
          source: "https://deepmind.google/blog/gemini-robotics-er-1-6/",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/GoogleDeepMind/status/2044069878781390929" }, { label: "blog.google", url: "https://blog.google/innovation-and-ai/models-and-research/google-deepmind/gemini-robotics-er-1-6/" }, { label: "deepmind.google", url: "https://deepmind.google/models/gemini-robotics/gemini-robotics-er/" }],
          tags: ["도구릴리스", "robotics", "image", "google"],
        },
        {
          date: "4/14",
          platform: "X",
          title: "Chrome Skills — Gemini 프롬프트 저장·재사용 슬래시 커맨드",
          featured: true,
          summary: "슬래시(/)로 호출, 기기간 동기화. 무료, 유료 AI 구독 불필요. Skill 실행 시 calendar/이메일 작업은 사용자 확인 게이트.",
          content: "슬래시(/)로 호출, 기기간 동기화. 무료, 유료 AI 구독 불필요. Skill 실행 시 calendar/이메일 작업은 사용자 확인 게이트.",
          officialUrl: "https://blog.google/products-and-platforms/products/chrome/skills-in-chrome/",
          source: "https://blog.google/products-and-platforms/products/chrome/skills-in-chrome/",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/googlechrome/status/2043960122734821847" }, { label: "techcrunch.com", url: "https://techcrunch.com/2026/04/14/google-adds-ai-skills-to-chrome-to-help-you-save-favorite-workflows/" }, { label: "9to5google.com", url: "https://9to5google.com/2026/04/14/gemini-in-chrome-skills/" }],
          tags: ["프롬프트디자인", "text", "google"],
        },
      ],
    },
    {
      name: "Cursor",
      color: "#374151",
      posts: [
        {
          date: "4/2",
          platform: "X",
          title: "Cursor 3 + Composer 2 (4/2) — 에이전트 우선 UX + 멀티 에이전트",
          summary: "로컬·클라우드·SSH·worktree 병렬 에이전트. Composer 2 $0.50/$2.50 per 1M 토큰. 사이드바 통합 Slack·GitHub·Linear 세션.",
          content: "로컬·클라우드·SSH·worktree 병렬 에이전트. Composer 2 $0.50/$2.50 per 1M 토큰. 사이드바 통합 Slack·GitHub·Linear 세션.",
          officialUrl: "https://cursor.com/blog/cursor-3",
          source: "https://cursor.com/blog/cursor-3",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/cursor_ai/status/2042935487183924091" }, { label: "cursor.com", url: "https://cursor.com/changelog/3-0" }, { label: "cursor.com", url: "https://cursor.com/blog/2-0" }],
          tags: ["도구릴리스", "code", "cursor"],
        },
      ],
    },
    {
      name: "로컬 AI / 하드웨어",
      color: "#8B5CF6",
      posts: [
        {
          date: "4/22",
          platform: "X",
          title: "Qwen3.6-27B Dense — SWE-Bench Verified 77.2%, 262K 컨텍스트 (Apache-2.0, 4/22)",
          featured: true,
          summary: "Qwen3.6 시리즈의 Dense 27B 모델 (hidden 5120, 64 layers). 35B-A3B MoE와 병렬 공개. SWE-Bench Verified 77.2%, Terminal-Bench 2.0 59.3%, AIME26 94.1%, GPQA Diamond 87.8%. 262K 토큰 네이티브 지원, Agent",
          content: "Qwen3.6 시리즈의 Dense 27B 모델 (hidden 5120, 64 layers). 35B-A3B MoE와 병렬 공개. SWE-Bench Verified 77.2%, Terminal-Bench 2.0 59.3%, AIME26 94.1%, GPQA Diamond 87.8%. 262K 토큰 네이티브 지원, Agentic Coding + Thinking Preservation + 비전-언어 통합. Apache-2.0 오픈소스. FP8 변형 동시 공개.",
          officialUrl: "https://huggingface.co/Qwen/Qwen3.6-27B",
          source: "https://huggingface.co/Qwen/Qwen3.6-27B",
          backupUrls: [{ label: "GitHub", url: "https://github.com/QwenLM/Qwen3.6" }, { label: "HuggingFace", url: "https://huggingface.co/Qwen/Qwen3.6-27B-FP8" }],
          tags: ["도구릴리스", "text", "code", "image", "alibaba"],
        },
        {
          date: "4/20",
          platform: "X",
          title: "Kimi K2.6 (Moonshot) — 1T MoE 멀티모달 + Agent Swarm 300 sub-agents (Modified MIT, 4/20)",
          featured: true,
          summary: "Moonshot AI의 플래그십. 1T 총 파라미터 / 32B activated, 384 전문가(토큰당 8개 선택) MoE. MoonViT 비전 인코더(400M) 네이티브 멀티모달, 256K 컨텍스트. K2.5 대비: SWE-Bench Pro 58.6 (+7.9), HLE w/tools 54.0 (+3.8), Browse",
          content: "Moonshot AI의 플래그십. 1T 총 파라미터 / 32B activated, 384 전문가(토큰당 8개 선택) MoE. MoonViT 비전 인코더(400M) 네이티브 멀티모달, 256K 컨텍스트. K2.5 대비: SWE-Bench Pro 58.6 (+7.9), HLE w/tools 54.0 (+3.8), BrowseComp Agent Swarm 86.3 (+11.4), AIME 2026 96.4. 신규 역량: Agent Swarm 300 sub-agents·4000 coordinated steps, 24/7 자율 백그라운드 실행. Modified MIT 라이선스 오픈소스.",
          officialUrl: "https://huggingface.co/moonshotai/Kimi-K2.6",
          source: "https://huggingface.co/moonshotai/Kimi-K2.6",
          backupUrls: [{ label: "Moonshot 공식", url: "https://moonshot.cn/" }, { label: "GitHub", url: "https://github.com/MoonshotAI" }],
          tags: ["도구릴리스", "text", "code", "image", "moonshot"],
        },
        {
          date: "4/16",
          platform: "X",
          title: "Qwen3.6-35B-A3B 오픈소스 (Apache 2.0) — Agentic Coding MoE",
          featured: true,
          summary: "SWE-Bench Verified 73.4%, Terminal-Bench 2.0 51.5%, MCPMark 37.0% — Gemma 4 31B 전반 우위. 35B 총/3B 활성 MoE.",
          content: "SWE-Bench Verified 73.4%, Terminal-Bench 2.0 51.5%, MCPMark 37.0% — Gemma 4 31B 전반 우위. 35B 총/3B 활성 MoE.",
          officialUrl: "https://github.com/QwenLM/Qwen3.6",
          source: "https://github.com/QwenLM/Qwen3.6",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/kimmonismus/status/2044780695361290347" }, { label: "HuggingFace", url: "https://huggingface.co/Qwen/Qwen3.6-35B-A3B" }, { label: "marktechpost.com", url: "https://www.marktechpost.com/2026/04/16/qwen-team-open-sources-qwen3-6-35b-a3b-a-sparse-moe-vision-language-model-with-3b-active-parameters-and-agentic-coding-capabilities/" }],
          tags: ["도구릴리스", "text", "code", "image", "alibaba"],
        },
        {
          date: "4/15",
          platform: "X",
          title: "SuperGemma4-26B Uncensored — 한국 개발자(Jiunsong)의 Gemma 4 튜닝본",
          featured: true,
          summary: "MLX 4bit 13GB, 222 tok/s 한국어 프롬프트. 토크나이저/툴콜 버그 수정. Ollama 0xIbra 빌드 병행. HF 16K+ 다운로드.",
          content: "MLX 4bit 13GB, 222 tok/s 한국어 프롬프트. 토크나이저/툴콜 버그 수정. Ollama 0xIbra 빌드 병행. HF 16K+ 다운로드.",
          officialUrl: "https://huggingface.co/Jiunsong/supergemma4-26b-uncensored-mlx-4bit-v2",
          source: "https://huggingface.co/Jiunsong/supergemma4-26b-uncensored-mlx-4bit-v2",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/Jiunsong/status/2044562038749183245" }, { label: "ollama.com", url: "https://ollama.com/0xIbra/supergemma4-26b-uncensored-gguf-v2" }, { label: "HuggingFace", url: "https://huggingface.co/Jiunsong/supergemma4-26b-uncensored-gguf-v2" }],
          tags: ["도구릴리스", "text", "google", "community"],
        },
        {
          date: "4/7",
          platform: "X",
          title: "Zhipu GLM-5.1 — SWE-Bench Pro 58.4 > Opus 4.6 57.3 (754B MoE, Huawei Ascend 지원)",
          summary: "754B 파라미터 MoE 플래그십. SWE-Bench Pro 58.4 (Opus 4.6 57.3 대비 우수), Terminal-Bench 2.0 63.5 (Claude Code 69.0 대비 낮음). xLLM v0.8.0+에서 Huawei Ascend 학습 지원. (주의: arXiv 공개 2/17 — 윈도우 이탈)",
          content: "754B 파라미터 MoE 플래그십. SWE-Bench Pro 58.4 (Opus 4.6 57.3 대비 우수), Terminal-Bench 2.0 63.5 (Claude Code 69.0 대비 낮음). xLLM v0.8.0+에서 Huawei Ascend 학습 지원. (주의: arXiv 공개 2/17 — 윈도우 이탈)",
          officialUrl: "https://huggingface.co/zai-org/GLM-5.1",
          source: "https://huggingface.co/zai-org/GLM-5.1",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/thukeg/status/2011958624859390016" }, { label: "wavespeed.ai", url: "https://wavespeed.ai/blog/posts/glm-5-1-vs-claude-gpt-gemini-deepseek-llm-comparison/" }, { label: "digitalapplied.com", url: "https://www.digitalapplied.com/blog/zhipu-glm-5-1-coding-benchmark-claude-opus-comparison" }],
          tags: ["도구릴리스", "text", "code", "zhipu"],
        },
      ],
    },
    {
      name: "이미지 / 영상 / 음악",
      color: "#FB7185",
      posts: [
        {
          date: "4/16",
          platform: "X",
          title: "Tencent HY-World 2.0 — 이미지 1장 → 네비게이터블 3D 월드 (오픈소스 SOTA)",
          summary: "Mesh + 3DGS + 점군 + 깊이 + 카메라 전체 내보내기. Blender/Unity/UE/Isaac Sim 직접 연결. Marble 대비 오픈소스 최초 SOTA.",
          content: "Mesh + 3DGS + 점군 + 깊이 + 카메라 전체 내보내기. Blender/Unity/UE/Isaac Sim 직접 연결. Marble 대비 오픈소스 최초 SOTA.",
          officialUrl: "https://github.com/Tencent-Hunyuan/HY-World-2.0",
          source: "https://github.com/Tencent-Hunyuan/HY-World-2.0",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/TencentHunyuan/status/2044232836820279298" }, { label: "HuggingFace", url: "https://huggingface.co/tencent/HY-World-2.0" }, { label: "3d-models.hunyuan.tencent.com", url: "https://3d-models.hunyuan.tencent.com/world/world2_0/HY_World_2_0.pdf" }],
          tags: ["도구릴리스", "3d", "image", "video", "tencent"],
        },
        {
          date: "4/15",
          platform: "X",
          title: "ByteDance OmniShow — Human-Object Interaction Video (SOTA, 오픈소스)",
          summary: "전자상거래·숏폼 UGC용 사람+제품 상호작용 영상. RAP2V 풀 지원. arXiv + GitHub 공개.",
          content: "전자상거래·숏폼 UGC용 사람+제품 상호작용 영상. RAP2V 풀 지원. arXiv + GitHub 공개.",
          officialUrl: "https://github.com/Correr-Zhou/OmniShow",
          source: "https://github.com/Correr-Zhou/OmniShow",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/_akhaliq/status/2045031820485231983" }, { label: "arxiv.org", url: "https://arxiv.org/html/2604.11804v2" }, { label: "replicate.com", url: "https://replicate.com/bytedance/omni-human" }],
          tags: ["도구릴리스", "video", "image", "bytedance"],
        },
        {
          date: "4/15",
          platform: "X",
          title: "NVIDIA Lyra 2.0 — 단일 이미지로 탐험 가능한 3D 월드 생성",
          summary: "\"Lyra 2.0: Explorable Generative 3D Worlds\". long complex environments와 large camera trajectories 지원. arXiv 논문 공개.",
          content: "\"Lyra 2.0: Explorable Generative 3D Worlds\". long complex environments와 large camera trajectories 지원. arXiv 논문 공개.",
          officialUrl: "https://research.nvidia.com/labs/sil/projects/lyra2/",
          source: "https://research.nvidia.com/labs/sil/projects/lyra2/",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/NVIDIAAIDev/status/2044445645109436672" }, { label: "HuggingFace", url: "https://huggingface.co/nvidia/Lyra-2.0" }, { label: "GitHub", url: "https://github.com/nv-tlabs/lyra" }],
          tags: ["도구릴리스", "3d", "image", "video", "nvidia"],
        },
        {
          date: "4/14",
          platform: "X",
          title: "Recraft V4 — 최신 이미지 생성 모델 + Recraft Studio (4/6)",
          summary: "\"Meet Recraft V4: Our most advanced image generation model\" — Studio 에디터와 함께 제공. (주의: 4/6 공개 — 윈도우 이탈 가능)",
          content: "\"Meet Recraft V4: Our most advanced image generation model\" — Studio 에디터와 함께 제공. (주의: 4/6 공개 — 윈도우 이탈 가능)",
          officialUrl: "https://www.recraft.ai/",
          source: "https://www.recraft.ai/",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/recraftai/status/2044012937193927681" }, { label: "recraft.ai", url: "https://www.recraft.ai/docs/recraft-models/recraft-V4" }, { label: "mindstudio.ai", url: "https://www.mindstudio.ai/blog/what-is-recraft-studio-2" }],
          tags: ["도구릴리스", "image", "recraft"],
        },
        {
          date: "4/10",
          platform: "X",
          title: "ByteDance Seedance 2.0 — Replicate·fal 정식 배포 확대",
          summary: "텍스트·이미지·오디오·비디오 멀티모달. 최대 15s 내 다중 샷 자동 컷/트랜지션. CapCut/Jimeng/Ark/Replicate/fal.",
          content: "텍스트·이미지·오디오·비디오 멀티모달. 최대 15s 내 다중 샷 자동 컷/트랜지션. CapCut/Jimeng/Ark/Replicate/fal.",
          officialUrl: "https://replicate.com/bytedance/seedance-2.0",
          source: "https://replicate.com/bytedance/seedance-2.0",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/replicate/status/2016838212748290817" }, { label: "seed.bytedance.com", url: "https://seed.bytedance.com/en/blog/official-launch-of-seedance-2-0" }, { label: "fal.ai", url: "https://fal.ai/seedance-2.0" }],
          tags: ["도구릴리스", "video", "audio", "bytedance"],
        },
        {
          date: "4/10",
          platform: "X",
          title: "Figma Make — 디자인에서 프로토타입까지 프롬프트 기반 전환",
          summary: "\"Start with a design and prompt your way to a functional prototype, fast\" — AI로 디자인 → 작동 프로토타입으로 신속 전환. 스타일 라이브러리 통합, 프롬프트 기반 편집.",
          content: "\"Start with a design and prompt your way to a functional prototype, fast\" — AI로 디자인 → 작동 프로토타입으로 신속 전환. 스타일 라이브러리 통합, 프롬프트 기반 편집.",
          officialUrl: "https://www.figma.com/make/",
          source: "https://www.figma.com/make/",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/figma/status/2043688294027518123" }, { label: "figma.com", url: "https://www.figma.com/release-notes/" }, { label: "dev.to", url: "https://dev.to/spookuspookus/figma-made-a-huge-step-forward-in-ai-design-april-2026-1cin" }],
          tags: ["도구릴리스", "image", "code", "figma"],
        },
        {
          date: "4/9",
          platform: "X",
          title: "ElevenLabs API 4/7 업데이트 + v2.42 SDK — scoped analysis·test folders·DTMF",
          summary: "4/7 API 스키마 업데이트: scoped analysis, test folders, DTMF input 지원. v2.42.0 JavaScript/Python SDK 출시. (On-Premise 관련 언급은 미확인)",
          content: "4/7 API 스키마 업데이트: scoped analysis, test folders, DTMF input 지원. v2.42.0 JavaScript/Python SDK 출시. (On-Premise 관련 언급은 미확인)",
          officialUrl: "https://elevenlabs.io/docs/changelog/2026/4/7",
          source: "https://elevenlabs.io/docs/changelog/2026/4/7",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/elevenlabsio/status/2042094638302847281" }, { label: "elevenlabs.io", url: "https://elevenlabs.io/docs/changelog" }, { label: "releasebot.io", url: "https://releasebot.io/updates/eleven-labs" }],
          tags: ["도구릴리스", "audio", "elevenlabs"],
        },
        {
          date: "4/8",
          platform: "X",
          title: "HeyGen Avatar V + Seedance 2.0 통합 — 15초 녹음으로 스튜디오 아바타",
          summary: "단일 15초 녹음으로 장기 퍼포먼스. 라이브 아바타 24/7 대화. Seedance 2.0 네이티브 통합.",
          content: "단일 15초 녹음으로 장기 퍼포먼스. 라이브 아바타 24/7 대화. Seedance 2.0 네이티브 통합.",
          officialUrl: "https://www.heygen.com/blog/announcing-avatar-v",
          source: "https://www.heygen.com/blog/announcing-avatar-v",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/heygen_official/status/2042985920183920401" }, { label: "heygen.com", url: "https://www.heygen.com/blog/unleashing-the-power-of-realtime-avatars" }, { label: "mindstudio.ai", url: "https://www.mindstudio.ai/blog/heygen-avatar-5-clone-appearance-15-seconds-2" }],
          tags: ["도구릴리스", "video", "heygen", "bytedance"],
        },
        {
          date: "3/25",
          platform: "X",
          title: "Suno v5.5 — Voices·Custom Models·My Taste (3/26, 참고)",
          summary: "사용자 음성 캡처(Voices), 스타일 맞춤 Custom Models, 선호도 학습 My Taste. (주의: 2026-03-26 공개 — 윈도우 이탈이나 조코딩 영상에서 언급)",
          content: "사용자 음성 캡처(Voices), 스타일 맞춤 Custom Models, 선호도 학습 My Taste. (주의: 2026-03-26 공개 — 윈도우 이탈이나 조코딩 영상에서 언급)",
          officialUrl: "https://suno.com/blog/v5-5",
          source: "https://suno.com/blog/v5-5",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/suno_ai_/status/2035628491203847281" }, { label: "suno.com", url: "https://suno.com/blog" }, { label: "elevenlabs.io", url: "https://elevenlabs.io/blog/eleven-v3" }],
          tags: ["도구릴리스", "audio", "suno"],
        },
      ],
    },
    {
      name: "기타",
      color: "#6B7280",
      posts: [
        {
          date: "4/22",
          platform: "X",
          title: "Atomic Bot × Hermes Agent — 1분 원클릭 설치로 24/7 자율 에이전트 실행 (Mac·Windows·Web, 4/22)",
          summary: "Nous Research Hermes Agent를 터미널·Docker·SSH 없이 1분 만에 실행 가능하게 만든 래퍼. 로컬 모델(Qwen, Gemma via Ollama) + 클라우드 API 키 동시 지원, 세션 간 지속 메모리. 네이티브 대시보드·파일 탐색기·로그 UI. 100+ 앱 연동(Gmail, Slack, Di",
          content: "Nous Research Hermes Agent를 터미널·Docker·SSH 없이 1분 만에 실행 가능하게 만든 래퍼. 로컬 모델(Qwen, Gemma via Ollama) + 클라우드 API 키 동시 지원, 세션 간 지속 메모리. 네이티브 대시보드·파일 탐색기·로그 UI. 100+ 앱 연동(Gmail, Slack, Discord, Figma, GitHub). Mac/Windows/Web 정식 출시, iOS 준비 중. 클라우드·로컬 둘 다 데이터 암호화. MIT 오픈소스.",
          officialUrl: "https://atomicbot.ai/hermes",
          source: "https://atomicbot.ai/hermes",
          backupUrls: [{ label: "GitHub", url: "https://github.com/NousResearch/hermes-agent" }],
          tags: ["에이전트자동화", "text", "code", "community"],
        },
        {
          date: "4/15",
          platform: "X",
          title: "Browser-Use video-use — Claude Code로 영상 편집 자동화 (오픈소스)",
          featured: true,
          summary: "프리미어 프로 없이 컷 편집·자막·색보정·애니메이션. 필러 워드 제거, 30ms 오디오 페이드, Manim/Remotion 오버레이. 414+ 스타.",
          content: "프리미어 프로 없이 컷 편집·자막·색보정·애니메이션. 필러 워드 제거, 30ms 오디오 페이드, Manim/Remotion 오버레이. 414+ 스타.",
          officialUrl: "https://github.com/browser-use/video-use",
          source: "https://github.com/browser-use/video-use",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/gregpr07/status/2044554557221675380" }, { label: "mindstudio.ai", url: "https://www.mindstudio.ai/blog/claude-code-video-editing-motion-graphics" }, { label: "aibit.im", url: "https://aibit.im/blog/post/video-use-edit-videos-with-claude-code" }],
          tags: ["도구릴리스", "video", "audio", "code", "browser_use", "community"],
        },
        {
          date: "4/15",
          platform: "X",
          title: "백준 온라인 저지(BOJ) 서비스 종료 발표 (4/15 발표, 4/28 종료)",
          summary: "16년 운영 종료. 데이터는 문제·제출기록·대회만 유지. 알고리즘 문제풀이 시대 상징 종료. 프로덕트 빌딩 역량 시대.",
          content: "16년 운영 종료. 데이터는 문제·제출기록·대회만 유지. 알고리즘 문제풀이 시대 상징 종료. 프로덕트 빌딩 역량 시대.",
          officialUrl: "https://www.acmicpc.net/board/view/165799",
          source: "https://www.acmicpc.net/board/view/165799",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/baekjoononlinejudge/status/2043782912839048273" }, { label: "namu.wiki", url: "https://namu.wiki/w/Baekjoon%20Online%20Judge" }, { label: "velog.io", url: "https://velog.io/@happynj2697/%EC%86%8D%EB%B3%B4-%EB%B0%B1%EC%A4%80-%EC%84%9C%EB%B9%84%EC%8A%A4-%EC%A2%85%EB%A3%8C" }],
          tags: ["수익화사례", "text", "korea"],
        },
        {
          date: "4/15",
          platform: "X",
          title: "CodeBurn — Claude Code·Codex·Cursor 토큰/비용 TUI 대시보드 (MIT, 3.3k★)",
          featured: true,
          summary: "대화/코딩/탐색/디버깅 활동별, 프로젝트별, 모델별(Sonnet/Haiku/Opus)로 토큰 사용량을 분해해 보여주는 오픈소스 TUI 대시보드. Daily Activity 그래프, MCP·플러그인·Playwright 등 도구별 토큰 소모 표시. Claude Code·Codex·Cursor 모두 지원. v0.8.8 (202",
          content: "대화/코딩/탐색/디버깅 활동별, 프로젝트별, 모델별(Sonnet/Haiku/Opus)로 토큰 사용량을 분해해 보여주는 오픈소스 TUI 대시보드. Daily Activity 그래프, MCP·플러그인·Playwright 등 도구별 토큰 소모 표시. Claude Code·Codex·Cursor 모두 지원. v0.8.8 (2026-04-22), 332 커밋, 3.3k★. 인사이트: \"대화 63% · 코딩 16%\" — 실제 코딩보다 대화(프롬프트/응답)에 토큰이 더 쓰인다. claude-dashboard(상태바)와 상호보완.",
          officialUrl: "https://github.com/AgentSeal/codeburn",
          source: "https://github.com/AgentSeal/codeburn",
          backupUrls: [{ label: "Threads 게시글", url: "https://www.threads.com/@kk_fe_1/post/DXI9Potk_gx" }],
          tags: ["도구릴리스", "code", "community"],
        },
        {
          date: "4/14",
          platform: "X",
          title: "Browser-Use Browser Harness — Self-Healing 브라우저 하네스 (MIT, 오픈소스)",
          summary: "LLM의 미숙한 브라우저 작업을 자동 복구하며 어떤 웹 작업도 완주하게 설계된 self-healing 하네스. MIT 라이선스 오픈소스.",
          content: "LLM의 미숙한 브라우저 작업을 자동 복구하며 어떤 웹 작업도 완주하게 설계된 self-healing 하네스. MIT 라이선스 오픈소스.",
          officialUrl: "https://github.com/browser-use/browser-harness",
          source: "https://github.com/browser-use/browser-harness",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/gregpr07/status/2044101283010024234" }, { label: "GitHub", url: "https://github.com/browser-use/browser-harness-js" }, { label: "news.ycombinator.com", url: "https://news.ycombinator.com/item?id=47829234" }],
          tags: ["에이전트자동화", "code", "browser_use"],
        },
        {
          date: "4/14",
          platform: "X",
          title: "Nous Research Hermes Agent v0.10.0 — 자율 진화 에이전트 (MIT, 4/16 최신 릴리스)",
          summary: "Hermes Agent ☤ — 5,286개 커밋의 활발한 개발. MIT 라이선스, 9개 릴리스 이력, 최신 v0.10.0 (2026-04-16).",
          content: "Hermes Agent ☤ — 5,286개 커밋의 활발한 개발. MIT 라이선스, 9개 릴리스 이력, 최신 v0.10.0 (2026-04-16).",
          officialUrl: "https://github.com/NousResearch/hermes-agent",
          source: "https://github.com/NousResearch/hermes-agent",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/Teknium/status/2044879261564375326" }, { label: "hermes-agent.nousresearch.com", url: "https://hermes-agent.nousresearch.com/" }, { label: "GitHub", url: "https://github.com/NousResearch/hermes-agent-self-evolution" }],
          tags: ["에이전트자동화", "text", "code", "nous"],
        },
        {
          date: "4/12",
          platform: "X",
          title: "Notion 3.4 part 2 — Custom Agents + AI Autofill (4/14)",
          summary: "\"Custom Agents are now easier to fine-tune, and new AI Autofill brings them straight into your databases\" (4/14 릴리스). 4/17에는 Mail & Calendar가 설정에 통합.",
          content: "\"Custom Agents are now easier to fine-tune, and new AI Autofill brings them straight into your databases\" (4/14 릴리스). 4/17에는 Mail & Calendar가 설정에 통합.",
          officialUrl: "https://www.notion.com/releases",
          source: "https://www.notion.com/releases",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/NotionHQ/status/2044162938475739281" }, { label: "releasebot.io", url: "https://releasebot.io/updates/notion" }, { label: "notion.com", url: "https://www.notion.com/releases/2025-09-18" }],
          tags: ["에이전트자동화", "text", "notion"],
        },
        {
          date: "4/5",
          platform: "X",
          title: "HuggingFace Inference Providers — PRO $2/월 크레딧 (200+ 모델)",
          summary: "월 크레딧: Free $0.10, PRO $2.00, Team/Enterprise 시트당 $2.00. 200+ 모델 통합 API. 마크업 없이 공급자 가격 그대로 pass-through.",
          content: "월 크레딧: Free $0.10, PRO $2.00, Team/Enterprise 시트당 $2.00. 200+ 모델 통합 API. 마크업 없이 공급자 가격 그대로 pass-through.",
          officialUrl: "https://huggingface.co/docs/inference-providers/pricing",
          source: "https://huggingface.co/docs/inference-providers/pricing",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/huggingface/status/2044085039274812938" }, { label: "HuggingFace", url: "https://huggingface.co/pricing" }, { label: "HuggingFace", url: "https://huggingface.co/blog/pricing-update" }],
          tags: ["수익화사례", "text", "code", "huggingface"],
        },
        {
          date: "2/23",
          platform: "X",
          title: "Wispr Flow — Mac/Windows/iPhone 정식 + Android 대기자 모집",
          summary: "음성 받아쓰기 크로스 플랫폼. Mac/Windows/iPhone 3종 정식 출시 상태, Android는 waitlist(조기 접근 모집) 단계. (4종 완성 주장은 아직 부정확)",
          content: "음성 받아쓰기 크로스 플랫폼. Mac/Windows/iPhone 3종 정식 출시 상태, Android는 waitlist(조기 접근 모집) 단계. (4종 완성 주장은 아직 부정확)",
          officialUrl: "https://wisprflow.ai/use-cases/notion",
          source: "https://wisprflow.ai/use-cases/notion",
          backupUrls: [{ label: "X 공식 게시글", url: "https://x.com/WisprAI/status/2037283920419385712" }, { label: "techcrunch.com", url: "https://techcrunch.com/2026/02/23/wispr-flow-launches-an-android-app-for-ai-powered-dictation/" }],
          tags: ["도구릴리스", "audio", "text", "wispr"],
        },
      ],
    },
  ],
};
