import type { WeeklyData } from "../data";

// 2026-w21 (5/15 ~ 5/21)
// 자동 생성: 4라운드 수집 + 5차 prune 기반 archive
// 주차 기준 목~수 (5/15 목 = 새 주차 시작)

export const week21: WeeklyData = {
  week: 21,
  year: 2026,
  slug: "2026-w21",
  period: "5/15 ~ 5/21",
  totalPosts: 62,
  companies: [
    {
      name: "OpenAI",
      color: "#10A37F",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "AdventHealth advances whole-person care with OpenAI",
          summary: "",
          officialUrl: "https://openai.com/index/adventhealth",
          source: "https://openai.com/index/adventhealth",
          tags: ["ChatGPT for Healthcare", "공식"],
          slug: "adventhealth-advances-whole-person-care--54bdd59c",
          readMinutes: 1,
        },
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Codex rust-v0.133.0",
          summary: "",
          officialUrl: "https://github.com/openai/codex/releases/tag/rust-v0.133.0",
          source: "https://github.com/openai/codex/releases/tag/rust-v0.133.0",
          tags: ["Codex CLI", "Goals", "공식", "hero후보"],
          featured: true,
          slug: "codex-rust-v0-133-0-184c8422",
          readMinutes: 1,
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "An OpenAI model has disproved a central conjecture in discrete geometry",
          summary: "",
          officialUrl: "https://openai.com/index/model-disproves-discrete-geometry-conjecture",
          source: "https://openai.com/index/model-disproves-discrete-geometry-conjecture",
          tags: ["OpenAI Research", "Math", "공식"],
          slug: "an-openai-model-has-disproved-a-central--73dee1f9",
          readMinutes: 1,
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "The next phase of OpenAI’s Education for Countries",
          summary: "",
          officialUrl: "https://openai.com/index/the-next-phase-of-education-for-countries",
          source: "https://openai.com/index/the-next-phase-of-education-for-countries",
          tags: ["Education for Countries", "Global Affairs", "공식"],
          slug: "the-next-phase-of-openai-s-education-for-b2b66ea4",
          readMinutes: 1,
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "How Ramp engineers accelerate code review with Codex",
          summary: "",
          officialUrl: "https://openai.com/index/ramp",
          source: "https://openai.com/index/ramp",
          tags: ["Codex", "GPT-5.5", "enterprise adoption", "공식"],
          slug: "how-ramp-engineers-accelerate-code-revie-dfe54bb2",
          readMinutes: 1,
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "OpenAI Cookbook commit: Macro evals cookbook",
          summary: "",
          officialUrl: "https://github.com/openai/openai-cookbook/commit/0075904c509819f8d746794001a7a27066258956",
          source: "https://github.com/openai/openai-cookbook/commit/0075904c509819f8d746794001a7a27066258956",
          tags: ["OpenAI Cookbook", "evals", "공식"],
          slug: "openai-cookbook-commit-macro-evals-cookb-d9bf2d74",
          readMinutes: 1,
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Introducing OpenAI for Singapore",
          summary: "",
          officialUrl: "https://openai.com/index/introducing-openai-for-singapore",
          source: "https://openai.com/index/introducing-openai-for-singapore",
          tags: ["OpenAI for Singapore", "Global Affairs", "공식"],
          slug: "introducing-openai-for-singapore-39fd4877",
          readMinutes: 1,
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Advancing content provenance for a safer, more transparent AI ecosystem",
          summary: "",
          officialUrl: "https://openai.com/index/advancing-content-provenance",
          source: "https://openai.com/index/advancing-content-provenance",
          tags: ["Safety", "Content provenance", "공식"],
          slug: "advancing-content-provenance-for-a-safer-7ce118d8",
          readMinutes: 1,
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Codex rust-v0.132.0",
          summary: "",
          officialUrl: "https://github.com/openai/codex/releases/tag/rust-v0.132.0",
          source: "https://github.com/openai/codex/releases/tag/rust-v0.132.0",
          tags: ["Codex CLI", "Python SDK auth", "공식"],
          slug: "codex-rust-v0-132-0-7e22537d",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/codex-rust-v0-132-0-7e22537d.jpg",
            alt: "Codex rust-v0.132.0",
          },
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "OpenAI and Dell partner to bring Codex to hybrid and on-premise enterprise environments",
          summary: "",
          officialUrl: "https://openai.com/index/dell-codex-enterprise-partnership",
          source: "https://openai.com/index/dell-codex-enterprise-partnership",
          tags: ["Codex", "Dell", "enterprise deployment", "공식"],
          slug: "openai-and-dell-partner-to-bring-codex-t-9d5c4fff",
          readMinutes: 1,
        },
        {
          date: "5/16",
          platform: "X+Threads",
          title: "OpenAI and Malta partner to bring ChatGPT Plus to all citizens",
          summary: "",
          officialUrl: "https://openai.com/index/malta-chatgpt-plus-partnership",
          source: "https://openai.com/index/malta-chatgpt-plus-partnership",
          tags: ["ChatGPT Plus", "Malta", "Global Affairs", "공식"],
          slug: "openai-and-malta-partner-to-bring-chatgp-e74cfa1e",
          readMinutes: 1,
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "A new personal finance experience in ChatGPT",
          summary: "",
          officialUrl: "https://openai.com/index/personal-finance-chatgpt",
          source: "https://openai.com/index/personal-finance-chatgpt",
          tags: ["ChatGPT", "Personal finance", "공식"],
          slug: "a-new-personal-finance-experience-in-cha-4f6e31bb",
          readMinutes: 1,
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "Databricks brings GPT-5.5 to enterprise agent workflows",
          summary: "",
          officialUrl: "https://openai.com/index/databricks",
          source: "https://openai.com/index/databricks",
          tags: ["GPT-5.5", "Databricks", "agents", "공식"],
          slug: "databricks-brings-gpt-5-5-to-enterprise--6719cd72",
          readMinutes: 1,
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "How sales teams use Codex",
          summary: "",
          officialUrl: "https://openai.com/academy/codex-for-work/how-sales-teams-use-codex",
          source: "https://openai.com/academy/codex-for-work/how-sales-teams-use-codex",
          tags: ["Codex for Work", "Sales", "공식"],
          slug: "how-sales-teams-use-codex-43467e2c",
          readMinutes: 1,
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "How business operations teams use Codex",
          summary: "",
          officialUrl: "https://openai.com/academy/codex-for-work/how-business-operations-teams-use-codex",
          source: "https://openai.com/academy/codex-for-work/how-business-operations-teams-use-codex",
          tags: ["Codex for Work", "Business operations", "공식"],
          slug: "how-business-operations-teams-use-codex-14e2778d",
          readMinutes: 1,
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "How data science teams use Codex",
          summary: "",
          officialUrl: "https://openai.com/academy/codex-for-work/how-data-science-teams-use-codex",
          source: "https://openai.com/academy/codex-for-work/how-data-science-teams-use-codex",
          tags: ["Codex for Work", "Data science", "공식"],
          slug: "how-data-science-teams-use-codex-f9d62a00",
          readMinutes: 1,
        },
        {
          date: "5/14",
          platform: "X+Threads",
          title: "Codex in the ChatGPT mobile app (iOS / Android)",
          summary: "OpenAI가 ChatGPT 모바일 앱(iOS/Android)에서 Mac/devbox에서 돌아가는 Codex 세션을 원격으로 제어할 수 있게 했다. 같은 주에 Hooks GA, Business/Enterprise programmatic access tokens, HIPAA-compliant Codex, Remote SSH GA가 함께 풀렸다.",
          officialUrl: "https://openai.com/index/",
          source: "https://openai.com/index/",
          tags: ["Codex", "ChatGPT mobile", "Codex Mac app", "Hooks", "Remote SSH", "공식", "hero후보"],
          featured: true,
          slug: "codex-in-the-chatgpt-mobile-app-ios-andr-13026e4d",
          readMinutes: 1,
        },
      ],
    },
    {
      name: "Google",
      color: "#4285F4",
      posts: [
        {
          date: "5/20",
          platform: "X+Threads",
          title: "A new experiment brings better group meetings to Google Beam",
          summary: "Google described a Google Beam experiment for more natural hybrid group meetings using HP Dimension immersive displays and spatial audio.",
          officialUrl: "https://blog.google/innovation-and-ai/models-and-research/google-research/google-beam-group-meetings/",
          source: "https://blog.google/innovation-and-ai/models-and-research/google-research/google-beam-group-meetings/",
          tags: ["Google Beam", "Google Research", "공식"],
          slug: "a-new-experiment-brings-better-group-mee-01decd7a",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/a-new-experiment-brings-better-group-mee-01decd7a.png",
            alt: "A new experiment brings better group meetings to Google Beam",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "I/O 2026: Welcome to the agentic Gemini era",
          summary: "Google summarized I/O 2026 AI announcements including Gemini 3.5 Flash, Spark, agentic Search, TPU 8, Gemini Omni, and SynthID expansion.",
          officialUrl: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
          source: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
          tags: ["Gemini", "Search", "Workspace", "Cloud", "Android", "TPU", "공식", "hero후보"],
          featured: true,
          slug: "i-o-2026-welcome-to-the-agentic-gemini-e-4283a2bd",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/i-o-2026-welcome-to-the-agentic-gemini-e-4283a2bd.png",
            alt: "I/O 2026: Welcome to the agentic Gemini era",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "The Gemini app becomes more agentic, delivering proactive, 24/7 help",
          summary: "Google announced more proactive Gemini app experiences, Daily Brief, Omni video generation, Spark agent functions, and macOS improvements.",
          officialUrl: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
          source: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
          tags: ["Gemini app", "Gemini 3.5 Flash", "Omni", "Daily Brief", "Spark", "공식"],
          slug: "the-gemini-app-becomes-more-agentic-deli-8bec6d8c",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/the-gemini-app-becomes-more-agentic-deli-8bec6d8c.jpg",
            alt: "The Gemini app becomes more agentic, delivering proactive, 24/7 help",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Introducing Managed Agents in the Gemini API",
          summary: "Google introduced Gemini API Managed Agents running Antigravity-based agents inside secure cloud Linux sandboxes.",
          officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
          source: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
          tags: ["Gemini API", "Managed Agents", "Antigravity", "공식", "hero후보"],
          featured: true,
          slug: "introducing-managed-agents-in-the-gemini-ac0ae172",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/introducing-managed-agents-in-the-gemini-ac0ae172.png",
            alt: "Introducing Managed Agents in the Gemini API",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Bring any idea to life: Google AI Studio at I/O 2026",
          summary: "Google announced AI Studio updates for Workspace integration, Android app building, mobile pre-registration, Antigravity export, and no-cost deployment.",
          officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026/",
          source: "https://blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026/",
          tags: ["Google AI Studio", "Android", "Workspace", "Antigravity", "공식"],
          slug: "bring-any-idea-to-life-google-ai-studio--66d64068",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/bring-any-idea-to-life-google-ai-studio--66d64068.png",
            alt: "Bring any idea to life: Google AI Studio at I/O 2026",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Building the agentic future: Developer highlights from I/O 2026",
          summary: "Google summarized I/O 2026 developer announcements around Antigravity 2.0, Gemini API Managed Agents, AI Studio integrations, and Build with Gemini XPRIZE Hackathon.",
          officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
          source: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
          tags: ["Antigravity 2.0", "Gemini API", "Managed Agents", "Google AI Studio", "공식"],
          slug: "building-the-agentic-future-developer-hi-c8b5b49d",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/building-the-agentic-future-developer-hi-c8b5b49d.png",
            alt: "Building the agentic future: Developer highlights from I/O 2026",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "NVIDIA and Google Cloud Empower the Next Wave of AI Builders",
          summary: "",
          officialUrl: "https://blogs.nvidia.com/blog/google-cloud-developer-community-ai-builders/",
          source: "https://blogs.nvidia.com/blog/google-cloud-developer-community-ai-builders/",
          tags: ["NVIDIA AI platform", "Google Cloud", "Gemma", "Nemotron", "공식"],
          slug: "nvidia-and-google-cloud-empower-the-next-639e55a0",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/nvidia-and-google-cloud-empower-the-next-639e55a0.jpg",
            alt: "NVIDIA and Google Cloud Empower the Next Wave of AI Builders",
          },
        },
      ],
    },
    {
      name: "Anthropic / Claude",
      color: "#E87040",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Anthropic Claude for Small Business",
          summary: "",
          officialUrl: "https://www.anthropic.com/news/claude-for-small-business",
          source: "https://www.anthropic.com/news/claude-for-small-business",
          tags: ["Claude", "SMB", "go-to-market", "공식"],
          slug: "anthropic-claude-for-small-business-3b7ab7f2",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/anthropic-claude-for-small-business-3b7ab7f2.jpg",
            alt: "Anthropic Claude for Small Business",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Widening the conversation on frontier AI",
          summary: "Anthropic described work to broaden frontier AI discussions with religion, philosophy, culture, and civil society experts.",
          officialUrl: "https://www.anthropic.com/news/widening-conversation-ai",
          source: "https://www.anthropic.com/news/widening-conversation-ai",
          tags: ["AI safety", "governance", "Claude values", "공식"],
          slug: "widening-the-conversation-on-frontier-ai-e122375d",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/widening-the-conversation-on-frontier-ai-e122375d.jpg",
            alt: "Widening the conversation on frontier AI",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "KPMG integrates Claude across its core business and workforce of more than 276,000 in strategic alliance",
          summary: "KPMG announced Claude integration across core business workflows and a 276,000+ workforce through a strategic alliance with Anthropic.",
          officialUrl: "https://www.anthropic.com/news/anthropic-kpmg",
          source: "https://www.anthropic.com/news/anthropic-kpmg",
          tags: ["Claude", "Enterprise AI", "Managed Agents", "Claude Code", "공식"],
          slug: "kpmg-integrates-claude-across-its-core-b-e02f19cc",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/kpmg-integrates-claude-across-its-core-b-e02f19cc.jpg",
            alt: "KPMG integrates Claude across its core business and workforce of more than 276,000 in strategic alliance",
          },
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Anthropic acquires Stainless",
          summary: "Anthropic acquired Stainless to strengthen Claude developer experience, SDK generation, CLI and MCP-connected tooling.",
          officialUrl: "https://www.anthropic.com/news/anthropic-acquires-stainless",
          source: "https://www.anthropic.com/news/anthropic-acquires-stainless",
          tags: ["Claude Platform", "Stainless", "SDK", "MCP", "공식"],
          slug: "anthropic-acquires-stainless-c7a48d62",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/anthropic-acquires-stainless-c7a48d62.jpg",
            alt: "Anthropic acquires Stainless",
          },
        },
        {
          date: "5/11",
          platform: "X+Threads",
          title: "Claude Code Agent View (Research Preview)",
          summary: "Anthropic이 Claude Code 2.1.139부터 모든 병렬 세션을 한 화면에서 관리하는 Agent View를 Research Preview로 공개했다. 이후 `claude agents --cwd <path>`와 pinned background sessions 같은 후속 업데이트가 같은 주에 추가되며 5월 15일 이후에도 영향이 이어졌다.",
          officialUrl: "https://www.anthropic.com/news",
          source: "https://www.anthropic.com/news",
          tags: ["Claude Code", "Agent View", "multi-agent CLI", "공식"],
          slug: "claude-code-agent-view-research-preview-1cd2fb14",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/claude-code-agent-view-research-preview-1cd2fb14.jpg",
            alt: "Claude Code Agent View (Research Preview)",
          },
        },
      ],
    },
    {
      name: "NVIDIA",
      color: "#76B900",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "NVIDIA GTC Taipei at COMPUTEX: Live Updates on What's Next in AI",
          summary: "",
          officialUrl: "https://blogs.nvidia.com/blog/nvidia-gtc-taipei-computex-2026-news/",
          source: "https://blogs.nvidia.com/blog/nvidia-gtc-taipei-computex-2026-news/",
          tags: ["NVIDIA AI", "GTC Taipei", "COMPUTEX", "Jetson Thor", "공식"],
          slug: "nvidia-gtc-taipei-at-computex-live-updat-03bdec81",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/nvidia-gtc-taipei-at-computex-live-updat-03bdec81.jpg",
            alt: "NVIDIA GTC Taipei at COMPUTEX: Live Updates on What's Next in AI",
          },
        },
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Building Token-Metered AI Services on Telco AI Factories",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/building-token-metered-ai-services-on-telco-ai-factories/",
          source: "https://developer.nvidia.com/blog/building-token-metered-ai-services-on-telco-ai-factories/",
          tags: ["NVIDIA Telco AI", "AI Factory", "NIM", "NeMo", "공식"],
          slug: "building-token-metered-ai-services-on-te-434cbec0",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/building-token-metered-ai-services-on-te-434cbec0.webp",
            alt: "Building Token-Metered AI Services on Telco AI Factories",
          },
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "NVIDIA Announces Financial Results for First Quarter Fiscal 2027",
          summary: "",
          officialUrl: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
          source: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
          tags: ["NVIDIA Data Center", "AI factories", "Blackwell", "공식", "hero후보"],
          featured: true,
          slug: "nvidia-announces-financial-results-for-f-b2ddd86c",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/nvidia-announces-financial-results-for-f-b2ddd86c.jpg",
            alt: "NVIDIA Announces Financial Results for First Quarter Fiscal 2027",
          },
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Mastering Agentic Techniques: AI Agent Customization",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/mastering-agentic-techniques-ai-agent-customization/",
          source: "https://developer.nvidia.com/blog/mastering-agentic-techniques-ai-agent-customization/",
          tags: ["NVIDIA NeMo", "Agentic AI", "Nemotron", "공식"],
          slug: "mastering-agentic-techniques-ai-agent-cu-18dc78b2",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/mastering-agentic-techniques-ai-agent-cu-18dc78b2.webp",
            alt: "Mastering Agentic Techniques: AI Agent Customization",
          },
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Add a Specialized Deep Research Skill to Agent Harnesses",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/add-a-specialized-deep-research-skill-to-agent-harnesses/",
          source: "https://developer.nvidia.com/blog/add-a-specialized-deep-research-skill-to-agent-harnesses/",
          tags: ["NVIDIA AI-Q", "NeMo Agent Toolkit", "agent harness", "공식"],
          slug: "add-a-specialized-deep-research-skill-to-4d486b31",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/add-a-specialized-deep-research-skill-to-4d486b31.webp",
            alt: "Add a Specialized Deep Research Skill to Agent Harnesses",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "NVIDIA-Verified Agent Skills Provide Capability Governance for AI Agents",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/nvidia-verified-agent-skills-provide-capability-governance-for-ai-agents/",
          source: "https://developer.nvidia.com/blog/nvidia-verified-agent-skills-provide-capability-governance-for-ai-agents/",
          tags: ["NVIDIA Agent Skills", "agent governance", "공식"],
          slug: "nvidia-verified-agent-skills-provide-cap-e84a94b7",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/nvidia-verified-agent-skills-provide-cap-e84a94b7.webp",
            alt: "NVIDIA-Verified Agent Skills Provide Capability Governance for AI Agents",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Mastering Agentic Techniques: AI Agent Evaluation",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/mastering-agentic-techniques-ai-agent-evaluation/",
          source: "https://developer.nvidia.com/blog/mastering-agentic-techniques-ai-agent-evaluation/",
          tags: ["NVIDIA NeMo Agent Toolkit", "agent evaluation", "공식"],
          slug: "mastering-agentic-techniques-ai-agent-ev-8987f06f",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/mastering-agentic-techniques-ai-agent-ev-8987f06f.webp",
            alt: "Mastering Agentic Techniques: AI Agent Evaluation",
          },
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "NVIDIA CEO Jensen Huang at Dell Technologies World: Demand Is Going Parabolic, Utterly Parabolic",
          summary: "",
          officialUrl: "https://blogs.nvidia.com/blog/dell-technologies-agent-enterprise-ai/",
          source: "https://blogs.nvidia.com/blog/dell-technologies-agent-enterprise-ai/",
          tags: ["Dell AI Factory with NVIDIA", "Vera Rubin", "enterprise agentic AI", "공식"],
          slug: "nvidia-ceo-jensen-huang-at-dell-technolo-e58f42c0",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/nvidia-ceo-jensen-huang-at-dell-technolo-e58f42c0.jpg",
            alt: "NVIDIA CEO Jensen Huang at Dell Technologies World: Demand Is Going Parabolic, Utterly Parabolic",
          },
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Vera Arrives: NVIDIA's First CPU Built for Agents Lands at Top AI Labs",
          summary: "",
          officialUrl: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
          source: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
          tags: ["NVIDIA Vera CPU", "Vera Rubin NVL72", "agentic AI infrastructure", "공식", "hero후보"],
          featured: true,
          slug: "vera-arrives-nvidia-s-first-cpu-built-fo-2dd68315",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/vera-arrives-nvidia-s-first-cpu-built-fo-2dd68315.jpg",
            alt: "Vera Arrives: NVIDIA's First CPU Built for Agents Lands at Top AI Labs",
          },
        },
      ],
    },
    {
      name: "GitHub",
      color: "#181717",
      posts: [
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Auto model selection now routes based on your task in VS Code",
          summary: "GitHub Copilot in VS Code now routes to models based on task type through auto model selection.",
          officialUrl: "https://github.blog/changelog/2026-05-20-auto-model-selection-now-routes-based-on-your-task-in-vs-code",
          source: "https://github.blog/changelog/2026-05-20-auto-model-selection-now-routes-based-on-your-task-in-vs-code",
          tags: ["GitHub Copilot", "VS Code", "model routing", "공식"],
          slug: "auto-model-selection-now-routes-based-on-cd41cce4",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/auto-model-selection-now-routes-based-on-cd41cce4.png",
            alt: "Auto model selection now routes based on your task in VS Code",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Easily apply Copilot code review feedback with Copilot cloud agent",
          summary: "GitHub improved Copilot cloud agent so it can help apply code review feedback.",
          officialUrl: "https://github.blog/changelog/2026-05-19-easily-apply-copilot-code-review-feedback-with-copilot-cloud-agent",
          source: "https://github.blog/changelog/2026-05-19-easily-apply-copilot-code-review-feedback-with-copilot-cloud-agent",
          tags: ["GitHub Copilot cloud agent", "code review", "공식", "hero후보"],
          featured: true,
          slug: "easily-apply-copilot-code-review-feedbac-4683c903",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/easily-apply-copilot-code-review-feedbac-4683c903.jpg",
            alt: "Easily apply Copilot code review feedback with Copilot cloud agent",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Gemini 3.5 Flash is generally available for GitHub Copilot",
          summary: "Gemini 3.5 Flash became generally available in GitHub Copilot.",
          officialUrl: "https://github.blog/changelog/2026-05-19-gemini-3-5-flash-is-generally-available-for-github-copilot",
          source: "https://github.blog/changelog/2026-05-19-gemini-3-5-flash-is-generally-available-for-github-copilot",
          tags: ["GitHub Copilot", "models", "공식"],
          slug: "gemini-3-5-flash-is-generally-available--4d91d7f1",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/gemini-3-5-flash-is-generally-available--4d91d7f1.png",
            alt: "Gemini 3.5 Flash is generally available for GitHub Copilot",
          },
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "One-click fixes for failing Actions with Copilot cloud agent",
          summary: "GitHub added one-click Copilot cloud agent fixes for failing GitHub Actions workflows.",
          officialUrl: "https://github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
          source: "https://github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
          tags: ["GitHub Actions", "Copilot cloud agent", "공식", "hero후보"],
          featured: true,
          slug: "one-click-fixes-for-failing-actions-with-e02c868a",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/one-click-fixes-for-failing-actions-with-e02c868a.png",
            alt: "One-click fixes for failing Actions with Copilot cloud agent",
          },
        },
        {
          date: "5/17",
          platform: "X+Threads",
          title: "GPT-5.3-Codex is now the base model for Copilot Business and Enterprise",
          summary: "GitHub changed the base model for Copilot Business and Enterprise to GPT-5.3-Codex.",
          officialUrl: "https://github.blog/changelog/2026-05-17-gpt-5-3-codex-is-now-the-base-model-for-copilot-business-and-enterprise",
          source: "https://github.blog/changelog/2026-05-17-gpt-5-3-codex-is-now-the-base-model-for-copilot-business-and-enterprise",
          tags: ["GitHub Copilot Business", "GitHub Copilot Enterprise", "공식"],
          slug: "gpt-5-3-codex-is-now-the-base-model-for--d3b67286",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/gpt-5-3-codex-is-now-the-base-model-for--d3b67286.png",
            alt: "GPT-5.3-Codex is now the base model for Copilot Business and Enterprise",
          },
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "Copilot Memory supports user preferences for Pro, Pro+ users",
          summary: "GitHub added user preference support to Copilot Memory for Pro and Pro+ users.",
          officialUrl: "https://github.blog/changelog/2026-05-15-copilot-memory-supports-user-preferences-for-pro-pro-users",
          source: "https://github.blog/changelog/2026-05-15-copilot-memory-supports-user-preferences-for-pro-pro-users",
          tags: ["GitHub Copilot Memory", "공식"],
          slug: "copilot-memory-supports-user-preferences-785b4e51",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/copilot-memory-supports-user-preferences-785b4e51.png",
            alt: "Copilot Memory supports user preferences for Pro, Pro+ users",
          },
        },
      ],
    },
    {
      name: "Cursor / Anysphere",
      color: "#374151",
      posts: [
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Improvements to Cursor Automations",
          summary: "Cursor added Automations to the Agents Window and introduced multi-repository/no-repository automation templates.",
          officialUrl: "https://cursor.com/changelog/05-20-26",
          source: "https://cursor.com/changelog/05-20-26",
          tags: ["Cursor Automations", "Agents Window", "공식"],
          slug: "improvements-to-cursor-automations-4b9e0ee2",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/improvements-to-cursor-automations-4b9e0ee2.png",
            alt: "Improvements to Cursor Automations",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Cursor in Jira",
          summary: "Cursor added Jira integration so users can mention @Cursor or assign issues to run the cloud agent and receive PR links.",
          officialUrl: "https://cursor.com/changelog/05-19-26",
          source: "https://cursor.com/changelog/05-19-26",
          tags: ["Cursor cloud agent", "Jira", "공식"],
          slug: "cursor-in-jira-57aa0e15",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/cursor-in-jira-57aa0e15.png",
            alt: "Cursor in Jira",
          },
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Composer 2.5",
          summary: "Cursor Composer 2.5 improved long-running work, instruction following, and collaboration.",
          officialUrl: "https://cursor.com/changelog/composer-2-5",
          source: "https://cursor.com/changelog/composer-2-5",
          tags: ["Cursor Composer", "공식"],
          slug: "composer-2-5-3507df22",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/composer-2-5-3507df22.png",
            alt: "Composer 2.5",
          },
        },
      ],
    },
    {
      name: "Microsoft",
      color: "#00BCF2",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Plan Before You Build: Introducing the Plan agent in Visual Studio",
          summary: "Microsoft introduced a Visual Studio Plan agent for creating, editing, and sharing implementation plans before building.",
          officialUrl: "https://devblogs.microsoft.com/visualstudio/plan-before-you-build-introducing-the-plan-agent-in-visual-studio/",
          source: "https://devblogs.microsoft.com/visualstudio/plan-before-you-build-introducing-the-plan-agent-in-visual-studio/",
          tags: ["Visual Studio", "Copilot", "Plan agent", "공식"],
          slug: "plan-before-you-build-introducing-the-pl-6e7d2f7a",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/plan-before-you-build-introducing-the-pl-6e7d2f7a.webp",
            alt: "Plan Before You Build: Introducing the Plan agent in Visual Studio",
          },
        },
      ],
    },
    {
      name: "xAI / Grok",
      color: "#1D1D1F",
      posts: [
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Grok Build — xAI의 터미널 기반 parallel coding agent (early beta)",
          summary: "xAI가 5/14 공개한 Grok Build CLI/TUI는 풀스크린 터미널 UI, 최대 8개 parallel sub-agent, Plan Mode, 131K~2M 컨텍스트를 지원한다. SuperGrok Heavy 구독자(월 $300, 프로모션 $99) 전용 early beta.",
          content: "**이게 뭐예요?**\n\nGrok Build는 xAI가 2026년 5월 14일 early beta로 공개한 터미널 기반 AI 코딩 에이전트입니다. CLI와 TUI(Terminal User Interface) 양쪽으로 동작하며, 자연어 명령으로 계획→검색→코드 작성/편집→실행→테스트까지 자동화합니다.\n\n설치는 한 줄: `curl -fsSL https://x.ai/cli/install.sh | bash`\n\n**주요 기능 (공식 검증)**\n\n- **TUI**: 풀스크린, 마우스 지원, Vim-like 단축키, 실시간 diff, 멀티 창\n- **Plan Mode**: 작업 계획을 먼저 제시, 개발자가 수정·승인 후 실행 (안전 중심)\n- **Parallel Sub-agent**: 최대 8개 에이전트 동시 독립 작업\n- **컨텍스트**: 131K~2M 토큰 범위 (자료별 편차)\n- Git 통합 / 멀티 파일 편집 / Shell 실행 / X 실시간 검색\n\n**접근성·가격**\n\n현재 SuperGrok Heavy 구독자 전용 early beta. 월 $300, 6개월 프로모션 시 $99. 일반·무료 Grok 사용자는 사용 불가. (x.ai/news/grok-build-cli)\n\n**Claude Code · Codex CLI와의 비교 (해외 리뷰 기준)**\n\n| 항목 | Grok Build | Claude Code | Codex CLI |\n|---|---|---|---|\n| 인터페이스 | Terminal-first TUI (최고 평가) | Terminal + IDE | Terminal shell |\n| 병렬 에이전트 | 최대 8개 (강점) | 1~2개 | 제한적 |\n| Plan Mode | 그래프 + 직접 편집 | 선형 텍스트 | 기본 |\n| 실행 속도 | 가장 빠름 | 계획에서 상대적 느림 | 중간 |\n| Reasoning / 코드 품질 | 빠른 실행 중심 | 가장 우수 (deep reasoning) | 중간~좋음 |\n| 대형 코드베이스 | 모듈러 프로젝트 강함 | monorepo / legacy 최고 | 중간 |\n| SWE-Bench (참고) | ~51% | ~57% | ~54% |\n| Best For | 빠른 prototyping, 대형 리팩토링 | 복잡한 refactoring, 코드 품질 | OpenAI 생태계, 가성비 |\n\n출처: eigent.ai/blog/grok-build-cli, rejoicehub.com (2026.5)\n\n**현재 평가 · 한계**\n\n- 긍정: \"지금까지 본 AI CLI 중 최고의 TUI\", \"parallel agent로 대형 작업 속도가 압도적\" (LinkedIn day-one beta review, X 사용자 후기)\n- 한계: early beta 단계, 접근성 제한, 일부 reasoning depth에서 Claude Code에 뒤처진다는 의견 다수\n- 업데이트: xAI 팀이 매일 패치·기능 추가\n\n**한 줄 요약**\n\nGrok Build는 터미널 중심의 강력한 parallel agentic 코딩 도구로, TUI와 속도에서 차별점을 보이지만, 아직 early beta이며 복잡한 reasoning에서는 Claude Code가 앞선다는 평가가 지배적입니다.",
          officialUrl: "https://x.ai/news/grok-build-cli",
          source: "https://docs.x.ai/developers/release-notes",
          backupUrls: [
            { label: "xAI 공식 — Grok Build CLI 발표", url: "https://x.ai/news/grok-build-cli" },
            { label: "xAI 공식 — x.ai/cli (설치 / 다운로드)", url: "https://x.ai/cli" },
            { label: "xAI Release Notes (Grok Build 0.1 entry)", url: "https://docs.x.ai/developers/release-notes" },
            { label: "Grok Build 0.1 model docs", url: "https://docs.x.ai/developers/models/grok-build-0.1" },
            { label: "eigent.ai — Grok Build vs Claude Code vs Codex CLI", url: "https://eigent.ai/blog/grok-build-cli" },
            { label: "rejoicehub — Grok Build vs Claude Code vs Codex CLI", url: "https://rejoicehub.com/blogs/grok-build-vs-claude-code-vs-codex-cli" },
            { label: "Vercel AI Gateway — Grok Build 0.1 추가", url: "https://vercel.com/changelog/grok-build-0-1-now-available-on-vercel-ai-gateway" },
          ],
          tags: ["xAI", "Grok Build", "CLI", "TUI", "parallel agent", "Plan Mode", "공식", "hero후보"],
          featured: true,
          slug: "grok-build-0-1-added-to-xai-release-note-1de20131",
          readMinutes: 4,
          thumbnail: {
            src: "/og-cache/grok-build-0-1-added-to-xai-release-note-1de20131.jpg",
            alt: "Grok Build 0.1 added to xAI release notes",
          },
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "Grok Model Retirement on May 15, 2026",
          summary: "",
          officialUrl: "https://docs.x.ai/developers/migration/may-15-retirement",
          source: "https://docs.x.ai/developers/migration/may-15-retirement",
          tags: ["xAI API", "Grok Models", "공식"],
          slug: "grok-model-retirement-on-may-15-2026-9ba2517f",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/grok-model-retirement-on-may-15-2026-9ba2517f.jpg",
            alt: "Grok Model Retirement on May 15, 2026",
          },
        },
      ],
    },
    {
      name: "Vercel",
      color: "#000000",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Qwen 3.7 Max now available on Vercel AI Gateway",
          summary: "Vercel added Qwen 3.7 Max to AI Gateway.",
          officialUrl: "https://vercel.com/changelog/qwen-3-7-max-now-available-on-vercel-ai-gateway",
          source: "https://vercel.com/changelog/qwen-3-7-max-now-available-on-vercel-ai-gateway",
          tags: ["Vercel AI Gateway", "Qwen", "공식"],
          slug: "qwen-3-7-max-now-available-on-vercel-ai--ea436015",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/qwen-3-7-max-now-available-on-vercel-ai--ea436015.png",
            alt: "Qwen 3.7 Max now available on Vercel AI Gateway",
          },
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Chat SDK now includes AI SDK tools",
          summary: "Vercel added chat/ai and createChatTools(chat) to connect AI agents and SDK actions more easily.",
          officialUrl: "https://vercel.com/changelog/chat-sdk-now-includes-ai-sdk-tools",
          source: "https://vercel.com/changelog/chat-sdk-now-includes-ai-sdk-tools",
          tags: ["Vercel Chat SDK", "AI SDK", "공식"],
          slug: "chat-sdk-now-includes-ai-sdk-tools-fbff1453",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/chat-sdk-now-includes-ai-sdk-tools-fbff1453.png",
            alt: "Chat SDK now includes AI SDK tools",
          },
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Grok Build 0.1 now available on Vercel AI Gateway",
          summary: "Vercel added xAI's agentic coding model Grok Build 0.1 to AI Gateway.",
          officialUrl: "https://vercel.com/changelog/grok-build-0-1-now-available-on-vercel-ai-gateway",
          source: "https://vercel.com/changelog/grok-build-0-1-now-available-on-vercel-ai-gateway",
          tags: ["Vercel AI Gateway", "xAI", "agentic coding", "공식"],
          slug: "grok-build-0-1-now-available-on-vercel-a-b7c5d45d",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/grok-build-0-1-now-available-on-vercel-a-b7c5d45d.png",
            alt: "Grok Build 0.1 now available on Vercel AI Gateway",
          },
        },
      ],
    },
    {
      name: "Krea",
      color: "#FF3B82",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Krea 2 LoRA training is here",
          summary: "소수 이미지에서 스타일/캐릭터/오브젝트를 학습하는 LoRA를 Krea 2에 직접 학습·강도 조절·다중 LoRA 스택까지 지원.",
          officialUrl: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
          source: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
          tags: ["Krea 2", "LoRA training", "multi-LoRA stacking", "공식"],
          slug: "krea-2-lora-training-is-here-17d6e9dc",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/krea-2-lora-training-is-here-17d6e9dc.webp",
            alt: "Krea 2 LoRA training is here",
          },
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Krea 2 deep dive",
          summary: "Krea 2 스타일 레퍼런스·무드보드·프롬프트 사용법을 정리한 공식 가이드.",
          officialUrl: "https://www.krea.ai/release-notes/krea-2-deep-dive",
          source: "https://www.krea.ai/release-notes/krea-2-deep-dive",
          tags: ["Krea 2", "style references", "moodboard", "공식"],
          slug: "krea-2-deep-dive-91a631fa",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/krea-2-deep-dive-91a631fa.webp",
            alt: "Krea 2 deep dive",
          },
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Krea 2 is live for everyone",
          summary: "Krea 2 전체 사용자 공개. 한 주 동안 모든 가입자에게 무제한 Krea 2 생성을 제공.",
          officialUrl: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
          source: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
          tags: ["Krea 2", "공식"],
          slug: "krea-2-is-live-for-everyone-b5dfeabe",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/krea-2-is-live-for-everyone-b5dfeabe.webp",
            alt: "Krea 2 is live for everyone",
          },
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "K2 is now available for Pro",
          summary: "Krea 2가 Pro 가입자에게 공개됐다. 일러스트, 애니메이션, 포토리얼 사이의 스타일 통제가 핵심.",
          officialUrl: "https://www.krea.ai/release-notes/k2-is-now-available-for-pro",
          source: "https://www.krea.ai/release-notes/k2-is-now-available-for-pro",
          tags: ["Krea 2", "image foundation model", "공식"],
          slug: "k2-is-now-available-for-pro-4a1a33b6",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/k2-is-now-available-for-pro-4a1a33b6.png",
            alt: "K2 is now available for Pro",
          },
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "Krea at Cannes Film Festival",
          summary: "Krea 공동창업자 Diego Rodriguez가 미국관에서 작곡가 Roahn Hylton과 함께 실시간 비주얼 생성 시연.",
          officialUrl: "https://www.krea.ai/release-notes/krea-at-cannes-film-festival",
          source: "https://www.krea.ai/release-notes/krea-at-cannes-film-festival",
          tags: ["Krea 2", "real-time generation", "film", "공식"],
          slug: "krea-at-cannes-film-festival-d09a5965",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/krea-at-cannes-film-festival-d09a5965.png",
            alt: "Krea at Cannes Film Festival",
          },
        },
      ],
    },
    {
      name: "Meta",
      color: "#0866FF",
      posts: [
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Our AI Wearables Are Changing the Game for Disabled People",
          summary: "",
          officialUrl: "https://about.fb.com/news/2026/05/meta-ai-wearables-changing-the-game-for-disabled-people/",
          source: "https://about.fb.com/news/2026/05/meta-ai-wearables-changing-the-game-for-disabled-people/",
          tags: ["Meta AI wearables", "AI glasses", "accessibility", "공식"],
          slug: "our-ai-wearables-are-changing-the-game-f-e1466393",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/our-ai-wearables-are-changing-the-game-f-e1466393.jpg",
            alt: "Our AI Wearables Are Changing the Game for Disabled People",
          },
        },
      ],
    },
    {
      name: "Hugging Face / 모델",
      color: "#FFD21E",
      posts: [
        {
          date: "5/18",
          platform: "X+Threads",
          title: "The Open Agent Leaderboard",
          summary: "IBM Research introduced an Open Agent Leaderboard on the Hugging Face Blog for evaluating agents.",
          officialUrl: "https://huggingface.co/blog/ibm-research/open-agent-leaderboard",
          source: "https://huggingface.co/blog/ibm-research/open-agent-leaderboard",
          tags: ["agent evaluation", "leaderboard", "공식"],
          slug: "the-open-agent-leaderboard-4aacdb26",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/the-open-agent-leaderboard-4aacdb26.png",
            alt: "The Open Agent Leaderboard",
          },
        },
      ],
    },
    {
      name: "오픈소스 / 도구",
      color: "#6B7280",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Nutlope/hallmark — anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
          summary: "anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
          officialUrl: "https://github.com/Nutlope/hallmark",
          source: "https://github.com/Nutlope/hallmark",
          tags: ["오픈소스 공유 후보", "공식"],
          slug: "nutlope-hallmark-anti-ai-slop-디자인-가이드를-코-4fabea9d",
          readMinutes: 1,
          thumbnail: {
            src: "/og-cache/nutlope-hallmark-anti-ai-slop-디자인-가이드를-코-4fabea9d.jpg",
            alt: "Nutlope/hallmark — anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
          },
        },
        {
          date: "5/21",
          platform: "X+Threads",
          title: "YC Diana Hu — AI-native company 구성 방식",
          summary: "YC 파트너 관점에서 AI-native 회사가 갖춰야 할 구조.",
          officialUrl: "https://www.youtube.com/watch?v=EN7frwQIbKc",
          source: "https://www.youtube.com/watch?v=EN7frwQIbKc",
          tags: ["실전 팁", "공식"],
          slug: "yc-diana-hu-ai-native-company-구성-방식-85b5079d",
          readMinutes: 1,
        },
      ],
    },
  ],
};
