import type { WeeklyData } from "../data";

// Editorial cutoff: 2026-08-26 21:48 KST. Official-date-verified items only.
export const week34: WeeklyData = {
  week: 34,
  year: 2026,
  slug: "2026-w34",
  period: "8/17 ~ 8/23",
  totalPosts: 14,
  companies: [
    {
      name: "Anthropic",
      color: "#E87040",
      posts: [
        {
          date: "8/17",
          platform: "X+Threads",
          title: "Claude Code, GitLab MR 상태 배지와 사용량 제한 자동 재개 추가",
          deck: "GitLab remote와 인증된 glab CLI가 있으면 footer/statusline에 MR !N 상태 표시",
          summary: "GitLab remote와 인증된 glab CLI가 있으면 footer/statusline에 MR !N 상태 표시 claude.ai 사용량 제한 초기화 시 세션 자동 계속 Windows NT namespace 경로를 사전승인 파일 접근 경계에서 거부",
          source: "https://github.com/anthropics/claude-code/releases/tag/v2.1.234",
          officialUrl: "https://github.com/anthropics/claude-code/releases/tag/v2.1.234",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "claude-code-20260817-v2-1-234",
          en: { title: "Claude Code adds GitLab MR status and automatic usage-limit resume", deck: "GitLab merge-request state now appears in the footer and status line.", summary: "Claude Code 2.1.234 displays authenticated GitLab merge-request status, resumes sessions when claude.ai usage limits reset, and rejects Windows NT namespace paths at the pre-approved file boundary." },
        },
        {
          date: "8/19",
          platform: "X+Threads",
          title: "Claude Code, 다른 세션이 유휴 상태가 되면 1회 알림",
          deck: "SendMessage에 notify_when_idle 추가",
          summary: "SendMessage에 notify_when_idle 추가 동일 머신의 다른 세션이 다음 idle 상태가 될 때 opt-in one-shot 알림 /goal이 장시간 백그라운드 작업을 30분, 이후 1시간·2시간 간격으로 확인 주의: 작업 성공 판정이 아니라 idle 전환 알림.",
          source: "https://github.com/anthropics/claude-code/releases/tag/v2.1.236",
          officialUrl: "https://github.com/anthropics/claude-code/releases/tag/v2.1.236",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "claude-code-20260819-v2-1-236",
          en: { title: "Claude Code can notify you once when another session goes idle", deck: "An opt-in, one-shot cross-session notification.", summary: "Claude Code 2.1.236 adds notify_when_idle to SendMessage, notifying the caller once when another local session next becomes idle. It signals idleness, not task success." },
        }
      ],
    },
    {
      name: "Ollama",
      color: "#111827",
      posts: [
        {
          date: "8/19",
          platform: "X+Threads",
          title: "Ollama, 모델 메타데이터 캐시로 첫 토큰 지연 절반",
          deck: "벤치마크 TTFT 약 995ms에서 524ms로 감소",
          summary: "벤치마크 TTFT 약 995ms에서 524ms로 감소 Qwen 3.8 system message 정규화 중간 parser 오류 뒤 chat/generate 멈춤 수정 주의: TTFT 수치는 Ollama 릴리스 자체 벤치마크.",
          source: "https://github.com/ollama/ollama/releases/tag/v0.32.15",
          officialUrl: "https://github.com/ollama/ollama/releases/tag/v0.32.15",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "ollama-20260819-v0-32-15",
          en: { title: "Ollama halves time to first token with model metadata caching", deck: "Vendor benchmark falls from about 995 ms to 524 ms.", summary: "Ollama 0.32.15 caches model metadata to reduce time to first token, and fixes Qwen 3.8 parser failures that could stop chat and generate requests." },
        },
        {
          date: "8/21",
          platform: "X+Threads",
          title: "Ollama, Claude Desktop에서 로컬 모델을 직접 선택",
          deck: "메뉴바에서 Claude가 사용할 Ollama 모델 on/off",
          summary: "메뉴바에서 Claude가 사용할 Ollama 모델 on/off Claude 안에서 로컬 Ollama 모델 선택 취소된 긴 prefill의 캐시 복구 정확성 개선 주의: release candidate이며 GA 아님.",
          source: "https://github.com/ollama/ollama/releases/tag/v0.33.0-rc2",
          officialUrl: "https://github.com/ollama/ollama/releases/tag/v0.33.0-rc2",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "ollama-20260821-v0-33-rc2",
          en: { title: "Ollama models become selectable inside Claude Desktop", deck: "A menu-bar switch connects local models to Claude Desktop.", summary: "Ollama 0.33.0-rc2 lets Claude Desktop users enable and select Ollama models from the menu bar and Apps view. This is a release candidate, not general availability." },
        }
      ],
    },
    {
      name: "OpenRouter",
      color: "#6D5DFC",
      posts: [
        {
          date: "8/19",
          platform: "X+Threads",
          title: "OpenRouter, Stripe에 합류하되 이름·제품·로드맵 유지",
          deck: "거래는 수주 내 종결 예정",
          summary: "거래는 수주 내 종결 예정 same mission, same name, same product, same roadmap Stripe 인프라와 사기 대응 역량 활용 주의: 인수 대가와 지분 구조 미공개.",
          source: "https://openrouter.ai/blog/announcements/openrouter-is-joining-stripe/",
          officialUrl: "https://openrouter.ai/blog/announcements/openrouter-is-joining-stripe/",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "openrouter-20260819-stripe",
          en: { title: "OpenRouter joins Stripe while keeping its name, product and roadmap", deck: "The multi-model routing company retains its operating identity.", summary: "OpenRouter announced it is joining Stripe while keeping the same name, product and roadmap. Financial terms and ownership details were not disclosed." },
        }
      ],
    },
    {
      name: "Wiz",
      color: "#6B46C1",
      posts: [
        {
          date: "8/17",
          platform: "X+Threads",
          title: "AI가 공동 작성한 CI 변경, Snowflake Jira 자격 증명 노출 경로 만들었다",
          deck: "이슈 제목의 직접 셸 보간으로 인증 없는 명령 실행 가능",
          summary: "이슈 제목의 직접 셸 보간으로 인증 없는 명령 실행 가능 러너의 Jira 읽기 자격 증명 접근 가능 Snowflake가 6월 23일 수정하고 6월 24일 토큰 교체 감사 로그에서 제3자 접근 증거 없음 주의: 취약점 사건 발생은 6월이며 8월 17일은 연구 공개일; Copilot이 코드 자체를 생성했는지는 불명확.",
          source: "https://www.wiz.io/blog/red-agent-snowflake-copilot-cicd-bug",
          officialUrl: "https://www.wiz.io/blog/red-agent-snowflake-copilot-cicd-bug",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "wiz-20260817-snowflake-cicd",
          en: { title: "A CI change exposed a Snowflake Jira credential path", deck: "Issue-title shell interpolation enabled unauthenticated command execution.", summary: "Wiz disclosed a Snowflake GitHub Actions flaw where issue titles reached a shell, exposing a path to Jira read credentials. Snowflake fixed it on June 23 and rotated the token on June 24; the research was published August 17." },
        }
      ],
    },
    {
      name: "Higgsfield",
      color: "#E11D48",
      posts: [
        {
          date: "8/17",
          platform: "X+Threads",
          title: "Higgsfield, Claude·ChatGPT·Cursor에서 제작 도구를 부르는 MCP 공개",
          deck: "Claude·ChatGPT·Cursor·CLI 에이전트에서 Higgsfield 이미지·영상·오디오 제작 도구 연결",
          summary: "Claude·ChatGPT·Cursor·CLI 에이전트에서 Higgsfield 이미지·영상·오디오 제작 도구 연결 UGC 광고·현지화 콘텐츠·랜딩 페이지 생성 흐름 제시 주의: 신규 모델 원출시가 아니라 통합 지원 가이드.",
          source: "https://higgsfield.ai/blog/mcp-for-marketers",
          officialUrl: "https://higgsfield.ai/blog/mcp-for-marketers",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "higgsfield-20260817-mcp",
          en: { title: "Higgsfield exposes creative tools through MCP", deck: "Claude, ChatGPT and Cursor can invoke its media workflows.", summary: "Higgsfield published an MCP integration for calling its creative workflows from agent clients. It is an integration release rather than a new underlying model." },
        },
        {
          date: "8/18",
          platform: "X+Threads",
          title: "Higgsfield Marketing Studio, 1,500개 템플릿 중심으로 개편",
          deck: "프롬프트 우선 흐름을 1,500개 이상 템플릿 기반으로 전환",
          summary: "프롬프트 우선 흐름을 1,500개 이상 템플릿 기반으로 전환 Product Shots·Ads·Marketplace·Posters·UGC Videos·Motion 여섯 범주 제공 주의: 기존 제품 업데이트이며 원출시일은 별도.",
          source: "https://higgsfield.ai/blog/new-marketing-studio-higgsfield",
          officialUrl: "https://higgsfield.ai/blog/new-marketing-studio-higgsfield",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "higgsfield-20260818-marketing-studio",
          en: { title: "Higgsfield rebuilds Marketing Studio around 1,500 templates", deck: "Template-led generation targets repeatable campaign production.", summary: "Higgsfield updated Marketing Studio with more than 1,500 templates, reorganizing media generation around repeatable marketing workflows." },
        },
        {
          date: "8/20",
          platform: "X+Threads",
          title: "Higgsfield, 생성 결과를 편집 가능한 Blender 장면으로 연결",
          deck: "Blender 플러그인과 MCP Bridge 공개",
          summary: "Blender 플러그인과 MCP Bridge 공개 생성 결과를 geometry·material·rig·clip 형태로 장면에 삽입 Blender 4.2~5.1과 Windows·macOS 지원 주의: Higgsfield 원모델 출시가 아니라 Blender 통합 지원.",
          source: "https://higgsfield.ai/blog/higgsfield-blender-plugin",
          officialUrl: "https://higgsfield.ai/blog/higgsfield-blender-plugin",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "higgsfield-20260820-blender",
          en: { title: "Higgsfield connects generated output to editable Blender scenes", deck: "Generated media moves into a production-grade editing environment.", summary: "Higgsfield released a Blender plugin and MCP bridge that carries generated output into editable scenes. This is Blender integration support, not a new base-model launch." },
        },
        {
          date: "8/20",
          platform: "X+Threads",
          title: "Higgsfield, 기존 영상의 조명·색을 다시 설계하는 편집 도구 출시",
          deck: "원본 움직임과 구도를 유지하며 조명 방향·색·강도 조절",
          summary: "원본 움직임과 구도를 유지하며 조명 방향·색·강도 조절 참조 이미지와 프리셋 기반 색보정 15초당 각 도구 135크레딧·미화 6.75달러 제시 주의: 가격은 공식 페이지 기준 시점 가격.",
          source: "https://higgsfield.ai/blog/video-relight-color-palette-higgsfield",
          officialUrl: "https://higgsfield.ai/blog/video-relight-color-palette-higgsfield",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "higgsfield-20260820-video-relight",
          en: { title: "Higgsfield launches video relighting and palette editing", deck: "Competition moves from generation into post-production control.", summary: "Higgsfield introduced standalone tools for redesigning lighting and colour palettes in existing video." },
        }
      ],
    },
    {
      name: "Pika",
      color: "#8B5CF6",
      posts: [
        {
          date: "8/18",
          platform: "X+Threads",
          title: "Pika, 음악·효과음·음성·영상 사운드 모델 4종 동시 공개",
          deck: "Soundtrack은 영상에서 동기화된 음향 장면 생성",
          summary: "Soundtrack은 영상에서 동기화된 음향 장면 생성 Music은 최대 90초 곡을 평균 6.21초에 생성한다고 주장 SFX는 1~20초 MP3 효과음을 실시간 수준으로 생성 Speech는 5초 참조 음성 복제·최대 5분 생성·RTF 0.02 제시 주의: 성능 수치는 Pika 자체 주장; 한국어 지원은 명시되지 않음.",
          source: "https://pika.art/blog/pika-soundtrack",
          officialUrl: "https://pika.art/blog/pika-soundtrack",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "pika-20260818-audio-suite",
          en: { title: "Pika launches four models for music, effects, speech and video sound", deck: "The video platform expands across the full audio layer.", summary: "Pika announced Soundtrack, Music, SFX and Speech together. Vendor claims include up to 90-second music, real-time-class effects generation and five-second voice references; Korean support was not specified." },
        }
      ],
    },
    {
      name: "Stability AI",
      color: "#2563EB",
      posts: [
        {
          date: "8/18",
          platform: "X+Threads",
          title: "Stability AI, Stable Audio를 DAW 편집 워크플로로 확장",
          deck: "Stable Audio 3.0 기반 DAW 플러그인 베타와 웹 앱 업데이트",
          summary: "Stable Audio 3.0 기반 DAW 플러그인 베타와 웹 앱 업데이트 반복 프롬프팅·audio-to-audio variation·트랙별 믹싱·효과·내보내기 제공 macOS AU·VST3와 Apple Silicon·Intel Mac 지원 주의: early beta; 원 모델 원출시가 아니라 편집 워크플로 업데이트.",
          source: "https://stability.ai/news-updates/sharing-a-new-way-to-work-with-stable-audio",
          officialUrl: "https://stability.ai/news-updates/sharing-a-new-way-to-work-with-stable-audio",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "stability-20260818-stable-audio-workflow",
          en: { title: "Stability AI extends Stable Audio into DAW workflows", deck: "A beta plugin and revised web app target production editing.", summary: "Stability AI announced an early-beta DAW plugin and updated web workflow for Stable Audio 3.0, moving music generation into an editable production process." },
        }
      ],
    },
    {
      name: "Tripo",
      color: "#F97316",
      posts: [
        {
          date: "8/17",
          platform: "X+Threads",
          title: "Tripo Image Gen, 한 번에 30장 3D 변환과 9개 변형 추가",
          deck: "Character·Asset Extraction과 Cutout 제공",
          summary: "Character·Asset Extraction과 Cutout 제공 최대 30장 Batch to 3D 선택형 4K 출력과 참조 기반 9개 Variant 제공 주의: 기존 Image Gen 업데이트이며 상세 페이지 자체에는 날짜 반복 표기 없음.",
          source: "https://www.tripo3d.ai/blog/tripo-image-gen-update",
          officialUrl: "https://www.tripo3d.ai/blog/tripo-image-gen-update",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "tripo-20260817-image-gen",
          en: { title: "Tripo Image Gen adds 30-image 3D batches and nine variations", deck: "Image generation connects directly to 3D asset workflows.", summary: "Tripo updated Image Gen with batch conversion of up to 30 images, nine variations and asset extraction for downstream 3D production." },
        },
        {
          date: "8/19",
          platform: "X+Threads",
          title: "Tripo P2.0 Preview, 생성 3D를 리깅 가능한 쿼드 메시로",
          deck: "native quad topology와 논리적 edge flow 제공",
          summary: "native quad topology와 논리적 edge flow 제공 500~25,000 quad faces 또는 500~50,000 triangle faces 범위 리깅·애니메이션·게임 제작 파이프라인 목표 Tripo Studio에서 사용자당 2회 무료 생성 안내 주의: Preview이며 정식 P2.0 GA가 아님.",
          source: "https://www.tripo3d.ai/blog/tripo-p2-0-preview",
          officialUrl: "https://www.tripo3d.ai/blog/tripo-p2-0-preview",
          verifiedAt: "2026-08-26",
          backupUrls: [],
          tags: ["AI", "2026-08b"],
          slug: "tripo-20260819-p2-preview",
          en: { title: "Tripo P2.0 Preview generates riggable quad meshes", deck: "The 3D bottleneck shifts from appearance to editable topology.", summary: "Tripo previewed P2.0 with native quad topology and Smart Mesh output intended for rigging. It remains a preview rather than general availability." },
        }
      ],
    }
  ],
};
