import type { WeeklyData } from "../data";

// 2026-w21 (5/15 ~ 5/21)
// 자동 생성: 4라운드 수집 + 5차 prune 기반 archive
// 주차 기준 목~수 (5/15 목 = 새 주차 시작)

export const week21: WeeklyData = {
  week: 21,
  year: 2026,
  slug: "2026-w21",
  period: "5/15 ~ 5/21",
  totalPosts: 62,
  companies: [
    {
      name: "OpenAI",
      color: "#10A37F",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "AdventHealth advances whole-person care with OpenAI",
          summary: "",
          officialUrl: "https://openai.com/index/adventhealth",
          source: "https://openai.com/index/adventhealth",
          tags: ["ChatGPT for Healthcare", "공식"],
        },
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Codex rust-v0.133.0",
          summary: "",
          officialUrl: "https://github.com/openai/codex/releases/tag/rust-v0.133.0",
          source: "https://github.com/openai/codex/releases/tag/rust-v0.133.0",
          tags: ["Codex CLI", "Goals", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "An OpenAI model has disproved a central conjecture in discrete geometry",
          summary: "",
          officialUrl: "https://openai.com/index/model-disproves-discrete-geometry-conjecture",
          source: "https://openai.com/index/model-disproves-discrete-geometry-conjecture",
          tags: ["OpenAI Research", "Math", "공식"],
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "The next phase of OpenAI’s Education for Countries",
          summary: "",
          officialUrl: "https://openai.com/index/the-next-phase-of-education-for-countries",
          source: "https://openai.com/index/the-next-phase-of-education-for-countries",
          tags: ["Education for Countries", "Global Affairs", "공식"],
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "How Ramp engineers accelerate code review with Codex",
          summary: "",
          officialUrl: "https://openai.com/index/ramp",
          source: "https://openai.com/index/ramp",
          tags: ["Codex", "GPT-5.5", "enterprise adoption", "공식"],
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "OpenAI Cookbook commit: Macro evals cookbook",
          summary: "",
          officialUrl: "https://github.com/openai/openai-cookbook/commit/0075904c509819f8d746794001a7a27066258956",
          source: "https://github.com/openai/openai-cookbook/commit/0075904c509819f8d746794001a7a27066258956",
          tags: ["OpenAI Cookbook", "evals", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Introducing OpenAI for Singapore",
          summary: "",
          officialUrl: "https://openai.com/index/introducing-openai-for-singapore",
          source: "https://openai.com/index/introducing-openai-for-singapore",
          tags: ["OpenAI for Singapore", "Global Affairs", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Advancing content provenance for a safer, more transparent AI ecosystem",
          summary: "",
          officialUrl: "https://openai.com/index/advancing-content-provenance",
          source: "https://openai.com/index/advancing-content-provenance",
          tags: ["Safety", "Content provenance", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Codex rust-v0.132.0",
          summary: "",
          officialUrl: "https://github.com/openai/codex/releases/tag/rust-v0.132.0",
          source: "https://github.com/openai/codex/releases/tag/rust-v0.132.0",
          tags: ["Codex CLI", "Python SDK auth", "공식"],
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "OpenAI and Dell partner to bring Codex to hybrid and on-premise enterprise environments",
          summary: "",
          officialUrl: "https://openai.com/index/dell-codex-enterprise-partnership",
          source: "https://openai.com/index/dell-codex-enterprise-partnership",
          tags: ["Codex", "Dell", "enterprise deployment", "공식"],
        },
        {
          date: "5/16",
          platform: "X+Threads",
          title: "OpenAI and Malta partner to bring ChatGPT Plus to all citizens",
          summary: "",
          officialUrl: "https://openai.com/index/malta-chatgpt-plus-partnership",
          source: "https://openai.com/index/malta-chatgpt-plus-partnership",
          tags: ["ChatGPT Plus", "Malta", "Global Affairs", "공식"],
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "A new personal finance experience in ChatGPT",
          summary: "",
          officialUrl: "https://openai.com/index/personal-finance-chatgpt",
          source: "https://openai.com/index/personal-finance-chatgpt",
          tags: ["ChatGPT", "Personal finance", "공식"],
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "Databricks brings GPT-5.5 to enterprise agent workflows",
          summary: "",
          officialUrl: "https://openai.com/index/databricks",
          source: "https://openai.com/index/databricks",
          tags: ["GPT-5.5", "Databricks", "agents", "공식"],
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "How sales teams use Codex",
          summary: "",
          officialUrl: "https://openai.com/academy/codex-for-work/how-sales-teams-use-codex",
          source: "https://openai.com/academy/codex-for-work/how-sales-teams-use-codex",
          tags: ["Codex for Work", "Sales", "공식"],
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "How business operations teams use Codex",
          summary: "",
          officialUrl: "https://openai.com/academy/codex-for-work/how-business-operations-teams-use-codex",
          source: "https://openai.com/academy/codex-for-work/how-business-operations-teams-use-codex",
          tags: ["Codex for Work", "Business operations", "공식"],
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "How data science teams use Codex",
          summary: "",
          officialUrl: "https://openai.com/academy/codex-for-work/how-data-science-teams-use-codex",
          source: "https://openai.com/academy/codex-for-work/how-data-science-teams-use-codex",
          tags: ["Codex for Work", "Data science", "공식"],
        },
        {
          date: "5/14",
          platform: "X+Threads",
          title: "Codex in the ChatGPT mobile app (iOS / Android)",
          summary: "OpenAI가 ChatGPT 모바일 앱(iOS/Android)에서 Mac/devbox에서 돌아가는 Codex 세션을 원격으로 제어할 수 있게 했다. 같은 주에 Hooks GA, Business/Enterprise programmatic access tokens, HIPAA-compliant Codex, Remote SSH GA가 함께 풀렸다.",
          officialUrl: "https://openai.com/index/",
          source: "https://openai.com/index/",
          tags: ["Codex", "ChatGPT mobile", "Codex Mac app", "Hooks", "Remote SSH", "공식", "hero후보"],
          featured: true,
        },
      ],
    },
    {
      name: "Google",
      color: "#4285F4",
      posts: [
        {
          date: "5/20",
          platform: "X+Threads",
          title: "A new experiment brings better group meetings to Google Beam",
          summary: "Google described a Google Beam experiment for more natural hybrid group meetings using HP Dimension immersive displays and spatial audio.",
          officialUrl: "https://blog.google/innovation-and-ai/models-and-research/google-research/google-beam-group-meetings/",
          source: "https://blog.google/innovation-and-ai/models-and-research/google-research/google-beam-group-meetings/",
          tags: ["Google Beam", "Google Research", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "I/O 2026: Welcome to the agentic Gemini era",
          summary: "Google summarized I/O 2026 AI announcements including Gemini 3.5 Flash, Spark, agentic Search, TPU 8, Gemini Omni, and SynthID expansion.",
          officialUrl: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
          source: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
          tags: ["Gemini", "Search", "Workspace", "Cloud", "Android", "TPU", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "The Gemini app becomes more agentic, delivering proactive, 24/7 help",
          summary: "Google announced more proactive Gemini app experiences, Daily Brief, Omni video generation, Spark agent functions, and macOS improvements.",
          officialUrl: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
          source: "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
          tags: ["Gemini app", "Gemini 3.5 Flash", "Omni", "Daily Brief", "Spark", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Introducing Managed Agents in the Gemini API",
          summary: "Google introduced Gemini API Managed Agents running Antigravity-based agents inside secure cloud Linux sandboxes.",
          officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
          source: "https://blog.google/innovation-and-ai/technology/developers-tools/managed-agents-gemini-api/",
          tags: ["Gemini API", "Managed Agents", "Antigravity", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Bring any idea to life: Google AI Studio at I/O 2026",
          summary: "Google announced AI Studio updates for Workspace integration, Android app building, mobile pre-registration, Antigravity export, and no-cost deployment.",
          officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026/",
          source: "https://blog.google/innovation-and-ai/technology/developers-tools/google-ai-studio-io-2026/",
          tags: ["Google AI Studio", "Android", "Workspace", "Antigravity", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Building the agentic future: Developer highlights from I/O 2026",
          summary: "Google summarized I/O 2026 developer announcements around Antigravity 2.0, Gemini API Managed Agents, AI Studio integrations, and Build with Gemini XPRIZE Hackathon.",
          officialUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
          source: "https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/",
          tags: ["Antigravity 2.0", "Gemini API", "Managed Agents", "Google AI Studio", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "NVIDIA and Google Cloud Empower the Next Wave of AI Builders",
          summary: "",
          officialUrl: "https://blogs.nvidia.com/blog/google-cloud-developer-community-ai-builders/",
          source: "https://blogs.nvidia.com/blog/google-cloud-developer-community-ai-builders/",
          tags: ["NVIDIA AI platform", "Google Cloud", "Gemma", "Nemotron", "공식"],
        },
      ],
    },
    {
      name: "Anthropic / Claude",
      color: "#E87040",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Anthropic Claude for Small Business",
          summary: "",
          officialUrl: "https://www.anthropic.com/news/claude-for-small-business",
          source: "https://www.anthropic.com/news/claude-for-small-business",
          tags: ["Claude", "SMB", "go-to-market", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Widening the conversation on frontier AI",
          summary: "Anthropic described work to broaden frontier AI discussions with religion, philosophy, culture, and civil society experts.",
          officialUrl: "https://www.anthropic.com/news/widening-conversation-ai",
          source: "https://www.anthropic.com/news/widening-conversation-ai",
          tags: ["AI safety", "governance", "Claude values", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "KPMG integrates Claude across its core business and workforce of more than 276,000 in strategic alliance",
          summary: "KPMG announced Claude integration across core business workflows and a 276,000+ workforce through a strategic alliance with Anthropic.",
          officialUrl: "https://www.anthropic.com/news/anthropic-kpmg",
          source: "https://www.anthropic.com/news/anthropic-kpmg",
          tags: ["Claude", "Enterprise AI", "Managed Agents", "Claude Code", "공식"],
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Anthropic acquires Stainless",
          summary: "Anthropic acquired Stainless to strengthen Claude developer experience, SDK generation, CLI and MCP-connected tooling.",
          officialUrl: "https://www.anthropic.com/news/anthropic-acquires-stainless",
          source: "https://www.anthropic.com/news/anthropic-acquires-stainless",
          tags: ["Claude Platform", "Stainless", "SDK", "MCP", "공식"],
        },
        {
          date: "5/11",
          platform: "X+Threads",
          title: "Claude Code Agent View (Research Preview)",
          summary: "Anthropic이 Claude Code 2.1.139부터 모든 병렬 세션을 한 화면에서 관리하는 Agent View를 Research Preview로 공개했다. 이후 `claude agents --cwd <path>`와 pinned background sessions 같은 후속 업데이트가 같은 주에 추가되며 5월 15일 이후에도 영향이 이어졌다.",
          officialUrl: "https://www.anthropic.com/news",
          source: "https://www.anthropic.com/news",
          tags: ["Claude Code", "Agent View", "multi-agent CLI", "공식"],
        },
      ],
    },
    {
      name: "NVIDIA",
      color: "#76B900",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "NVIDIA GTC Taipei at COMPUTEX: Live Updates on What's Next in AI",
          summary: "",
          officialUrl: "https://blogs.nvidia.com/blog/nvidia-gtc-taipei-computex-2026-news/",
          source: "https://blogs.nvidia.com/blog/nvidia-gtc-taipei-computex-2026-news/",
          tags: ["NVIDIA AI", "GTC Taipei", "COMPUTEX", "Jetson Thor", "공식"],
        },
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Building Token-Metered AI Services on Telco AI Factories",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/building-token-metered-ai-services-on-telco-ai-factories/",
          source: "https://developer.nvidia.com/blog/building-token-metered-ai-services-on-telco-ai-factories/",
          tags: ["NVIDIA Telco AI", "AI Factory", "NIM", "NeMo", "공식"],
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "NVIDIA Announces Financial Results for First Quarter Fiscal 2027",
          summary: "",
          officialUrl: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
          source: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
          tags: ["NVIDIA Data Center", "AI factories", "Blackwell", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Mastering Agentic Techniques: AI Agent Customization",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/mastering-agentic-techniques-ai-agent-customization/",
          source: "https://developer.nvidia.com/blog/mastering-agentic-techniques-ai-agent-customization/",
          tags: ["NVIDIA NeMo", "Agentic AI", "Nemotron", "공식"],
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Add a Specialized Deep Research Skill to Agent Harnesses",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/add-a-specialized-deep-research-skill-to-agent-harnesses/",
          source: "https://developer.nvidia.com/blog/add-a-specialized-deep-research-skill-to-agent-harnesses/",
          tags: ["NVIDIA AI-Q", "NeMo Agent Toolkit", "agent harness", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "NVIDIA-Verified Agent Skills Provide Capability Governance for AI Agents",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/nvidia-verified-agent-skills-provide-capability-governance-for-ai-agents/",
          source: "https://developer.nvidia.com/blog/nvidia-verified-agent-skills-provide-capability-governance-for-ai-agents/",
          tags: ["NVIDIA Agent Skills", "agent governance", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Mastering Agentic Techniques: AI Agent Evaluation",
          summary: "",
          officialUrl: "https://developer.nvidia.com/blog/mastering-agentic-techniques-ai-agent-evaluation/",
          source: "https://developer.nvidia.com/blog/mastering-agentic-techniques-ai-agent-evaluation/",
          tags: ["NVIDIA NeMo Agent Toolkit", "agent evaluation", "공식"],
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "NVIDIA CEO Jensen Huang at Dell Technologies World: Demand Is Going Parabolic, Utterly Parabolic",
          summary: "",
          officialUrl: "https://blogs.nvidia.com/blog/dell-technologies-agent-enterprise-ai/",
          source: "https://blogs.nvidia.com/blog/dell-technologies-agent-enterprise-ai/",
          tags: ["Dell AI Factory with NVIDIA", "Vera Rubin", "enterprise agentic AI", "공식"],
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Vera Arrives: NVIDIA's First CPU Built for Agents Lands at Top AI Labs",
          summary: "",
          officialUrl: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
          source: "https://blogs.nvidia.com/blog/vera-cpu-delivery/",
          tags: ["NVIDIA Vera CPU", "Vera Rubin NVL72", "agentic AI infrastructure", "공식", "hero후보"],
          featured: true,
        },
      ],
    },
    {
      name: "GitHub",
      color: "#181717",
      posts: [
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Auto model selection now routes based on your task in VS Code",
          summary: "GitHub Copilot in VS Code now routes to models based on task type through auto model selection.",
          officialUrl: "https://github.blog/changelog/2026-05-20-auto-model-selection-now-routes-based-on-your-task-in-vs-code",
          source: "https://github.blog/changelog/2026-05-20-auto-model-selection-now-routes-based-on-your-task-in-vs-code",
          tags: ["GitHub Copilot", "VS Code", "model routing", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Easily apply Copilot code review feedback with Copilot cloud agent",
          summary: "GitHub improved Copilot cloud agent so it can help apply code review feedback.",
          officialUrl: "https://github.blog/changelog/2026-05-19-easily-apply-copilot-code-review-feedback-with-copilot-cloud-agent",
          source: "https://github.blog/changelog/2026-05-19-easily-apply-copilot-code-review-feedback-with-copilot-cloud-agent",
          tags: ["GitHub Copilot cloud agent", "code review", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Gemini 3.5 Flash is generally available for GitHub Copilot",
          summary: "Gemini 3.5 Flash became generally available in GitHub Copilot.",
          officialUrl: "https://github.blog/changelog/2026-05-19-gemini-3-5-flash-is-generally-available-for-github-copilot",
          source: "https://github.blog/changelog/2026-05-19-gemini-3-5-flash-is-generally-available-for-github-copilot",
          tags: ["GitHub Copilot", "models", "공식"],
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "One-click fixes for failing Actions with Copilot cloud agent",
          summary: "GitHub added one-click Copilot cloud agent fixes for failing GitHub Actions workflows.",
          officialUrl: "https://github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
          source: "https://github.blog/changelog/2026-05-18-one-click-fixes-for-failing-actions-with-copilot-cloud-agent",
          tags: ["GitHub Actions", "Copilot cloud agent", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/17",
          platform: "X+Threads",
          title: "GPT-5.3-Codex is now the base model for Copilot Business and Enterprise",
          summary: "GitHub changed the base model for Copilot Business and Enterprise to GPT-5.3-Codex.",
          officialUrl: "https://github.blog/changelog/2026-05-17-gpt-5-3-codex-is-now-the-base-model-for-copilot-business-and-enterprise",
          source: "https://github.blog/changelog/2026-05-17-gpt-5-3-codex-is-now-the-base-model-for-copilot-business-and-enterprise",
          tags: ["GitHub Copilot Business", "GitHub Copilot Enterprise", "공식"],
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "Copilot Memory supports user preferences for Pro, Pro+ users",
          summary: "GitHub added user preference support to Copilot Memory for Pro and Pro+ users.",
          officialUrl: "https://github.blog/changelog/2026-05-15-copilot-memory-supports-user-preferences-for-pro-pro-users",
          source: "https://github.blog/changelog/2026-05-15-copilot-memory-supports-user-preferences-for-pro-pro-users",
          tags: ["GitHub Copilot Memory", "공식"],
        },
      ],
    },
    {
      name: "Cursor / Anysphere",
      color: "#374151",
      posts: [
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Improvements to Cursor Automations",
          summary: "Cursor added Automations to the Agents Window and introduced multi-repository/no-repository automation templates.",
          officialUrl: "https://cursor.com/changelog/05-20-26",
          source: "https://cursor.com/changelog/05-20-26",
          tags: ["Cursor Automations", "Agents Window", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Cursor in Jira",
          summary: "Cursor added Jira integration so users can mention @Cursor or assign issues to run the cloud agent and receive PR links.",
          officialUrl: "https://cursor.com/changelog/05-19-26",
          source: "https://cursor.com/changelog/05-19-26",
          tags: ["Cursor cloud agent", "Jira", "공식"],
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Composer 2.5",
          summary: "Cursor Composer 2.5 improved long-running work, instruction following, and collaboration.",
          officialUrl: "https://cursor.com/changelog/composer-2-5",
          source: "https://cursor.com/changelog/composer-2-5",
          tags: ["Cursor Composer", "공식"],
        },
      ],
    },
    {
      name: "Microsoft",
      color: "#00BCF2",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Plan Before You Build: Introducing the Plan agent in Visual Studio",
          summary: "Microsoft introduced a Visual Studio Plan agent for creating, editing, and sharing implementation plans before building.",
          officialUrl: "https://devblogs.microsoft.com/visualstudio/plan-before-you-build-introducing-the-plan-agent-in-visual-studio/",
          source: "https://devblogs.microsoft.com/visualstudio/plan-before-you-build-introducing-the-plan-agent-in-visual-studio/",
          tags: ["Visual Studio", "Copilot", "Plan agent", "공식"],
        },
      ],
    },
    {
      name: "xAI / Grok",
      color: "#1D1D1F",
      posts: [
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Grok Build 0.1 added to xAI release notes",
          summary: "",
          officialUrl: "https://docs.x.ai/developers/release-notes",
          source: "https://docs.x.ai/developers/release-notes",
          tags: ["xAI API", "Grok Build", "coding agent model", "공식", "hero후보"],
          featured: true,
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "Grok Model Retirement on May 15, 2026",
          summary: "",
          officialUrl: "https://docs.x.ai/developers/migration/may-15-retirement",
          source: "https://docs.x.ai/developers/migration/may-15-retirement",
          tags: ["xAI API", "Grok Models", "공식"],
        },
      ],
    },
    {
      name: "Vercel",
      color: "#000000",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Qwen 3.7 Max now available on Vercel AI Gateway",
          summary: "Vercel added Qwen 3.7 Max to AI Gateway.",
          officialUrl: "https://vercel.com/changelog/qwen-3-7-max-now-available-on-vercel-ai-gateway",
          source: "https://vercel.com/changelog/qwen-3-7-max-now-available-on-vercel-ai-gateway",
          tags: ["Vercel AI Gateway", "Qwen", "공식"],
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Chat SDK now includes AI SDK tools",
          summary: "Vercel added chat/ai and createChatTools(chat) to connect AI agents and SDK actions more easily.",
          officialUrl: "https://vercel.com/changelog/chat-sdk-now-includes-ai-sdk-tools",
          source: "https://vercel.com/changelog/chat-sdk-now-includes-ai-sdk-tools",
          tags: ["Vercel Chat SDK", "AI SDK", "공식"],
        },
        {
          date: "5/20",
          platform: "X+Threads",
          title: "Grok Build 0.1 now available on Vercel AI Gateway",
          summary: "Vercel added xAI's agentic coding model Grok Build 0.1 to AI Gateway.",
          officialUrl: "https://vercel.com/changelog/grok-build-0-1-now-available-on-vercel-ai-gateway",
          source: "https://vercel.com/changelog/grok-build-0-1-now-available-on-vercel-ai-gateway",
          tags: ["Vercel AI Gateway", "xAI", "agentic coding", "공식"],
        },
      ],
    },
    {
      name: "Krea",
      color: "#FF3B82",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Krea 2 LoRA training is here",
          summary: "소수 이미지에서 스타일/캐릭터/오브젝트를 학습하는 LoRA를 Krea 2에 직접 학습·강도 조절·다중 LoRA 스택까지 지원.",
          officialUrl: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
          source: "https://www.krea.ai/release-notes/krea-2-lora-training-is-here",
          tags: ["Krea 2", "LoRA training", "multi-LoRA stacking", "공식"],
        },
        {
          date: "5/19",
          platform: "X+Threads",
          title: "Krea 2 deep dive",
          summary: "Krea 2 스타일 레퍼런스·무드보드·프롬프트 사용법을 정리한 공식 가이드.",
          officialUrl: "https://www.krea.ai/release-notes/krea-2-deep-dive",
          source: "https://www.krea.ai/release-notes/krea-2-deep-dive",
          tags: ["Krea 2", "style references", "moodboard", "공식"],
        },
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Krea 2 is live for everyone",
          summary: "Krea 2 전체 사용자 공개. 한 주 동안 모든 가입자에게 무제한 Krea 2 생성을 제공.",
          officialUrl: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
          source: "https://www.krea.ai/release-notes/krea-2-is-live-for-everyone",
          tags: ["Krea 2", "공식"],
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "K2 is now available for Pro",
          summary: "Krea 2가 Pro 가입자에게 공개됐다. 일러스트, 애니메이션, 포토리얼 사이의 스타일 통제가 핵심.",
          officialUrl: "https://www.krea.ai/release-notes/k2-is-now-available-for-pro",
          source: "https://www.krea.ai/release-notes/k2-is-now-available-for-pro",
          tags: ["Krea 2", "image foundation model", "공식"],
        },
        {
          date: "5/15",
          platform: "X+Threads",
          title: "Krea at Cannes Film Festival",
          summary: "Krea 공동창업자 Diego Rodriguez가 미국관에서 작곡가 Roahn Hylton과 함께 실시간 비주얼 생성 시연.",
          officialUrl: "https://www.krea.ai/release-notes/krea-at-cannes-film-festival",
          source: "https://www.krea.ai/release-notes/krea-at-cannes-film-festival",
          tags: ["Krea 2", "real-time generation", "film", "공식"],
        },
      ],
    },
    {
      name: "Meta",
      color: "#0866FF",
      posts: [
        {
          date: "5/18",
          platform: "X+Threads",
          title: "Our AI Wearables Are Changing the Game for Disabled People",
          summary: "",
          officialUrl: "https://about.fb.com/news/2026/05/meta-ai-wearables-changing-the-game-for-disabled-people/",
          source: "https://about.fb.com/news/2026/05/meta-ai-wearables-changing-the-game-for-disabled-people/",
          tags: ["Meta AI wearables", "AI glasses", "accessibility", "공식"],
        },
      ],
    },
    {
      name: "Hugging Face / 모델",
      color: "#FFD21E",
      posts: [
        {
          date: "5/18",
          platform: "X+Threads",
          title: "The Open Agent Leaderboard",
          summary: "IBM Research introduced an Open Agent Leaderboard on the Hugging Face Blog for evaluating agents.",
          officialUrl: "https://huggingface.co/blog/ibm-research/open-agent-leaderboard",
          source: "https://huggingface.co/blog/ibm-research/open-agent-leaderboard",
          tags: ["agent evaluation", "leaderboard", "공식"],
        },
      ],
    },
    {
      name: "오픈소스 / 도구",
      color: "#6B7280",
      posts: [
        {
          date: "5/21",
          platform: "X+Threads",
          title: "Nutlope/hallmark — anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
          summary: "anti-AI-slop 디자인 가이드를 코드 스킬로 패키지화한 오픈소스. 사용자가 찾던 '오픈소스 공유할 만한' 후보.",
          officialUrl: "https://github.com/Nutlope/hallmark",
          source: "https://github.com/Nutlope/hallmark",
          tags: ["오픈소스 공유 후보", "공식"],
        },
        {
          date: "5/21",
          platform: "X+Threads",
          title: "YC Diana Hu — AI-native company 구성 방식",
          summary: "YC 파트너 관점에서 AI-native 회사가 갖춰야 할 구조.",
          officialUrl: "https://www.youtube.com/watch?v=EN7frwQIbKc",
          source: "https://www.youtube.com/watch?v=EN7frwQIbKc",
          tags: ["실전 팁", "공식"],
        },
      ],
    },
  ],
};
